### ISSUE TITLE
Replicate Dart tests on Android - crucial

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#1026]
See https://github.com/flutter/flutter/issues/115751#issuecomment-1426753920

**Comment by bartekpacia** [comment]
Prerequisite: #969

**Comment by bartekpacia** [comment]
**WIP**

**TBD: Decide on granularity of remote test invocation (test file vs test method invocation)**
Seems like remote test file invocation is simpler, but will be less granular? Needs research.

PTR - PatrolTestRunner
AUT - app under test


Let's consider this example file with 3 integration tests. We'll refer to them as TST1, TST2, TST3:

```dart
void main() {
  patrol(
    'TST1 counter state is incremented when button is tapped',
    ($) async {
      await createApp($);
      await $(FloatingActionButton).tap();
      expect($(#counterText).text, '1');
      await $(FloatingActionButton).tap();
      expect($(#counterText).text, '2');
    },
  );

  patrol(
    'TST2 counter state is the same after reopening the app',
    ($) async {
      await createApp($);
      await $(FloatingActionButton).tap();
      expect($(#counterText).text, '1');
      await $.native.pressHome();
      await $.native.openApp();
      expect($(#counterText).text, '1');
      await $(FloatingActionButton).tap();
      expect($(#counterText).text, '2');
    },
  );

  patrol(
    'TST3 counter state is the after opening and closing notifications',
    ($) async {
      await createApp($);
      await $(FloatingActionButton).tap();
      expect($(#counterText).text, '1');
      await $.native.openNotifications();
      await $.native.closeNotifications();
      expect($(#counterText).text, '1');
      await $(FloatingActionButton).tap();
      expect($(#counterText).text, '2');
    },
  );
}

```

```mermaid
sequenceDiagram
    participant PTR
    participant AUT
    AUT->>PTR: Send Dart tests (TST1, TST2, TST3)
    AUT-->>PTR: Run TST1
    AUT-->>PTR: Run TST2
    AUT-->>PTR: Run TST3
```

**Comment by bartekpacia** [comment]
Current progress: 
- All bundled (currently manually) Dart tests are collected by an artificial Dart test and sent to the native Android side using gRPC. The native side correctly translates the groups into native JUnit `Description`s (groups and tests). This is not completed yet, requires more work.

A problem appeared with dynamically creating JUnit test cases. We need to do this, so we can use Android Test Orchestrator. 

Currently I see 2 solutions to this problem, none of them perfect:
- use JUnit 4 parametrized tests ([Android Test Orchestrator works with them](https://stackoverflow.com/a/67858790/7009800))
- use JUnit 5 `@TestFactory` ([looks like it works with Android Test Orchestrator](https://github.com/mannodermaus/android-junit5/issues/163)). JUnit5 has better support for dynamic creation of tests than JUnit4, but it's not officially supported on Android
