### ISSUE TITLE
`scrollTo` doesn't work in some scenarios with complex ListView on Android

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#1032]
Customers: @zoskar and @iasiu.

**Comment by bartekpacia** [comment]
Notes:
- Reproduced on `Pixel 6 API 33` emulator, cannot reproduce on `iPhone 14 Pro Max` simulator

**Comment by bartekpacia** [comment]
PR in a customer project with a workaround: https://github.com/welliba/welliba/pull/4649/files

**Comment by zoskar** [comment]
Retested with:

`patrol: 2.0.0-dev.2`

`patrol_cli v2.0.0-dev.2`

`Flutter 3.10.0 • channel stable • https://github.com/flutter/flutter.git Framework • revision 84a1e904f4 (3 weeks ago) • 2023-05-09 07:41:44 -0700 Engine • revision d44b5a94c9 Tools • Dart 3.0.0 • DevTools 2.23.1`

Same result

**Comment by bartekpacia** [comment]
@zoskar Did it work on Android and on Flutter 3.10? So you're saying you did **not** experience #1265?

**Comment by zoskar** [comment]
I received it on some tests

**Comment by jBorkowska** [comment]
We confirmed with @zoskar that scrolling rework fixed this issue.
