### ISSUE TITLE
`tap()` sometimes taps on invisible widgets

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1048]
Example: https://github.com/jBorkowska/flutter-wonderous-app/blob/patrol-bug/integration_test/test_test.dart, but remove `scrollTo()` in line 25.
Then `tap()` is called on finder, which matches 2 widgets, but only one of them is hittestable. At the same time, the one that is not hittestable is higher in widget tree that the hittestable one (more in for in this [issue](https://github.com/leancodepl/patrol/issues/1046)). But real tap is called on `finder.first`, not `finder.hitTestable().first` (https://github.com/leancodepl/patrol/blob/master/packages/patrol/lib/src/custom_finders/patrol_tester.dart#L230).

**Comment by bartekpacia** [comment]
Thank you very much for this report. This was a bug in `PatrolTester.waitUntilVisible()` – it should be fixed by #1072.

**Comment by bartekpacia** [comment]
Fixed in #1072.
