### ISSUE TITLE
No native function to lock and unlock the device with PIN

### ISSUE THREAD

**Issue by lukasz8888** [leancodepl/patrol#1053]
I am working on a mobile app that works only on physical devices for security reasons.

Also, the SDK that I used keeps user's data in secure storage and access to it is possible only if the user's device has PIN authentication set up. The SDK blocks access to the storage if the device has been unlocked for more than 5 minutes. In that case, the user needs to lock the device and unlock it again (with the PIN code).

Now, I need to write an automated test that:
- locks the device
- unlocks the device with a PIN code (it should work both on Android and iOS)
- performs the actual tests

In the Patrol documentation I couldn't find any function that would allow for the lock and unlock operation.

Also - ideally - I would like to run the tests in Firebase Test Labs and for this reason I need a set of physical devices that are PIN-locked.

Is that all achievable or it's way beyond what Patrol and Firebase Test Labs offer?

**Comment by bartekpacia** [comment]
Hi @lukasz8888 – thanks for creating this issue and sharing your use case. Sounds quite niche.

> locks the device

Normal apps cannot do this, and Patrol doesn't have any built-in functionality to do this. Looks like it could be possible by [making an app a device admin](https://stackoverflow.com/questions/19745890/how-do-i-lock-phone-programmatically-android), but then I'm pretty sure it won't run on devicelabs.

> unlocks the device with a PIN code (it should work both on Android and iOS)

This should work, given that the automation was running before the screen was locked. I [performed a native view hierarchy dump](https://patrol.leancode.co/tips-and-tricks#inspecting-native-view-hierarchy) on my Android emulator and (as I expected) the UI has added accessibility labels, so it should be possible to tap on them like this:

```dart
await $.native.tap(Selector(text: "1"));
```

> I would like to run the tests in Firebase Test Labs and for this reason I need a set of physical devices that are PIN-locked.

I'm pretty sure FTL doesn't support it.

**Comment by bartekpacia** [comment]
Closing to clean up the backlog. We don't plan to add such features.
