### ISSUE TITLE
When triggering Hot Restart for the first time after the test starts, the user has to click enter

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1065]
Steps to reproduce:
1. Run `patrol develop -t <test file>
2. Wait for message that hot restart is ready
3. Press `r`

Nothing happens until user presses enter. Occurs only first time per test run.

**Comment by bartekpacia** [comment]
Cannot reproduce it on macOS :( Maybe it's windows specific? 

Did you encounter this while testing `customer: budowa`? Which test was that?

**Comment by jBorkowska** [comment]
Check on WIndows, it's happening every time to me.

**Comment by bartekpacia** [comment]
I don't have access to a Windows machine.

**Comment by bartekpacia** [comment]
Action item: run some example app tests on Windows with Hot Restart.

If it works, let's close this issue.

**Comment by bartekpacia** [comment]
I think this is a duplicate of #1365, which was fixed in #1377.

**Comment by bartekpacia** [comment]
No response - closing.
