### ISSUE TITLE
Fix resolution of iOS specific values

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1089]
Discovered while investigating and fixing #1067.

For Flutter to build a complete iOS apk, only a flavor is needed:

```console
flutter build ios -t integration_test/daily_mission_test.dart --flavor dev
```

But for Patrol, the user has to specify `configuration` and `scheme` explicitly:

```console
patrol develop -t integration_test/daily_mission_test.dart --flavor dev --configuration Debug-dev --scheme dev
```

Let's make `patrol` work like `flutter`.

**Comment by Albert221** [comment]
I believe this is related: [The workspace named "Runner" does not contain a scheme named "Runner". error for Flutter integration test with patrol in iOS](https://stackoverflow.com/questions/75718822/the-workspace-named-runner-does-not-contain-a-scheme-named-runner-error-for)
