### ISSUE TITLE
If `scrollTo` haven't found any visible widget, it scrolls to first invisible widget matching provided finder

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1091]
This bug results in a strange behavior, when partol scrolls to maximum iterations of scrolling, but after that `ensureVisible` is called on a finder without `.hitTestable()` and it goes (may go) to a widget, which is invisible (in our case - up). Test does not fail (accidentally), but takes longer bc of unnecessary scrolling.

**Comment by bartekpacia** [comment]
@jBorkowska Could you please provide more info about this problem? Who encountered this?

**Comment by jBorkowska** [comment]
Yes, @zoskar has encountered it.

**Comment by bartekpacia** [comment]
This is likely related to [this line](https://github.com/leancodepl/patrol/blob/7aa3e5c1234cd87b31ad2ed0b058d76928e869a1/packages/patrol/lib/src/custom_finders/patrol_tester.dart#L435).

**Comment by jBorkowska** [comment]
To check after scrolling rework

**Comment by jBorkowska** [comment]
No longer relevant bc of scrolling rework

**Comment by jBorkowska** [comment]
No longer relevant bc of scrolling rework
