### ISSUE TITLE
Error on patrol test " No .xctestrun file was found"

### ISSUE THREAD

**Issue by AlexisDeslandes** [leancodepl/patrol#1105]
**Describe the bug**

When I run command:
`patrol test --flavor qa` I get "No .xctestrun file was found at .../build/ios_integ/Build/Products

My tests were successfully running few weeks ago, with different versions and patrol drive.

**To Reproduce**

1. Run `patrol test --flavor qa`
2. Logs: 

No device specified, using the first one (iPhone 14 Pro)
Every test target will be run 1 time(s)
• Building app with entrypoint authentication_test.dart for iOS simulator...
✓ Completed building app with entrypoint authentication_test.dart for iOS simulator (37.7s)
• Running app with entrypoint authentication_test.dart for iOS simulator on simulator iPhone 14 Pro...
Error: No .xctestrun file was found at .../build/ios_integ/Build/Products
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
 FAIL  authentication_test.dart on iPhone 14 Pro

**Expected behavior**

The test should run.

**Device information**

- Device: iPhone 14 pro simulator
- OS version: iOs 16.2
- Does it also both on physical and virtual devices? [Yes, no, didn't check] Didn't check

<details>
<summary>Additional information</summary>

Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12cb4eb7a0 (3 weeks ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93
Tools • Dart 2.19.3 • DevTools 2.20.1

patrol: ^1.0.8

patrol_cli v1.1.0

</details>

**Comment by bartekpacia** [comment]
Hi @AlexisDeslandes, sorry for the problems!

Can you show me the output of `ls -lAh build/ios_integ/Build/Products`?

**Comment by bartekpacia** [comment]
It might got broken by #1090

**Comment by AlexisDeslandes** [comment]
Sorry mistake I forgot that,
the file is here.

`ls -lAh build/ios_integ/Build/Products 
total 8
drwxr-xr-x@ 82 adeslandes  staff   2.6K Mar 21 16:01 Debug-qa-iphonesimulator
-rw-r--r--   1 adeslandes  staff   439B Mar 21 16:40 qa_iphonesimulator16.2.xctestrun`

**Comment by AlexisDeslandes** [comment]
![Capture d’écran 2023-03-21 à 17 19 36](https://user-images.githubusercontent.com/22497285/226673273-c3c424a1-65c5-4673-b75b-1d2940653c28.png)
![Capture d’écran 2023-03-21 à 17 19 57](https://user-images.githubusercontent.com/22497285/226673276-80378f2c-6bb1-4548-821e-ca20a86da667.png)

**Comment by bartekpacia** [comment]
Looks good.

One last ask – could you run `patrol test --flavor qa --verbose` and show the log output? I'm interested in the part between invocations of `$ xcodebuild -showsdks -json` and `$ xcodebuild test-without-building -xctestrun ...` (they are blue, so should be easy to find - but paste the whole log anyway). Thanks!

**Comment by AlexisDeslandes** [comment]
No Rosetta is not enabled. Yes i'm on apple silicon.

```
$ xcodebuild -showsdks -json
Assuming SDK version 16.2 for iphonesimulator
Looking for .xctestrun matching qa_iphonesimulator16.2-*.xctestrun at /Users/adeslandes/work/enterprise/build/ios_integ/Build/Products
Error: No .xctestrun file was found at /Users/adeslandes/work/enterprise/build/ios_integ/Build/Products
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend._xcTestRunPath (package:patrol_cli/src/ios/ios_test_backend.dart:240:7)
<asynchronous suspension>
#2      IOSTestBackend.execute.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:152:15)
<asynchronous suspension>
#3      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#4      IOSTestBackend.execute (package:patrol_cli/src/ios/ios_test_backend.dart:137:5)
<asynchronous suspension>
#5      TestCommand._executorFor.<anonymous closure> (package:patrol_cli/src/commands/test.dart:273:9)
<asynchronous suspension>
#6      _NativeTestRunner.run.runTestsOnDevice (package:patrol_cli/src/test_runner.dart:243:15)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#8      _NativeTestRunner.run (package:patrol_cli/src/test_runner.dart:258:5)
<asynchronous suspension>
#9      TestCommand.run (package:patrol_cli/src/commands/test.dart:182:21)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:284:18)
<asynchronous suspension>
#12     PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:223:18)
<asynchronous suspension>
#13     patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:47:20)
<asynchronous suspension>
#14     main (file:///Users/adeslandes/.pub-cache/hosted/pub.dev/patrol_cli-1.1.0/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
 FAIL  authentication_test.dart on iPhone 14 Pro
```


xcodebuild test-without-building -xctestrun ... is never called.

**Comment by bartekpacia** [comment]
Okay, it's almost certainly a bug.

The fix is to change [these lines](https://github.com/leancodepl/patrol/blob/00c07f469b45e701bcb9bf79521ab19688c002b4/packages/patrol_cli/lib/src/ios/ios_test_backend.dart#L222-L232) to allow for no explicit specification of architecture.
