### ISSUE TITLE
Introduce a safe alternative to `PatrolFinder.waitUntilVisible()` that doesn't throw after timeout

### ISSUE THREAD

**Issue by ehabibov** [leancodepl/patrol#1113]
Feature request:

Sometimes there are cases when we expect something to appear on the screen (after transition for ex.) and have to skip it and continue. So we have to wait for that element(s) but they might appear and might not appear. So using `.waitUntilVisible()` is not appropriate for that case as if element(s) not appear we receive exception and execution failed.

I propose update [waiter](https://github.com/leancodepl/patrol/blob/master/packages/patrol/lib/src/custom_finders/patrol_finder.dart#L298) with smth like that `.waitUntilVisible({Duration? timeout, bool safe = false})` and setting optional `safe=true` if we want to wait for elem and not getting breaking exception in case nothing found.

**Comment by bartekpacia** [comment]
Hi @ehabibov 👋 Thanks for creating this issue!

This sounds good to me. We'll think about it. For now, I suggest you create an extension method `safeWaitUntilVisible`/`maybeWaitUntilVisible`/`tryWaitUntilVisible` yourself:

```dart
extension PatrolFinderX on PatrolFinder {
  Future<void> tryWaitUntilVisible({Duration? timeout}) async {
    try {
      await tester.waitUntilVisible(this, timeout: timeout);
    } on WaitUntilVisibleTimeoutException catch (_) {
      // do nothing, it's okay
    }
  }
}
}
```

**Comment by bartekpacia** [comment]
@ehabibov Let me know if the workaround works for you.

**Comment by ehabibov** [comment]
@bartekpacia yes, thank you, for hint. 
I'll let you know soon.

**Comment by ehabibov** [comment]
@bartekpacia I'm sorry for delay. Yes, workaround worked and totally eligible - thank you. Would be nice having that in repo but not urgent at all.
Might be a case for `.waitUntilExists()` also but not sure as don't get for now how does it work (as I see *all* participant elems in overall widget tree but `.waitUntilExists()` works like `.waitUntilVisible()` when `.waitUntilVisible()` does not work).

**Comment by jBorkowska** [comment]
We decided to not add this feature, workaround mentioned earlier can be used.
