### ISSUE TITLE
weird behavior when testing for iOS

### ISSUE THREAD

**Issue by wheeOs** [leancodepl/patrol#1116]
**Describe the bug**

I have written a simple integration test which is working and passing like a charm for Android. But for iOS the test gets run in a weird way. First of all, two _copys_ of the active iOS simulator get opened. Then multiple attempts to run the actual test are noticeable on one of the simulator instances. The actual test gets run after over 90 seconds. During those attempts a black view with the label "Test starting.." pops up multiple times. After finishing the actual test OSX's simulator application gets closed in such a way that I have to reopen the simulator manually when I want to rerun the test. For Android I can run the test repeatedly without having to reopen the emulator manually.  

log
```
wo@MacBook-Pro-von-W ridecube_mobile_app % patrol test --target integration_test/bundled_test.dart
No device specified, using the first one (iPhone 8 Plus)
Every test target will be run 1 time(s)
• Building app with entrypoint bundled_test.dart for iOS simulator (debug)...
✓ Completed building app with entrypoint bundled_test.dart for iOS simulator (45.6s)
• Running app with entrypoint bundled_test.dart for iOS simulator on simulator iPhone 8 Plus...
        2023-03-24 17:53:51.260 xcodebuild[28202:1147828] [MT] IDETestOperationsObserverDebug: 97.185 elapsed -- Testing started completed.
        2023-03-24 17:53:51.261 xcodebuild[28202:1147828] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
        2023-03-24 17:53:51.261 xcodebuild[28202:1147828] [MT] IDETestOperationsObserverDebug: 97.185 sec, +97.185 sec -- end
        2023-03-24 17:53:51.346 xcodebuild[28202:1147828] [MT] IDEResultKit: Warning: While writing a result bundle to /Users/wo/Library/Developer/Xcode/DerivedData/Runner-dibsnffrolqeqbcrlpdaxktfnmen/Logs/Test/Test-Runner-2023.03.24_17-52-14-+0100.xcresult, not all contents have been imported, as the Staging directory still contains the following files/directories: ["1_Test"]
✓ Completed executing app with entrypoint bundled_test.dart for iOS simulator on simulator iPhone 8 Plus (101.3s)
 PASS  bundled_test.dart on iPhone 8 Plus
```

screenshots of those simulator instances
![Bildschirmfoto 2023-03-24 um 17 52 59](https://user-images.githubusercontent.com/101183252/227590932-3cb2d5b6-d5c0-40b3-b463-690d01a981d4.png)

**To Reproduce**

just running `patrol test --target integration_test/bundled_test.dart` with the following test:
```dart
patrolTest(
          "dummy test",
          nativeAutomation: true, ($) async {

            await $.pumpWidgetAndSettle(MaterialApp(builder: (_, __) =>const Center(child: Text("foo"))));

            expect($(Center), findsOneWidget, reason: "should display onboarding slider");
      });
```

  

**Expected behavior**

Having a test execution for iOS as smooth and quick as in Android.

**Device information**

- Device: any iphone simulator
- OS version: iOS 16.0
- Does it also both on physical and virtual devices? didn't check

  

<details>
<summary>Additional information</summary>

Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (2 weeks ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1

patrol: ^1.0.6

patrol_cli v1.1.1

</details>

**Additional context**

**Comment by bartekpacia** [comment]
Hi @wheeOs, thanks for creating the issue and sorry for the problems.

I think your problem stems from the default setting when running UI tests on iOS - that a new iOS Simulator is created for a new test run. See [this answer](https://github.com/leancodepl/patrol/issues/910#issuecomment-1425752147) to see how to disable it. Let me know if this helps you.

**Comment by wheeOs** [comment]
hi @bartekpacia, thanks! That, at least, fixed the issue with the multiple simulator instances and test restarts (- 30 secs). But still the issue concerning multiple reattempts remains. Thus that simple test still takes more than 60 secs.

Here is how it looks like. By the way, you'll notice a screen orientation switch behavior

![patrol_ios_test_reattempts](https://user-images.githubusercontent.com/101183252/227891842-7b2c6aab-bebc-481f-a277-7f8c6eb243ad.gif)

**Comment by wheeOs** [comment]
Fortunately I could fix the last mentioned issue! While we are on the subject of "default settings", I noticed that I also had to disable `RunnerUITestsLaunchTests`, which exists in flutter by default

<img width="545" alt="image" src="https://user-images.githubusercontent.com/101183252/227893626-7bebea27-16fc-4947-9b10-7e8d92780aa9.png">

**Comment by brtbrt** [comment]
> Fortunately I could fix the last mentioned issue! While we are on the subject of "default settings", I noticed that I also had to disable `RunnerUITestsLaunchTests`, which exists in flutter by default

made my day ❤️
