### ISSUE TITLE
Our all WebView tests on both iOS and Android are failing

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1139]
We should get them fixed, it's an important feature and we should continuously verify it.

```
 FAIL  webview_hackernews_test.dart on emulator-5554
 FAIL  webview_leancode_test.dart on emulator-5554
 FAIL  webview_login_test.dart on emulator-5554
 FAIL  webview_stackoverflow_test.dart on emulator-5554
```

cc @mateuszwojtczak @jBorkowska

**Comment by samderlust** [comment]
I guess it's related to native screen? we can not tap only. currently I'm having issue with testing with map. there is noway to tap on the map. patrol doesn't have `tapAt`

**Comment by bartekpacia** [comment]
Nope, it's not that. [We do support tapping on native views](https://patrol.leancode.co/native/usage#basics), it's one of our main features.

Patrol doesn't have `tap at coordinates` because it's non-portable between devices.

**Comment by superjantung** [comment]
Which version does this web view interaction work in? I need to use it.

**Comment by bartekpacia** [comment]
Note for the future: see [this](https://github.com/bartekpacia/Landmarks/blob/75e1fbe1ef3013b04f7a3ce8c57adaebef95c030/LandmarksUITests/LandmarksUITests.swift#L12-L37), that might help with webviews on iOS.

**Comment by bartekpacia** [comment]
@superjantung Always use the newest versions. There are problems though (that's why this issue exists). [Here](https://github.com/leancodepl/patrol/issues/244#issuecomment-1542164972)'s a possible workaround for the time being.

**Comment by bartekpacia** [comment]
@fylyppo What's the status of this?

**Comment by bartekpacia** [comment]
Now we have most of WebView tests passing, but they're flaky nevertheless. Closing this in favor of #244.
