### ISSUE TITLE
Unable to update to latest version 1.1.3

### ISSUE THREAD

**Issue by PeterBriggsGreggs** [leancodepl/patrol#1143]
Hi,
I tried running the patrol update command however the update process failed to download all the required artifacts. Message below are from the terminal in AS:
peterbriggs@Peters-MacBook-Pro-2 gotg_apps_grecords % patrol update
✓ New patrol_cli version is available (1.1.3) (0.4s)
✓ Updated patrol_cli to version 1.1.3 (4.1s)
✗ Failed to download artifacts for version 1.1.3 (0.4s)
Exception: Failed to download Artifact.archive(name: AutomatorServer-iphoneos-arm64, version: 1.1.3, ext: app) from https://github.com/leancodepl/patrol/releases/download/patrol_cli-v1.1.3/AutomatorServer-iphoneos-arm64-1.1.3.zip
#0      ArtifactsRepository._downloadArtifact (package:patrol_cli/src/common/artifacts_repository.dart:295:7)
<asynchronous suspension>
#1      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
<asynchronous suspension>
#2      ArtifactsRepository.downloadArtifacts (package:patrol_cli/src/common/artifacts_repository.dart:279:5)
<asynchronous suspension>
#3      UpdateCommand.run (package:patrol_cli/src/features/update/update_command.dart:76:7)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#5      PatrolCommandRunner.runCommand (package:patrol_cli/src/command_runner.dart:291:18)
<asynchronous suspension>
#6      PatrolCommandRunner.run (package:patrol_cli/src/command_runner.dart:235:18)
<asynchronous suspension>
#7      patrolCommandRunner (package:patrol_cli/src/command_runner.dart:52:14)
<asynchronous suspension>
#8      main (file:///Users/peterbriggs/.pub-cache/hosted/pub.dartlang.org/patrol_cli-0.8.2+1/bin/main.dart:6:20)
<asynchronous suspension>

When clicking on the link failing link, the following web page is displayed, with a Not Found message:
![image](https://user-images.githubusercontent.com/86053215/228551102-7d6effd3-f6a6-47bd-8264-7aac522d017f.png)

Please can you investigate this issue.
Thank you

**Comment by bartekpacia** [comment]
Hi @PeterBriggsGreggs, sorry for the problems. This issue [was already mentioned here](https://github.com/leancodepl/patrol/discussions/1099), and the solution mentioned there should work for you as well. Tell me if it helps!

**Comment by PeterBriggsGreggs** [comment]
Hi,
No...  following the suggestions made in the other issue didn't work. 
Deactivating and reactivating didn't install version 1.1.3
Below is a verbose flutter doctor which shows Dart version as 2.19.5
Any other suggestions most welcome.

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/86053215/228554106-e29ab8ac-7ae7-4e7c-a332-b310f7fa6f1c.png">

**Comment by bartekpacia** [comment]
I think the cause is here: "Warning: `dart` on your path resolves to ...". So `dart` resolves to Dart 2.17, which is not supported by Patrol CLI, which requires at least Dart 2.18.

PS Next time, copy the text from terminal and paste it, instead of attaching a screenshot.

**Comment by bartekpacia** [comment]
Please also show output of `patrol doctor`.

**Comment by PeterBriggsGreggs** [comment]
Patrol Doctor details:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/86053215/228556698-68db967f-c311-4c7f-a4b0-824c35662fb4.png">

**Comment by bartekpacia** [comment]
You need Dart 2.18.

Please run `dart --version` and see that your version of Dart is probably older.

**Comment by bartekpacia** [comment]
`flutter doctor` output you shared hints at the problem:
```
Warning: dart on your path resolves to /us/local/Cellar/dart/2.17.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/peterbriggs/flutter. Consider adding
/Users/peterbriggs/flutter/bin to the front of your path.
```

That's because you actually have two `dart`s installed on your PC. Flutter comes with its own Dart, so make sure to uninstall any Dart that is not from Flutter. Looks like you installed `dart` with Homebrew, so uninstall it: `brew uninstall dart`.

**Comment by bartekpacia** [comment]
> That's because you actually have two `dart`s installed on your PC. Flutter comes with its own Dart, so make sure to uninstall any Dart that is not from Flutter.

No, as long as `dart` in your IDE is the same as the `dart` command from your command-line.

Good decision with using `fvm` - I use it too. Just do `fvm install <your_version>` and `fvm global <your_version>` (e.g. `fvm install stable` and `fvm global stable`) and it will download and set up the newest Flutter and Dart.

**Comment by PeterBriggsGreggs** [comment]
I've uninstalled Dart.
I've checked the dart version after the uninstall and it shows 2.19.5
I've run patrol update and received these messages below:
<img width="915" alt="image" src="https://user-images.githubusercontent.com/86053215/228561843-89d85dfd-10fa-4f68-8faa-a7a72ec963d4.png">

**Comment by bartekpacia** [comment]
Nice, now the last step is to install and compile `patrol_cli` again, because it was first compiled on an older Dart version and it can't work on a newer.

```console
dart pub global deactivate patrol_cli
```

```console
dart pub global activate patrol_cli
```

If this works, please close the issue :)

**Comment by PeterBriggsGreggs** [comment]
Yes... that's worked.
Thank you for your help and support
