### ISSUE TITLE
Stuck on testing started 

### ISSUE THREAD

**Issue by zachary22321** [leancodepl/patrol#1149]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

I am writing a native test in iOS.
Using the example provided in the documentation.
The simulator starts, but then it hangs on a screen that says:
Test starting....

I run this by selecting product->test

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

void main() {
  patrolTest(
    'counter state is the same after going to home and switching apps',
    nativeAutomation: true,
        ($) async {
      // Replace later with your app's main widget
      await $.pumpWidgetAndSettle(
        MaterialApp(
          home: Scaffold(
            appBar: AppBar(title: const Text('app')),
            backgroundColor: Colors.blue,
          ),
        ),
      );

      expect($('app'), findsOneWidget);
      await $.native.pressHome();
    },
  );
}

### Actual results

The simulator starts, but then it hangs on a screen that says:
Test starting....

When I run from the command line (of which the logs are included) I don't even get to the test starting screen

### Logs

<details>
<summary>Logs</summary>

uswrname@Zacharys-Mac-mini save_extra_money % patrol test --target integration_test/example_test.dart -v
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/uswrname/Development/save_extra_money/integration_test/example_test.dart
$ flutter --no-version-check devices --machine
No device specified, using the first one (iPhone 14)
Received 1 device(s) to run on
Received device: iPhone 14
Every test target will be run 1 time(s)
Received 5 --dart-define(s) (0 custom, 5 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=money.saveextra.save_extra_money
Received internal --dart-define: PATROL_APP_BUNDLE_ID=money.saveextra.save_extra_money
Received internal --dart-define: PATROL_ANDROID_APP_NAME=save_extra_money
Received internal --dart-define: PATROL_IOS_APP_NAME=save_extra_money
• Building app with entrypoint example_test.dart for iOS simulator (debug)...
$ flutter build ios --no-version-check --config-only --no-codesign --debug --simulator --target /Users/uswrname/Development/save_extra_money/integration_test/example_test.dart --dart-define PATROL_WAIT=0 --dart-define PATROL_APP_PACKAGE_NAME=money.saveextra.save_extra_money --dart-define PATROL_APP_BUNDLE_ID=money.saveextra.save_extra_money --dart-define PATROL_ANDROID_APP_NAME=save_extra_money --dart-define PATROL_IOS_APP_NAME=save_extra_money --dart-define PATROL_TEST_LABEL=example_test.dart
        Building money.saveextra.saveExtraMoney for simulator (ios)...
$ xcodebuild build-for-testing -workspace Runner.xcworkspace -scheme Runner -configuration Debug -sdk iphonesimulator -destination generic/platform=iOS Simulator -quiet -derivedDataPath ../build/ios_integ OTHER_SWIFT_FLAGS=$(inherited) -D PATROL_ENABLED
        ld: warning: dylib (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/flutter_appauth/flutter_appauth.framework/flutter_appauth) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        ld: warning: dylib (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/flutter_secure_storage/flutter_secure_storage.framework/flutter_secure_storage) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        ld: warning: dylib (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/integration_test/integration_test.framework/integration_test) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        ld: warning: dylib (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/local_auth_ios/local_auth_ios.framework/local_auth_ios) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        ld: warning: dylib (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/patrol/patrol.framework/patrol) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        ld: warning: dylib (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/uni_links/uni_links.framework/uni_links) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        ld: warning: dylib (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/url_launcher_ios/url_launcher_ios.framework/url_launcher_ios) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        ld: warning: object file (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/Pods_Runner.framework/Pods_Runner(Pods_Runner_vers.o)) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        ld: warning: object file (/Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Debug-iphonesimulator/Pods_Runner.framework/Pods_Runner(Pods-Runner-dummy.o)) was built for newer iOS Simulator version (13.0) than being linked (11.0)
        note: Building targets in dependency order
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIODarwin' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOAtomics' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOWindows' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOHTTPParser' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOBoringSSL' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CGRPCZlib' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'AppAuth' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOLinux' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'CNIOBoringSSLShims' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target '_NIODataStructures' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'Logging' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOConcurrencyHelpers' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftProtobuf' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOCore' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOEmbedded' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOPosix' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIO' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOTLS' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOFoundationCompat' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOHTTP1' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOExtras' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOTransportServices' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOSSL' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOHPACK' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'SwiftNIOHTTP2' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.2.99. (in target 'gRPC-Swift' from project 'Pods')
        /Users/uswrname/Development/save_extra_money/ios/Runner.xcodeproj: warning: The Copy Bundle Resources build phase contains this target's Info.plist file '/Users/uswrname/Development/save_extra_money/ios/Runner/Info-debug.plist'. (in target 'Runner' from project 'Runner')
        note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
        warning: Run script build phase 'xcode_backend build' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
        warning: Run script build phase 'xcode_backend embed_and_thin' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RunnerUITests' from project 'Runner')
✓ Completed building app with entrypoint example_test.dart for iOS simulator (46.9s)
• Running app with entrypoint example_test.dart for iOS simulator on simulator iPhone 14...
$ xcodebuild -showsdks -json
Assuming SDK version 16.2 for iphonesimulator
Looking for .xctestrun matching Runner_iphonesimulator16.2*.xctestrun at /Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products
Found 2 match(es), the first one will be used
Found /Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Runner_iphonesimulator16.2.xctestrun
Found /Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Runner_iphonesimulator16.2-arm64-x86_64.xctestrun
$ xcodebuild test-without-building -xctestrun /Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Runner_iphonesimulator16.2.xctestrun -destination platform=iOS Simulator,name=iPhone 14
        Command line invocation:
            /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /Users/uswrname/Development/save_extra_money/build/ios_integ/Build/Products/Runner_iphonesimulator16.2.xctestrun -destination "platform=iOS Simulator,name=iPhone 14"
        
        User defaults from command line:
            IDEPackageSupportUseBuiltinSCM = YES
        
        2023-03-29 22:26:07.372 xcodebuild[27080:24391854] Writing error result bundle to /var/folders/bv/s5ky2n_x58n50tn4ly02czyr0000gn/T/ResultBundle_2023-29-03_22-26-0007.xcresult
        xcodebuild: error: Failed to build workspace Runner with scheme Runner.
                Reason: There are no test bundles available to test.
                Recovery suggestion: Ensure that all package dependencies have resolved and that there are no missing test bundles in the active scheme or test plan.
✗ Failed to execute tests of app with entrypoint example_test.dart for iOS simulator on simulator iPhone 14 (xcodebuild exited with code 70) (2.9s)
Error: xcodebuild exited with code 70
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      IOSTestBackend.execute.<anonymous closure> (package:patrol_cli/src/ios/ios_test_backend.dart:182:9)
<asynchronous suspension>
#2      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)
<asynchronous suspension>
#3      IOSTestBackend.execute (package:patrol_cli/src/ios/ios_test_backend.dart:139:5)
<asynchronous suspension>
#4      TestCommand._executorFor.<anonymous closure> (package:patrol_cli/src/commands/test.dart:273:9)
<asynchronous suspension>
#5      _NativeTestRunner.run.runTestsOnDevice (package:patrol_cli/src/test_runner.dart:243:15)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#7      _NativeTestRunner.run (package:patrol_cli/src/test_runner.dart:258:5)
<asynchronous suspension>
#8      TestCommand.run (package:patrol_cli/src/commands/test.dart:182:21)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:284:18)
<asynchronous suspension>
#11     PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:223:18)
<asynchronous suspension>
#12     patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:47:20)
<asynchronous suspension>
#13     main (file:///Users/uswrname/.pub-cache/hosted/pub.dev/patrol_cli-1.1.3/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
$ xcrun simctl uninstall 3D4C71B2-821B-4605-9EAE-89DDC5CFC158 money.saveextra.save_extra_money
$ xcrun simctl uninstall 3D4C71B2-821B-4605-9EAE-89DDC5CFC158 money.saveextra.save_extra_money.RunnerUITests.xctrunner
 FAIL  example_test.dart on iPhone 14

</details>

### Patrol version

patrol_cli v1.1.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Say program not installed
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by zachary22321** [comment]
@bartekpacia 

I've gone though the instructions there 10 times and went through it again. I don't see anything that I have missed.

What step do you think I missed?

I have two problems.
1) When running in xcode using product/test it opens the simulator and starts the test, then hangs on Testing starting.... in the simulator.

2) When I run it from the command line I get the other error about no test bundles

**Comment by zachary22321** [comment]
I made a hello world project that has the issue and uploaded it to a public github here:
https://github.com/zachary22321/patrol_stuck_on_test_starting2

I can't run it through the command line as I get an error, but when I run it through product/test in xcode it hangs on a scrreen that says Test starting....

![Simulator Screen Shot - iPhone 14 - 2023-03-29 at 22 22 34](https://user-images.githubusercontent.com/88008051/228948448-b3d40463-e2a2-4fbf-a08f-c05c15bb8621.png)

**Comment by bartekpacia** [comment]
Great to hear that.

BTW you should only run tests through Patrol CLI (`patrol test`), or run apps that were pre-built with `patrol build`.

**Comment by roflo1** [comment]
For the record, I experienced the same hanging by adding a trivial test where nativeAutomation was set to false. Setting both tests to true didn't hang.
