### ISSUE TITLE
Gradle Build fails not finding Patrol classes 

### ISSUE THREAD

**Issue by PeterBriggsGreggs** [leancodepl/patrol#1161]
Hi,
I'm having problems getting the tests to run on the emulator or a physical device. I didn't have the Android configuration for running Native so I have added that, however, I also found that I was having problems with builds using the JDK version 19 which I had to install. After checking StackOverflow I found other people having problems with Gradle builds on JDK versions above JDK17. I have now down graded my Java JDK to openjdk-17 and set the necessary PATH details.

The problem I am now getting is to do with the builder not being able to find some Patrol classes that are needed for the build, as shown below.

Please can you tell me what I'm missing or doing wrong.
Thank you for you help.

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/86053215/229150473-4ebe4597-db73-41af-b133-70bf660071cd.png">

Patrol version: patrol_cli v1.1.3

Patrol Doctor details:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/86053215/229150323-22457765-470a-44f9-a5b5-cf49967641da.png">

### Contents of MainActivityTest.java

package uk.co.greggs.gotg_apps_grecords.unstable;

import org.junit.Rule;
import org.junit.runner.RunWith;
import pl.leancode.patrol.PatrolTestRule;
import pl.leancode.patrol.PatrolTestRunner;

https://github.com/RunWith(PatrolTestRunner.class)
public class MainActivityTest {
https://github.com/rule
public PatrolTestRule rule = new PatrolTestRule<>(MainActivity.class);
}

### Verbose output when running the test

peterbriggs@Peters-MBP-2 gotg_apps_grecords % patrol test --target integration_test/tests/login/login_test.dart --verbose
Verbose mode enabled. More logs will be printed.
Received 1 test target(s)
Received test target: /Users/peterbriggs/GOTG.Apps.GRecords/gotg_apps_grecords/integration_test/tests/login/login_test.dart
Received Android flavor: unstable
Received iOS flavor: unstable
$ flutter --no-version-check devices --machine
No device specified, using the first one (emulator-5554)
Received 1 device(s) to run on
Received device: emulator-5554
Every test target will be run 1 time(s)
Received 5 --dart-define(s) (0 custom, 5 internal)
Received internal --dart-define: PATROL_WAIT=0
Received internal --dart-define: PATROL_APP_PACKAGE_NAME=uk.co.greggs.gotg_apps_grecords.unstable
Received internal --dart-define: PATROL_APP_BUNDLE_ID=uk.co.greggs.gotg_apps_grecords.unstable
Received internal --dart-define: PATROL_ANDROID_APP_NAME=G-Records
Received internal --dart-define: PATROL_IOS_APP_NAME=G-Records
• Building apk with entrypoint login_test.dart...
$ ./gradlew :app:assembleUnstableDebug -Ptarget=/Users/peterbriggs/GOTG.Apps.GRecords/gotg_apps_grecords/integration_test/tests/login/login_test.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9dWsuY28uZ3JlZ2dzLmdvdGdfYXBwc19ncmVjb3Jkcy51bnN0YWJsZQ==,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9dWsuY28uZ3JlZ2dzLmdvdGdfYXBwc19ncmVjb3Jkcy51bnN0YWJsZQ==,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9Ry1SZWNvcmRz,UEFUUk9MX0lPU19BUFBfTkFNRT1HLVJlY29yZHM=,UEFUUk9MX1RFU1RfTEFCRUw9bG9naW5fdGVzdC5kYXJ0
:
: > Configure project :syncfusion_flutter_pdfviewer
: WARNING: The option setting 'android.enableR8=true' is deprecated.
: It will be removed in version 5.0 of the Android Gradle plugin.
: You will no longer be able to disable R8
:
: > Task :app:compileFlutterBuildUnstableDebug

    : 
    : > Task :app:compressUnstableDebugAssets
    : Execution optimizations have been disabled for task ':app:compressUnstableDebugAssets' to ensure correctness due to the following reasons:
    :   - Gradle detected a problem with the following location: '/Users/peterbriggs/GOTG.Apps.GRecords/gotg_apps_grecords/build/app/intermediates/merged_assets/unstableDebug/out'. Reason: Task ':app:compressUnstableDebugAssets' uses this output of task ':app:copyFlutterAssetsUnstableDebug' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
    : 
    : > Task :app:packageUnstableDebug UP-TO-DATE
    : > Task :app:assembleUnstableDebug
    : 
    : Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
    : 
    : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
    : 
    : See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
    : 
    : Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
    : Please consult deprecation warnings for more details.
    : 
    : BUILD SUCCESSFUL in 17s
    : 230 actionable tasks: 7 executed, 223 up-to-date
$ ./gradlew :app:assembleUnstableDebugAndroidTest -Ptarget=/Users/peterbriggs/GOTG.Apps.GRecords/gotg_apps_grecords/integration_test/tests/login/login_test.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9dWsuY28uZ3JlZ2dzLmdvdGdfYXBwc19ncmVjb3Jkcy51bnN0YWJsZQ==,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9dWsuY28uZ3JlZ2dzLmdvdGdfYXBwc19ncmVjb3Jkcy51bnN0YWJsZQ==,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9Ry1SZWNvcmRz,UEFUUk9MX0lPU19BUFBfTkFNRT1HLVJlY29yZHM=,UEFUUk9MX1RFU1RfTEFCRUw9bG9naW5fdGVzdC5kYXJ0
:
: > Configure project :syncfusion_flutter_pdfviewer
: WARNING: The option setting 'android.enableR8=true' is deprecated.
: It will be removed in version 5.0 of the Android Gradle plugin.
: You will no longer be able to disable R8
:
: > Task :app:preBuild UP-TO-DATE
: > Task :app:preUnstableDebugBuild UP-TO-DATE
: > Task :connectivity_plus:preBuild UP-TO-DATE
: > Task :connectivity_plus:preDebugBuild UP-TO-DATE
: > Task :connectivity_plus:compileDebugAidl NO-SOURCE
: > Task :flutter_plugin_android_lifecycle:preBuild UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:preDebugBuild UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:compileDebugAidl NO-SOURCE
: > Task :image_picker_android:preBuild UP-TO-DATE
: > Task :image_picker_android:preDebugBuild UP-TO-DATE
: > Task :image_picker_android:compileDebugAidl NO-SOURCE
: > Task :integration_test:preBuild UP-TO-DATE
: > Task :integration_test:preDebugBuild UP-TO-DATE
: > Task :integration_test:compileDebugAidl NO-SOURCE
: > Task :isar_flutter_libs:preBuild UP-TO-DATE
: > Task :isar_flutter_libs:preDebugBuild UP-TO-DATE
: > Task :isar_flutter_libs:compileDebugAidl NO-SOURCE
: > Task :move_to_background:preBuild UP-TO-DATE
: > Task :move_to_background:preDebugBuild UP-TO-DATE
: > Task :move_to_background:compileDebugAidl NO-SOURCE
: > Task :package_info_plus:preBuild UP-TO-DATE
: > Task :package_info_plus:preDebugBuild UP-TO-DATE
: > Task :package_info_plus:compileDebugAidl NO-SOURCE
: > Task :path_provider_android:preBuild UP-TO-DATE
: > Task :path_provider_android:preDebugBuild UP-TO-DATE
: > Task :path_provider_android:compileDebugAidl NO-SOURCE
: > Task :patrol:preBuild UP-TO-DATE
: > Task :patrol:preDebugBuild UP-TO-DATE
: > Task :patrol:compileDebugAidl NO-SOURCE
: > Task :syncfusion_flutter_pdfviewer:preBuild UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:preDebugBuild UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:compileDebugAidl NO-SOURCE
: > Task :url_launcher_android:preBuild UP-TO-DATE
: > Task :url_launcher_android:preDebugBuild UP-TO-DATE
: > Task :url_launcher_android:compileDebugAidl NO-SOURCE
: > Task :app:compileUnstableDebugAidl NO-SOURCE
: > Task :connectivity_plus:packageDebugRenderscript NO-SOURCE
: > Task :flutter_plugin_android_lifecycle:packageDebugRenderscript NO-SOURCE
: > Task :image_picker_android:packageDebugRenderscript NO-SOURCE
: > Task :integration_test:packageDebugRenderscript NO-SOURCE
: > Task :isar_flutter_libs:packageDebugRenderscript NO-SOURCE
: > Task :move_to_background:packageDebugRenderscript NO-SOURCE
: > Task :package_info_plus:packageDebugRenderscript NO-SOURCE
: > Task :path_provider_android:packageDebugRenderscript NO-SOURCE
: > Task :patrol:packageDebugRenderscript NO-SOURCE
: > Task :syncfusion_flutter_pdfviewer:packageDebugRenderscript NO-SOURCE
: > Task :url_launcher_android:packageDebugRenderscript NO-SOURCE
: > Task :app:compileUnstableDebugRenderscript NO-SOURCE
: > Task :app:generateUnstableDebugBuildConfig UP-TO-DATE
: > Task :connectivity_plus:writeDebugAarMetadata UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:writeDebugAarMetadata UP-TO-DATE
: > Task :image_picker_android:writeDebugAarMetadata UP-TO-DATE
: > Task :integration_test:writeDebugAarMetadata UP-TO-DATE
: > Task :isar_flutter_libs:writeDebugAarMetadata UP-TO-DATE
: > Task :move_to_background:writeDebugAarMetadata UP-TO-DATE
: > Task :package_info_plus:writeDebugAarMetadata UP-TO-DATE
: > Task :path_provider_android:writeDebugAarMetadata UP-TO-DATE
: > Task :patrol:writeDebugAarMetadata UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:writeDebugAarMetadata UP-TO-DATE
: > Task :url_launcher_android:writeDebugAarMetadata UP-TO-DATE
: > Task :app:checkUnstableDebugAarMetadata UP-TO-DATE
: > Task :app:generateUnstableDebugResValues UP-TO-DATE
: > Task :app:generateUnstableDebugResources UP-TO-DATE
: > Task :connectivity_plus:compileDebugRenderscript NO-SOURCE
: > Task :connectivity_plus:generateDebugResValues UP-TO-DATE
: > Task :connectivity_plus:generateDebugResources UP-TO-DATE
: > Task :connectivity_plus:packageDebugResources UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:compileDebugRenderscript NO-SOURCE
: > Task :flutter_plugin_android_lifecycle:generateDebugResValues UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:generateDebugResources UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:packageDebugResources UP-TO-DATE
: > Task :image_picker_android:compileDebugRenderscript NO-SOURCE
: > Task :image_picker_android:generateDebugResValues UP-TO-DATE
: > Task :image_picker_android:generateDebugResources UP-TO-DATE
: > Task :image_picker_android:packageDebugResources UP-TO-DATE
: > Task :integration_test:compileDebugRenderscript NO-SOURCE
: > Task :integration_test:generateDebugResValues UP-TO-DATE
: > Task :integration_test:generateDebugResources UP-TO-DATE
: > Task :integration_test:packageDebugResources UP-TO-DATE
: > Task :isar_flutter_libs:compileDebugRenderscript NO-SOURCE
: > Task :isar_flutter_libs:generateDebugResValues UP-TO-DATE
: > Task :isar_flutter_libs:generateDebugResources UP-TO-DATE
: > Task :isar_flutter_libs:packageDebugResources UP-TO-DATE
: > Task :move_to_background:compileDebugRenderscript NO-SOURCE
: > Task :move_to_background:generateDebugResValues UP-TO-DATE
: > Task :move_to_background:generateDebugResources UP-TO-DATE
: > Task :move_to_background:packageDebugResources UP-TO-DATE
: > Task :package_info_plus:compileDebugRenderscript NO-SOURCE
: > Task :package_info_plus:generateDebugResValues UP-TO-DATE
: > Task :package_info_plus:generateDebugResources UP-TO-DATE
: > Task :package_info_plus:packageDebugResources UP-TO-DATE
: > Task :path_provider_android:compileDebugRenderscript NO-SOURCE
: > Task :path_provider_android:generateDebugResValues UP-TO-DATE
: > Task :path_provider_android:generateDebugResources UP-TO-DATE
: > Task :path_provider_android:packageDebugResources UP-TO-DATE
: > Task :patrol:compileDebugRenderscript NO-SOURCE
: > Task :patrol:generateDebugResValues UP-TO-DATE
: > Task :patrol:generateDebugResources UP-TO-DATE
: > Task :patrol:packageDebugResources UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:compileDebugRenderscript NO-SOURCE
: > Task :syncfusion_flutter_pdfviewer:generateDebugResValues UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:generateDebugResources UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:packageDebugResources UP-TO-DATE
: > Task :url_launcher_android:compileDebugRenderscript NO-SOURCE
: > Task :url_launcher_android:generateDebugResValues UP-TO-DATE
: > Task :url_launcher_android:generateDebugResources UP-TO-DATE
: > Task :url_launcher_android:packageDebugResources UP-TO-DATE
: > Task :app:mergeUnstableDebugResources UP-TO-DATE
: > Task :app:createUnstableDebugCompatibleScreenManifests UP-TO-DATE
: > Task :app:extractDeepLinksUnstableDebug UP-TO-DATE
: > Task :connectivity_plus:extractDeepLinksDebug UP-TO-DATE
: > Task :connectivity_plus:processDebugManifest UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:extractDeepLinksDebug UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:processDebugManifest UP-TO-DATE
: > Task :image_picker_android:extractDeepLinksDebug UP-TO-DATE
: > Task :image_picker_android:processDebugManifest UP-TO-DATE
: > Task :integration_test:extractDeepLinksDebug UP-TO-DATE
: > Task :integration_test:processDebugManifest UP-TO-DATE
: > Task :isar_flutter_libs:extractDeepLinksDebug UP-TO-DATE
: > Task :isar_flutter_libs:processDebugManifest UP-TO-DATE
: > Task :move_to_background:extractDeepLinksDebug UP-TO-DATE
: > Task :move_to_background:processDebugManifest UP-TO-DATE
: > Task :package_info_plus:extractDeepLinksDebug UP-TO-DATE
: > Task :package_info_plus:processDebugManifest UP-TO-DATE
: > Task :path_provider_android:extractDeepLinksDebug UP-TO-DATE
: > Task :path_provider_android:processDebugManifest UP-TO-DATE
: > Task :patrol:extractDeepLinksDebug UP-TO-DATE
: > Task :patrol:processDebugManifest UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:extractDeepLinksDebug UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:processDebugManifest UP-TO-DATE
: > Task :url_launcher_android:extractDeepLinksDebug UP-TO-DATE
: > Task :url_launcher_android:processDebugManifest UP-TO-DATE
: > Task :app:processUnstableDebugMainManifest UP-TO-DATE
: > Task :app:processUnstableDebugManifest UP-TO-DATE
: > Task :app:processUnstableDebugManifestForPackage UP-TO-DATE
: > Task :connectivity_plus:compileDebugLibraryResources UP-TO-DATE
: > Task :connectivity_plus:parseDebugLocalResources UP-TO-DATE
: > Task :connectivity_plus:generateDebugRFile UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:compileDebugLibraryResources UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:parseDebugLocalResources UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:generateDebugRFile UP-TO-DATE
: > Task :image_picker_android:compileDebugLibraryResources UP-TO-DATE
: > Task :image_picker_android:parseDebugLocalResources UP-TO-DATE
: > Task :image_picker_android:generateDebugRFile UP-TO-DATE
: > Task :integration_test:compileDebugLibraryResources UP-TO-DATE
: > Task :integration_test:parseDebugLocalResources UP-TO-DATE
: > Task :integration_test:generateDebugRFile UP-TO-DATE
: > Task :isar_flutter_libs:compileDebugLibraryResources UP-TO-DATE
: > Task :isar_flutter_libs:parseDebugLocalResources UP-TO-DATE
: > Task :isar_flutter_libs:generateDebugRFile UP-TO-DATE
: > Task :move_to_background:compileDebugLibraryResources UP-TO-DATE
: > Task :move_to_background:parseDebugLocalResources UP-TO-DATE
: > Task :move_to_background:generateDebugRFile UP-TO-DATE
: > Task :package_info_plus:compileDebugLibraryResources UP-TO-DATE
: > Task :package_info_plus:parseDebugLocalResources UP-TO-DATE
: > Task :package_info_plus:generateDebugRFile UP-TO-DATE
: > Task :path_provider_android:compileDebugLibraryResources UP-TO-DATE
: > Task :path_provider_android:parseDebugLocalResources UP-TO-DATE
: > Task :path_provider_android:generateDebugRFile UP-TO-DATE
: > Task :patrol:compileDebugLibraryResources UP-TO-DATE
: > Task :patrol:parseDebugLocalResources UP-TO-DATE
: > Task :patrol:generateDebugRFile UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:compileDebugLibraryResources UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:parseDebugLocalResources UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:generateDebugRFile UP-TO-DATE
: > Task :url_launcher_android:compileDebugLibraryResources UP-TO-DATE
: > Task :url_launcher_android:parseDebugLocalResources UP-TO-DATE
: > Task :url_launcher_android:generateDebugRFile UP-TO-DATE
: > Task :app:processUnstableDebugResources UP-TO-DATE
: > Task :connectivity_plus:generateDebugBuildConfig UP-TO-DATE
: > Task :connectivity_plus:javaPreCompileDebug UP-TO-DATE
: > Task :connectivity_plus:compileDebugJavaWithJavac UP-TO-DATE
: > Task :connectivity_plus:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:generateDebugBuildConfig UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:javaPreCompileDebug UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:compileDebugJavaWithJavac UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :image_picker_android:generateDebugBuildConfig UP-TO-DATE
: > Task :image_picker_android:javaPreCompileDebug UP-TO-DATE
: > Task :image_picker_android:compileDebugJavaWithJavac UP-TO-DATE
: > Task :image_picker_android:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :integration_test:generateDebugBuildConfig UP-TO-DATE
: > Task :integration_test:javaPreCompileDebug UP-TO-DATE
: > Task :integration_test:compileDebugJavaWithJavac UP-TO-DATE
: > Task :integration_test:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :isar_flutter_libs:generateDebugBuildConfig UP-TO-DATE
: > Task :isar_flutter_libs:javaPreCompileDebug UP-TO-DATE
: > Task :isar_flutter_libs:compileDebugJavaWithJavac UP-TO-DATE
: > Task :isar_flutter_libs:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :move_to_background:generateDebugBuildConfig UP-TO-DATE
: > Task :move_to_background:javaPreCompileDebug UP-TO-DATE
: > Task :move_to_background:compileDebugJavaWithJavac UP-TO-DATE
: > Task :move_to_background:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :package_info_plus:generateDebugBuildConfig UP-TO-DATE
: > Task :package_info_plus:compileDebugKotlin UP-TO-DATE
: > Task :package_info_plus:javaPreCompileDebug UP-TO-DATE
: > Task :package_info_plus:compileDebugJavaWithJavac UP-TO-DATE
: > Task :package_info_plus:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :path_provider_android:generateDebugBuildConfig UP-TO-DATE
: > Task :path_provider_android:javaPreCompileDebug UP-TO-DATE
: > Task :path_provider_android:compileDebugJavaWithJavac UP-TO-DATE
: > Task :path_provider_android:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :patrol:generateDebugBuildConfig UP-TO-DATE
: > Task :patrol:extractDebugProto UP-TO-DATE
: > Task :integration_test:processDebugJavaRes NO-SOURCE
: > Task :integration_test:bundleLibResDebug NO-SOURCE
: > Task :integration_test:bundleLibRuntimeToJarDebug UP-TO-DATE
: > Task :integration_test:createFullJarDebug UP-TO-DATE
: > Task :patrol:extractIncludeDebugProto UP-TO-DATE
: > Task :patrol:extractProto UP-TO-DATE
: > Task :patrol:generateDebugProto NO-SOURCE
: > Task :patrol:compileDebugKotlin UP-TO-DATE
: > Task :patrol:javaPreCompileDebug UP-TO-DATE
: > Task :patrol:compileDebugJavaWithJavac UP-TO-DATE
: > Task :patrol:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:generateDebugBuildConfig UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:javaPreCompileDebug UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:compileDebugJavaWithJavac UP-TO-DATE
: > Task :syncfusion_flutter_pdfviewer:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :url_launcher_android:generateDebugBuildConfig UP-TO-DATE
: > Task :url_launcher_android:javaPreCompileDebug UP-TO-DATE
: > Task :url_launcher_android:compileDebugJavaWithJavac UP-TO-DATE
: > Task :url_launcher_android:bundleLibCompileToJarDebug UP-TO-DATE
: > Task :app:javaPreCompileUnstableDebug UP-TO-DATE
: > Task :app:preUnstableDebugAndroidTestBuild SKIPPED
: > Task :app:compileUnstableDebugAndroidTestAidl NO-SOURCE
: > Task :app:processUnstableDebugAndroidTestManifest UP-TO-DATE
: > Task :app:compileUnstableDebugAndroidTestRenderscript NO-SOURCE
: > Task :app:generateUnstableDebugAndroidTestBuildConfig UP-TO-DATE
: > Task :app:checkUnstableDebugAndroidTestAarMetadata UP-TO-DATE
: > Task :app:generateUnstableDebugAndroidTestResValues UP-TO-DATE
: > Task :app:generateUnstableDebugAndroidTestResources UP-TO-DATE
: > Task :app:mergeUnstableDebugAndroidTestResources UP-TO-DATE
: > Task :app:processUnstableDebugAndroidTestResources UP-TO-DATE
: > Task :app:javaPreCompileUnstableDebugAndroidTest UP-TO-DATE
: > Task :app:mergeUnstableDebugAndroidTestShaders UP-TO-DATE
: > Task :app:compileUnstableDebugAndroidTestShaders NO-SOURCE
: > Task :app:generateUnstableDebugAndroidTestAssets UP-TO-DATE
: > Task :connectivity_plus:mergeDebugShaders UP-TO-DATE
: > Task :connectivity_plus:compileDebugShaders NO-SOURCE
: > Task :connectivity_plus:generateDebugAssets UP-TO-DATE
: > Task :connectivity_plus:packageDebugAssets UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:mergeDebugShaders UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:compileDebugShaders NO-SOURCE
: > Task :flutter_plugin_android_lifecycle:generateDebugAssets UP-TO-DATE
: > Task :flutter_plugin_android_lifecycle:packageDebugAssets UP-TO-DATE
: > Task :image_picker_android:mergeDebugShaders UP-TO-DATE
: > Task :image_picker_android:compileDebugShaders NO-SOURCE
: > Task :image_picker_android:generateDebugAssets UP-TO-DATE
: > Task :app:compileUnstableDebugKotlin
: > Task :image_picker_android:packageDebugAssets UP-TO-DATE
: > Task :app:compileUnstableDebugJavaWithJavac UP-TO-DATE
: > Task :app:bundleUnstableDebugClasses UP-TO-DATE
: > Task :app:compileUnstableDebugAndroidTestKotlin NO-SOURCE
:
: > Task :app:compileUnstableDebugAndroidTestJavaWithJavac FAILED
/Users/peterbriggs/GOTG.Apps.GRecords/gotg_apps_grecords/android/app/src/androidTest/java/uk/co/greggs/gotg_apps_grecords/unstable/MainActivityTest.java:11: error: cannot find symbol
public PatrolTestRule rule = new PatrolTestRule<>(MainActivity.class);
^
symbol: class MainActivity
location: class MainActivityTest
/Users/peterbriggs/GOTG.Apps.GRecords/gotg_apps_grecords/android/app/src/androidTest/java/uk/co/greggs/gotg_apps_grecords/unstable/MainActivityTest.java:11: error: cannot find symbol
public PatrolTestRule rule = new PatrolTestRule<>(MainActivity.class);
^
symbol: class MainActivity
location: class MainActivityTest
2 errors

    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':app:compileUnstableDebugAndroidTestJavaWithJavac'.
    > Compilation failed; see the compiler error output for details.
    
    * Try:
    > Run with --stacktrace option to get the stack trace.
    > Run with --info or --debug option to get more log output.
    > Run with --scan to get full insights.
    
    * Get more help at https://help.gradle.org
    
    BUILD FAILED in 4s
    : 
    : Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
    : 
    : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
    : 
    : See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
    : 168 actionable tasks: 2 executed, 166 up-to-date
✗ Failed to build apk with entrypoint login_test.dart (Gradle build failed with code 1) (22.6s)
Exception: Gradle build failed with code 1
#0 AndroidTestBackend.build. (package:patrol_cli/src/android/android_test_backend.dart:90:9)

https://github.com/leancodepl/patrol/issues/1 DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:44:7)

https://github.com/leancodepl/patrol/issues/2 AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)

https://github.com/leancodepl/patrol/issues/3 TestCommand._builderFor. (package:patrol_cli/src/commands/test.dart:222:9)

https://github.com/leancodepl/patrol/issues/4 _NativeTestRunner.run.runTestsOnDevice (package:patrol_cli/src/test_runner.dart:230:13)

https://github.com/leancodepl/patrol/issues/5 Future.wait. (dart:async/future.dart:522:21)

https://github.com/leancodepl/patrol/issues/6 _NativeTestRunner.run (package:patrol_cli/src/test_runner.dart:258:5)

https://github.com/leancodepl/patrol/issues/7 TestCommand.run (package:patrol_cli/src/commands/test.dart:182:21)

https://github.com/leancodepl/patrol/issues/8 CommandRunner.runCommand (package:args/command_runner.dart:212:13)

https://github.com/leancodepl/patrol/issues/9 PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:284:18)

https://github.com/leancodepl/patrol/issues/10 PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:223:18)

https://github.com/leancodepl/patrol/issues/11 patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:47:20)

https://github.com/leancodepl/patrol/issues/12 main (file:///Users/peterbriggs/.pub-cache/hosted/pub.dev/patrol_cli-1.1.3/bin/main.dart:6:20)

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
FAIL login_test.dart on emulator-5554
peterbriggs@Peters-MBP-2 gotg_apps_grecords %

**Comment by bartekpacia** [comment]
I don't think Java 17 works well with Flutter. Why don't you use JDK 11?

**Comment by PeterBriggsGreggs** [comment]
I have downgraded to Java 11 and set the JAVA_HOME path, however I am still getting the same problem as described above.

Regarding the template, is it easier to close this call and for me to open a new one using the template or is there a way to convert the issue to follow the template style ?
Thank you.

**Comment by PeterBriggsGreggs** [comment]
Closing this issue and re-opening it using the main bug template
