### ISSUE TITLE
Possibility to disable logging native commands

### ISSUE THREAD

**Issue by fylyppo** [leancodepl/patrol#1176]
I have suggestion to add option to disable logging native commands.

 I use looped `$.native.getNativeViews` and my output from `flutter logs` looks like:

<img width="651" alt="Zrzut ekranu 2023-04-4 o 17 18 24" src="https://user-images.githubusercontent.com/63547653/229842090-0ffb3187-33d8-4f6e-9c11-767b978c8f74.png">

**Comment by bartekpacia** [comment]
Adding `patrol_cli` label because I think we'll also want a possibility to disable these logs with some CLI flag. We could re-use `--verbose` for it (if passed, then print the native logs), but I don't think it's a good idea – `--verbose` is a bit different thing.

We can add a

**Comment by ReubenTurner-esusu** [comment]
@bartekpacia We need to be able to do custom logging with patrol, is there any movement on adding `nativeAutomatorLogger` as an argument to the `PatrolTester` constructor so it can be used inside `patrolTest`?
