### ISSUE TITLE
`patrol test` - assume FLAK tests to PASS

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1181]
Requested by @fylyppo.

The tests in the project he works on are flaky.

He suggests adding a flag to `patrol_cli` to make `FLAK` tests become `PASS`:

![203557831-a99f6fa4-f9be-419b-89b7-7c17cc619304](https://user-images.githubusercontent.com/40357511/230058572-0bfd7c29-c315-4bca-9c81-d18689f7b035.png)

The tentative name for the flag: `--ignore-flakes`.

**Comment by bartekpacia** [comment]
@fylyppo can't just use `patrol test || true`, because then the exit code would be 0 even if all tests failed.

**Comment by fylyppo** [comment]
Maybe we can stay with FLAK output from test target (it gives me more info in tests summary) but let's change exit code for situation like:

 PASS  first_test.dart on emulator-5554
 PASS  second_test.dart on emulator-5554
 PASS  third_test.dart on emulator-5554
 FLAK  fourth_test.dart on emulator-5554
 FLAK  fifth_test.dart on emulator-5554
 
 to be "0".
 
 Reason: I have some listener for exit code and the goal is to know only about critical errors from test (only if test target fail every time).

**Comment by bartekpacia** [comment]
Good idea - I like it.

**Comment by bartekpacia** [comment]
We lost this feature in 2.0.

Action item for @bartekpacia: Check how Gradle-generated and Xcode-generated reports look like with repeated tests: https://stackoverflow.com/questions/39193268/run-espresso-test-multiple-times
Action item for @fylyppo : Check if repeating tests N times works on Firebase Test Lab

**Comment by bartekpacia** [comment]
This UI doesn't exist anymore since Patrol 2.0
