### ISSUE TITLE
CLI should define minimal supported `patrol` version

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1184]
So we won't break users in situations like #1185 (only internal implementation details changed, but users might experience errors if they use mismatched versions of `patrol` and `patrol_cli`).

Otherwise, we'll often break our users who don't upgrade.

This will catch only one side of errors: if the `patrol` version is lower than the minimal version of `patrol` supported by `patrol_cli`.

We'll also have to detect if the `patrol_cli` version is lower than the minimal version of `patrol_cli` support by `patrol`.

cc @mateuszwojtczak @jBorkowska

**Comment by bartekpacia** [comment]
#999 would be useful here.

**Comment by jBorkowska** [comment]
Idea: print info about minimal and maximal version of patrol, that patrol_cli works with. If we are in a project folder, we can verify, if patrol version in pubspec is compatible and if not, print warning. We could print such a warning when running tests etc., like we do about update.

**Comment by bartekpacia** [comment]
Idea: we could automatically generate the version compatibility table.

**Comment by jBorkowska** [comment]
Related to #1193

**Comment by jBorkowska** [comment]
Is it done @piotruela ?
