### ISSUE TITLE
Patrol on iOS requires RunnerUITests target to have explicit signing config 

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#1189]
There's lack of information in docs about this issue.
We should either allow for automatic signing or write explicitly about how to setup signing config in docs.
I'd prefer going with automatic signing path since requiring QA to have fastlane setup sounds cumbersome and not DX-friendly.

**Comment by bartekpacia** [comment]
We already allow automatic signing. In fact, I couldn't get Fastlane Match to work with the UI test target :|
