### ISSUE TITLE
how to seperate test 

### ISSUE THREAD

**Issue by abdalazeez1** [leancodepl/patrol#1199]
in integration test i used group and test to seperate test but that not work in patrol and cant find any thing about that in dcos can help me

**Comment by abdalazeez1** [comment]
> the

this is question is not bug 

how can use test and group func using patrol

**Comment by bartekpacia** [comment]
The same as in normal tests.

```dart
import 'package:test/test.dart';

void main() {
  group('String', () {
    patrolTest('some test 1', nativeAutomation: true, ($) {
      // ...
    });

    patrolTest('some test 2', nativeAutomation: true, ($) {
      // ...
    });
  });
}
```

**Comment by abdalazeez1** [comment]
> The same as in normal tests.
> 
> ```dart
> import 'package:test/test.dart';
> 
> void main() {
>   group('String', () {
>     patrolTest('some test 1', nativeAutomation: true, ($) {
>       // ...
>     });
> 
>     patrolTest('some test 2', nativeAutomation: true, ($) {
>       // ...
>     });
>   });
> }
> ```
thnaks 
can help me to add patrol test in configuration run in android studio

**Comment by abdalazeez1** [comment]
![Screenshot from 2023-04-15 17-28-55](https://user-images.githubusercontent.com/66934042/232491664-1877625d-ca76-41cd-9d12-b8eb3afb4b1d.png)

**Comment by abdalazeez1** [comment]
![Screenshot from 2023-04-17 15-59-30](https://user-images.githubusercontent.com/66934042/232491813-582ca15e-2354-4835-97e3-da1372d4109c.png)

**Comment by bartekpacia** [comment]
We don't support it. You have to use [`patrol test`](https://patrol.leancode.co/cli-commands/test). If you want to debug tests, you can also use [`patrol develop`](https://patrol.leancode.co/cli-commands/develop).
