### ISSUE TITLE
Investigate not being able to `tap()` on a widget without the explicit specification of `GestureDetector` finder

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1204]
@zoskar reported that he does:

```dart
await $(#someWidget).$(GestureDetector).tap();
```

to tap on `#someWidget`. He does so because this:

```dart
await $(#someWidget).tap();
```

doesn't work.

We need to investigate this problem and fix it (or, if we can't, explain it in the docs). I think it might be related to the [HitTestBehavior](https://api.flutter.dev/flutter/rendering/HitTestBehavior.html) of `#someWidget`.

**Comment by zoskar** [comment]
@bartekpacia putting widget keys deeper in widget tree (under GestureDetectors) fixed these cases for me, you can close the issue

**Comment by bartekpacia** [comment]
Thanks!
