### ISSUE TITLE
Example of photo attachments

### ISSUE THREAD

**Issue by Tamerlanchiques** [leancodepl/patrol#1216]
Hi, is there way to test attachment of photos?   

Like tap on some button in Flutter app UI -> choose photo from gallery.

**Comment by bartekpacia** [comment]
Hi 👋🏻

> is there way to test attachment of photos?

Yes, there is - in fact, we are doing it in one of the apps we're working on. Unfortunately I don't have the code I could share here.

This question was asked before [here](https://github.com/leancodepl/patrol/discussions/918) and [here](https://github.com/leancodepl/patrol/issues/635).

Essentially, you can accomplish what you want with `$.native.tap()`. To find what native views to tap on, you can make a [native view hierarchy dump](https://patrol.leancode.co/tips-and-tricks#inspecting-native-view-hierarchy).

**Comment by bartekpacia** [comment]
I think that our example app should have tests that demonstrate selecting photos and files from local storage.

cc @jBorkowska

**Comment by jBorkowska** [comment]
I created new issue, https://github.com/leancodepl/patrol/issues/2056, closing
