### ISSUE TITLE
Integration test stops after setUp call and returning "passed" mark

### ISSUE THREAD

**Issue by Tamerlanchiques** [leancodepl/patrol#1231]
Before test I would prepare database for it. So I use setUp function which calls function in API class for removing test user account from database if it exists because I will test user account registration and provide same data between tests.

```dart
class IntegrationTestApi with REST {
  Future<void> removeTesterAccountIfExists() async => delete('tester/account');
}
```

```dart
void main() {
  setUp(
    () {
      IntegrationTestApi().removeTesterAccountIfExists();
    },
  );

  patrolTest(
    'App started successfully',
    nativeAutomation: true,
    (PatrolTester $) async {
// …
``` 

But test completes as "passed" just after starting without any real work.

https://user-images.githubusercontent.com/11006352/234412454-6f136c17-1925-4b7b-a02c-9f6c5e4df242.mp4

Whats wrong?

**Comment by Tamerlanchiques** [comment]
API-calls not allowed in integration tests as in widget tests?

**Comment by bartekpacia** [comment]
> API-calls not allowed in integration tests as in widget tests?

They are allowed. App during integration testing behaves mostly like a real app.

> Whats wrong?

It's hard to tell just by looking at the code you provided. I'd say everything is fine – the app starts, the `expect()` passes, and that's it - end of test. What would you expect?
