### ISSUE TITLE
firebase test lab timing out wiht no test case results patrol 1.9 and 1.19

### ISSUE THREAD

**Issue by neiljaywarner** [leancodepl/patrol#1232]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

1.   - ./gradlew :app:assembleDevelopmentDebugAndroidTest
    - ./gradlew :app:assembleDevelopmentDebug -Ptarget="$(pwd)/../integration_test/firebase_test_lab_test.dart" -Pdart-defines="$(echo -n "blahblah=blah" | base64),$(echo -n "app.flavor=development" | base64)"
2. 
gcloud firebase test android run --type instrumentation --app "build/app/outputs/apk/development/debug/app-development-debug.apk" --test "build/app/outputs/apk/androidTest/development/debug/app-development-debug-androidTest.apk" --timeout 9m

### Actual results

firebase test lab times out bc no test cases - but passes witrh patrol 1.8
occurs even if the test run has no patrol or native autiomation.
in fact test is
`
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized(); // NEW

  group('Firebase Test Lab Grouped Tests', () {
    testWidgets('fexample2', (tester) async {
      expect(2 + 2, equals(4));
    });
    testWidgets('passing test example1', (tester) async {
      expect(2 + 1, equals(3));
    });
 
  });
}

`

### Patrol version

  patrol: ^1.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Program adb found in /Users/neil.warner/Library/Android/sdk/platform-tools//adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
Program ios-deploy not found (install with `brew install ios-deploy`)

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.7.10, on macOS 12.6.5 21G531 darwin-x64, locale en-US)
    • Flutter version 3.7.10 on channel stable at /Users/neil.warner/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (3 weeks ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/neil.warner/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • SM G960U1 (mobile)         • 594b4d3841563398                     • android-arm64  • Android 10 (API 29)
    • iPhone 14 Pro Max (mobile) • 82C9B50D-2C46-4C3C-956D-DCE3A3765896 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6.5 21G531 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

**Comment by bartekpacia** [comment]
To build tests for Firebase Test Lab (and similar cloud device labs, like emulator.wtf, etc.) you should use `patrol build android` or `patrol build ios`. [Learn more here](https://patrol.leancode.co/cli-commands/build).

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment and I'll be happy to continue the discussion.
