### ISSUE TITLE
Integration test router?

### ISSUE THREAD

**Issue by Tamerlanchiques** [leancodepl/patrol#1242]
In my integration tests I have many common 'routes'.

For example, I want to test adding transport feature that situated in user profile. For that, I go to user profile and then tap 'add transport' button and do some stuff. After that, I start next test that restarts app and testing user passport editing feature and goes to user profile again. 

That time I created file named `integration_test_routes.dart` and defined here a function:

```dart
import 'package:myapp/pages/pages_keys.dart';
import 'package:patrol/patrol.dart';

Future<void> goFromStartPageToUserProfilePage(PatrolTester $) async {
  await $(PK.mainMenuButton).tap();
  await $(PK.mainMenuDrawerProfileButton).tap();
}
```

Now I can just paste `goFromStartPageToUserProfilePage` function everywhere I need and don't make code dublicates.

But I think that more complex router is possible.

Like… lets define routes of application as "chains": "mainPage->userProfile", "mainPage->userProfile->userProfileEditPage", etc.

And our "go" function will be something like `go(from: 'mainPage', to: 'userProfile')` or `go(from: 'mainPage', to: 'userProfileEditPage')`, etc.

So… Intention of this issue is to find out if there are better options than mine and, maybe, to propose to implement a routing system in patrol library in the future.

**Comment by bartekpacia** [comment]
Hi again :)

If I understand correctly, you're testing many features of your app in a single `patrolTest()`? If yes, then we consider it an antipattern (it breaks test reporting, makes tests flaky, etc.)

I think what you're after is described here: [patrol.leancode.pl/tips-and-tricks#bundling-many-tests-into-a-single-app-binary](https://patrol.leancode.pl/tips-and-tricks#bundling-many-tests-into-a-single-app-binary).

We discussed a somewhat similar topic here: https://github.com/leancodepl/patrol/discussions/511


Apps are very different and I doubt we can create a generic "test router" solution.
