### ISSUE TITLE
Support iOS clipboard permission?

### ISSUE THREAD

**Issue by fzyzcjy** [leancodepl/patrol#1243]
A quick question: On recent iOS versions, if we want to read clipboard (e.g. detect copied deep links of the app and open it), iOS will pop up a system dialog. Is it possible to simulate clicking it? I have checked https://patrol.leancode.co/native/feature-parity, and the "permissions" row looks promising. I can make a PR if I am going to use patrol (in combination with convenient_test) and it is missing.

**Comment by bartekpacia** [comment]
Hi 👋🏻 

I don't think I've ever used Patrol's native automation feature to accept the iOS _clipboard permission dialog_, but if that dialog looks the same as all the other dialogs (the microphone, camera, etc.), then it should work with Patrol out of the box.

If you find that it doesn't work, please comment with accurate reproduction information and I'll reopen :)

Thanks!
