### ISSUE TITLE
Use analytics despite not enabling them

### ISSUE THREAD

**Issue by ErasmoCM** [leancodepl/patrol#1246]
### Is there an existing issue for this?

- [x] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

1. When patrol ask for enable analytics, answer no.
2. run any command of Patrol cli

### Actual results

Patrol cli request to https://www.google-analytics.com/mp/collect

### Logs

<details>
<summary>Logs</summary>

```
<!-- -->
```

</details>

### Patrol version

patrol: ^1.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Patrol CLI version: 1.1.7
Program adb found in /Users/user/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/user/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
Program ios-deploy not found (install with `brew install ios-deploy`) -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.3.1 22E772610a darwin-arm64, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.78.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found! -->
```

</details>

**Comment by bartekpacia** [comment]
Thank you very much for reporting this.
