### ISSUE TITLE
Screen stucks after the app launches

### ISSUE THREAD

**Issue by Binitojha12** [leancodepl/patrol#1247]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

```dart
patrolTest(
  'Validate User able to buy gold with Positive Cases',
  nativeAutomation: true,
  nativeAutomatorConfig: const NativeAutomatorConfig(
    packageName: 'com.jify.mobile.development',
    bundleId: 'com.jify.mobile.development',
  ),
  bindingType: BindingType.integrationTest,
  ($) async {
    await pumpMainApp($);
  
    final onboardingWorkflow = OnboardingWorkFlow($);
    final dashboardScreen = DashboardScreen($);
    final goldHomeScreen = GoldHomeScreen($);
    final buyGoldScreen = BuyGoldScreen($);
    final goldPurchaseDetailsScreen = GoldPurchaseDetailsScreen($);
  
    // .......code to be continued
```

### Actual results

When I try to run the patrol test with nativeAutomation= true, the app launches and freezes on the first screen. I tried all the possible ways and followed each instructions mentioned in the official docs but still not able to ressolve.
sometime it just says test starting and test finished and freezes the screen.

 Please help me to ressolve the same. 

### Logs

<details>
<summary>Logs</summary>

```
No device specified, using the first one (emulator-5554)
Every test target will be run 1 time(s)
• Building apk with entrypoint all_test.dart...
✓ Completed building apk with entrypoint all_test.dart (21.5s)
• Executing tests of apk with entrypoint all_test.dart on emulator-5554...

```

</details>

### Patrol version

patrol: ^1.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6.1 21G217 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.74.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6.1 21G217 darwin-x64, locale en-GB)
    • Flutter version 3.3.4 on channel stable at /Users/testvagrant/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (7 months ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/testvagrant/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/testvagrant/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 223.8617.8

[✓] VS Code (version 1.74.0)
    • VS Code at /Users/testvagrant/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.6.1 21G217 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.63

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
Hi @Binitojha12, sorry for the problem and thank you reporting it.

I see you're doing `nativeAutomation: true`, but simultaneously set `bindingType: BindingType.integrationTest`.

Patrol has its own binding - `PatrolBinding` - and it's used by default. Please try removing this line:

```
bindingType: BindingType.integrationTest,
```

and let me know if it helps (and if it doesn't, share the error message).

**Comment by Binitojha12** [comment]
hi @bartekpacia , thanks for your quick response,
I tried  without passing bindingType explicitly and also by passing bindingType : BindingType.patrol.
in all the cases the response was same.
For your reference, please find the below logs (with bindingType)

No device specified, using the first one (emulator-5554)
Every test target will be run 1 time(s)
• Building apk with entrypoint all_test.dart...
✓ Completed building apk with entrypoint all_test.dart (33.3s)
• Executing tests of apk with entrypoint all_test.dart on emulator-5554...
✗ Failed to execute tests of apk with entrypoint all_test.dart on emulator-5554 (Gradle test execution interrupted) (2311.6s)





I tried all the possible ways but result was same.

**Comment by Binitojha12** [comment]
hi @bartekpacia, thanks for your quick response,
I tried without passing any bindingType explicitly, and also by passing bindingType: BindingType.patrol in all the cases response are same.
Please find the requested logs (with passing any bindingType)

No device specified, using the first one (emulator-5554)
Every test target will be run 1 time(s)
• Building apk with entrypoint all_test.dart...
✓ Completed building apk with entrypoint all_test.dart (28.2s)
• Executing tests of apk with entrypoint all_test.dart on emulator-5554...


Output of patrol doctor:-
Patrol CLI version: 1.1.7
Program adb found in /Users/testvagrant/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/testvagrant/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
Program ios-deploy found in /usr/local/bin/ios-deploy

please help me to fix this, it build the apk, tries to launch the app but it freezes

**Comment by bartekpacia** [comment]
Can you run `patrol test` and immediately after you do it, run `flutter logs` and paste the output of the latter here?

**Comment by Binitojha12** [comment]
please find the requested logs :- 


Showing sdk gphone64 x86 64 logs:
D/FlutterBranchSDK(20231): onAttachedToEngine call
D/FlutterBranchSDK(20231): setupChannels call
D/FlutterBranchSDK(20231): Branch SDK with log enable
D/FlutterBranchSDK(20231): onAttachedToActivity call
D/FlutterBranchSDK(20231): setActivity call
D/FlutterGeolocator(20231): Attaching Geolocator to activity
I/flutter (20231): The Dart VM service is listening on http://127.0.0.1:40971/TxtTHf5mPL4=/
W/FlutterActivityAndFragmentDelegate(20231): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator(20231): Creating service.
D/FlutterGeolocator(20231): Binding to location service.
D/FlutterGeolocator(20231): Geolocator foreground service connected
D/FlutterGeolocator(20231): Initializing Geolocator services
D/FlutterGeolocator(20231): Flutter engine connected. Connected engine count 1
D/FlutterBranchSDK(20231): BranchReferralInitListener - params: {"+clicked_branch_link":false,"+is_first_session":false}
I/flutter (20231): Patrol (native): Android app name: 
I/flutter (20231): Patrol (native): iOS app name: 
I/flutter (20231): Patrol (native): Android package name: com.jify.mobile.development
I/flutter (20231): Patrol (native): iOS bundle identifier: com.jify.mobile.development
E/flutter (20231): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/foundation/binding.dart': Failed assertion: line 146 pos 12: '_debugInitializedType == null': is not true.
E/flutter (20231): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (20231): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (20231): #2      new BindingBase (package:flutter/src/foundation/binding.dart:146:12)
E/flutter (20231): #3      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #4      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #5      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #6      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #7      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding&RendererBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #8      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding&RendererBinding&PaintingBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #9      new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding&RendererBinding&PaintingBinding&WidgetsBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #10     new _TestWidgetsFlutterBinding&BindingBase&SchedulerBinding&ServicesBinding&GestureBinding&SemanticsBinding&RendererBinding&PaintingBinding&WidgetsBinding&TestDefaultBinaryMessengerBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #11     new TestWidgetsFlutterBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #12     new LiveTestWidgetsFlutterBinding (package:flutter_test/src/binding.dart)
E/flutter (20231): #13     new IntegrationTestWidgetsFlutterBinding (package:integration_test/integration_test.dart)
E/flutter (20231): #14     new PatrolBinding (package:patrol/src/binding.dart)
E/flutter (20231): #15     new PatrolBinding.ensureInitialized (package:patrol/src/binding.dart:77:7)
E/flutter (20231): #16     patrolTest (package:patrol/src/common.dart:54:39)
E/flutter (20231): #17     main.<anonymous closure> (file:///Users/testvagrant/Documents/ProjectTV/mobile_app/integration_test/tests/gold/buy_gold.test.dart:27:5)
E/flutter (20231): #18     Declarer.group.<anonymous closure> (package:test_api/src/backend/declarer.dart:267:37)
E/flutter (20231): #19     _rootRun (dart:async/zone.dart:1391:13)
E/flutter (20231): #20     _CustomZone.run (dart:async/zone.dart:1293:19)
E/flutter (20231): #21     _runZoned (dart:async/zone.dart:1829:10)
E/flutter (20231): #22     runZoned (dart:async/zone.dart:1751:10)
E/flutter (20231): #23     Declarer.declare (package:test_api/src/backend/declarer.dart:169:7)
E/flutter (20231): #24     Declarer.group (package:test_api/src/backend/declarer.dart:264:14)
E/flutter (20231): #25     group (package:flutter_test/src/test_compat.dart:189:13)
E/flutter (20231): #26     main (file:///Users/testvagrant/Documents/ProjectTV/mobile_app/integration_test/tests/gold/buy_gold.test.dart:26:3)
E/flutter (20231): #27     main (file:///Users/testvagrant/Documents/ProjectTV/mobile_app/integration_test/suites/all_test.dart:13:15)
E/flutter (20231): #28     _runMain.<anonymous closure> (dart:ui/hooks.dart:134:23)
E/flutter (20231): #29     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (20231): #30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter (20231): 
I/flutter (20231): 00:00 +0: (tearDownAll)
I/flutter (20231): 00:00 +1: All tests passed!

**Comment by bartekpacia** [comment]
Thanks for providing these logs. I've seen similar errors many times.

Can you show me the whole test file? In particular, I'm wondering if you're calling `IntegrationTestWidgetsFlutterBinding.ensureInitialized()`, because if you do, it will crash.

**Comment by Binitojha12** [comment]
@bartekpacia , its my bad.. i missed to comment out this line.
but when I do, below is the logs please find


Showing sdk gphone64 x86 64 logs:
D/FlutterBranchSDK(22610): onAttachedToEngine call
D/FlutterBranchSDK(22610): setupChannels call
D/FlutterBranchSDK(22610): Branch SDK with log enable
D/FlutterBranchSDK(22610): onAttachedToActivity call
D/FlutterBranchSDK(22610): setActivity call
D/FlutterGeolocator(22610): Attaching Geolocator to activity
I/flutter (22610): The Dart VM service is listening on http://127.0.0.1:37111/VXG4X0Fs10A=/
W/FlutterActivityAndFragmentDelegate(22610): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator(22610): Creating service.
D/FlutterGeolocator(22610): Binding to location service.
D/FlutterGeolocator(22610): Geolocator foreground service connected
D/FlutterGeolocator(22610): Initializing Geolocator services
D/FlutterGeolocator(22610): Flutter engine connected. Connected engine count 1
D/FlutterBranchSDK(22610): BranchReferralInitListener - params: {"+clicked_branch_link":false,"+is_first_session":false}
I/flutter (22610): Patrol (native): Android app name: 
I/flutter (22610): Patrol (native): iOS app name: 
I/flutter (22610): Patrol (native): Android package name: com.jify.mobile.development
I/flutter (22610): Patrol (native): iOS bundle identifier: com.jify.mobile.development
I/flutter (22610): 00:00 +0: Buy Gold Test : Validate User able to buy gold with Positive Cases
I/flutter (22610): Patrol (native): configure() started
I/flutter (22610): Patrol (native): configure() succeeded
I/flutter (22610): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (22610): The following assertion was thrown building KeyedSubtree-[#d3448]:
I/flutter (22610): Object/factory with  type SecureStorage is not registered inside GetIt.
I/flutter (22610): (Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
I/flutter (22610): Did you forget to register it?)
I/flutter (22610): 'package:get_it/get_it_impl.dart':
I/flutter (22610): Failed assertion: line 372 pos 7: 'instanceFactory != null'
I/flutter (22610): 
I/flutter (22610): The relevant error-causing widget was:
I/flutter (22610):   KeyedSubtree-[#d3448]
I/flutter (22610):   KeyedSubtree:file:///Users/testvagrant/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_phoenix-1.1.0/lib/flutter_phoenix.dart:30:12
I/flutter (22610): 
I/flutter (22610): When the exception was thrown, this was the stack:
I/flutter (22610): #2      _GetItImplementation._findFactoryByNameAndType (package:get_it/get_it_impl.dart:372:7)
I/flutter (22610): #3      _GetItImplementation.get (package:get_it/get_it_impl.dart:393:29)
I/flutter (22610): #4      _GetItImplementation.call (package:get_it/get_it_impl.dart:430:12)
I/flutter (22610): #5      new _MyAppState (package:jify_mobile/app.dart:48:33)
I/flutter (22610): #6      MyApp.createState (package:jify_mobile/app.dart:44:33)
I/flutter (22610): #7      new StatefulElement (package:flutter/src/widgets/framework.dart:4964:25)
I/flutter (22610): #8      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:763:38)
I/flutter (22610): ...     Normal element mounting (15 frames)
I/flutter (22610): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
I/flutter (22610): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
I/flutter (22610): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
I/flutter (22610): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
I/flutter (22610): #27     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
I/flutter (22610): #28     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
I/flutter (22610): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
I/flutter (22610): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
I/flutter (22610): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
I/flutter (22610): #32     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
I/flutter (22610): #33     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1172:5)
I/flutter (22610): #34     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1186:7)
I/flutter (22610): #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
I/flutter (22610): #36     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
I/flutter (22610): #37     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
I/flutter (22610): #38     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
I/flutter (22610): #39     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
I/flutter (22610): #40     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
I/flutter (22610): #41     LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1559:13)
I/flutter (22610): #42     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
I/flutter (22610): #46     _invoke (dart:ui/hooks.dart:150:10)
I/flutter (22610): #47     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
I/flutter (22610): #48     _drawFrame (dart:ui/hooks.dart:115:31)
I/flutter (22610): (elided 5 frames from class _AssertionError and dart:async)
I/flutter (22610): 
I/flutter (22610): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22610): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (22610): The following LateError was thrown running a test:
I/flutter (22610): LateInitializationError: Field '_variables@59358569' has not been initialized.
I/flutter (22610): 
I/flutter (22610): When the exception was thrown, this was the stack:
I/flutter (22610): #0      FlutterConfigPlus._variables (package:flutter_config_plus/flutter_config_plus.dart)
I/flutter (22610): #1      FlutterConfigPlus.get (package:flutter_config_plus/flutter_config_plus.dart:27:31)
I/flutter (22610): #2      CredentialsClient.getAllTestGroupKycUsersCredential (file:///Users/testvagrant/Documents/ProjectTV/mobile_app/integration_test/clients/data/credentials_client.dart:13:33)
I/flutter (22610): <asynchronous suspension>
I/flutter (22610): #3      CredentialsClient.getAllTestGroupKycUserCredential (file:///Users/testvagrant/Documents/ProjectTV/mobile_app/integration_test/clients/data/credentials_client.dart:23:12)
I/flutter (22610): <asynchronous suspension>
I/flutter (22610): #4      main.<anonymous closure>.<anonymous closure> (file:///Users/testvagrant/Documents/ProjectTV/mobile_app/integration_test/tests/gold/buy_gold.test.dart:44:13)
I/flutter (22610): <asynchronous suspension>
I/flutter (22610): #5      patrolTest.<anonymous closure> (package:patrol/src/common.dart:83:7)
I/flutter (22610): <asynchronous suspension>
I/flutter (22610): #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
I/flutter (22610): <asynchronous suspension>
I/flutter (22610): #7      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:5)
I/flutter (22610): <asynchronous suspension>
I/flutter (22610): 
I/flutter (22610): The test description was:
I/flutter (22610):   Validate User able to buy gold with Positive Cases
I/flutter (22610): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22610): ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter (22610): The following message was thrown:
I/flutter (22610): Multiple exceptions (2) were detected during the running of the current test, and at least one was
I/flutter (22610): unexpected.
I/flutter (22610): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22610): 00:05 +0: Buy Gold Test : Validate User able to buy gold with Positive Cases [E]
I/flutter (22610):   Test failed. See exception logs above.
I/flutter (22610):   The test description was: Validate User able to buy gold with Positive Cases
I/flutter (22610):   
I/flutter (22610): 00:05 +0 -1: Buy Gold Test : (tearDownAll)
I/flutter (22610): PatrolBinding: Sending 1 test results to the native side...
I/flutter (22610): Patrol (native): submitTestResults() started
I/flutter (22610): Patrol (native): submitTestResults() succeeded
I/flutter (22610): PatrolBinding: Test results sent
I/flutter (22610): 00:05 +1 -1: Some tests failed.
D/FlutterBranchSDK(22610): onActivityStopped call
D/FlutterBranchSDK(22610): onActivityDestroyed call
D/FlutterGeolocator(22610): Detaching Geolocator from activity
D/FlutterBranchSDK(22610): onDetachedFromActivity call
D/FlutterGeolocator(22610): Flutter engine disconnected. Connected engine count 0
D/FlutterGeolocator(22610): Disposing Geolocator services
E/FlutterGeolocator(22610): Geolocator position updates stopped
D/FlutterGeolocator(22610): Stopping location service.
D/FlutterBranchSDK(22610): onDetachedFromEngine call
D/FlutterBranchSDK(22610): teardownChannels call
D/FlutterGeolocator(22610): Unbinding from location service.
D/FlutterGeolocator(22610): Destroying location service.
D/FlutterGeolocator(22610): Stopping location service.
D/FlutterGeolocator(22610): Destroyed location service.

**Comment by bartekpacia** [comment]
Now I'm pretty sure your problem is not related to Patrol. Sounds like you have GetIt misconfigured:

```
The following assertion was thrown building KeyedSubtree-[#d3448]:
I/flutter (22610): Object/factory with type SecureStorage is not registered inside GetIt.
I/flutter (22610): (Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
I/flutter (22610): Did you forget to register it?)
```

**Comment by Binitojha12** [comment]
[testFiles.zip](https://github.com/leancodepl/patrol/files/11415604/testFiles.zip)

Hi @bartekpacia , i have fixed the above error by upgrading getIT version, but
i have attached the test files:
I have two test classes with PatrolTest and nativeAutomation : true.
When I run the test, it starts and ends automatically, and there is no error. Even the logs says the tests are passed.

Can you please review my test class files if Iam missing something. It can be a great help!

please find the updated logs below :-

Showing sdk gphone64 x86 64 logs:
D/FlutterBranchSDK(25994): onAttachedToEngine call
D/FlutterBranchSDK(25994): setupChannels call
D/FlutterBranchSDK(25994): Branch SDK with log enable
D/FlutterBranchSDK(25994): onAttachedToActivity call
D/FlutterBranchSDK(25994): setActivity call
I/flutter (25994): The Dart VM service is listening on http://127.0.0.1:40189/9QDw8VMXvvw=/
D/FlutterGeolocator(25994): Attaching Geolocator to activity
W/FlutterActivityAndFragmentDelegate(25994): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator(25994): Creating service.
D/FlutterGeolocator(25994): Binding to location service.
D/FlutterGeolocator(25994): Geolocator foreground service connected
D/FlutterGeolocator(25994): Initializing Geolocator services
D/FlutterGeolocator(25994): Flutter engine connected. Connected engine count 1
D/FlutterBranchSDK(25994): BranchReferralInitListener - params: {"+clicked_branch_link":false,"+is_first_session":false}
I/flutter (25994): Patrol (native): Android app name: Jify-Dev
I/flutter (25994): Patrol (native): iOS app name: 
I/flutter (25994): Patrol (native): Android package name: com.jify.mobile.development
I/flutter (25994): Patrol (native): iOS bundle identifier: com.jify.mobile.development
I/flutter (25994): Patrol (native): Android app name: Jify-Dev
I/flutter (25994): Patrol (native): iOS app name: 
I/flutter (25994): Patrol (native): Android package name: com.jify.mobile.development
I/flutter (25994): Patrol (native): iOS bundle identifier: com.jify.mobile.development
I/flutter (25994): 00:00 +0: Setup : Init App
I/flutter (25994): Patrol (native): configure() started
I/flutter (25994): Patrol (native): configure() succeeded
I/flutter (25994): DEV
I/flutter (25994): onBoardingMain 
I/flutter (25994): onLoginMain 
I/flutter (25994): permGranted: false
I/flutter (25994): runApp false:: false
I/flutter (25994): 00:02 +1: Setup : (tearDownAll)
I/flutter (25994): PatrolBinding: Sending 1 test results to the native side...
I/flutter (25994): Patrol (native): submitTestResults() started
I/flutter (25994): Patrol (native): submitTestResults() succeeded
I/flutter (25994): PatrolBinding: Test results sent
I/flutter (25994): 00:02 +2: Buy Gold Test : Validate User able to buy gold with Positive Cases
I/flutter (25994): Patrol (native): configure() started
I/flutter (25994): Patrol (native): configure() succeeded
D/FlutterBranchSDK(25994): onListen call
D/FlutterBranchSDK(25994): onActivityStopped call
D/FlutterBranchSDK(25994): onActivityDestroyed call
D/FlutterBranchSDK(25994): onDetachedFromActivity call
D/FlutterGeolocator(25994): Detaching Geolocator from activity
D/FlutterBranchSDK(25994): onDetachedFromEngine call
D/FlutterBranchSDK(25994): teardownChannels call
D/FlutterGeolocator(25994): Flutter engine disconnected. Connected engine count 0
D/FlutterGeolocator(25994): Disposing Geolocator services
E/FlutterGeolocator(25994): Geolocator position updates stopped
D/FlutterGeolocator(25994): Stopping location service.
I/flutter (25994): 00:05 +2: Setup : Init App
I/flutter (25994): listenDynamicLinks - DeepLink Data: {+clicked_branch_link: false, +is_first_session: false}
D/FlutterGeolocator(25994): Unbinding from location service.
D/FlutterGeolocator(25994): Destroying location service.
D/FlutterGeolocator(25994): Stopping location service.
D/FlutterGeolocator(25994): Destroyed location service.
D/FlutterBranchSDK(26377): onAttachedToEngine call
D/FlutterBranchSDK(26377): setupChannels call
D/FlutterBranchSDK(26377): Branch SDK with log enable
D/FlutterBranchSDK(26377): onAttachedToActivity call
D/FlutterBranchSDK(26377): setActivity call
D/FlutterGeolocator(26377): Attaching Geolocator to activity
I/flutter (26377): The Dart VM service is listening on http://127.0.0.1:37743/i2sOj1Uf6ds=/
W/FlutterActivityAndFragmentDelegate(26377): A splash screen was provided to Flutter, but this is deprecated. See flutter.dev/go/android-splash-migration for migration steps.
D/FlutterGeolocator(26377): Creating service.
D/FlutterGeolocator(26377): Binding to location service.
D/FlutterGeolocator(26377): Geolocator foreground service connected
D/FlutterGeolocator(26377): Initializing Geolocator services
D/FlutterGeolocator(26377): Flutter engine connected. Connected engine count 1
D/FlutterBranchSDK(26377): BranchReferralInitListener - params: {"+clicked_branch_link":false,"+is_first_session":false}
I/flutter (26377): Patrol (native): Android app name: Jify-Dev
I/flutter (26377): Patrol (native): iOS app name: 
I/flutter (26377): Patrol (native): Android package name: com.jify.mobile.development
I/flutter (26377): Patrol (native): iOS bundle identifier: com.jify.mobile.development
I/flutter (26377): 00:00 +0: Setup : Init App
I/flutter (26377): Patrol (native): configure() started
I/flutter (26377): Patrol (native): configure() succeeded
I/flutter (26377): DEV
I/flutter (26377): onBoardingMain 
I/flutter (26377): onLoginMain 
I/flutter (26377): permGranted: false
I/flutter (26377): runApp false:: false
I/flutter (26377): 00:02 +1: Setup : (tearDownAll)
I/flutter (26377): PatrolBinding: Sending 1 test results to the native side...
I/flutter (26377): Patrol (native): submitTestResults() started
I/flutter (26377): Patrol (native): submitTestResults() succeeded
I/flutter (26377): PatrolBinding: Test results sent
I/flutter (26377): 00:02 +2: All tests passed!
D/FlutterBranchSDK(26377): onActivityStopped call
D/FlutterBranchSDK(26377): onActivityDestroyed call
D/FlutterGeolocator(26377): Detaching Geolocator from activity
D/FlutterBranchSDK(26377): onDetachedFromActivity call
D/FlutterGeolocator(26377): Flutter engine disconnected. Connected engine count 0
D/FlutterGeolocator(26377): Disposing Geolocator services
E/FlutterGeolocator(26377): Geolocator position updates stopped
D/FlutterGeolocator(26377): Stopping location service.
D/FlutterBranchSDK(26377): onDetachedFromEngine call
D/FlutterBranchSDK(26377): teardownChannels call
D/FlutterGeolocator(26377): Unbinding from location service.
D/FlutterGeolocator(26377): Destroying location service.
D/FlutterGeolocator(26377): Stopping location service.
D/FlutterGeolocator(26377): Destroyed location service.

**Comment by bartekpacia** [comment]
Hi, the files you attached are strangely garbled:

![3](https://user-images.githubusercontent.com/40357511/236699347-96e0164a-3880-47d0-bfb1-abffedafcb20.png)

Can you please fix them?

**Comment by Binitojha12** [comment]
buy_gold.test.dart
setup_test.dart
all_test.dart
init.test.dart

hi @bartekpacia , i think when I zipped that folder it went something wrong.
I have cross checked now, please find attached files

**Comment by Binitojha12** [comment]
https://github.com/binitojha1/dummyRepo

hi @bartekpacia  please find the repo link containing those files.
the above issue was due to converting it into zip i guess.

**Comment by bartekpacia** [comment]
Thank you for providing me with this repo.

I'll take a look at it ASAP.

**Comment by bartekpacia** [comment]
I see you only attached the 4 test files – I cannot run it. It'd be of great help if you `flutter create`d a simple app and performed the setup.

But before you do this, I encourage you to take a look at [our example app](https://github.com/leancodepl/patrol/tree/master/packages/patrol/example/android) - especially at the Gradle and Java files that the [Native Automation setup guide](https://patrol.leancode.co/native/setup) talks about. Compare these files with your app, and you might spot some mistakes:
- [MainActivityTest.java](https://github.com/leancodepl/patrol/blob/master/packages/patrol/example/android/app/src/androidTest/java/pl/leancode/patrol/example/MainActivityTest.java)
- [app/build.gradle](https://github.com/leancodepl/patrol/blob/master/packages/patrol/example/android/app/build.gradle)

A common mistake that people make is putting `MainActivityTest.java` in incorrect location. For example, if your `MainActivity.java` (or `MainActivity.kt` - doesn't matter) is in `android/app/src/main/kotlin/pl/leancode/patrol/example/MainActivity.java`, then `MainActivityTest.java` must go into `android/app/src/androidTest/java/pl/leancode/patrol/example/MainActivityTest.java`.

And if your `MainActivity.java` is in `android/app/src/main/java/com/awesome/company/MainActivity.java`, then `MainActivityTest.java` must go into `android/app/src/androidTest/java/com/awesome/company/MainActivityTest.java`.

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment and I'll be happy to continue the discussion :)
