### ISSUE TITLE
[Question] Does patrol support Flutter Webapp?

### ISSUE THREAD

**Issue by linh-hectre** [leancodepl/patrol#1270]
My team intends to use patrol for the Flutter mobile application.

But in the near future, we also have the Flutter web app and the Flutter Winform app.

Is it possible to use patrol to deal with them?

Thanks guys!

**Comment by bartekpacia** [comment]
Hi @linh-hectre,

I'm curious what use-cases you see for Patrol being used in web app. Could you tell a bit more?

**Comment by bautistagetahead** [comment]
@bartekpacia i have been looking an appropriate tool to do this for a long time too - found it very hard to automate testing on a flutter web application

**Comment by bartekpacia** [comment]
What exactly do you want to test in the Flutter Web app? Patrol's main feature is _native automation_, which lets you tap on system permission dialogs etc. Is this a common use case when testing web apps?

**Comment by linh-hectre** [comment]
> What exactly do you want to test in the Flutter Web app? Patrol's main feature is _native automation_, which lets you tap on system permission dialogs etc. Is this a common use case when testing web apps?

@bartekpacia Like Selenium for Web App and Appium for Mobile App

When testing a web application, the common use case is that we go to an URL, input texts to textboxes, click some buttons, verify some text displayed on the screen...etc...

I see that when the browser rendered the webpage written in Flutter, the DOM tree contains only a canvas which makes Selenium unable to interact with

**Comment by bartekpacia** [comment]
Thanks for explaining!

> However, I see that when the browser renders the webpage written in Flutter, the DOM tree contains only a canvas which makes Selenium unable to interact with

Can't you use the HTML renderer for testing?

BTW, to answer the issue - no, Patrol's _native automation_ feature doesn't support Flutter Web apps. You can still use _custom finders_ to write widget tests, though.

We would like to support Flutter Web, but currently, there are no plans to do it. We need to stabilize mobile first.

**Comment by adrian-moisa** [comment]
I've had a ticket opened long time ago asking the Flutter team to add support for test ids in Flutter html renderer. Currently there's no convenient way to hook into the DOM tree and to precisely intercept a div except by searching for text. https://github.com/flutter/flutter/issues/97455 . I've written a project web first and it's currently over 100k LOC. I'm desperately searching for a solution of integration testing that does not require me to do manual pump at all times. It's a terrible API to write tests with. Patrol was very promising at first sight, but then I learned there's no web support. That's a big bummer. I'll be trying to setup my Android build and hopefully get some progress done this way. Though I have to say I'm mainly developing in the browser for MVP. Please do consider extending Patrol for more than native. Flutter web is growing and your API is boasting in the docs to be more terse. That's good enough reason to port it to web as well.
