### ISSUE TITLE
Patrol CLI sometimes throws "Connection closed before full header was received" error

### ISSUE THREAD

**Issue by fylyppo** [leancodepl/patrol#1282]
### Is there an existing issue for this?

- [X] I have searched the [existing issues](https://github.com/leancodepl/patrol/issues)

### Steps to reproduce

1. You can run this workflow: https://github.com/leancodepl/patrol/actions/workflows/test-ios-simulator.yaml

### Actual results

I have noticed it only while testing on iOS simulator but I'm not sure it can't happen while testing on Android.
Two out of about thirty times `patrol build` or `patrol test` is throwing an error: `Connection closed before full header was received` and command fails to run or build tests.
Check run here: https://github.com/leancodepl/patrol/actions/runs/4990196745/jobs/8935097806#step:8:20

### Logs

<details>
<summary>Logs</summary>

```
Connection closed before full header was received
#0      IOClient.send (package:http/src/io_client.dart:90:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      _withClient (package:http/http.dart:164:12)
<asynchronous suspension>
#3      PubUpdater._getPackageInfo (package:pub_updater/src/pub_updater.dart:68:22)
<asynchronous suspension>
#4      PubUpdater.getLatestVersion (package:pub_updater/src/pub_updater.dart:44:25)
<asynchronous suspension>
#5      PatrolCommandRunner._checkForUpdate (package:patrol_cli/src/runner/patrol_command_runner.dart:365:27)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:306:7)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:258:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:66:[20](https://github.com/leancodepl/patrol/actions/runs/4990196745/jobs/8935097806#step:8:21))
<asynchronous suspension>
#9      main (file:///Users/runner/work/patrol/patrol/packages/patrol_cli/bin/main.dart:6:20)
<asynchronous suspension>

Error: Process completed with exit code 1.
```

</details>

### Patrol version

patrol: ^1.2.0-dev.3
patrol_cli: ^1.1.9

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
I don't need a doctor
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
I don't have
```

</details>

**Comment by bartekpacia** [comment]
Let's disable checking for update when we're running on CI.
