### ISSUE TITLE
Test is marked with a green "PASS" even when a test fails

### ISSUE THREAD

**Issue by vijaya-sakhamuri** [leancodepl/patrol#1309]
I followed all the setup steps as mentioned in patrol documentation, but still getting PASS result when a test fails.  Flutter logs shows the correct results. I am attaching here some screenshots for PASS and Fail tests, actual PASS test shows the correct package but Fail tests shows default-package. Can you please review and let me know how we can resolve this issue?
<img width="882" alt="Screen Shot 2023-05-23 at 11 53 21 AM" src="https://github.com/leancodepl/patrol/assets/37450484/e2e3f40b-9695-483e-8932-ff6883f86b16">
<img width="990" alt="Screen Shot 2023-05-23 at 11 57 49 AM" src="https://github.com/leancodepl/patrol/assets/37450484/449a00b4-f0dc-4955-874a-eb0d3cedfcac">

**Comment by bartekpacia** [comment]
Hi @vijaya-sakhamuri, unfortunately I'm not able to help you unless you [create an actual bug](https://github.com/leancodepl/patrol/issues/new/choose) and fill out all the required details.

I encourage you to create a new issue, and I'll close this one.
