### ISSUE TITLE
Rework of scrolling methods

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1323]
We decided to change implementation of scrolling methods, to make them usable in more scenarios.

How it works now:

- scrolling can be performed only on a widget, that is of type `Scrollable`. That blocks usage of `scrollTo()` (and similar) on widgets do have custom gesture handling, but do not implement `Scrollable`.
- `Scrollable` that we want to scroll has to be found and has to be visible (more specifically - [hitTestable](https://api.flutter.dev/flutter/flutter_test/Finder/hitTestable.html)). There are some scenarios in which it doesn't work, because the desired `Scrollable` seems to be not hitTestable (though it is visible to the user).
- the actual dragging is implemented in the [`drag()` method from `flutter_test`](https://api.flutter.dev/flutter/flutter_test/WidgetController/drag.html). This causes very fast scrolling on `Scrollable`s with some non-standard scroll physics, which results in scrolling too far to find the widget we're looking for.

We would like:

- to be independent of what type the widget being scrolled is. `drag()` method can scroll any widget, though in some situations just nothing happens. We want to enable scrolling all widgets, including custom widgets, not only `Scrollable`.
- to perform dragging more slowly (which would be configurable) - to prevent from scrolling too far when there are some custom scroll physics.
- to enable usage of different pumping methods between drags.

**Comment by bartekpacia** [comment]
Thanks for writing this up. LGTM.

IIRC we also discussed the tradeoffs and implementation – it'd be great to have them here (before we start working on a PR).

**Comment by bartekpacia** [comment]
This was done in #1325 and released in Patrol 2.0.
