### ISSUE TITLE
Clarify when to pass bundle identifier when handling iOS dialogs

### ISSUE THREAD

**Issue by katarzyna-juszczak** [leancodepl/patrol#1324]
Patrol docs instruct to pass bundleId when there is need to handle permissions on iOS device with non-English locale. This is located in "Usage" of Native automation section in Patrol docs.

However, if I want to handle other dialogs than permission request (e.g. sign in with Apple), I need to specify bundleId of Springboard even when device language is set to English US.

I believe it would be good to make it more precise in docs.

**Comment by bartekpacia** [comment]
Thanks for reporting this.

More context:
- [link](https://patrol.leancode.co/native/usage)
- screenshot:
  
  ![Screenshot 2023-05-30 at 6 37 26 PM](https://github.com/leancodepl/patrol/assets/40357511/be0a01a7-5369-44e9-b523-342acebd4b6f)

**Comment by bartekpacia** [comment]
Kinda related -> #609

**Comment by jBorkowska** [comment]
It's in the docs now, closing
