### ISSUE TITLE
Bump http to 1.0.0 and intl to 0.18.1

### ISSUE THREAD

**Issue by ziadsarour** [leancodepl/patrol#1340]
### Steps to reproduce

Bump : 
- http: 1.0.0 (unable to upgrade google fonts to 5.0.0)
- intl: 0.18.1 (unable to upgrade flutter to 3.12.0, not yet in stable but I think it's better to do it now)

### Actual results

Unable to upgrade packages

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 1.1.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by bartekpacia** [comment]
We can't do it now, since it requires Dart 3.0, so it requires Flutter 3.10.

We want to keep supporting Flutter 3.3 and 3.7 for as long as possible.

![Screenshot 2023-06-11 at 11 08 56 PM](https://github.com/leancodepl/patrol/assets/40357511/23db5301-b6fd-4a3c-8dbd-9fdfc7edfa75)

**Comment by bartekpacia** [comment]
I'm going to close this, but thanks for raising this matter. We'll likely force Dart 3.0 and Flutter 3.10 when the next stable Flutter comes out.

**Comment by bartekpacia** [comment]
Done in #1485.
