### ISSUE TITLE
Patrol 2.0 shortcomings

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1341]
In this issue, we gather a list of problems, bugs, and lacks related to the [test bundling feature](https://github.com/leancodepl/patrol/issues/1004). This is mostly an extract of problems mentioned in [this comment](https://github.com/leancodepl/patrol/issues/1004#issuecomment-1562852165).

Individual issues might be created later.

---
- preserve the tree structure of Dart tests when translated to native tests **(update: see [#1502](https://github.com/leancodepl/patrol/issues/1502))**

  Given the following hierarchy of the `integration_test` directory:
    
  ```
  integration_test
  ├── feature_bravo
  │   ├── 1_test.dart
  │   └── 2_test.dart
  └── feature_delta
      ├── 1_test.dart
      └── 2_test.dart
  ```
  
  the results are presented like this on a native platform (in the example below: Android:)
  
  ```
  test feature_bravo.1_test.dart ✅
  test feature_bravo.2_test.dart ✅
  test feature_delta.1_test.dart ✅
  test feature_delta.2_test.dart ✅
  ```
  
  but should be presented like this instead:
  
  ```
  group feature_bravo
  ├── test 1_test.dart ✅
  └── test 2_test.dart ✅
  group feature_delta
  ├── test 1_test.dart ✅
  └── test 2_test.dart ✅
  ```
  
  In other words, the hierarchy is removed, but it's emulated by `.` (a dot).

---
- `group()` cannot be used **(update: see [#1619](https://github.com/leancodepl/patrol/issues/1619))**

  This stems from how tests are _registered for execution_ by `patrolTest()`.

  See also:
  - [Related code with a comment containing more details](https://github.com/leancodepl/patrol/blob/ecb3c47acbccc52d003250f6a18c91ff570a28cc/packages/patrol/lib/src/common.dart#L85-L138).

---
- set-up and tear-down callbacks cannot be used **(update: see [#1503](https://github.com/leancodepl/patrol/issues/1503))**

  Or rather: they can be used, but they execute in a very different order.
  This applies to `setUp()`, `setUpAll()`, `tearDown()`, `tearDownAll()`, and similar.

  Assume there are 3 tests in the `integration_test` director:

  <details>
  <summary>Source code</summary>

  ```dart
  import 'common.dart';
  
  // integration_test/alpha_test.dart
  
  void main() {
    print('PATROL_DEBUG: alpha_test file loaded');
  
    setUp(() {
      print('PATROL_DEBUG: alpha_test setup');
    });
  
    tearDown(() {
      print('PATROL_DEBUG: alpha_test teardown');
    });
  
    patrolTest('alpha_test', nativeAutomation: true, ($) async {
      print('PATROL_DEBUG: alpha_test body');
      await $.pumpWidget(ExampleApp());
    });
  }
  ```
  
  ```dart
  import 'common.dart';
  
  // integration_test/bravo_test.dart
  
  void main() {
    print('PATROL_DEBUG: bravo_test file loaded');
  
    setUp(() {
      print('PATROL_DEBUG: bravo_test setup');
    });
  
    tearDown(() {
      print('PATROL_DEBUG: bravo_test teardown');
    });
  
    patrolTest('bravo_test', nativeAutomation: true, ($) async {
      print('PATROL_DEBUG: bravo_test body');
      await $.pumpWidget(ExampleApp());
    });
  }
  ```
  
  ```dart
  import 'common.dart';
  
  // integration_test/charlie_test.dart
  
  void main() {
    print('PATROL_DEBUG: charlie_test file loaded');
  
    setUp(() {
      print('PATROL_DEBUG: charlie_test setup');
    });
  
    tearDown(() {
      print('PATROL_DEBUG: charlie_test teardown');
    });
  
    patrolTest('charlie test', nativeAutomation: true, ($) async {
      print('PATROL_DEBUG: charlie_test body');
      await $.pumpWidget(ExampleApp());
    });
  }
  ```

  </details> 

  Here's how it'll end up being:

  <details>
  <summary>Logs</summary>
  
  ```sh
  $ adb logcat -v color -d | grep -E 'PATROL_DEBUG' | cut -d ':' -f 4,5
   PATROL_DEBUG: alpha_test file loaded
   PATROL_DEBUG: bravo_test file loaded
   PATROL_DEBUG: charlie_test file loaded
   PATROL_DEBUG: alpha_test setup
   PATROL_DEBUG: alpha_test file loaded
   PATROL_DEBUG: bravo_test file loaded
   PATROL_DEBUG: charlie_test file loaded
   PATROL_DEBUG: alpha_test setup
   PATROL_DEBUG: alpha_test body
   PATROL_DEBUG: alpha_test teardown
   PATROL_DEBUG: bravo_test setup
   PATROL_DEBUG: alpha_test file loaded
   PATROL_DEBUG: bravo_test file loaded
   PATROL_DEBUG: charlie_test file loaded
   PATROL_DEBUG: alpha_test setup
   PATROL_DEBUG: alpha_test teardown
   PATROL_DEBUG: bravo_test setup
   PATROL_DEBUG: bravo_test body
   PATROL_DEBUG: bravo_test teardown
   PATROL_DEBUG: charlie_test setup
   PATROL_DEBUG: alpha_test file loaded
   PATROL_DEBUG: bravo_test file loaded
   PATROL_DEBUG: charlie_test file loaded
   PATROL_DEBUG: alpha_test setup
   PATROL_DEBUG: alpha_test teardown
   PATROL_DEBUG: bravo_test setup
   PATROL_DEBUG: bravo_test teardown
   PATROL_DEBUG: charlie_test setup
   PATROL_DEBUG: charlie_test body
   PATROL_DEBUG: charlie_test teardown
  ```

  </details>
  
  This is because of the way we implemented running a particular test. Tests that appear before it aren't actually skipped – they are run but finish immediately. Think: fallthrough.
  
---

- The `main()` function must not be asynchronous.

  Example of **incorrect test**:
  
  ```dart
  void main() async {
    patrolTest(...);
  }
  ```
  
  Example of **correct** test:
  
  ```dart
  void main() {
    patrolTest(...);
  }
  ```

**Comment by mzdm** [comment]
Q: Test bundling is optional or it will be the only option in 2.0? `setUp, tearDown` etc. are quite crucial in our codebase and I am wondering what the workarounds will be

**Comment by bartekpacia** [comment]
Please also note that `MainActivityTest.java` was changed in 2.0.0-dev.3, [here](https://github.com/leancodepl/patrol/blob/develop/packages/patrol/example/android/app/src/androidTest/java/pl/leancode/patrol/example/MainActivityTest.java)'s how it must look like now.

**Comment by findmanish** [comment]
@bartekpacia  In my case I don't have this MainActivityTest.java should I add this file and code according to patrol_cli_2.0.0 documentation as getting some errors in test_bundle.dart and build.gradle on activating patrol_cli to 2.0.0

Is there any way to go back on patrol_cli_1.1.11?

**Comment by bartekpacia** [comment]
Sure, you can easily downgrade to v1:

```
dart pub global activate patrol_cli ^1.0.0
```

**Comment by EyedBread** [comment]
Hi! I'm trying to set up the native automation with android, and running "patrol test --target integration_test/example_test.dart" gets me this error:

You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

No device specified, using the first one (R3CRA0BA7FD)
• Building apk with entrypoint test_bundle.dart...

        FAILURE: Build failed with an exception.

        * What went wrong:
        A problem occurred configuring root project 'android'.
        > Could not resolve all files for configuration ':classpath'.
           > Could not resolve com.android.tools.build:gradle:7.4.2.
             Required by:
                 project :
              > No matching variant of com.android.tools.build:gradle:7.4.2 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.5' but:
                  - Variant 'apiElements' capability com.android.tools.build:gradle:7.4.2 declares a library, packaged as a jar, and its dependencies declared externally:
                      - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
                      - Other compatible attribute:
                          - Doesn't say anything about org.gradle.plugin.api-version (required '7.5')
                  - Variant 'javadocElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:
                      - Incompatible because this component declares documentation and the consumer needed a library
                      - Other compatible attributes:
                          - Doesn't say anything about its target Java version (required compatibility with Java 8)
                          - Doesn't say anything about its elements (required them packaged as a jar)
                          - Doesn't say anything about org.gradle.plugin.api-version (required '7.5')
                  - Variant 'runtimeElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
                      - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8      
                      - Other compatible attribute:
                          - Doesn't say anything about org.gradle.plugin.api-version (required '7.5')
                  - Variant 'sourcesElements' capability com.android.tools.build:gradle:7.4.2 declares a runtime of a component, and its dependencies declared externally:
                      - Incompatible because this component declares documentation and the consumer needed a library
                      - Other compatible attributes:
                          - Doesn't say anything about its target Java version (required compatibility with Java 8)
                          - Doesn't say anything about its elements (required them packaged as a jar)
                          - Doesn't say anything about org.gradle.plugin.api-version (required '7.5')

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 6s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (8.8s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
 FAIL  test_bundle.dart on R3CRA0BA7FD
 
 Any insight on what may be the problem?

**Comment by bartekpacia** [comment]
Hi @EyedBread, this looks like an issue related to your app's Gradle build files. Please create a new issue and provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so I can help. This issue is not the right place for issues like this one.

**Comment by GentiShtjefni** [comment]
In the new Patrol 2.0, in the generated file test_bundle.dart, the main_test.dart file is imported as "/main_test/dart" while i think it should be "./main_test.dart"

**Comment by bartekpacia** [comment]
@GentiShtjefni Thanks for reporting this. Could you open a new issue and explain this problem in more detail?

**Comment by pdax-johnlester** [comment]
Hi @bartekpacia, is patrol available for Flutter Web?

**Comment by bartekpacia** [comment]
You can use custom finders on the web (the `$`), but native automation is not available.

**Comment by pdax-johnlester** [comment]
Cool! One last thing man, how can I run the actual patrol test when the target device is a web browser?

**Comment by bartekpacia** [comment]
You have to use `flutter_driver` to run _widget tests_ on the web. [Here are official Flutter docs about it](https://docs.flutter.dev/cookbook/testing/integration/introduction#5b-web).

**Comment by pdax-johnlester** [comment]
Thanks @bartekpacia appreciate it! It's still the tradition way, i thought there's another way from partol to set it up. Anyways, looking forward for more success on your tool! 🚀

**Comment by bartekpacia** [comment]
Happy to hear that:) good luck and if you encounter any more problems, don't hesitate to create an issue.

Now forgive me but I'll minimize this little discussion because it's a bit off-topic here :) but no big deal

**Comment by jBorkowska** [comment]
There are separate issues for this topics, closing
