### ISSUE TITLE
Hot restart is not working

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1344]
On newest dev release. Here are logs:

`The Dart VM service is listening on http://127.0.0.1:34371/PWEVup_JCFM=/
        Patrol (native): packageName is not set. It's recommended to set it.
        00:00 +0: test
        00:00 +0: test [E]
          'package:flutter_test/src/binding.dart': Failed assertion: line 1956 pos 12: '!_expectingFrame': is not true.
          dart:core-patch/errors_patch.dart 51:61           _AssertionError._doThrowNew
          dart:core-patch/errors_patch.dart 40:5            _AssertionError._throwNew
          package:flutter_test/src/binding.dart 1956:12     LiveTestWidgetsFlutterBinding.postTest
          dart:async/future.dart 305:31                     new Future.sync
          package:test_api/src/backend/invoker.dart 236:18  Invoker.runTearDowns.<fn>.<fn>
          package:test_api/src/backend/invoker.dart 258:17  Invoker._waitForOutstandingCallbacks.<fn>
          dart:async/zone.dart 1399:13                      _rootRun
          dart:async/zone.dart 1301:19                      _CustomZone.run
          dart:async/zone.dart 1804:10                      _runZoned
          dart:async/zone.dart 1747:10                      runZoned
          package:test_api/src/backend/invoker.dart 254:5   Invoker._waitForOutstandingCallbacks
          package:test_api/src/backend/invoker.dart 235:9   Invoker.runTearDowns.<fn>
          dart:async/zone.dart 1399:13                      _rootRun
          dart:async/zone.dart 1301:19                   
        00:00 +0 -1: (tearDownAll)
        00:00 +0 -1: test
        ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
        The following assertion was thrown running a test (but after the test had completed):
        'package:patrol/src/binding.dart': Failed assertion: line 166 pos 12: '_currentDartTestFile !=
        null': is not true.

        When the exception was thrown, this was the stack:
        #2      PatrolBinding.attachRootWidget (package:patrol/src/binding.dart:166:12)
        #3      WidgetTester._pumpWidget (package:flutter_test/src/widget_tester.dart:590:13)
        #4      WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:577:14)
        #7      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:68:41)
        #8      WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:576:27)
        #9      PatrolTester.pumpWidgetAndSettle (package:patrol/src/custom_finders/patrol_tester.dart:191:18)
        #10     main.<anonymous closure> (file:///Users/user/project/integration_test/test_test.dart:12:15)
        #11     patrolTest.<anonymous closure> (package:patrol/src/common.dart:120:21)
        #12     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
        <asynchronous suspension>
        #13     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:986:5)
        <asynchronous suspension>
        (elided 4 frames from class _AssertionError and dart:async)
        ════════════════════════════════════════════════════════════════════════════════════════════════════
        00:00 +1 -1: Some tests failed.`

**Comment by bartekpacia** [comment]
Fixed by #1347.
