### ISSUE TITLE
Getting connection refused if AdGuard DNS is active on Mac

### ISSUE THREAD

**Issue by uzuki-P** [leancodepl/patrol#1361]
### Steps to reproduce

1. Install AdGuard Public DNS filter from their site
2. run ` patrol test --target integration_test/example_test.dart --flavor staging`

### Actual results

It return `Connection refused`

### Logs

<details>
<summary>Logs</summary>

```
Unhandled exception:
Connection refused
#0      IOClient.send (package:http/src/io_client.dart:94:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32)
<asynchronous suspension>
#2      Analytics.sendCommand (package:patrol_cli/src/analytics/analytics.dart:77:5)
<asynchronous suspension>

```

</details>

### Patrol version

patrol: ^1.1.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 1.1.11
Program adb found in /Users/uzukip/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/uzukip/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4 22F66 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1.1)
[✓] VS Code (version 1.79.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by bartekpacia** [comment]
Hi, thanks for reporting this.

Looks like this is because of analytics. Please disable them by:

```
rm ~/.config/patrol_cli/analytics.json
```

and then run `patrol_cli` again. It should ask whether to enable analytics, and you should answer "No".

**Comment by uzuki-P** [comment]
Thank You
I've been trying `deactivate` and `reactivate` the cli package but the analytics still on. Didn't think it will be on `.config`.😅
