### ISSUE TITLE
New scrolling is too slow

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1383]
Reproduction here: #1384, but basically, add the following line at the end of `example_test`

```dart
await $('EXAMPLE_KEY: at the bottom').scrollTo().tap();
```

---

Clone it and run:

```
patrol test -t integration_test/example_test.dart --dart-define EXAMPLE_KEY="at the bottom"
```

Observe slow scroll:

https://github.com/leancodepl/patrol/assets/40357511/1f83cb83-4385-4bb6-8f2e-87b7fbbcc29c

**Comment by jBorkowska** [comment]
We could try setting drag's duration to 0 seconds (or just shorter duration).
