### ISSUE TITLE
Remove possibility to use other bindings than `PatrolBinding` during integration tests

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1425]
This logic should be simplified:

https://github.com/leancodepl/patrol/blob/d89c3869e0e42d8207ac711922dac7a2f3f7a174/packages/patrol/lib/src/common.dart#L61-L75

In particular:
- `BindingType.integrationTest` should be removed (#1368)
- actually, the whole `BindingType` enum should be removed
- New logic:
  - `if (nativeAutomation)` then initialize `PatrolBinding`
  - `else`, don't do anything (use the default binding that `flutter test` initializes)

---

I doubt specifying using the default `integration_test` binding works now, and we don't even have tests for them. Also, I see no benefit in allowing this.

See also:
- #1368

**Comment by jBorkowska** [comment]
See also #1273

**Comment by bartekpacia** [comment]
This should be together with #1273, preferably in a single PR.
