### ISSUE TITLE
`grantPermissionOnlyThisTime` fails on Android < 11

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1450]
See https://developer.android.com/about/versions/11/privacy/permissions#one-time.

We need to decide whether it failing is the right behavior, or maybe should we fallback to `grantPermission()`?

**Comment by jBorkowska** [comment]
Checked, doesn't work on API 29 (Android 10)

**Comment by bartekpacia** [comment]
The question persists:

> We need to decide whether failing is the right behavior (because there's no concept of "grant permission only this time" on older OS versions), or maybe should we fallback to grantPermission()?

**Comment by jBorkowska** [comment]
The answer is "Yes" :)

**Comment by jBorkowska** [comment]
Ah, wait, I mean fallback to `grantPermission()` sounds good.

**Comment by bartekpacia** [comment]
This... already works as expected, and I can't recall fixing it..

@jBorkowska I'm going to (reluctantly) close this :|

**Comment by jBorkowska** [comment]
Wait what?

**Comment by jBorkowska** [comment]
Test `permissions_location_test.dart` fails on API 29 (Pixel_5_API_29) when you change line 43 to
`await $.native.grantPermissionOnlyThisTime();`

**Comment by bartekpacia** [comment]
Thanks for investigation @jBorkowska.

But line 43 is just a `}`.

https://github.com/leancodepl/patrol/blob/658cd5af763f6431eda8a3416b5b97024f18b202/packages/patrol/example/integration_test/permissions_many_test.dart

**Comment by bartekpacia** [comment]
Ah, so it was the location permission dialog, not a generic one, haha. We forgot to include this info in the OP.
