### ISSUE TITLE
How to access keyboard buttons using patrol

### ISSUE THREAD

**Issue by lravihs** [leancodepl/patrol#1453]
### Steps to reproduce

I wanna know how to click keyboard buttons using patrol. I am not able to find it in the patrol website

### Actual results

Not able to interact using selectors

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol:^2.0.0

### Patrol Doctor output

NA

### Flutter Doctor output

NA

**Comment by bartekpacia** [comment]
This is not currently possible.

Can you explain you use-case in more detail?

**Comment by lravihs** [comment]
After entering the email password credentials in sign-in screen have to hide the keyboard. I have done it in flutter using this code - **await tester.testTextInput.receiveAction(TextInputAction.done);** but in patrol I am not able to click done button in keyboard

**Comment by lravihs** [comment]
Otherwise is there any option to instantiate WidgetTester once after we instantiated the PatrolTester.?

**Comment by bartekpacia** [comment]
You can access the `WidgetTester` by doing `$.tester`. This is explained [in the docs](https://patrol.leancode.co/finders/usage#falling-back).

**Comment by lravihs** [comment]
Thanks a lot. It's cleared now
