### ISSUE TITLE
How to get the text of the element. Please provide the syntax for this method

### ISSUE THREAD

**Issue by lravihs** [leancodepl/patrol#1454]
### Steps to reproduce

NA

### Actual results

Not able to get the text of the element

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol:^2.0.0

### Patrol Doctor output

NA

### Flutter Doctor output

NA

**Comment by bartekpacia** [comment]
This issue doesn't follow the template.
