### ISSUE TITLE
Patrol v2.0.1 clearPackageData "true" doesn't work

### ISSUE THREAD

**Issue by benjamin-inspectly** [leancodepl/patrol#1469]
### Steps to reproduce

Hi Patrol!

Nice upgrade with patrol v2! I love the test bundling feature.
But I seem to have a problem getting "clearPackageData" to work.

I am currently only testing Android builds, and have added this line in my app-specific build.gradle file during my upgrade to Patrol v2:
![image](https://github.com/leancodepl/patrol/assets/114057836/fbbffadb-c131-4244-a9e5-280eb59dc44b)

Do you have any idea why this isn't working? I would like to have complete isolation between my tests so that I don't have to start some of my tests by logging out.

I have 2 "_test.dart" files and the app is restarting before running each test file, but does not clear the app data as if I went into "Settings" - "Apps" - found my app and cleared it manually.

Have I misunderstood anything? Or am I missing anything.

Thank you!

### Actual results

clearPackageData not working

### Logs

<details>
<summary>Logs</summary>

```
No logs for this issue
```

</details>

### Patrol version

![image](https://github.com/leancodepl/patrol/assets/114057836/426d050d-0da1-46bc-a376-d8d00bc53a00)

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.0.1
Program adb found in C:\Users\BenjaminMejbomBerndt\AppData\Local\Android\Sdk\platform-tools\adb.exe
Env var $ANDROID_HOME set to C:\Users\BenjaminMejbomBerndt\AppData\Local\Android\Sdk
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.3, on Microsoft Windows [Version 10.0.22621.1848], locale en-DK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.2)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.79.1)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by bartekpacia** [comment]
Hi @benjamin-inspectly, sorry for the problems.

It's strange that it doesn't work. How are you running the tests (`patrol test` or some cloud device farm)? What device and Android version? It'd also be helpful if you attached a log file from `adb` after running your tests:

```
adb logcat -d > logcat.txt
```

BTW, I see you're using `patrol_cli v2.0.1`, which [requires at least `patrol v2.0.1`](https://pub.dev/packages/patrol_cli/changelog). I recommend always using the latest versions:)

**Comment by bartekpacia** [comment]
Since this issue is old and has no new activity, I'm going to close it. Please create a new issue if you experience a similar problem.
