### ISSUE TITLE
Tapping on notifications doesn't work on physical iOS device

### ISSUE THREAD

**Issue by fylyppo** [leancodepl/patrol#1475]
### Steps to reproduce

1. Run notifications_test.dart on physical iOS device

### Actual results

after `await $.native.tapOnNotificationBySelector(
        Selector(textContains: 'Someone liked'),
      );`
you can see that you still need to tap on "Open" button.
What's interesting tapping on notifications works on simulator (`tapOnNotificationBySelector` takes me to app)
![IMG_C8DEB0B5D74B-1](https://github.com/leancodepl/patrol/assets/63547653/5d0ba06f-e4db-4e5e-b7d3-64edf1ab3cae)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol 2.0.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by bartekpacia** [comment]
It works on my private iPhone 12 mini.

**Comment by bartekpacia** [comment]
Which specific iOS device did you run on?
