### ISSUE TITLE
taking screenshots

### ISSUE THREAD

**Issue by solaristhesun** [leancodepl/patrol#1476]
### Steps to reproduce

.

### Actual results

Hello, I found patrol via https://github.com/flutter/flutter/issues/48045#issuecomment-1319159115. I was excited to take screenshots using "$.host.takeScreenshot()" but now found there is no $.host. What is going on there?

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^2.0.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by bartekpacia** [comment]
Hi @solaristhesun, we had that feature in 0.x, but we had to remove it in 1.x.

See #534.
