### ISSUE TITLE
windows cannot downgrade to patrol_cli ^1.0.0

### ISSUE THREAD

**Issue by GentiShtjefni** [leancodepl/patrol#1497]
### Steps to reproduce

I deactivated patrol_cli and tried to re activate it by running this command `dart pub global activate patrol_cli ^1.0.0` because I dont want the latest version, and this is the issue I get:
`C:\Users\User\Documents\DashFuel\flutter>dart pub global activate patrol_cli ^1.0.0
+ _fe_analyzer_shared 62.0.0.6s)
+ adb 0.2.5
+ analyzer 6.0.0
+ ansi_styles 0.3.2+1
+ args 2.4.2
+ async 2.11.0
+ boolean_selector 2.1.1
+ collection 1.17.2
+ convert 3.1.1
+ coverage 1.6.3
+ crypto 3.0.3
+ dart_internal 0.2.8
+ dispose_scope 2.1.0
+ equatable 2.0.5
+ file 6.1.4 (7.0.0 available)
+ freezed_annotation 2.2.0
+ frontend_server_client 3.2.0
+ glob 2.1.2
+ http 0.13.6 (1.1.0 available)
+ http_multi_server 3.2.1
+ http_parser 4.0.2
+ io 1.0.4
+ js 0.6.7
+ json_annotation 4.8.1
+ logging 1.2.0
+ mason_logger 0.2.7
+ matcher 0.12.16
+ meta 1.9.1
+ mime 1.0.4
+ mocktail 0.3.0
+ node_preamble 2.0.2
+ package_config 2.1.0
+ path 1.8.3
+ patrol_cli 1.0.0 (2.0.2 available)
+ platform 3.1.0
+ pool 1.5.1
+ process 4.2.4
+ pub_semver 2.1.4
+ pub_updater 0.2.4 (0.3.1 available)
+ shelf 1.4.1
+ shelf_packages_handler 3.0.2
+ shelf_static 1.1.2
+ shelf_web_socket 1.0.4
+ source_map_stack_trace 2.1.1
+ source_maps 0.10.12
+ source_span 1.10.0
+ stack_trace 1.11.1
+ stream_channel 2.1.2
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ test 1.24.4
+ test_api 0.6.1
+ test_core 0.5.4
+ tuple 2.0.2
+ typed_data 1.3.2
+ vm_service 11.7.2
+ watcher 1.1.0
+ web_socket_channel 2.4.0
+ webkit_inspection_protocol 1.2.0
+ yaml 3.1.2
Building package executables... (4.8s)
Failed to build patrol_cli:main:
../../../AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-1.0.0/lib/src/common/logger.dart:60:8: Error: The method 'Logger.warn' has fewer named arguments than those of overrid
den method 'Logger.warn'.
  void warn(String? message, {String tag = ''}) {
       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/mason_logger-0.2.7/lib/src/mason_logger.dart:153:8: Context: This is the overridden method ('warn').
  void warn(String? message, {String tag = 'WARN', LogStyle? style}) {
       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-1.0.0/lib/src/common/logger.dart:60:8: Error: The method 'Logger.warn' doesn't have the named parameter 'style' of ove
rridden method 'Logger.warn'.
  void warn(String? message, {String tag = ''}) {
       ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/mason_logger-0.2.7/lib/src/mason_logger.dart:153:8: Context: This is the overridden method ('warn').
  void warn(String? message, {String tag = 'WARN', LogStyle? style}) {
       ^

` 
when I try without the version `dart pub global activate patrol_cli` it works and it installs the latest version: 
`C:\Users\User\Documents\DashFuel\flutter>dart pub global activate patrol_cli        
+ _fe_analyzer_shared 62.0.0.1s)
+ adb 0.2.5
+ analyzer 6.0.0
+ ansi_styles 0.3.2+1
+ args 2.4.2
+ async 2.11.0
+ boolean_selector 2.1.1
+ ci 0.1.0
+ cli_completion 0.3.0
+ collection 1.17.2
+ convert 3.1.1
+ coverage 1.6.3
+ crypto 3.0.3
+ dart_internal 0.2.8
+ dispose_scope 2.1.0
+ equatable 2.0.5
+ file 6.1.4 (7.0.0 available)
+ frontend_server_client 3.2.0
+ glob 2.1.2
+ http 0.13.6 (1.1.0 available)
+ http_multi_server 3.2.1
+ http_parser 4.0.2
+ io 1.0.4
+ js 0.6.7
+ json_annotation 4.8.1
+ logging 1.2.0
+ mason_logger 0.2.5 (0.2.7 available)
+ matcher 0.12.16
+ meta 1.9.1
+ mime 1.0.4
+ mocktail 0.3.0
+ node_preamble 2.0.2
+ package_config 2.1.0
+ path 1.8.3
+ patrol_cli 2.0.2
+ platform 3.1.0
+ pool 1.5.1
+ process 4.2.4
+ pub_semver 2.1.4
+ pub_updater 0.2.4 (0.3.1 available)
+ shelf 1.4.1
+ shelf_packages_handler 3.0.2
+ shelf_static 1.1.2
+ shelf_web_socket 1.0.4
+ source_map_stack_trace 2.1.1
+ source_maps 0.10.12
+ source_span 1.10.0
+ stack_trace 1.11.1
+ stream_channel 2.1.2
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ test 1.24.4
+ test_api 0.6.1
+ test_core 0.5.4
+ tuple 2.0.2
+ typed_data 1.3.2
+ uuid 3.0.7
+ vm_service 11.7.2
+ watcher 1.1.0
+ web_socket_channel 2.4.0
+ webkit_inspection_protocol 1.2.0
+ yaml 3.1.2
Building package executables... (2.1s)
Built patrol_cli:main.
Installed executable patrol.
Activated patrol_cli 2.0.2.
`

### Actual results

..

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^2.0.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
C:\Users\User\Documents\DashFuel\flutter>patrol doctor output
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.0.2
Program adb found in C:\Users\User\AppData\Local\Android\Sdk\platform-tools\adb.exe
Env var $ANDROID_HOME is not set
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19044.1288], locale en-GB)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2020.3)
[√] Android Studio (version 2022.2)
[√] Connected device (4 available)
[√] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by bartekpacia** [comment]
Try doing `dart pub cache clean` and then repeating the process.

**Comment by GentiShtjefni** [comment]
I tried `dart pub cache clean` and also `flutter pub cache repair` and still doesn't work

**Comment by Curosevic** [comment]
Having the same issue here

**Comment by bartekpacia** [comment]
Quite strange that it doesn't work only on Windows.

**Comment by GentiShtjefni** [comment]
@bartekpacia Just tried to downgrade the same project on Mac and it worked.

**Comment by bartekpacia** [comment]
I'm going to close it since nobody should be downgrading to v1 anymore (it's too old).
