### ISSUE TITLE
Better reporter for tests

### ISSUE THREAD

**Issue by karfaoui11** [leancodepl/patrol#1531]
I hope that this feature is part of of your roadmap.
But it should be super nice to have a clean reporter (with a silent option to avoid displaying flutter related warnings)
like "spec".
With clear error message, it's not clear at all when a step or an assertion fails, it should be a nice to have and a great helper for debugging.

**Comment by Gaurav-CareMonitor** [comment]
+1

**Comment by bartekpacia** [comment]
related: #528 and #951

**Comment by bartekpacia** [comment]
superseded by #1855
