### ISSUE TITLE
java.lang.ClassCastException: androidx.test.runner.AndroidJUnitRunner cannot be cast to pl.leancode.patrol.PatrolJUnitRunner         :       at MainActivityTest.testCases(MainActivityTest.java:24)

### ISSUE THREAD

**Issue by RuslikMer** [leancodepl/patrol#1538]
### build.gradle

android {
    compileSdkVersion 33
    buildToolsVersion '33'
    defaultConfig {
        applicationId "com.bambinifashion.staging"
        minSdkVersion 33
        targetSdkVersion 33
        versionCode 33
        versionName '33'
        testInstrumentationRunner "pl.leancode.patrol.PatrolJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: "true"
    }

    testOptions {
        execution "ANDROIDX_TEST_ORCHESTRATOR"
    }
}

dependencies {
    androidTestUtil "androidx.test:orchestrator:1.4.2"
}

### MainActivityTest.java

package com.bambinifashion.staging;

import org.junit.runner.RunWith;
import com.bambinifashion.bambinifashion.MainActivity;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.Test;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;
import pl.leancode.patrol.PatrolJUnitRunner;

@RunWith(Parameterized.class)
public class MainActivityTest {
    @Parameters(name = "{0}")
    public static Object[] testCases() {
        PatrolJUnitRunner instrumentation = (PatrolJUnitRunner) InstrumentationRegistry.getInstrumentation();
        instrumentation.setUp(MainActivity.class);
        instrumentation.waitForPatrolAppService();
        return instrumentation.listDartTests();
    }

    public MainActivityTest(String dartTestName) {
        this.dartTestName = dartTestName;
    }

    private final String dartTestName;

    @Test
    public void runDartTest() {
        PatrolJUnitRunner instrumentation = (PatrolJUnitRunner) InstrumentationRegistry.getInstrumentation();
        instrumentation.runDartTest(dartTestName);
    }
}

### Logs

 > Task :app:connectedStagingDebugAndroidTest
        : Starting 1 tests on SM-S901E - 13
        : 
        : com.bambinifashion.staging.MainActivityTest > initializationError[SM-S901E - 13] FAILED 
        :       java.lang.ClassCastException: androidx.test.runner.AndroidJUnitRunner cannot be cast to pl.leancode.patrol.PatrolJUnitRunner
        :       at com.bambinifashion.staging.MainActivityTest.testCases(MainActivityTest.java:24)
        : Tests on SM-S901E - 13 failed: There was 1 failure(s).

### Patrol version

^2.0.1

### Patrol Doctor output

Patrol CLI version: 2.0.4
Program adb found in /Users/rus/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/rus/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale ru-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

</details>

**Comment by RuslikMer** [comment]
I set it up according to the instructions https://patrol.leancode.co/getting-started/native, but it didn’t work, I had to add sdk versions to build.gradle, the mainActivityTest file is exactly like in the instructions, I just replaced it with my package, I get this error

**Comment by jBorkowska** [comment]
Hi, thank you for creating this issue.
We are investigating your problem. Could you provide some more information:
- which command do you use to run your tests?
- which version of patrol_cli do you use?
- is "staging" a flavor in your app?

**Comment by RuslikMer** [comment]
> Hi, thank you for creating this issue. We are investigating your problem. Could you provide some more information:
> 
> * which command do you use to run your tests?
> * which version of patrol_cli do you use?
> * is "staging" a flavor in your app?

- patrol test --target integration_test/patrol_test.dart --flavor staging --verbose
- Patrol CLI 2.0

**Comment by RuslikMer** [comment]
pubspec.yml

patrol:
  app_name: bambinifashion
  flavor: staging
  android:
    package_name: com.bambinifashion.staging

**Comment by jBorkowska** [comment]
It looks like you provided package name of a flavor, not the whole app in the `MainActivityTest.java` file. Try changing the package line to `package com.bambinifashion`.
If this won't solve the problem, instead of changing `package` import, try to not pass the `flavor` option in `patrol test` command.

**Comment by jBorkowska** [comment]
Also, if you provided flavor in pub spec, you don't need to pass it as a parameter in `patrol test`

**Comment by RuslikMer** [comment]
tried to change package from com.bambinifashion.staging to com.bambinifashion , but it's impossible, because only com.bambinifashion.staging exist, and tried to run without --flavor staging, it didn't help, same error

**Comment by jBorkowska** [comment]
Another question: why there is additional import in `MainActivityTest.java`? 
```import com.bambinifashion.bambinifashion.MainActivity;```

**Comment by jBorkowska** [comment]
It looks like your package name is `com.bambinifashion.bambinifashion`, try setting it as package import in the first line and removing the `import com.bambinifashion.bambinifashion.MainActivity;` line

**Comment by RuslikMer** [comment]
<img width="1107" alt="Снимок экрана 2023-07-17 в 14 07 37" src="https://github.com/leancodepl/patrol/assets/30290012/64ff15b9-389b-4bf2-9ab6-c9e69f38e130">
If commit this import

**Comment by jBorkowska** [comment]
Ok, but the MainActivity should be imported from package, so try replacing
```package com.bambinifashion.staging;```
with
```package com.bambinifashion.bambinifashion;```
because `MainActivity.class` is taken form there

**Comment by RuslikMer** [comment]
imports problem resolved, thank you!
  but main issue still exist
  java.lang.ClassCastException: androidx.test.runner.AndroidJUnitRunner cannot be cast to pl.leancode.patrol.PatrolJUnitRunner

**Comment by jBorkowska** [comment]
Oh no :(
Let's try something else then. Could you check java version on your machine?

**Comment by mateuszwojtczak** [comment]
Hi @RuslikMer!
Could you also share your build.gradle files (both app- and top-level)?

**Comment by RuslikMer** [comment]
> Hi @RuslikMer! Could you also share your build.gradle files (both app- and top-level)?

android/app/build.gradle

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader -> localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
// END: FlutterFire Configuration
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.bambinifashion"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        //minSdkVersion flutter.minSdkVersion
        minSdkVersion 21
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    flavorDimensions "version"

    productFlavors {
        staging {
            dimension "version"
            resValue "string", "app_name", "BAMBINIFASHION [Staging]"
            applicationIdSuffix = ".staging"
            versionNameSuffix = ""
        }
        production {
            dimension = "version"
            resValue "string", "app_name", "BAMBINIFASHION"
            applicationIdSuffix = ".production"
            versionNameSuffix = ""
        }
    }
}

task wrapper(type: Wrapper){
    gradleVersion = '7.5'
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

task prepareKotlinBuildScriptModel {

}


android/build.gradle

apply plugin: 'com.android.application'
buildscript {
    //ext.kotlin_version = '1.7.10'
    ext.kotlin_version = '1.8.0' // Flutter Stripe requirement
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

//plugins {
//    id "com.android.application"
//}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

//task clean(type: Delete) {
//    delete rootProject.buildDir
//}

android {
    compileSdkVersion 33
    buildToolsVersion '33'
    defaultConfig {
        applicationId "com.bambinifashion.staging"
        minSdkVersion 33
        targetSdkVersion 33
        versionCode 33
        versionName '33'
        testInstrumentationRunner "pl.leancode.patrol.PatrolJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: "true"
    }

    testOptions {
        execution "ANDROIDX_TEST_ORCHESTRATOR"
    }
}

dependencies {
    androidTestUtil "androidx.test:orchestrator:1.4.2"
}

**Comment by RuslikMer** [comment]
> Oh no :( Let's try something else then. Could you check java version on your machine?

openjdk 11.0.19 2023-04-18 LTS
OpenJDK Runtime Environment Zulu11.64+19-CA (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.64+19-CA (build 11.0.19+7-LTS, mixed mode)

**Comment by jBorkowska** [comment]
Thanks for providing this info. It looks like you did the configuration in `build.gradle` properly, but in the wrong file - it should be done in the app-level `build.gradle` file. Hope it helps

**Comment by RuslikMer** [comment]
thanks, really, this issue solved, now have new one, will search solutions
