### ISSUE TITLE
Is it possible to run multiple test files on FTL at the same time?

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [leancodepl/patrol#1539]
### Steps to reproduce

First, I know this is not a problem with patrol but directly with firebase test lab but wondering if you have a workaround or a solution for this.

From the firebase docs: https://docs.flutter.dev/testing/integration-tests, they ask us to create assembleDebug
./gradlew app:assembleDebug -Ptarget=integration_test/<name>_test.dart for each test file.

### Actual results

There is a similar issue but that is not accepting comments anymore, Is this fixed? https://github.com/leancodepl/patrol/issues/1269

</details>

### Patrol version

[patrol ](patrol: ^2.0.2)

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.0.4
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale en-IN)
    • Flutter version 3.10.6 on channel stable at /Users/gaurav/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (5 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/gaurav/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.81.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (3 available)
    • POCO F1 (mobile) • 850c9bbc • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos    • darwin-arm64   • macOS 13.4 22F66 darwin-arm64
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by jBorkowska** [comment]
Hi @Gaurav-CareMonitor ! We released Patrol 2.0 recently, which enabled using Patrol with FTL. You can build necessary files using `patrol build android` and use them in FTL. If you encounter any problems or have any specific questions, feel free to create another issue.

**Comment by Gaurav-CareMonitor** [comment]
Hi @jBorkowska , I tried bundling different test files in a single apk
I am using this command:
`
patrol build android \
    --target integration_test/auth_test/single_user_login_test.dart \
    --target integration_test/app_test/metric_test.dart \
    --target integration_test/app_test/message_test.dart \
    --target integration_test/app_test/resource_visibility_test.dart \
    --verbose
`

but Firebase Test Lab throws this error after the first test:
```
io.grpc.StatusRuntimeException: UNKNOWN: 'package:patrol/src/native/patrol_app_service.dart': Failed assertion: line 129 pos 12: '_testExecutionCompleted.isCompleted == false': is not true.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at pl.leancode.patrol.contracts.PatrolAppServiceGrpc$PatrolAppServiceBlockingStub.runDartTest(PatrolAppServiceGrpc.java:215)
	at pl.leancode.patrol.PatrolAppServiceClient.runDartTest(PatrolAppServiceClient.java:40)
	at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:128)
	at com.health.caremonitor.MainActivityTest.runDartTest(MainActivityTest.java:29)

```

<img width="1145" alt="image" src="https://github.com/leancodepl/patrol/assets/113885801/c0b2220f-ff05-4b88-8e6c-c7a79a23ca5c">

**Comment by jBorkowska** [comment]
Are you sure that you sent 2 apks? Take a look at scripts in our repo, that are a part of our example app, maybe you'll find a solution there

**Comment by fylyppo** [comment]
[Here's the script we use](https://github.com/leancodepl/patrol/blob/1eeba82df27065e07eff8ac04b0c85b9d9548f72/packages/patrol/example/run_android_testlab#L4) but you don't need to set `packageName`.
It'll be also great if you show us your invocation to FTL.

**Comment by Gaurav-CareMonitor** [comment]
This is my FTL script
```
gcloud firebase test android run \
    --type instrumentation \
    --app build/app/outputs/apk/Caremonitor/debug/app-Caremonitor-debug.apk \
    --test build/app/outputs/apk/androidTest/Caremonitor/debug/app-Caremonitor-debug-androidTest.apk \
    --timeout 1m \
    --device=model=gts8uwifi,version=33
```

**Comment by Gaurav-CareMonitor** [comment]
Working fine after adding  `--use-orchestrator` flag. Thanks
<img width="423" alt="image" src="https://github.com/leancodepl/patrol/assets/113885801/e18d3ce5-8952-40ee-83e1-4ae9e2030f62">
