### ISSUE TITLE
[Website] Native setup page does not work

### ISSUE THREAD

**Issue by gabrielaraujoz** [leancodepl/patrol#1546]
### Steps to reproduce

Hi there, I've been trying to check the native setup page since yesterday but all I get is a 404 error. Could you please check if it's ok?

Link: https://patrol.leancode.co/native/setup

I got it from here, in the callout with the native setup info: https://patrol.leancode.co/ci/firebase-test-lab

### Actual results

.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

.

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by bartekpacia** [comment]
Hi, looks like that link is broken.

This is the correct one: https://patrol.leancode.co/getting-started/native

**Comment by jBorkowska** [comment]
Thank you for reporting this issue, probably the link changed and we forgot to update it. The page is now here: https://patrol.leancode.co/getting-started/native

**Comment by gabrielaraujoz** [comment]
Thanks a lot <3
