### ISSUE TITLE
App launching twice

### ISSUE THREAD

**Issue by RuslikMer** [leancodepl/patrol#1547]
### Steps to reproduce

<img width="730" alt="Снимок экрана 2023-07-18 в 16 13 08" src="https://github.com/leancodepl/patrol/assets/30290012/85d77289-3a72-4e3e-bac9-e8e7802f821b">

### Actual results

https://github.com/leancodepl/patrol/assets/30290012/a1ffc9d1-ceb3-4467-8964-8f5887cdd678

### Logs

<details>
<summary>Logs</summary>

</details>

### Patrol version

^2.0.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

Patrol CLI version: 2.0.4
Program adb found in /Users/rus/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/rus/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with brew install ideviceinstaller)

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale ru-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (3 available)
[✓] Network resources

</details>

**Comment by jBorkowska** [comment]
Hi @RuslikMer . The video that you posted looks good - there is always a "fake test run" done by Patrol that is needed to discover all the tests that it needs to run, so there will be always an additional app opening before real tests.

**Comment by jBorkowska** [comment]
This looks like the test is running twice, but it is not - try adding more steps in your test and then it will be more clear

**Comment by jBorkowska** [comment]
Closing issue, rwach out if you encounter any other issues
