### ISSUE TITLE
Disparity of `Selector` behavior between Android and iOS

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1554]
Patrol has the [`Selector`](https://github.com/leancodepl/patrol/blob/d8e462d2f4418f9558f8bab7595e460f50042160/contracts.proto#L178-L191) and [`NativeView`](https://github.com/leancodepl/patrol/blob/d8e462d2f4418f9558f8bab7595e460f50042160/contracts.proto#L196-L206) classes. They provide cross-platform interaction with the underlying native UI.

Currently, there are many differences `Selector` and `NativeView` between its behavior on Android and iOS.

### More about these 2 classes

<details><summary>Selector</summary>

On Android, `Selector`s are translated to [`BySelector`](https://developer.android.com/reference/androidx/test/uiautomator/BySelector)s and/or [`UiSelector`](https://developer.android.com/reference/androidx/test/uiautomator/UiSelector).

On iOS, `Selector`s are translated to [`XCUIElementQuery`](https://developer.apple.com/documentation/xctest/xcuielementquery)-ies. Sometimes, we construct them using `NSSelector`. They allow for searching using many view properties: `identifier`, `title`, `label`, `value`, and `placeholderValue`.

</details> 

<details><summary>NativeView</summary>

On Android, `NativeView`s are created from [`UiObject2`](https://developer.android.com/reference/androidx/test/uiautomator/UiObject2)s.

On iOS, `NativeView`s are created from [`XCUIElement`](https://developer.apple.com/documentation/xctest/xcuielement)s.

</details> 

### Problems

- **on iOS, only `Selector.text` is taken into account** when searching for views
- some `Selector` fields, such as [`resourceId`](https://github.com/leancodepl/patrol/blob/d8e462d2f4418f9558f8bab7595e460f50042160/contracts.proto#L186), are Android-only. That's because the `Selector` API predates iOS support.
- some `NativeView` fields, such as [`resourceName`](https://github.com/leancodepl/patrol/blob/d8e462d2f4418f9558f8bab7595e460f50042160/contracts.proto#L203), are Android-only. Cause the same as above.
- #1403
- #663

**Comment by fylyppo** [comment]
On iOS `Selector.className` and `Selector.instance` are taken into account also.
It'll be good to have also `textStartsWith` and `textContains` on iOS.
