### ISSUE TITLE
java.lang.AssertionError: Dart test failed

### ISSUE THREAD

**Issue by RuslikMer** [leancodepl/patrol#1563]
### Steps to reproduce

<img width="741" alt="Снимок экрана 2023-07-20 в 16 17 35" src="https://github.com/leancodepl/patrol/assets/30290012/de4c95d1-fb8f-42b0-863c-e081b3227316">
<img width="644" alt="Снимок экрана 2023-07-20 в 16 16 28" src="https://github.com/leancodepl/patrol/assets/30290012/1a0f26e3-eac4-4ef6-9397-4214663eb28f">

### Actual results

https://github.com/leancodepl/patrol/assets/30290012/7f51e927-47e9-4cb4-9f2a-315c588fa10e

### Logs

<details>
<summary>Logs</summary>

> Task :app:connectedStagingDebugAndroidTest
        : Starting 1 tests on SM-S901E - 13
        : 
        : com.bambinifashion.bambinifashion.MainActivityTest > runDartTest[patrol_test][SM-S901E - 13] FAILED 
        :       java.lang.AssertionError: Dart test failed: patrol_test
        :       ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
        : Tests on SM-S901E - 13 failed: There was 1 failure(s).

</details>

### Patrol version

^2.0.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

Patrol CLI version: 2.0.4
Program adb found in /Users/rus/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/rus/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with brew install ideviceinstaller)

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale ru-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (3 available)
[✓] Network resources

</details>

**Comment by RuslikMer** [comment]
await $.pumpWidgetAndSettle(app.main() as Widget); this doesn't work, but really there were some problem in app,
and it starts only by app.main()

**Comment by foxmind1** [comment]
I kept getting this exception at the end of a test, somehow after running a different test and then running the first test worked for me
