### ISSUE TITLE
Tap on n-th push notification from target app

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#157]
similar to #22

**Comment by bartekpacia** [comment]
This is implemented.

**Comment by bartekpacia** [comment]
We've somehow forgotten about it. Ouch.

The problem is that newer Android and iOS versions "bundle" notifications, so it'll require a lot of API-level specific code to work reliably.

https://user-images.githubusercontent.com/40357511/222236133-44ae7df9-5549-486d-9049-822bd960c83d.mov
