### ISSUE TITLE
WaitUntilVisibleTimeoutException was thrown running a test

### ISSUE THREAD

**Issue by RuslikMer** [leancodepl/patrol#1576]
### Steps to reproduce

await $(find.widgetWithText(Transform, tabName)).tap();  //patrol
it's ruined tests step with an error that element doesn't exist,  but by flutter_test library it works perfect
    await tester.tap(
      find.widgetWithText(Transform, tabName),
      warnIfMissed: false,
    );

    await tester.pump(const Duration(seconds: 2));

And if I use patrol "tester" like this
await $.tester.tap(
      find.widgetWithText(Transform, tabName),
      warnIfMissed: false,
    );

    await $.tester.pump(const Duration(seconds: 5));

It doesn't work too with error 
The finder "zero widgets with type "Transform" which is an
ancestor of text "Menu"" (used in a call to "tap()") could not
find any matching widgets.

### Actual results

The following WaitUntilVisibleTimeoutException was thrown running
a test:
TimeoutException after 0:00:10.000000: Finder "exactly one widget
with type "Transform" which is an ancestor of text "Menu":
Transform(dependencies: [Directionality], renderObject:
RenderTransform#36969 relayoutBoundary=up20)" did not find any
visible (i.e. hit-testable) widgets

### Logs

<details>
<summary>Logs</summary>

</details>

### Patrol version

2.0.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

Patrol CLI version: 2.0.4
Program adb found in /Users/rus/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/rus/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with brew install ideviceinstaller)

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale ru-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (3 available)
[✓] Network resources
</details>

**Comment by jBorkowska** [comment]
Hi @RuslikMer. Patrol's `tap()` method does a bit more than raw `tap()` from `flutter_test`. Our version checks, if the widget is tappable, which in `flutter_test` is also possible by using `.hitTestable()` after finder object. Also, we do automatic pumping, so after every action there is `pumpAndSettle()` call (by default, you can modify it through PatrolTesterConfig).

The exception you got tells, that no hit-testable widgets were found, so maybe the widget you are searching for is not hit-testable - second version you posted doesn't check that.

Probably you could write another finder, that would find a hit-testable widget, which will be in the same place on screen as the one you find now, and Patrol's tap would work with it.

**Comment by RuslikMer** [comment]
and if there will not be any hit-testable widgets?

**Comment by jBorkowska** [comment]
Then Patrol won't be able to click on it. We consider non-hit testable widgets as widgets that are not visible for a real user. If you still want to interact with it for some reason, use raw tap method from `flutter_test`. Though we do not recommend it, because we find it unreliable when it comes to simulating real user (especially bc it can tap on something, that is in the widget tree, but is not visible on the screen).

**Comment by RuslikMer** [comment]
but in my case this element is visible, okay will check another widgets

**Comment by jBorkowska** [comment]
I see, but the widget can be not hit-testable, even if it is on the screen, it's unfortunately not 1-1 relationship :( We haven't figure out yet why it works like that, but that's how Flutter works and we depend on it. I recommend trying another widgets as you said

**Comment by jBorkowska** [comment]
Closing, feel free to reopen if the issue persists
