### ISSUE TITLE
Outdated section in docs

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1583]
This section seems outdated: https://patrol.leancode.co/cli-commands/build#caveats

**Comment by neiljaywarner** [comment]
of course, still it is useful if you haven' tupgraded to 2.0 bc dependency issues :)

**Comment by bartekpacia** [comment]
Fixed in https://github.com/leancodepl/patrol/commit/7eff73739c181fa09354f5fc1e546b3bb0f8fba1
