### ISSUE TITLE
Cannot enter text in Stripe payment form

### ISSUE THREAD

**Issue by RuslikMer** [leancodepl/patrol#1587]
### Steps to reproduce

stripe form is native element, and it has only 2 locators in widget tree find.byType(CardField) and find.byType(StripeForm), all other in native view, when I tried to tap at this form by patrol it tap but doesn't interact,  and by my real tap it works fine like on screen
![2023-07-27 19 03 25](https://github.com/leancodepl/patrol/assets/30290012/85279ea3-c540-4235-ae8c-b76ea02fba6a)

what I already tried with both locators find.byType(CardField) and find.byType(StripeForm)
1) final stripe = find.byType(StripeForm); 
    final point = await $.tester.getCenter(stripe);
    print(point.dx);
    print(point.dy);
    await $.tester.tapAt(Offset(point.dx, point.dy));
  
2) await $(find.byType(StripeForm)).tap();

3) await $.native.tap(Selector(text: '1234123412341234'));

4) await $.native.enterText(
      Selector(text: '1234123412341234'),
      text: '${cardNumber}1228123',
    );

### Actual results

java.lang.AssertionError: Dart test failed: patrol_test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: GrpcError: enterText() failed with code
NOT_FOUND (selector UiSelector[TEXT=1234123412341234] found
nothing)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

^2.0.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

Patrol CLI version: 2.0.4
Program adb found in /Users/rus/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/rus/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with brew install ideviceinstaller)

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4 22F66 darwin-arm64, locale ru-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
[✓] Connected device (3 available)
[✓] Network resources
</details>

**Comment by jBorkowska** [comment]
Hi @RuslikMer. Which of the ways that you mentioned worked and which didn't? I didn't quite get it.

Also, if Stripe is a native view, then you'll have to use native tap and enterText. You can try here `enterTextByIndex` (have a look at our API reference: https://pub.dev/documentation/patrol/latest/patrol/NativeAutomator/enterTextByIndex.html

**Comment by RuslikMer** [comment]
nothing worked from what I mentioned, on screen I just show what I expected

**Comment by jBorkowska** [comment]
Then I recommend trying `enterTextByIndex` or trying to get specific resourceId or classname of this native element. This page in docs might help: https://patrol.leancode.co/tips-and-tricks#inspecting-native-view-hierarchy

**Comment by RuslikMer** [comment]
https://github.com/leancodepl/patrol/assets/30290012/5030de86-d3c2-49ac-89b2-f29b0a80add0

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
        : 
        [ddms]: Exception during activity from Selector.
        [ddms]: null
        java.nio.channels.CancelledKeyException
                at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
                at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
                at java.base/java.nio.channels.SelectionKey.isAcceptable(SelectionKey.java:425)
                at com.android.ddmlib.internal.jdwp.JdwpProxyServer.runAsServer(JdwpProxyServer.java:281)
                at com.android.ddmlib.internal.jdwp.JdwpProxyServer.run(JdwpProxyServer.java:321)
                at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by RuslikMer** [comment]
java.lang.AssertionError: Dart test failed: patrol_test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the
current test, and at least one was unexpected.

**Comment by jBorkowska** [comment]
@RuslikMer, try changing `KeyboardBehavior` to `alternative` - it shouldn't show the keyboard, so the field won't be covered by it

**Comment by RuslikMer** [comment]
unfortunately it's not working using alternative

**Comment by Gaurav-CareMonitor** [comment]
Getting same error while using patrol build

[ddms]: Exception during activity from Selector.
[ddms]: null
java.nio.channels.CancelledKeyException
at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
at java.base/java.nio.channels.SelectionKey.isAcceptable(SelectionKey.java:425)
at com.android.ddmlib.internal.jdwp.JdwpProxyServer.runAsServer(JdwpProxyServer.java:281)
at com.android.ddmlib.internal.jdwp.JdwpProxyServer.run(JdwpProxyServer.java:321)
at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by RuslikMer** [comment]
problem solved after we updated our app and this page too, so only alternative keyboard method helped for this iframe
