### ISSUE TITLE
How to select the dropdown value from the native webview

### ISSUE THREAD

**Issue by ashwinichannaveerappa** [leancodepl/patrol#1590]
### Steps to reproduce

![IMG-7289](https://github.com/leancodepl/patrol/assets/58765248/2af981ac-5214-488a-87ff-cc12e8064684)
![IMG-7290](https://github.com/leancodepl/patrol/assets/58765248/aa4413e7-9abe-4429-87a6-15d5b7f96a47)

### Actual results

Dear Team,
I am facing issues with selecting values from a dropdown list and tapping a checkbox in my test automation code.

1. For the dropdown list, I attempted to use the enterText method as an alternative. However, I am unable to simulate pressing the "ENTER" key after entering the desired value. As a result, the selection process is incomplete.

    await $.native.enterText(Selector(text: 'Country'), text: 'Austria',keyboardBehavior: KeyboardBehavior.showAndDismiss);

2. Similarly, for the checkbox, I tried using the tap method, but it doesn't seem to work as expected. The checkbox remains unselected, and the test cannot proceed further.

    await $.native.tap(Selector(text: 'I agree to the Terms and Conditions and have read the Privacy Policy'));

I would appreciate your assistance in resolving these issues. Please provide guidance or alternative solutions to handle dropdown selections and checkbox interactions in the testing framework.

Thank you for your help.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol_cli v2.0.4

### Patrol Doctor output

You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.0.4
Program adb found in C:\Users\achannav\scoop\shims\adb.exe
Env var $ANDROID_HOME set to C:\Users\achannav\AppData\Local\Android\sdk

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3208], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources

**Comment by jBorkowska** [comment]
Hi @ashwinichannaveerappa, sorry for late response, I'll try to reproduce your issue and let you know if I found anything

**Comment by ashwinichannaveerappa** [comment]
Hi @jBorkowska no problem, thanks for the quick update.

**Comment by jBorkowska** [comment]
Hi again, it looks like currently there is no way of tapping on this dropdown. We'll be trying to fix it and will let you know about any updates

Note to self: related to #992.

**Comment by ashwinichannaveerappa** [comment]
Thank you @jBorkowska , Is there any way to tap on check box? and swipe on the slider?

**Comment by ashwinichannaveerappa** [comment]
@jBorkowska Thank you for the quick reply.
yeah those are native elements. I will try with classname.

**Comment by jBorkowska** [comment]
@ashwinichannaveerappa Also it may be necessary to provide `appId` of the app that you try to interact with. By default Patrol would try to interact with app you're testing, so it will try to find native elements in the Flutter app. In your case, you might need to provide `appId` of Safari (I'm not sure which app is it on the screenshot) in `Selector` constructor

**Comment by ashwinichannaveerappa** [comment]
@jBorkowska with the appId it worked, thanks a lot for the quick help.
