### ISSUE TITLE
Image selection(image_picker) through patrol native test is not working properly

### ISSUE THREAD

**Issue by AshuSharma7** [leancodepl/patrol#1601]
### Steps to reproduce

1. Clone https://github.com/AshuSharma7/pinput_test/tree/image_picker_issue repository
2. Run "patrol develop --target integration_test/image_picker_test.dart"
3. Image picker page should show the image after being selected by tester, but it doesn't show any image on that page

### Actual results

PickImagePage page should show the image after being selected by image_picker, but it doesn't show the image on that page. While running the app normally, it works fine but through patrol test, an image gets selected using resource id of thumbnail but the PickImagePage doesn't show any image. And also test completes without any errors

### Logs

<details>
<summary>Logs</summary>

```
Every test target will be run 1 time(s)
• Building apk with entrypoint image_picker_test.dart...
✓ Completed building apk with entrypoint image_picker_test.dart (3.6s)
• Executing tests of apk with entrypoint image_picker_test.dart on device 192.168.29.29:5555...
✓ Completed executing apk with entrypoint image_pic
```

</details>

### Patrol version

patrol: ^1.1.4

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 1.1.11
Program adb found in /Users/ashusharma/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/ashusharma/Library/Android/sdk/
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
Program ios-deploy found in /opt/homebrew/bin/ios-deploy
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.4 22F66 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

**Comment by jBorkowska** [comment]
Hi @AshuSharma7. It's because the `pumpAndSettle` that you put on the end of the test triggers new frames before the image is loaded. If you add another `pumpAndSettle`, it will try to refresh the app once again, and this time the image will be ready to render and will appear on the screen

**Comment by AshuSharma7** [comment]
Thank you so much @jBorkowska. Extra pumpAndSettle worked, So I'll close this issue.
