### ISSUE TITLE
If test fails, it never completes

### ISSUE THREAD

**Issue by novas1r1** [leancodepl/patrol#1602]
### Steps to reproduce

1. Run `flutter build apk --debug` 
2. Write test file where all tests succeed:
```
void main() {
  patrolTest(
    'App is starting and login screen is shown',
    nativeAutomation: true,
    ($) async {
      final app = await AppConfig.initializeApp();

      await $.pumpWidgetAndSettle(app);

      expect($('Benutzername'), findsOneWidget);
      expect($('Passwort'), findsOneWidget);
      expect($('Login'), findsOneWidget);
    },
  );
}
```
3. Run `patrol test --target integration_test\example_test.dart --verbose`
4. Write test with a failing test:
```
void main() {
  patrolTest(
    'App is starting and login screen is shown',
    nativeAutomation: true,
    ($) async {
      final app = await AppConfig.initializeApp();

      await $.pumpWidgetAndSettle(app);

      expect($('NOT FOUND'), findsOneWidget);
      expect($('Passwort'), findsOneWidget);
      expect($('Login'), findsOneWidget);
    },
  );
}
```
5. Run `patrol test --target integration_test\example_test.dart --verbose` 

### Actual results

Hey,
I have multiple apps where I'm trying to work with patrol. Everything works fine, if all my tests are successful. Somehow - if there's one test, or a part of a test failing, the test is stuck forever and never finishes with a fail message. I tried reproducing it, but I can't with a plain project :(. I moved over all configuration files in a new test project, but the error is not showing up. I somehow have a feeling it has to do with dependencies - maybe Firebase? Any hint would be really appreciated, since I'm running out of ideas.

Here's a video running the test. It will stay in the this last line until I force close it:
"Starting 1 tests on Pixel_3a_API_31(AVD) - 12"

https://github.com/leancodepl/patrol/assets/2575205/ca546d84-9fd2-4359-a322-252eaf68a1ec

I do have a "WidgetsFlutterBinding.ensureInitialized();" in my main.dart. I originally had it in my AppConfig.initializeApp() but thought it could be an issue -> where do I need to put it? Should it run in the patrol test or not?

**Device:**
Android Emulator, Pixel 3A, API 31

Any help, hints, whatever would be highly appreciated!
I'm trying my best to get it reproducable somehow...

### Logs

<details>
<summary>Logs</summary>

```
I can't paste the logs because it's too many characters and then I can't open the issue :( 
```

</details>

### Patrol version

patrol: ^2.2.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.1.0
Program adb found in C:\Anwendungen\AndroidSDK\platform-tools\adb.exe
Env var $ANDROID_HOME set to C:\Anwendungen\AndroidSDK
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.23511.1000], locale de-DE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.15)
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.80.2)
[√] VS Code (version 1.81.0-insider)
[√] Connected device (4 available)
[√] Network resources
```

</details>

**Comment by jBorkowska** [comment]
Hi @novas1r1!

1. Ad. `WidgetsFlutterBinding.ensureInitialized();` - it shouldn't be called in a test. Patrol initializes its own binding and initializing another one can cause some problems.
2. Ad. your issue - I see on the video that you are overriding `FlutterError.onError`, so Patrol doesn't get the chance to get the exception that should cause the failure, hence it never finishes. Try removing it from the method you use to initialize the app for testing.

I also recommend you to try running `patrol develop` if there are some issues - it prints more logs (in particular - flutter logs) and the issue with overriding `onError` would appear there (I think, at least I saw it there in other projects with this problem).

**Comment by novas1r1** [comment]
Hey,
@jBorkowska wow, thank you for that incredible fast response!

1. I moved it out of the testing, thanks
2. Removing FlutterError.onError fixed my issue. Totally makes sense now....

Thank you very much <3!!!
