### ISSUE TITLE
How to run multiple _test.dart files in Firebase

### ISSUE THREAD

**Issue by ashwinichannaveerappa** [leancodepl/patrol#1608]
### Steps to reproduce

1. Build multiple _test.dart files
2. Run the tests in the firebase testlab

using below commnds
gcloud firebase test android run --type instrumentation --app build/app/outputs/apk/dev/debug/app-dev-debug.apk --test build/app/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk --device=model=redfin,version=30,orientation=portrait --timeout 45m

### Actual results

patrol test -v --targets integration_test\tests\login_test.dart,integration_test\tests\settings_test.dart,integration_test\tests\forgot_password_test.dart .........

gcloud firebase test android run --type instrumentation --app build/app/outputs/apk/dev/debug/app-dev-debug.apk --test build/app/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk --device=model=redfin,version=30,orientation=portrait --timeout 45m

the tests are failing. only login_testt.dart executed.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

 Patrol CLI 2.0

### Patrol Doctor output

<summary>Patrol Doctor output</summary>
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.0
Program adb found in C:\Users\achannav\scoop\shims\adb.exe
Env var $ANDROID_HOME set to C:\Users\achannav\AppData\Local\Android\sdk
```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3208], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Community Edition (version 2021.3)
[√] VS Code (version 1.81.0)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by bartekpacia** [comment]
Please create new, a well-formatted issue according to the template and provide all the required information. I'm not sure what the problem even is.

[Here we have documentation explaining how to run tests on Firebase Test Lab](https://patrol.leancode.co/ci/firebase-test-lab).
