### ISSUE TITLE
Add support for Dart-side `group()`s and multiple `test()`s

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1619]
A subtask of #1501.

**Comment by bartekpacia** [comment]
A problem with this approach is that the execution model of the tests will change.

Developers usually expect that their test file executes once, roughly from top to bottom. But when we implement the feature that this issue talks about, it'll become more complex.
Example

Let's consider a test file:

```dart
void main() {
  late int photoCount;

  group('test that photos are downloaded', () {
    test('download photos', () {
      photoCount = ...;
    });

    test('tap on the last but one photo', () {
      // do something that depends on photoCount
    });
  });
}
```

The user might reasonably expect that photoCount will be set during the second test, becasue it's set by the previous test. But it'll not be set, because every test case would be run in a new app process.

**Comment by shilangyu** [comment]
Maybe I am not speaking for the majority here, but in the example you gave I think it would be totally reasonable for it to fail. Relying on execution order of individual tests sounds like an anti pattern to me. Test tooling seems to even support options that would break dependency on order (`--test-randomize-ordering-seed`, and maybe `--concurrency`/`--total-shards`?)

**Comment by bartekpacia** [comment]
> Relying on execution order of individual tests sounds like an anti pattern to me.

It is, but I've seen our QAs do it quite a few times. I'm afraid that those additional restrictions will be tricky for them.

**Comment by bartekpacia** [comment]
We could also run _a whole test file_ in a new app process, instead of a test case. This would feel more natural.

I think it'd also make the distinction between the two types of "grouping" more clear:
- grouping by filesystem hierarchy - each file runs in a new process
- grouping by `package:test` hierarchy in individual file - all `group`s and `test`s run in the same process

**Comment by bartekpacia** [comment]
Idea: lint to not create global state ("non-local-to-test-case state") in Patrol tests.

**Comment by bartekpacia** [comment]
## Test names proposal

Restrictions:



Let's assume the following test structure:

```dart
// integration_test/examples/example_test.dart

void main() {
  group('top level group in file', () {
    group('alpha', () {
      patrol('first', ($) async { /* */ });
      patrol('second', ($) async { /* */ });
    });

    group('bravo', () {
      patrol('first', ($) async { /* */ });
      patrol('second', ($) async { /* */ });
    });
  });
}
```

- Must be the same across platforms (see #1486)
- Must be a valid Objective-C method name (only alphanumeric and `_`)

### A more believable example

It's a good practice to make `group()`s and `test()`s read like a sentence:

```dart
group('HomeScreen`, () {
  group('when not signed in', () {
    test('shows sign-in dialog'), () {
      // ...
     });
    
    test('does something else'), () {
      // ...
     });
 
  });

  group('when signed in'), () {
    test('shows newsletter dialog'), () {
      // ..
    });

    test('does a nice thing'), () {
      // ..
    });
});
```

It'd result in 4 test cases:

```
examples__example__HomeScreenWhenNotSignedInShowsSignInDialog
examples__example__HomeScreenWhenNotSignedInDoesSomethingElse
examples__example__HomeScreenWhenSignedInShowsNewsletterDialog
examples__example__HomeScreenWhenSignedInDoesANiceThing
```

**Comment by fylyppo** [comment]
okay, it's better idea for me

**Comment by bartekpacia** [comment]
This will require us to prohibit using `_` in `group()`s and `test()`s.

**Comment by ashwinichannaveerappa** [comment]
@bartekpacia is group() and test() feature is already available? I tried using it, but its not working the app gets stuck at login screen

``  group("Verify that user can perform different types of training Test", () {

  patrolTest("Speaking Exercise Test",
          ($) async {
        //l10n initialization
        await loadLocalization();
        await baseClass.initializeApp();
        await baseClass.loginWithValidCredentials($);
    
      });

  patrolTest("Selection Exercise Test",
          ($) async {
  });`

**Comment by mkhtradm01** [comment]
> @bartekpacia is group() and test() feature is already available? I tried using it, but its not working the app gets stuck at login screen
> 
> `group("Verify that user..", () { patrolTest("Test 1", ($) async { await loadLocalization();await baseClass.initializeApp();await baseClass.loginWithValidCredentials($); patrolTest(" Test 2",($) async {});}); `

I am also experiencing this issue when using a `group()`. We're [using bdd_widget_test](https://github.com/olexale/bdd_widget_test) to generate our test files from cucumber format files (`feature_name.feature`) using [Gherkin syntax](https://cucumber.io/docs/gherkin/reference/), but the moment we run single or multiple test file(s) patrol runs smoothly and finishes the test but then it never completes (it get hanged).

**Comment by bartekpacia** [comment]
Currently you cannot use `group()`s in tests, but #1634, once merged, will resolve it.

**Comment by bartekpacia** [comment]
Let's consider this done. Minor follow-ups were split into #1713 and #1714.

**Comment by roscadalexandru** [comment]
I am using the latest versions of patrol and patrol_cli.
I have this file with 2 tests inside a group. I am calling setUpAll to instantiate the bloc I need only once for all tests. I am doing this because what happens in the first test updates the state of the bloc so the second test can also take advantage of the new state. But it seems that the bloc is being reset and it doesn't keep its state. Am I using groups with patrol wrong? I am a bit confused.

**Comment by roscadalexandru** [comment]
@bartekpacia any thought on my last comment?
