### ISSUE TITLE
Consequences of PatrolFinders 

### ISSUE THREAD

**Issue by zltnDC** [leancodepl/patrol#1624]
We've extracted PatrolTester into a new package and we don't want to release another major version of the patrol package, so we need to avoid breaking changes. This issue collects small things that we may change in the future.

1. Delete typedef PatrolTester
2. patrolTest will always initialize NativeAutomator, so we can replace these lines of code in PatrolIntegrationTester:
```
final NativeAutomator? nativeAutomator;
NativeAutomator get native;
```
to
```
final NativeAutomator native;
```
or
```
final NativeAutomator nativeAutomator;
NativeAutomator get native => nativeAutomator;
```
3. Remove the nativeAutomation argument from the patrolTest() function

**Comment by bartekpacia** [comment]
[One more minor rename](https://github.com/leancodepl/patrol/blob/b2872ec307a95b81b0e0b81e048dafb73770cccd/packages/patrol/lib/src/native/native_automator.dart#L177).

**Comment by bartekpacia** [comment]
not exactly related to this issue but let's remember about #1369 when we'll be releasing breaking changes.
