### ISSUE TITLE
Patrol test not working on earlier version

### ISSUE THREAD

**Issue by GentiShtjefni** [leancodepl/patrol#1640]
### Steps to reproduce

Create a new project and set up patrol native tests. Downgrade it to 1.1.4 or whatever version below 2.0.0. Write a simple test and run it.

### Actual results

Users-MacBook-Pro:patrol_test user$ patrol test --target integration_test/main_test.dart
Update available! 1.1.11 → 2.1.2
Run patrol update to update
No device specified, using the first one (emulator-5554)
Every test target will be run 1 time(s)
• Building apk with entrypoint main_test.dart...
        /Users/user/Documents/patrol_test/android/app/src/androidTest/java/com/example/patrol_test/MainActivityTest.java:12: error: cannot find symbol
            public PatrolTestRule<MainActivity> rule = new PatrolTestRule<>(MainActivity.class);
                                  ^
          symbol:   class MainActivity
          location: class MainActivityTest
        /Users/user/Documents/patrol_test/android/app/src/androidTest/java/com/example/patrol_test/MainActivityTest.java:12: error: cannot find symbol
            public PatrolTestRule<MainActivity> rule = new PatrolTestRule<>(MainActivity.class);
                                                                            ^
          symbol:   class MainActivity
          location: class MainActivityTest
        2 errors
        FAILURE: Build failed with an exception.
        * What went wrong:
        Execution failed for task ':app:compileDebugAndroidTestJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        * Get more help at https://help.gradle.org/
        BUILD FAILED in 2s
✗ Failed to build apk with entrypoint main_test.dart (Gradle build failed with code 1) (17.5s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
 FAIL  main_test.dart on emulator-5554

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^1.1.11

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Users-MacBook-Pro:patrol_test user$ patrol doctor
Patrol CLI version: 1.1.11
Program adb found in /Users/user/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
Program ios-deploy not found (install with `brew install ios-deploy`)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Users-MacBook-Pro:patrol_test user$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-x64, locale en-AL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] Connected device (3 available)
[✓] Network resources
• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
[Follow the migration guide to use Patrol v2](https://patrol.leancode.co/v2).

**Comment by jBorkowska** [comment]
Hi @GentiShtjefni, it is expected behavior, Patrol 2.0 has a lot of changes and native setup differs between 2.0 and 1.* versions. If you have other questions, feel free to ask

**Comment by jBorkowska** [comment]
Closing bc of lack of response
