### ISSUE TITLE
Update documentation after nativeAutomation's deprecation

### ISSUE THREAD

**Issue by redDwarf03** [leancodepl/patrol#1646]
### Steps to reproduce

It concerns readme + https://pub.dev/documentation/patrol/latest/ + https://patrol.leancode.co/

### Actual results

Hello
the documentation doesn't seem to be up to date with the depreciation of nativeAutomation

### Logs

no comment

### Patrol version

patrol 2.2.3

### Patrol Doctor output

no comment

### Flutter Doctor output

no comment

**Comment by jBorkowska** [comment]
Hi @redDwarf03, we will update the documentation soon. We had a bit of miscommunication here, that's why those changes got released :) Please don't close this issue, we will track this task here

**Comment by findmanish** [comment]
Hi @jBorkowska @redDwarf03 nativaeAutomation is going to be deprecated? sorry If I misunderstood this issue incorrectly. I use nativeAutomation in my tests and using latest patrol_cli 2.1.3

**Comment by jBorkowska** [comment]
`nativeAutomation` flag is not marked deprecated anymore, we will remove this flag in next major release
