### ISSUE TITLE
Patrol fails to deny permission dialog on subsequent tests in bundle (Android device)

### ISSUE THREAD

**Issue by zoskar** [leancodepl/patrol#1647]
### Steps to reproduce

1. Open Patrol example app
2. Add test with following content:

`my_test.dart`

```
import 'common.dart';

void main() {
  patrol(
    '',
    ($) async {
      await createApp($);
      await $('Open notifications screen').tap();

      if (await $.native.isPermissionDialogVisible()) {
        await $.native.denyPermission();
      }

      await $('Show in a few seconds').waitUntilVisible();
    },
  );
}

```

3. Add second test `my_second_test.dart` with the same content as test above
4. Run `patrol test -t integration_test/my_test.dart -t integration_test/my_second_test.dart` on Android device

### Actual results

https://github.com/leancodepl/patrol/assets/29405522/6b56651e-e527-4209-8dd9-f574e0a9d7cc

Usually for Android system when permission request is denied it pops up on all tests in test bundle. In this case the test passes when run on Android emulator and permission dialog is displayed in both cases. When the same test is run on Android device (Android 13 OnePlus 8) the second test fails to tap on dialog - see logs below.

Especially interesting is that `$.native.isPermissionDialogVisible()` returns `true`, to most likely problem is with `$.native.denyPermission()`

When using `await $.native.tap(Selector(text: 'Nie zezwalaj'));` (deny on dialog) instead of `await $.native.denyPermission();` the test passes.

### Logs

<details>
<summary>Logs</summary>

```
java.lang.AssertionError: Dart test failed: my_second_test
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: GrpcError: denyPermission() failed with
code NOT_FOUND (selector button to deny permission found nothing)

When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:237:7)
<asynchronous suspension>
#1      NativeAutomator.denyPermission (package:patrol/src/native/native_automator.dart:775:5)
<asynchronous suspension>
#2      main.<anonymous closure> (file:///Users/oskarzajac/Documents/tmp/patrol/packages/patrol/example/integration_test/my_second_test.dart:11:9)
<asynchronous suspension>
#3      patrolTest.<anonymous closure> (package:patrol/src/common.dart:136:7)
<asynchronous suspension>
#4      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
<asynchronous suspension>
#5      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:986:5)
<asynchronous suspension>

═════════════════════════════════════════════════════════════════

at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:130)
at pl.leancode.patrol.example.MainActivityTest.runDartTest(MainActivityTest.java:29)
```

</details>

### Patrol version

patrol: 2.2.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.1.2
Program adb found in /Users/oskarzajac/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

**Comment by zoskar** [comment]
cc: @fylyppo 😉

**Comment by bartekpacia** [comment]
Hi @zoskar,

It's strange that the behavior differs.

I checked it on my machine and both `my_test` and `my_second_test` pass on Pixel 6 emulator, API 33 (= Android 13).

Could you test it on more devices and get back with the results?

**Comment by Hritik602** [comment]
@bartekpacia  
Hi I want to allow location permission but it won't work 
```
await $.tap(find.byKey(ValueKey('tapLocation');
    if (await $.native.isPermissionDialogVisible()) {
      // await $.native.tap(Selector(text: 'While using the app'));
      await $.native.grantPermissionWhenInUse();
    }

    await $.pumpAndSettle();
```
