### ISSUE TITLE
Cannot record performance timeline as I cannot use a custom test driver

### ISSUE THREAD

**Issue by mariopepe** [leancodepl/patrol#1650]
### Steps to reproduce

As a use I would like tot records a performance timeline while performing a specific task and save a summary of the results to a local file.

I.e. I want to scroll a list of elements and record the performance of my app during this operation.

The steps to achieve such a goal are easily explained in this official Flutter cookbook: https://docs.flutter.dev/cookbook/testing/integration/profiling

Fundamentally it is based on using a custom test driver such as this one:

```dart
import 'package:flutter_driver/flutter_driver.dart' as driver;
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() {
  return integrationDriver(
    responseDataCallback: (data) async {
      if (data != null) {
        final timeline = driver.Timeline.fromJson(data['scrolling_timeline']);

        // Convert the Timeline into a TimelineSummary that's easier to
        // read and understand.
        final summary = driver.TimelineSummary.summarize(timeline);

        // Then, write the entire timeline to disk in a json format.
        // This file can be opened in the Chrome browser's tracing tools
        // found by navigating to chrome://tracing.
        // Optionally, save the summary to disk by setting includeSummary
        // to true
        await summary.writeTimelineToFile(
          'scrolling_timeline',
          pretty: true,
          includeSummary: true,
        );
      }
    },
  );
}
```

together with an integration test of this shape:

``` dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:scrolling/main.dart';

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('Counter increments smoke test', (tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(MyApp(
      items: List<String>.generate(10000, (i) => 'Item $i'),
    ));

    final listFinder = find.byType(Scrollable);
    final itemFinder = find.byKey(const ValueKey('item_50_text'));

    await binding.traceAction(
      () async {
        // Scroll until the item to be found appears.
        await tester.scrollUntilVisible(         // <------- *
          itemFinder,
          500.0,
          scrollable: listFinder,
        );
      },
      reportKey: 'scrolling_timeline',
    );
  });
}
```

**Unfortunately I cannot specify the custom test driver in Patrol CLI, so I have no way of achieving my goal**

### Actual results

The patrol CLI does not allow to define a custom test driver path hence I cannot record programmatically on a local file the performance of my app.

### Logs

irrelevant in this case

### Patrol version

patrol: ^2.2.3

### Patrol Doctor output

irrelevant in this case

### Flutter Doctor output

irrelevant in this case

**Comment by mateuszwojtczak** [comment]
Hi @mariopepe!
Your code uses `flutter_driver` to get the timeline and write it on disk. Unfortunately, Patrol doesn't support using `flutter_driver` since it's only a grey-box solution - which means that we don't use host process and whole Patrol automation is being executed on the device.

However, I think it could be done without `flutter_driver`. You can play around with `PatrolBinding.instance` which is also a  `IntegrationTestWidgetsFlutterBinding` instance, so maybe you could somehow extract the data.

FYI, we don't have this performance feature on our roadmap right now, but if you try to do this yourself, we can help you with our ideas.
