### ISSUE TITLE
I need to scroll the screen by pressing the enter key from the Android keyboard. But after the enter is pressed, the keyboard hangs on the screen. Can you help me with this?

### ISSUE THREAD

**Issue by mustafauys** [leancodepl/patrol#1656]
### Steps to reproduce

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

class GonderiEkleRobot {
  const GonderiEkleRobot(this.$);

  final PatrolTester $;

  Future<void> gonderiEkle() async {
    await $.tap(find.text('Gönderi Ekle'));
    await $.pump();

    await $.tap(find.text('Dağıtıcı Adı'));
    await $.pump();

    await $.enterText(find.byKey(const Key('barkodNumarasi')), '123456789');
    await $.pump();

    await $.scrollUntilVisible(
      scrollDirection: AxisDirection.down,
      dragDuration: const Duration(seconds: 1),
      finder: find.text('Kaydet'),
    );
    await $.pump();

    await simulateKeyDownEvent(LogicalKeyboardKey.enter);
    await $.pump();
  }
}

### Actual results

        ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
        The following assertion was thrown running a test:
        A ReceivedFilesAndMessagesViewModel was used after being disposed.
        Once you have called dispose() on a ReceivedFilesAndMessagesViewModel, it can no longer be used.

        When the exception was thrown, this was the stack:
        #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
        #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
        #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:382:27)      
        (elided 10 frames from dart:async)

        The test description was:
          app_test
        ════════════════════════════════════════════════════════════════════════════════════════════════════
        00:50 +0: app_test app_test [E]
          Test failed. See exception logs above.
          The test description was: app_test

        00:50 +0 -1: (tearDownAll)
        00:50 +1 -1: Some tests failed.
        01:43 +1 -1: app_test app_test

![qqqqqq](https://github.com/leancodepl/patrol/assets/51384613/e88f90ca-71ff-4c75-8404-f499bcbee437)
![asd](https://github.com/leancodepl/patrol/assets/51384613/5f0e9b0c-054d-4449-99ce-802c3ccfeee4)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

 patrol: ^2.0.3
patrol_cli v2.1.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by fylyppo** [comment]
Hi, convert your test code according to https://patrol.leancode.co/finders/usage.
You can use `.scrollTo()` instead of scrolling by tapping enter.

**Comment by mustafauys** [comment]
@fylyppo According to the barcode number entered, dropdown options appear at the bottom, so I have to press the enter key.

**Comment by mustafauys** [comment]
@jBorkowska thanks.
