### ISSUE TITLE
Tests without `nativeAutomation: true` are being run on each other consecutive test run 

### ISSUE THREAD

**Issue by MarcinusX** [leancodepl/patrol#1657]
### Steps to reproduce

1. Clone https://github.com/MarcinusX/patrol/tree/tests_looped_example and cd into it
2. Run `patrol test`

The only difference between your repo and my fork is that I'm not using `nativeAutomation: true` in the tests. And because of that those tests are being run multiple times.

I had this issue in my own project and adding `nativeAutomation: true` to the tests made the issue disappear.

### Actual results

https://github.com/leancodepl/patrol/assets/16286046/dade0cb8-5d55-4a15-ae06-02bcf1233acc

What's happening here is with each test, all the previous tests are being run as well. This causes the execution time to grow exponentially as each test doubles the number of test runs for all the other tests. In the video, you can see the `example_test` being run multiple times.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

2.2.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
$patrol doctor                
Patrol CLI version: 2.1.2
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-PL)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.3/libexec/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/marcinszalek/flutter. Consider adding /Users/marcinszalek/flutter/bin to the
      front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
    ! Error: (null) needs to connect to determine its availability. Check the connection between the device and its
      companion iPhone, and the connection between the iPhone and Xcode. Both devices may also need to be restarted and
      unlocked. (code 1)
[✓] Network resources

! Doctor found issues in 1 category.

```

</details>

**Comment by bartekpacia** [comment]
solved
