### ISSUE TITLE
Any progress on allowing a json config file with dart defines to run the patrol test?

### ISSUE THREAD

**Issue by AndyCodemate** [leancodepl/patrol#1674]
In my own case we have around 6 variables with a config file.

Flavors in this case are not the usual dev, test, prod usage but flavors are different product brands within the product each with there own runtime variables coming from their own config files.

Looking specifically at android currently, we've got around this temporally by hard coding within build.gradle file but that then limits the branch to a single brand and cannot be merged into dev or test which is not ideal.

Is the change dependent on a flutter issue with dart define from file? 

https://github.com/flutter/flutter/issues/130599

Thanks 

### Discussed in https://github.com/leancodepl/patrol/discussions/1414

<div type='discussions-op-text'>

<sup>Originally posted by **anfernandezz** June 28, 2023</sup>
Hello! I had this issue when running integration tests but I solved it by defining the `--dart-define-from-file`, which is used in our `launch.json`. So basically, the code I'm working on uses `--dart-define-from-file` for each environment config to run. 

When I run the command  `patrol test --target integration_test/login_test.dart --verbose` I get this error: 

 ` Looking for GoogleService-Info.plist in /Users/MyName/workspace/ProjectName/ProjectName/ios/config//GoogleService-Info.plist`

Between the `config//GoogleService-Info.plist` there it should be 'dev', which we get from an environment string. 
I have tried:

- Adding all the contents from the config dev.json file into a .patrol.env as keys
- Passing the keys individually in the command

With no luck, in the logs I get that it reads the dart-defines I have passed, but it still doesn't retrieve it when looking for the GoogleService-Info.plist.

I think it would be a good idea to add the --dart-define-from-file to facilitate this, but shouldn't also adding all the keys into the .patrol.env have the same effect? 

I appreciate all the help you can provide, thanks! 
</div>

**Comment by bartekpacia** [comment]
We don't want to commit to an implementation of `dart-define-from-file` in Patrol while it may change in Flutter.

**Comment by AndyCodemate** [comment]
Thanks, seems like quite a key feature for us on the current product, a potential go/no go for the use of patrol. I'll keep an eye for progress on this, cheers.

**Comment by bartekpacia** [comment]
Could you describe your use case in more detail?

We support a `.patrol.env` file where you can keep dart defines. You could create a few variants of this file and a script to allow for easy switching between them for different flavors you have.

**Comment by AndyCodemate** [comment]
Let me check out the .patrol.env to see if it provides some options to our current context.

**Comment by bartekpacia** [comment]
[see docs about it](https://github.com/leancodepl/patrol/blob/538a6eaa4e6308938348aa6c53a028650450b86a/docs/tips-and-tricks.mdx#L64C1-L72)

**Comment by bartekpacia** [comment]
Since this issue is old and has no new activity, I'm going to close it. Please create a new issue if you experience a similar problem.
