### ISSUE TITLE
Issue in the execution order of the tests

### ISSUE THREAD

**Issue by RashmiShashindra** [leancodepl/patrol#1678]
### Steps to reproduce

1. Create multiple tests using patrol. (1 test per a 1 *_test.dart file)
2. Run the patrol tests with command
`patrol test -t integration_test/authorisation/sign_in/tests`
<img width="208" alt="image" src="https://github.com/leancodepl/patrol/assets/17737337/ac597914-0f0f-48f2-bef8-d7dc48301dfd">

### Actual results

When I run the command, it starts executing the tests. The order it runs is as below.

1. First it runs the 1st test file. Then closes the app.
2. As the second test, it again runs the 1st test and after that it starts the 2nd test right after the 1st test.
3. Let's say if I have 3 tests. Then it again runs 1st --> 2nd and then 3rd Test.

Attaching the automatically generated test_bundle.dart file here.

```
// GENERATED CODE - DO NOT MODIFY BY HAND AND DO NOT COMMIT TO VERSION CONTROL
// ignore_for_file: type=lint, invalid_use_of_internal_member

import 'dart:async';

import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';
import 'package:patrol/src/native/contracts/contracts.pbgrpc.dart';
import 'package:test_api/src/backend/invoker.dart';

// START: GENERATED TEST IMPORTS
import 'authorisation/sign_in/tests/authorization_correct_sign_in_test.dart' as authorisation__sign_in__tests__authorization_correct_sign_in_test;
import 'authorisation/sign_in/tests/authorization_incorrect_sign_in_error_validation_test.dart' as authorisation__sign_in__tests__authorization_incorrect_sign_in_error_validation_test;
// END: GENERATED TEST IMPORTS

Future<void> main() async {
  // This is the entrypoint of the bundled Dart test.
  //
  // Its responsibilies are:
  //  * Running a special Dart test that runs before all the other tests and
  //    explores the hierarchy of groups and tests.
  //  * Hosting a PatrolAppService, which the native side of Patrol uses to get
  //    the Dart tests, and to request execution of a specific Dart test.
  //
  // When running on Android, the Android Test Orchestrator, before running the
  // tests, makes an initial run to gather the tests that it will later run. The
  // native side of Patrol (specifically: PatrolJUnitRunner class) is hooked
  // into the Android Test Orchestrator lifecycle and knows when that initial
  // run happens. When it does, PatrolJUnitRunner makes an RPC call to
  // PatrolAppService and asks it for Dart tests.
  //
  // When running on iOS, the native side of Patrol (specifically: the
  // PATROL_INTEGRATION_TEST_IOS_RUNNER macro) makes an initial run to gather
  // the tests that it will later run (same as the Android). During that initial
  // run, it makes an RPC call to PatrolAppSevice and asks it for Dart tests.
  //
  // Once the native runner has the list of Dart tests, it dynamically creates
  // native test cases from them. On Android, this is done using the
  // Parametrized JUnit runner. On iOS, new test case methods are swizzled into
  // the RunnerUITests class, taking advantage of the very dynamic nature of
  // Objective-C runtime.
  //
  // Execution of these dynamically created native test cases is then fully
  // managed by the underlying native test framework (JUnit on Android, XCTest
  // on iOS). The native test cases do only one thing - request execution of the
  // Dart test (out of which they had been created) and wait for it to complete.
  // The result of running the Dart test is the result of the native test case.

  final nativeAutomator = NativeAutomator(config: NativeAutomatorConfig());
  await nativeAutomator.initialize();
  final binding = PatrolBinding.ensureInitialized();
  final testExplorationCompleter = Completer<DartTestGroup>();

  // A special test to expore the hierarchy of groups and tests. This is a hack
  // around https://github.com/dart-lang/test/issues/1998.
  //
  // This test must be the first to run. If not, the native side likely won't
  // receive any tests, and everything will fall apart.
  test('patrol_test_explorer', () {
    final topLevelGroup = Invoker.current!.liveTest.groups.first;
    final dartTestGroup = createDartTestGroup(topLevelGroup);
    testExplorationCompleter.complete(dartTestGroup);
  });

  // START: GENERATED TEST GROUPS
  group('authorisation.sign_in.tests.authorization_correct_sign_in_test', authorisation__sign_in__tests__authorization_correct_sign_in_test.main);
  group('authorisation.sign_in.tests.authorization_incorrect_sign_in_error_validation_test', authorisation__sign_in__tests__authorization_incorrect_sign_in_error_validation_test.main);
  // END: GENERATED TEST GROUPS

  final dartTestGroup = await testExplorationCompleter.future;
  final appService = PatrolAppService(topLevelDartTestGroup: dartTestGroup);
  binding.patrolAppService = appService;
  await runAppService(appService);

  // Until now, the native test runner was waiting for us, the Dart side, to
  // come alive. Now that we did, let's tell it that we're ready to be asked
  // about Dart tests.
  await nativeAutomator.markPatrolAppServiceReady();

  await appService.testExecutionCompleted;
}

```

### Logs

[test_log.txt](https://github.com/leancodepl/patrol/files/12573581/test_log.txt)

### Patrol version

patrol: 2.2.2

### Patrol Doctor output

```
My_machine_flutter % patrol doctor
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
You're using Patrol CLI 2.0, which has breaking changes.
Read the migration guide at https://patrol.leancode.co/v2.
Disable this warning by setting the PATROL_MIGRATED environment variable.

Patrol CLI version: 2.1.3
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME set to /Users/{Username}/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

```

### Flutter Doctor output

```
My_machine_flutter % flutter doctor --verbose

[✓] Flutter (Channel stable, 3.7.10, on macOS 13.5 22G74 darwin-arm64, locale en-EE)
    • Flutter version 3.7.10 on channel stable at /Users/{Username}/Documents/tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b12645012 (5 months ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/{Username}/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/{Username}/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 116.0.5845.179

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by RashmiShashindra** [comment]
Hi @bartekpacia thanks for the quick turnaround.

What my problem exactly is that let's say I have 3 tests (test files with each file containing 1 E2E test) in my suite.

Then it does execute for 3 times. But in below order and I think that should not be the way to execute .

1st Time - It executes the 1st test.
2nd Time - It executes the 1st test again --> then 2nd test along with it.
3rd Tome - It executes the 1st test again --> then 2nd test along with it --> and finally the 3rd test.

What I want is that 

1st time 1st test.
2nd time only the 2nd test. I don't want to execute the 1st test again.

Hope you got my question here. Thanks in advance!

**Comment by bartekpacia** [comment]
Can you show a video of this behavior?

**Comment by RashmiShashindra** [comment]
Unfortunately I am not in a position to publicly share a video of the execution due to the security concerns from this project. Is there a way that I can share a video privately with you?

**Comment by bartekpacia** [comment]
We provide support only on GitHub, if you want private support we can arrange a support contract. You can always prepare a reproducible, open-source sample.

Is this a big problem for you? We use Patrol extensively, know many people who do so, and nobody has reported this problem so far.

Under the hood, it works exactly as you described, but _the tests that were already executed are skipped_. This means that:

1. If you're executing the 3rd test, the 1st and 2nd tests run first.
2. **But:** The 1st and 2nd tests are immediately skipped. In other words, a `return` is called and the test callback of 1st and 2nd tests is never executed.

**Comment by RashmiShashindra** [comment]
I think you got my issue here. What you explained is correct.

`1. If you're executing the 3rd test, the 1st and 2nd tests run first.`

The issue here is that the 1st and 2nd tests which were already executed are actually not getting skipped because I can see those 2 tests are fully executing the flow which actually affects the overall execution time of the tests. But when I check the gradle report, it correctly displays the tests 1 by 1 and not duplicating in the report. (attaching the gradle report screenshot here for your reference.)

So would like to know whats your take on this. Is this the expected behavior or is this a bug? because I cannot visually see that the 1st and 2nd E2E tests are getting skipped, instead it actually executes the full flow.

Thanks again!

<img width="1116" alt="Screenshot 2023-09-11 at 13 48 50" src="https://github.com/leancodepl/patrol/assets/17737337/ead87e9a-68a6-4530-b8c7-708948066c19">

**Comment by bartekpacia** [comment]
Alright, so it sounds like a bug. Are you sure you have set up everything properly?

It'd be great if you could share a minimal, reproducible example of this problem, so I could just `git clone` and debug it.

**Comment by RashmiShashindra** [comment]
Yeah, I have setup all the things correctly. (The native android setup only since I am not using iOS currently.)

I will try to spare sometime and create and share a minimal reproducible example of this issue. Thanks for your attention on this matter. :)

**Comment by RashmiShashindra** [comment]
@bartekpacia Thank you so much for the quick turn around in this fix. When I add the nativeAutomation: true, it worked as expected. 

Just a quick question though, I am not really using any native features, so even though I dont use the native features, is it okay to add the nativeAutomation: true? 

Can I run the same tests in web as well?

appreciate your thought on this. Thanks in advance!

**Comment by RashmiShashindra** [comment]
@bartekpacia Thank you!

**Comment by bartekpacia** [comment]
For the record: #1657 is about the same exact problem.
