### ISSUE TITLE
native.tap(selector) doesn't work when circularProgressIndicator is active

### ISSUE THREAD

**Issue by ghost** [leancodepl/patrol#1688]
### Steps to reproduce

1. Clone https://github.com/bumper-visual/patrol_test and cd* into it
2. Start Android emulator (Pixel 4, API 31, Google Play)
3. Verify that the app builds fine: 'flutter build apk--debug
4. Run the integration test: patrol test --target integration_ test/example_test.dart*

### Actual results

test will pass if we comment circularProgressIndicator

### Patrol version

patrol: 2.2.4

### Patrol Doctor output

Patrol CLI version: 2.1.3
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME set to /Users/sasha/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

### Flutter Doctor output

[!] Flutter (Channel unknown, 3.7.10, on macOS 13.3.1 22E261 darwin-arm64, locale ru-UA)
    ! Flutter version 3.7.10 on channel unknown at /Users/sasha/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at
      https://flutter.dev/docs/get-started/install.
    • Framework revision 4b12645012 (5 months ago), 2023-04-03 17:46:48 -0700
    • Engine revision ec975089ac
    • Dart version 2.19.6
    • DevTools version 2.20.1
    • If those were intentional, you can disregard the above warnings; however it is recommended
      to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/sasha/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/sasha/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google
    Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.82.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 13.3.1 22E261 darwin-arm64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**Comment by bartekpacia** [comment]
But `example_test` doesn't contain a `CircularProgressIndicator`.

**Comment by bumper-visual** [comment]
example_test shouldn't have `CircularProgressIndicator` 
I use `CircularProgressIndicator` in my widget and Biometric dialog
and the test should tap on `FloatingActionButton` (to show Biometric dialog) and then dismiss it (press 'Cancel')
while Biometric dialog exists, `CircularProgressIndicator` is active

and the problem is that when I try native.tap(Selector('cancel')) test falls
but when I remove `CircularProgressIndicator`, everything works fine

**Comment by bartekpacia** [comment]
Ah, forgive me, I read that issue too fast and thought you mean `example_test` in Patrol's repo.
