### ISSUE TITLE
Patrol CLI doesn't support `--dart-define-from-file`

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#1742]
See discussion in #1477, especially [this comment](https://github.com/leancodepl/patrol/pull/1477#issuecomment-1635860323).

If we want to be consistent with Flutter, we should wait for https://github.com/flutter/flutter/issues/130599 to be resolved.

**Comment by vital-edu** [comment]
flutter/flutter#130599 was resolved. I assume this means the `blocked` label can removed from this issue.

**Comment by bartekpacia** [comment]
That's right - thanks!

**Comment by bartekpacia** [comment]
Our new min is 3.16, this is unblocked now.

**Comment by kane-knowby** [comment]
Any chance this is being worked on soon? I'm trying to evaluate whether we can use Patrol for our project and currently this is a blocker

**Comment by jay-athelas** [comment]
no update so far?
