### ISSUE TITLE
Native hierarchy in devtools

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1754]
As a user, I want to see current native hierarchy in devtools' Patrol tab.

- view of the current native hierarchy as tree of nodes with basic info (type and resourceId)
- view types as their names from NativeView class
- possibility to refresh using button
- by clicking on a node, there should be a panel on the side, showing all the available info about this node
- nodes can be expanded to show its children, like in the widget tree view in flutter's devtools

**Comment by neiljaywarner** [comment]
@bartekpacia @zltnDC @jBorkowska is this what is already done or something else or both? :)

**Comment by bartekpacia** [comment]
Yeah, this is done. Thanks!
