### ISSUE TITLE
update docs to remove confusing inconsistency regarding whether or not `patrol_cli` is mandatory

### ISSUE THREAD

**Issue by StephenWithPH** [leancodepl/patrol#1765]
### Use case

The pub.dev [docs](https://pub.dev/packages/patrol#patrol) for `patrol` include the line:

> It can be used on its own or with `patrol_cli`.

This line is from here:
https://github.com/leancodepl/patrol/blob/c08337011c4ba02d75173cf400aa31c8ba3ddc5b/packages/patrol/README.md#L12

Those docs go on to include example _integration_ test code which includes widget tests.

The above conflicts with the `Getting Started` section of [the docs](https://patrol.leancode.co/getting-started#install-patrol_cli), which says:

> Patrol CLI (command-line interface) is a small program that enables running Patrol UI tests. It is necessary to run UI tests (flutter test won't work! Here's why).

### Proposal

Remove the misleading line:

> It can be used on its own or with `patrol_cli`.

... and replace with something to the effect of `patrol_cli` is required to run widget tests.

**Comment by bartekpacia** [comment]
That's right - we forgot to update the docs. Thanks & sorry.
