### ISSUE TITLE
Can't run patrol tests with IOS simulator

### ISSUE THREAD

**Issue by AlexanderHorielko** [leancodepl/patrol#1767]
### Steps to reproduce

1. Make all steps that are written in docs related to setup
2. Run example test

### Actual results

Have this issue

Thread:   <_NSMainThread: 0x151e09970>{number = 1, name = main}
        Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
        2023-10-03 14:23:20.853 xcodebuild[25050:1242256] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22267/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
        Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
        Function: createItemModels(for:itemModelSource:)
        
        
Failed to build app with entrypoint test_bundle.dart for iOS simulator (xcodebuild exited with code 70) (19.8s)
Error: xcodebuild exited with code 70

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 2.3.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by bartekpacia** [comment]
Not reproducible. Please include all the information required by the bug report template.

**Comment by dale-lakes** [comment]
Issue has to do w/ running Patrol with XCode 15 - https://github.com/flutter/flutter/issues/135277
