### ISSUE TITLE
Long press gesture feature

### ISSUE THREAD

**Issue by Tamerlanchiques** [leancodepl/patrol#1770]
### Use case

In my integration test I need to make long press gesture on a button. As I see there is no trickless solution for this.

### Proposal

`await $(PK.timeslotInfoPageSdizTextField).longPress();` makes long press (around 2 seconds) gesture.

Or maybe modify existing tap method:
`await $(PK.timeslotInfoPageSdizTextField).tap(pressDuration: Duration(seconds:2);`

**Comment by bartekpacia** [comment]
Hi 👋🏻 

Looks like `WidgetTester` has the [longPress()](https://api.flutter.dev/flutter/flutter_test/WidgetController/longPress.html) method. We should add it to [`PatrolTester`](https://github.com/leancodepl/patrol/blob/c08337011c4ba02d75173cf400aa31c8ba3ddc5b/packages/patrol_finders/lib/src/custom_finders/patrol_tester.dart) and simply forward.

Would you be willing to contribute this feature? :)

**Comment by Tamerlanchiques** [comment]
Hi. Hm-m… looks like something not that hard so I could try to make my first code-contribute to open source. :)

**Comment by bartekpacia** [comment]
It's [Hacktoberfest](https://hacktoberfest.com/), after all :)

**Comment by Tamerlanchiques** [comment]
Yay, I'm FOSS Contributor now. Exited

_PeepoHappy_
