### ISSUE TITLE
Add logging to test output

### ISSUE THREAD

**Issue by itsJoKr** [leancodepl/patrol#1781]
### Use case

Using `print`, `debugPrint` or `developer.log` will not show any logs in the console where patrol is run.

Some logs during the tests would be very beneficial to me.

### Proposal

In the [docs](https://patrol.leancode.co/tips-and-tricks#ignoring-exceptions) in one example there's a following line: 

```dart
 $.log('Warning: $exceptionCount exceptions were ignored');
``` 

But I couldn't find such a method in patrol. How are you actually logging things in tests?

**Comment by jBorkowska** [comment]
Hi @itsJoKr, thank you for lately created issues :)

We recommend trying `patrol develop` command during test development. You can log there and see all exceptions, also you can use hot restart there

**Comment by itsJoKr** [comment]
Thanks. I'm going to close this for now.
