### ISSUE TITLE
Add to docs to be aware of proguard in the Getting started page

### ISSUE THREAD

**Issue by Guillergood** [leancodepl/patrol#1804]
### Steps to reproduce

NA

### Actual results

Just add it as a warning

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^2.3.1

### Patrol Doctor output

NA

### Flutter Doctor output

NA

**Comment by bartekpacia** [comment]
I don't know, don't have access to a physical Android device right now.

> It breaks the release app build.

Please post logcat of the exception. I suppose it's something related to Gson since it uses relfection.

**Comment by bartekpacia** [comment]
[Somebody already had this problem](https://github.com/leancodepl/patrol/issues/1542#issuecomment-1721217270).
