### ISSUE TITLE
404 in docs for using patrol finders in native widget tests

### ISSUE THREAD

**Issue by neiljaywarner** [leancodepl/patrol#1809]
### Steps to reproduce

1. go to https://patrol.leancode.co/patrol-finders-release
2. tap the [Using Patrol finders in widget tests](https://patrol.leancode.co/patrol/finders/finders-setup link

### Actual results

404 at https://patrol.leancode.co/patrol/finders/finders-setup
actual link is https://patrol.leancode.co/finders/finders-setup

### Logs

na

### Patrol version

na

### Patrol Doctor output

na

### Flutter Doctor output

na

**Comment by bartekpacia** [comment]
Thanks for reporting.

We have tried fixing it by setting up redirects in #1811 but it didn't work.

See also: #1817

**Comment by bartekpacia** [comment]
This is now fixed
