### ISSUE TITLE
`print()`s from app code don't work

### ISSUE THREAD

**Issue by adrian-moisa** [leancodepl/patrol#1813]
### Steps to reproduce

Test are working fine. I'm starting them via `patrol develop -t integration_test`. No problem here.

### Actual results

As in the title. If I print() a message from the integration test body it's visible in the terminal. If I print() from the app code there's no trace of the print. Not even logcat. I use `+++` to make these prints standout. They are nowhere to be found. Am I missing something? I tried running them from the play button in Android studio but then I encounter this issue: #1666 . 

neither `debugger();` works.

```dart
void main() {
  patrolTest(
    'Login page',
    nativeAutomation: true,
    ($) async {
      await $.pumpWidgetAndSettle(MyApp());

      print('+++ PATROL TEST'); // This print is visible
```

```dart
void main() async {
  platformDependentMainInit();

  print('+++ MAIN'); // This print is not visible in the logs, nor in logcat
```

- The intriguing part is that the app seems to be running fine. No major failure (except auth not working, that's what I'm trying to debug with print statements). 
- Also an additional question is: how can we track network traffic if the tests are not run with the Android Studio play button?

### Logs

<details>
<summary>Logs</summary>

```
 % patrol develop -t integration_test
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      

Update available! 2.1.5 → 2.2.1
Run patrol update to update

No device specified, using the first one (emulator-5554)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (28.2s)
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
Hot Restart: logs connected
Hot Restart: not attached to the app yet
        The Dart VM service is listening on http://127.0.0.1:42365/7UiWe_HC8ek=/
        Patrol (native): initialize() started
        Patrol (native): initialize() succeeded
        00:00 +0: auth_test Login page
        Patrol (native): configure() started
        Patrol (native): configure() succeeded
        +++ PATROL TEST
Hot Restart: attached to the app (press "r" to restart)


```

</details>

### Patrol version

2.1.5

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
% patrol doctor
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
Patrol CLI version: 2.1.5
Program adb found in /opt/homebrew/bin/adb
Env var $ANDROID_HOME set to ~/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.4 22F66 darwin-arm64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by adrian-moisa** [comment]
I tried to boil it down to the basics:

```dart
import 'package:flutter/material.dart';

const bool isTesting = bool.fromEnvironment('dart.vm.product');
var msgsArr = [''];

void main() async {
  print('+++ MAIN');
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    print('+++ MyApp INIT');
    super.initState();
  }

  Widget build(BuildContext context) {
    print('+++ MyApp BUILD');

    return MaterialApp(
      home: Container(
        child: Text('Dummy App'),
      ),
    );
  }
}

```

Very interesting output. From What I understand, basically only the prints in the main method are missing. Everything else starting from the MyApp class seems to be printing out.


**Web build**

<img width="310" alt="image" src="https://github.com/leancodepl/patrol/assets/11160141/3eb7ee32-3fb2-4e9d-ba15-7b262d1d2953">

**Terminal test runner**
Something intriguing this time. I no longer see the print from the test body. Despite the fact that it's still there.

```zsh
Update available! 2.1.5 → 2.2.1
Run patrol update to update

No device specified, using the first one (emulator-5554)
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (11.4s)
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
Hot Restart: logs connected
Hot Restart: not attached to the app yet
        The Dart VM service is listening on http://127.0.0.1:34927/K2PP1Jxo1t0=/
        Patrol (native): initialize() started
        Patrol (native): initialize() succeeded
        00:00 +0: auth_test Login page
        Patrol (native): configure() started
        Patrol (native): configure() succeeded
        +++ MyApp INIT
        +++ MyApp BUILD
```

**Comment by adrian-moisa** [comment]
There's something even fishier happening in main. It's not just missing print statements. It seems that whatever values I have assigned in the scope of the main class they go missing "Bermuda triangle style". I have some auth code that requests the token endpoint from the IAM and then it reads the value of the redirect uri. It takes the authorisation code and then composes a class called `Credential`. I store this credential class in a singleton `AuthService` for later use in the app. It's needed to read the user data from the idToken. Now the thing is that this Credential goes completely missing in action when I'm running the test runner. While the other builds they work just fine. I even tried to simply set a basic variable on the scope of the main file and to read it in the MyApp init. Well it's not there. The value is just gone... Idk but this is really really strange. I have a hunch it must be something related to the test runner, but I have no clue what. I could workaround by moving my auth code out of main down to the MyApp. But it wouldn't be a "happy ending". I'd be more satisfied if the auth code remains in main and does not break the typical oidc flow for flutter web.

**main.dart** 
Bare bone simplified
```dart
final _authService = AuthService();

void main() async {
  await _initOidcClientIfNotAuthThenLogin();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    print('+++ credential ${_authService.credential}');
    super.initState();
  }

  Widget build(BuildContext context) => MaterialApp.router(
        // ...
      );
}

_initOidcClientIfNotAuthThenLogin() async {
  if (ENABLE_AUTH) {
    await _authService.initOidcClient();
    final credential = await _authService.getCredentialsFromRedirectUri();

    if (credential == null) {
      await _authService.authenticate();
    }
  }
}
```


**Web**
<img width="306" alt="image" src="https://github.com/leancodepl/patrol/assets/11160141/af70a80d-5412-44ae-a5f3-8faa37cec4e1">


**Test Runner**
```zsh
Hot Restart: not attached to the app yet
        The Dart VM service is listening on http://127.0.0.1:41009/WUdO2T73dj0=/
        Patrol (native): initialize() started
        Patrol (native): initialize() succeeded
        00:00 +0: auth_test Login page
        Patrol (native): configure() started
        Patrol (native): configure() succeeded
        +++ PATROL TEST START
        +++ credential null  <----------- This should no be null
        +++ PATROL TEST END

```


Even more simplfied.

```dart
import 'package:flutter/material.dart';

String someVal = 'NOT_CHANGED';

void main() async {
  someVal = 'CHANGED';
  print('+++ MAIN $someVal');
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  void initState() {
    print('+++ INIT $someVal');
    super.initState();
  }

  Widget build(BuildContext context) => MaterialApp(
        home: Container(
          child: Text('Dummy App'),
        ),
      );
}
```

**Web**
<img width="341" alt="image" src="https://github.com/leancodepl/patrol/assets/11160141/3cf2938b-a856-4893-a131-9819cc3dd1c1">

**Test Runner**
```zsh
Hot Restart: not attached to the app yet
        The Dart VM service is listening on http://127.0.0.1:41519/LKB0XqKg5t4=/
        Patrol (native): initialize() started
        Patrol (native): initialize() succeeded
        00:00 +0: auth_test Login page
        Patrol (native): configure() started
        Patrol (native): configure() succeeded
        +++ PATROL TEST START
        +++ INIT NOT_CHANGED  <----------- ???????
        +++ PATROL TEST END
```

**Comment by adrian-moisa** [comment]
Good news, I've managed to move all my auth code from main down to "MyApp". Now it works apparently fine even inside the test runner. But the question still remains. Why main loses the state. I'll leave the ticket open in case you want to investigate further. Cheers!

**Comment by bartekpacia** [comment]
Hi @adrian-moisa, glad to hear that you finally managed to get it working.

This is really strange indeed. I think you should report that issue to Flutter – you already have a [minimal reproducible example](https://github.com/leancodepl/patrol/issues/1813#issuecomment-1767184016).

This issue also kind of reminds me of https://github.com/flutter/flutter/issues/113885, but I think that's a long shot to assume they're related.

**Comment by adrian-moisa** [comment]
Sounds a bit like a different issue. Can't say 100% for sure they are not related. But if so, they are different manifestations.

**Comment by bartekpacia** [comment]
This is very fishy indeed. Thanks for the samples above, but that's only app code. Could you also post the test you were running and the versions of patrol and patrol_cli used? Thanks in advance.

**Comment by adrian-moisa** [comment]
Sorry for the late reply, in the first message I have a sample of the test. Meaning bare bone with no logic, just to run it. Also specified there, version 2.1.5.

**Comment by piotruela** [comment]
Hi @adrian-moisa, if I understand the problem you've described correctly, the lack of prints from the `main()` function is caused by the fact that the body of the test you're invoking doesn't call the `main()` function. To fix that you can replace the line:
```await $.pumpWidgetAndSettle(MyApp());```
with 
```dart
import 'package:example_app/main.dart' as app;
...
app.main();
await $.pumpAndSettle();
```
Let me know if it helps or if I misunderstood the issue.

**Comment by mateuszwojtczak** [comment]
@adrian-moisa It's also important to not call `runApp()` method during the test

**Comment by adrian-moisa** [comment]
I recently upgraded to the latest lib. I'll have a new look on this example to see if the behaviour persists. Sorry for the late reply, I got sucked into a lot of work. I'll update here with my findings this weekend

**Comment by adrian-moisa** [comment]
I can confirm the problem is still here in 2.2.2. I had a small change to do and one of my colleagues used main again, and once again main fails to store variable values. So yes it's still here. We will soon move 2.3.x and I'll let you know if it's still there.

**Comment by bartekpacia** [comment]
Great to hear that @adrian-moisa! Thank you for your very detailed issues and proposals to Patrol - we highly appreciate it :) Also thanks for being a valuable member of our community.

**Comment by adrian-moisa** [comment]
Gladly, there's a lot of value in this framework and it's very promising thanks to your constant efforts. I've already trained 4 colleagues to use it. Wherever I go and there's opportunity I leave links towards this repo. I'll also use patrol for my own open source repo: https://github.com/visual-space/visual-editor. I'd also contribute directly fixes if there was more time available on my hands. Maybe in the future if my startup can pay the bills so I don't have a job in parallel. Until then I can help by spreading the word and providing feedback. I'm thinking maybe next January I could record some video teaching people how to test in patrol. Would serve me well for my own startup as well to have some early content on the platform.
