### ISSUE TITLE
Error: xcodebuild exited with code 65 following get started tutorial 

### ISSUE THREAD

**Issue by alepeltierlightfoot** [leancodepl/patrol#1835]
### Steps to reproduce

1. Follow the Get's Started tutorial to setup Patrol for IOS within xcode. I've set the IOS version to IOS 17.0
2. When I open RunnerUITest.m I can see xcode is throwing an error saying the patrol module can't be fount
3. I run `patrol test -t integration_test/example_test.dart --verbose` and get an error Error: xcodebuild exited with code 65. When digging into the logs it's complaining about duplicated c++ libaries and errors being thrown in flutter. 
4. I've checked it's not my tests by running them using flutters own integration_test framework and using the default example test provided in the documentation.
5. I've checked the pub spec and everything appears to be installed correctly

`dev_dependencies:
  flutter_test:
    sdk: flutter
  patrol: ^2.3.1
  test: ^1.5.1

patrol:
  app_name: Winnie
  ios:
    bundle_id: uk.co.lightfoot.winnie`

I'm running this in the IOS simulator provided out of xcode and MacOS Sonoma version 14

### Actual results

When I run `patrol test -t integration_test/example_test.dart --verbose` the request hangs for a bit and appears to be processing I then get the following error `Error: xcodebuild exited with code 65`

### Logs

<details>
<summary>Logs</summary>

https://pastebin.com/iN2zw6gk

</details>

### Patrol version

patrol: ^2.3.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
patrol doctor

In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.

Patrol CLI version: 2.2.1
Program adb found in /Users/alexlepeltier/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/alexlepeltier/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
flutter doctor

┌─────────────────────────────────────────────────────────┐
│ A new version of Flutter is available!                  │
│                                                         │
│ To update to the latest version, run "flutter upgrade". │
└─────────────────────────────────────────────────────────┘
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.8, on macOS 14.0 23A344 darwin-arm64, locale en-GB)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /opt/homebrew/Caskroom/flutter/3.13.5/flutter. Consider adding /opt/homebrew/Caskroom/flutter/3.13.5/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.2)
[✓] VS Code (version 1.82.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

</details>

**Comment by mkhtradm01** [comment]
I am also having this exact issue which blocks me. I am investigating.. @bartekpacia is this a known issue? if yes, any workarounds? Thank you 🥂

**Comment by bartekpacia** [comment]
You have an error in your test:

```
> integration_test/example_test.dart:9:9: Error: Expected named argument.
	        ($) async {
	        ^
	integration_test/example_test.dart:6:13: Error: Too few positional arguments: 2 required, 1 given.
	  patrolTest(
	            ^
	../../.pub-cache/hosted/pub.dev/patrol-2.3.1/lib/src/common.dart:44:6: Context: Found this candidate, but the arguments don't match.
	void patrolTest(
	     ^^^^^^^^^^
	Target kernel_snapshot failed: Exception
```

It's clearly visible in the logs.

**Comment by alepeltierlightfoot** [comment]
Thank you @bartekpacia I can't believe I missed that. Do you have any examples of a complete example of this test? I copied that one off the get started tutorial and when I look in native automation the PatrolTester function is deprecated. https://patrol.leancode.co/native/overview.

**Comment by bartekpacia** [comment]
I'm not sure what test you mean. Anyway, if you're looking for samples, we have an [example app](https://github.com/leancodepl/patrol/tree/master/packages/patrol/example) with [many tests](https://github.com/leancodepl/patrol/tree/master/packages/patrol/example/integration_test).

**Comment by bartekpacia** [comment]
closing
