### ISSUE TITLE
Ability to group tests, ability to disable tests, ability to run some tests exclusively/temporarely

### ISSUE THREAD

**Issue by adrian-moisa** [leancodepl/patrol#1856]
### Use case

Often when developing test it's necessary to disable some tests or all tests except some tests. At the moment all I can do is to rename the files from `*_test.dart` to smth else like `tmp.dart`

### Proposal

Would be nice to have a simple shortcut to disable some/all tests except. Both individual test cases or entire file. Similar to jasmine `describe`, `xdescribe`, `fdescribe` for groups / `it`, `xit` for test cases.

https://stackoverflow.com/questions/48740288/xdescribe-vs-fdescribe-in-jasmine

Also would be nice to have groups of tests. Maybe this is already available but I don't remember seeing it in the docs.

**Edit**: I think group exists already... I found this link: https://github.com/leancodepl/patrol/discussions/1838

**Comment by bartekpacia** [comment]
For now you can use `--exclude` to exclude whole files. `patrol test --help` to see more.

`group()`s are supported since patrol 2.3.0 and patrol_cli 2.2.0.

See also #1690 - we should enable it as well.

**Comment by bartekpacia** [comment]
Please close if I answered your questions. I think #1690 is a good place if you want to continue the discussion.

**Comment by adrian-moisa** [comment]
Maybe the only suggestion here is to review the docs. Somehow I can't find any mention of the groups feature. If I use the search feature it leads me to the tips and tricks page but there I can't see the groups code sample.
