### ISSUE TITLE
No test found for android release mode

### ISSUE THREAD

**Issue by jacjac11** [leancodepl/patrol#1869]
### Steps to reproduce

1.In build.gradle, add testBuildType "release"
2. run command 
```
patrol test \
  --flavor dev \
  --target integration_test/my_test.dart 
  --release
```

Debug mode works fine except for release.
To confirm it's related to proguard, I've set the following, this results in no tests found problem as well.

```
patrol test \
  --flavor dev \
  --target integration_test/my_test.dart 
```

```
     debug {
            signingConfig signingConfigs.debug
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```

Proguard content: 
-keep class kotlin.reflect.** { *; }
-keep class pl.leancode.patrol.** { *; }
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
-dontwarn org.slf4j.impl.StaticLoggerBinder

### Actual results

Actual : No test found
Expected: Complete test 

### Logs

<details>
<summary>Logs</summary>

```
        : > Task :app:mergeDevReleaseJavaResource
        : 
        : > Task :app:minifyDevReleaseWithR8
        : Supplied proguard configuration does not exist: /Users/xxx/Local/Work/xxxx/android/app/build/intermediates/default_proguard_files/global/proguard-android.txt-8.0.2
        : 
        : > Task :app:packageDevRelease UP-TO-DATE
        : > Task :app:createDevReleaseApkListingFileRedirect UP-TO-DATE
        : > Task :app:minifyDevReleaseAndroidTestWithR8
        : > Task :app:packageDevReleaseAndroidTest UP-TO-DATE
        : > Task :app:createDevReleaseAndroidTestApkListingFileRedirect UP-TO-DATE
        : 
        : > Task :app:connectedDevReleaseAndroidTest
        : Starting 0 tests on SM-S911B - 13
        : 
        : com.android.build.gradle.internal.testing.ConnectedDevice > No tests found.[SM-S911B - 13] FAILED 
        : No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
        : 
        : > Task :app:connectedDevReleaseAndroidTest FAILED
        
        FAILURE: Build failed with an exception.

```

</details>

### Patrol version

  patrol: ^2.4.0-dev.6

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.3.0-dev.2
Program adb found in /usr/local/bin/adb
Env var $ANDROID_HOME is not set
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /usr/local/bin/ideviceinstaller

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.0.1 22A400 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by bartekpacia** [comment]
This is a known issue, see #1542. Currently there's no known fix except for disabling ProGuard.

**Comment by jacjac11** [comment]
✗ Failed to execute tests of apk with entrypoint test_bundle.dart on device RXXXXXX (Gradle test execution failed with code 1) (82.4s)
Exception: Gradle test execution failed with code 1
#0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:140:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:106:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:277:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:169:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:321:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:265:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#9      main (file:///Users/xxx/.pub-cache/hosted/pub.dev/patrol_cli-2.3.0-dev.2/bin/main.dart:6:20)
<asynchronous suspension>

See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.

@bartekpacia I see only this message below.

**Comment by bartekpacia** [comment]
No, I mean logcat. `adb logcat` and scan it for suspicious ProGuard-related crashes (`ClassNotFound` etc.).

**Comment by jacjac11** [comment]
```
 xxxx.xxx.dev: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder: Error constructing runner
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder: java.lang.TypeNotPresentException: Type Lorg/junit/runners/Parameterized; not present
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at libcore.reflect.AnnotationMember.rethrowError(AnnotationMember.java:298)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at libcore.reflect.AnnotationMember.validateValue(AnnotationMember.java:341)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at libcore.reflect.AnnotationFactory.invoke(AnnotationFactory.java:299)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at $Proxy2.value(Unknown Source)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at androidx.test.internal.runner.junit4.AndroidAnnotatedBuilder.b(SourceFile:13)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at M2.j.c(SourceFile:1)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at C2.a.b(SourceFile:59)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at androidx.test.internal.runner.AndroidRunnerBuilder.b(SourceFile:26)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at androidx.test.internal.runner.AndroidLogOnlyBuilder.b(SourceFile:102)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at androidx.test.internal.runner.ScanningTestLoader.a(SourceFile:49)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at androidx.test.internal.runner.TestRequestBuilder.f(SourceFile:174)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at androidx.test.runner.AndroidJUnitRunner.buildRequest(SourceFile:40)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at androidx.test.runner.AndroidJUnitRunner.onStart(SourceFile:30)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2335)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/junit/runners/Parameterized;
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at java.lang.Class.getDeclaredAnnotation(Native Method)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at java.lang.Class.getAnnotation(Class.java:2526)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       at androidx.test.internal.runner.junit4.AndroidAnnotatedBuilder.b(SourceFile:3)
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       ... 9 more
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder: Caused by: java.lang.ClassNotFoundException: org.junit.runners.Parameterized
11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder:       ... 12 more

```

**Comment by jacjac11** [comment]
```
It was 11-07 20:35:25.056 13744 13766 E AndroidAnnotatedBuilder: java.lang.TypeNotPresentException: Type Lorg/junit/runners/Parameterized; not present.

After attempting to add more proguard rules as below, new issue arises.
-keep class kotlin.reflect.** { *; }
-keep class pl.leancode.patrol.** { *; }
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
-dontwarn org.slf4j.impl.StaticLoggerBinder
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task
-keep class androidx.window.sidecar.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class org.junit.runners.** { *; }
```

11-07 21:03:40.934 16426 16462 E TestRunner: java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
11-07 21:03:40.934 16426 16462 E TestRunner:    at z0.a.<init>(SourceFile:10)
11-07 21:03:40.934 16426 16462 E TestRunner:    at pl.leancode.patrol.PatrolJUnitRunner$2.<init>(Unknown Source:2)
11-07 21:03:40.934 16426 16462 E TestRunner:    at pl.leancode.patrol.PatrolJUnitRunner.writeStateFile(SourceFile:18)
11-07 21:03:40.934 16426 16462 E TestRunner:    at pl.leancode.patrol.PatrolJUnitRunner.saveLifecycleCallbacks(SourceFile:22)
11-07 21:03:40.934 16426 16462 E TestRunner:    at pl.leancode.patrol.PatrolJUnitRunner.handleLifecycleCallbacks(SourceFile:11)
11-07 21:03:40.934 16426 16462 E TestRunner:    at pl.leancode.patrol.PatrolJUnitRunner.listDartTests(SourceFile:1)
11-07 21:03:40.934 16426 16462 E TestRunner:    at net.xxxx.xxxx.MainActivityTest.testCases(MainActivityTest.java:17)
11-07 21:03:40.934 16426 16462 E TestRunner:    at java.lang.reflect.Method.invoke(Native Method)
11-07 21:03:40.934 16426 16462 E TestRunner:    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Unknown Source:10)
11-07 21:03:40.934 16426 16462 E TestRunner:    at w2.b.run(SourceFile:1)
11-07 21:03:40.934 16426 16462 E TestRunner:    at org.junit.runners.model.FrameworkMethod.invokeExplosively(Unknown Source:5)
11-07 21:03:40.934 16426 16462 E TestRunner:    at org.junit.runners.Parameterized$RunnersFactory.allParameters(SourceFile:5)
11-07 21:03:40.934 16426 16462 E TestRunner:    at org.junit.runners.Parameterized$RunnersFactory.<init>(SourceFile:5)
11-07 21:03:40.934 16426 16462 E TestRunner:    at org.junit.runners.Parameterized$RunnersFactory.<init>(SourceFile:1)
11-07 21:03:40.934 16426 16462 E TestRunner:    at org.junit.runners.Parameterized.<init>(SourceFile:1)
11-07 21:03:40.934 16426 16462 E TestRunner:    at java.lang.reflect.Constructor.newInstance0(Native Method)
11-07 21:03:40.934 16426 16462 E TestRunner:    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
11-07 21:03:40.934 16426 16462 E TestRunner:    at u2.b.a(SourceFile:17)
11-07 21:03:40.934 16426 16462 E TestRunner:    at u2.b.runnerForClass(SourceFile:19)
11-07 21:03:40.934 16426 16462 E TestRunner:    at androidx.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(SourceFile:39)
11-07 21:03:40.934 16426 16462 E TestRunner:    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(SourceFile:1)
11-07 21:03:40.934 16426 16462 E TestRunner:    at u2.a.runnerForClass(SourceFile:59)
11-07 21:03:40.934 16426 16462 E TestRunner:    at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(SourceFile:26)
11-07 21:03:40.934 16426 16462 E TestRunner:    at androidx.test.internal.runner.AndroidLogOnlyBuilder.runnerForClass(SourceFile:102)
11-07 21:03:40.934 16426 16462 E TestRunner:    at androidx.test.internal.runner.ScanningTestLoader.a(SourceFile:49)
11-07 21:03:40.934 16426 16462 E TestRunner:    at androidx.test.internal.runner.TestRequestBuilder.f(SourceFile:174)
11-07 21:03:40.934 16426 16462 E TestRunner:    at androidx.test.runner.AndroidJUnitRunner.buildRequest(SourceFile:40)
11-07 21:03:40.934 16426 16462 E TestRunner:    at androidx.test.runner.AndroidJUnitRunner.onStart(SourceFile:30)
11-07 21:03:40.934 16426 16462 E TestRunner:    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2335)
11-07 21:03:40.934 16426 16462 E TestRunner: ----- end exception -----

```
