### ISSUE TITLE
Patrol with Emulator.wtf does not work

### ISSUE THREAD

**Issue by petrnymsa** [leancodepl/patrol#1876]
I am trying to integrate Patrol tests with Emulator. wtf service to run our tests. 

- All tests locally works. 
- Single test (no matter which one) works on Emulator.wtf
- All tests do not work - every test fails basically on some "expect" with finders, that "widget X" can not be found.

Steps
1. `patrol build android`
2. ew-cli --token $EW_API_TOKEN --app build/app/outputs/apk/dev/debug/app-dev-debug.apk --test build/app/outputs/apk/androidTest/dev/debug/app-dev-debug-androidTest.apk  --use-orchestrator --clear-package-data

I've tried another option with sharding etc. 

Patrol version: patrol_cli v2.2.2
ew-cli version: 0.10.4

I tried to compare Patrol's example with our codebase and can't find any difference, which could probably be an issue.

**Comment by bartekpacia** [comment]
This issue is not reproducible.

Please provide accurate reproduction steps or we'll have to close it.

**Comment by bartekpacia** [comment]
Also consider asking on emulator.wtf's Slack channel.

**Comment by mateuszwojtczak** [comment]
@petrnymsa please provide a reproducible sample or consider asking this on our Discord server (https://discord.gg/K5hq2Stw). Closing this for now.
