### ISSUE TITLE
Test is not building on iOS

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#1889]
On branch task/patrol-extension

I get errors about concurrency in swift files:
`/Users/julia/patrol/packages/patrol/ios/Classes/AutomatorServer/Automator.swift:399:50: error: concurrency is only available in iOS 13.0.0 or newer
            func getUITreeRoots(installedApps: [String]) async throws -> [NativeView] {`

**Comment by bartekpacia** [comment]
fixed in #1891
