### ISSUE TITLE
 integration_test/test_bundle.dart:50:50: Error: Too many positional arguments: 0 allowed, but 1 found.

### ISSUE THREAD

**Issue by RomoloNobree** [leancodepl/patrol#1906]
### Steps to reproduce

Attempting to execute the example app using `patrol test -t integration_test/example_test.dart` results in the creation of a test_bundle.dart file. However, an error is encountered within this file.

![Screenshot 2023-11-15 at 10 30 38](https://github.com/leancodepl/patrol/assets/95217149/962aa962-0a4e-4398-a05a-e67e368e0d3f)

### Actual results

No device specified, using the first one (PT19655JA1222600300)
• Building apk with entrypoint test_bundle.dart...
        integration_test/test_bundle.dart:50:50: Error: Too many positional arguments: 0 allowed, but 1 found.
        Try removing the extra positional arguments.
          final binding = PatrolBinding.ensureInitialized(NativeAutomatorConfig());
                                                         ^
        ../lib/src/binding.dart:104:11: Context: Found this candidate, but the arguments don't match.
          factory PatrolBinding.ensureInitialized() {
                  ^^^^^^^^^^^^^^^^^
        Target kernel_snapshot failed: Exception

        FAILURE: Build failed with an exception.

        * Where:
        Script '/Users/romolon/Documents/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1297

        * What went wrong:
        Execution failed for task ':app:compileFlutterBuildDebug'.
        > Process 'command '/Users/romolon/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.

        * Get more help at https://help.gradle.org

        BUILD FAILED in 6s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (6.7s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:67:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:234:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:322:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:266:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#9      main (file:///Users/romolon/.pub-cache/hosted/pub.dev/patrol_cli-2.3.0/bin/main.dart:6:20)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 2.3.1
patrol: 2.3.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by bartekpacia** [comment]
**Quick fix:**

```
dart pub global activate patrol_cli 2.2.2
```

---

`patrol_cli 2.3.0` can only be used with `patrol 3.0.1`, which is available only on Flutter 3.16, which is not released yet.

**Comment by dima-prezhentsov** [comment]
I had the same problem and this quick fix helped solve it. But when running example_test.dart, nothing happens on my emulator 
logs in terminal:

> No device specified, using the first one (emulator-5554)
> • Building apk with entrypoint test_bundle.dart...
> ✓ Completed building apk with entrypoint test_bundle.dart (19.5s)
> • Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
> ✓ Completed executing apk with entrypoint test_bundle.dart on emulator-5554

**Comment by RomoloNobree** [comment]
Thanks [bartekpacia](https://github.com/bartekpacia) `dart pub global activate patrol_cli 2.2.2` fixed
