### ISSUE TITLE
Patrol don't load my WebView

### ISSUE THREAD

**Issue by zanelladev** [leancodepl/patrol#1921]
### Steps to reproduce

1. Using Android Emulator API 30
2. Patrol_cli version is 2.2.0
3. `patrol: ^2.3.2
     patrol_finders: ^1.0.0
     flutter_inappwebview: ^5.8.0` in pubspec.yaml
4.
```
void main() {

  patrolTest('Login Test |',
      nativeAutomation: true,
      bindingType: BindingType.integrationTest,
      nativeAutomatorConfig: const NativeAutomatorConfig(
          packageName: 'com.project.name'), (tester) async {
    await app.main();

    await tester.pumpWidget(const AppWidget());
    await tester.pumpAndSettle();

    await Future.delayed(const Duration(seconds: 10));

   // Here i test and go to the webview page successfully

    await tester.pumpAndSettle();
    
    await Future.delayed(const Duration(seconds: 40));

    final webview = find.byType(InAppWebView);
    
    expect(webview, findsOneWidget);
    
    // webview not loaded, crashhh

    await tester.pumpAndSettle();
    await tester.native.enterTextByIndex('user', index: 0);

    await tester.pumpAndSettle();

    await tester.native.enterTextByIndex('password', index: 1);

    await tester.pumpAndSettle();

    await tester.native.tap(
      Selector(text: 'Login'),
    );
  });
}
```

### Actual results

Patrol works fine, navigation to the WebView page, but when enter in the screen, webview no load, Future.delayed finish and crash. In Flutter test loads fine, in build app to.

### Logs

<details>
<summary>Logs</summary>

```
</details>
EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ??????????????????
        : Tests on Pixel_4_API_30(AVD) - 11 failed: There was 1 failure(s).
        : 
        : Test results saved as file:/C:/.../.../.../app/build/app/outputs/androidTest-results/connected/test-result.pb. Inspect these results in Android Studio by selecting Run > Import Tests From File from the menu bar and importing test-result.pb.
        : 
        : > Task :app:connectedDebugAndroidTest FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:connectedDebugAndroidTest'.
        
        
        #0      AndroidTestBackend.execute.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:140:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.execute (package:patrol_cli/src/android/android_test_backend.dart:106:5)
<asynchronous suspension>
#3      TestCommand._execute (package:patrol_cli/src/commands/test.dart:277:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:169:23)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:321:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:265:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#9      main (file:///C:/Users/user/AppData/Local/Pub/Cache/hosted/pub.dev/patrol_cli-2.2.0/bin/main.dart:6:20)
<asynchronous suspension>
```

### Patrol version

patrol: ^2.3.2

### Patrol Doctor output

patrol doctor
In next major release, patrolTest method will be intended for UI tests.
If you want to use Patrol in your widget tests, use patrol_finders package.

For more information, see https://patrol.leancode.co/patrol-finders-release
Disable this warning by setting the PATROL_FINDERS environment variable.
      
Patrol CLI version: 2.2.0
Program adb found in C:\Users\user\AppData\Local\Android\Sdk\platform-tools\adb.exe
Env var $ANDROID_HOME set to C:\Users\user\AppData\Local\Android\Sdk

### Flutter Doctor output

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [versÆo 10.0.22621.2715], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.84.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

**Comment by bartekpacia** [comment]
likely related #244
