### ISSUE TITLE
Split the example app into "app under tests" and Patrol example

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#1932]
- [ ] Use Patrol "challenge" as an example app.
- [ ] Transform existing example app to test app that will be used for internal Patrol testing
- [ ] Introduce desktop- and mobile-specific directories in both of those apps (related to #1926)
- [ ] Make sure CI/CD works with new apps

**Comment by bartekpacia** [comment]
See also #852, where more issues related to testing of Patrol itself are mentioned.
