### ISSUE TITLE
Widget Size and Color Test

### ISSUE THREAD

**Issue by ruveydagunal** [leancodepl/patrol#1936]
### Use case

While Flutter is testing, I want to test the colors and sizes of my widgets, there are not enough documents and I can't do this process.

### Proposal

import 'package:flutter/material.dart';
import 'package:patrol_test/home_view.dart';
import 'package:patrol_test/password_forgot.dart';
import 'package:patrol_test/signUp_view.dart';

class SignInView extends StatefulWidget {
  @override
  _SignInViewState createState() => _SignInViewState();
}

class _SignInViewState extends State<SignInView> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  TextEditingController _emailController = TextEditingController();
  TextEditingController _passwordController = TextEditingController();
  bool _obscureText = true;
  bool _formSubmitted = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Giriş Sayfası',
          key: Key('signInTitle'),
        ),
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back,
            key: Key('arrowBackButton'),
          ),
          onPressed: () {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (context) => HomeView(),
              ),
            );
          },
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                key: const Key('emailInput'),
                controller: _emailController,
                decoration: InputDecoration(
                  labelText: 'E-posta',
                  errorText: _formSubmitted
                      ? _validateEmail(_emailController.text)
                      : null,
                ),
                keyboardType: TextInputType.emailAddress,
              ),
              SizedBox(height: 16),
              TextFormField(
                key: const Key('passwordInput'),
                controller: _passwordController,
                decoration: InputDecoration(
                  labelText: 'Şifre',
                  errorText: _formSubmitted
                      ? _validatePassword(_passwordController.text)
                      : null,
                  suffixIcon: IconButton(
                    icon: Icon(
                        _obscureText ? Icons.visibility : Icons.visibility_off),
                    onPressed: () {
                      setState(() {
                        _obscureText = !_obscureText;
                      });
                    },
                  ),
                ),
                obscureText: _obscureText,
              ),
              SizedBox(height: 24),
              ElevatedButton(
                style: ElevatedButton.styleFrom(
                  primary: Colors.red
                ),
                key: const Key('signInButton'),
                onPressed: () {
                  setState(() {
                    _formSubmitted = true;
                  });

                  String? emailError = _validateEmail(_emailController.text);
                  String? passwordError =
                      _validatePassword(_passwordController.text);

                  if (emailError == null && passwordError == null) {
                    // Eğer e-posta ve şifre uygunsa yönlendirme yap
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => HomeView(),
                      ),
                    );
                  }
                },
                child: Text('Giriş Yap'),
              ),
              TextButton(
                key: Key('passwordForgot'),
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => PasswordForgot(),
                    ),
                  );
                },
                child: Text('Şifremi Unuttum'),
              ),
              Text('Hesabınız Yok mu?', key: Key('signUpText'),),
              ElevatedButton(
                key: const Key('signUpButton'),
                onPressed: () {
                  setState(() {
                    _formSubmitted = true;
                  });
                  if (_formKey.currentState!.validate()) {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => SignUpView(),
                      ),
                    );
                  }
                },
                child: Text('Üye Ol'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  String? _validateEmail(String value) {
    if (value.isEmpty) {
      return 'E-posta boş olamaz';
    } else if (!RegExp(r'^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$')
        .hasMatch(value)) {
      return 'Geçersiz e-posta formatı';
    }
    return null;
  }

  String? _validatePassword(String value) {
    if (value.isEmpty) {
      return 'Şifre boş olamaz';
    }
    return null;
  }
}
---------------------
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';
import 'package:patrol_test/main.dart';

void main() {
  patrolTest(
    'Sign in Successfully',
    ($) async {
      // Uygulamayı başlat
      await $.pumpWidgetAndSettle(const MyApp());

      // Appbar title ve buton kontrolü
      expect($(#signInTitle).exists, true);
      expect($(#arrowBackButton).exists, true);

      // Geri butonuna tıklandığında
      await $(#arrowBackButton).tap();
      expect($(#homeView).exists, true);
      await $(#arrowBackButtonHome).tap();

      // // E-posta ve şifre girişi
      await $(#emailInput).enterText('t@test.com');
      await $(#passwordInput).enterText('1q2w3e4r5T.');

      // // Giriş Yap butonuna tıklandığında
      await $(#signInButton).tap();
      expect($(#homeView).exists, true);
      await $(#arrowBackButtonHome).tap();

      await $('Giriş Yap')
        .which<ElevatedButton>((button) => !button.enabled)
        .which<ElevatedButton>(
          (btn) => btn.style?.backgroundColor?.resolve({}) == Colors.red,
        )
        .waitUntilVisible();

      // Şifremi Unuttum kontrolü
      await $(#passwordForgot).tap();
      expect($(#passwordForgotTitle).exists, true);
      await $(#arrowBackButtonForgot).tap();

      // Hesabınız Yok mu? text kontrolü
      expect($(#signUpText).exists, true);

      // Şifremi Unuttum kontrolü
      await $(#signUpButton).tap();
      expect($(#signUpTitle).exists, true);
      await $(#arrowBackButtonSignUp).tap();
    },
  );
}

**Comment by jBorkowska** [comment]
Hi @ruveydagunal! If you want to check widget's properties as size or color, you can access the widget object. Eg.:
```
   // obtaining Widget object of found element
   final button = $(#signUpButton).evaluate().first.widget as ElevatedButton;
   // accessing properties of that widget, eg. if is enabled
   expect(button.enabled, false);
```

Let me know if it helped

**Comment by ruveydagunal** [comment]
Hello, I tried to do the color control this way, but I'm getting an
error. I would be very glad if you could help
  patrolTest('UI > Sign In Button Color Successfully', ($) async {
    // Uygulamayı başlat
    await $.pumpWidgetAndSettle(const MyApp());
    // obtaining Widget object of found element
    final button = $(#signInButton).evaluate().first.widget as
ElevatedButton;
    // accessing properties of that widget, eg. if is enabled
    expect(button.enabled, true);
    expect(button.style?.backgroundColor, Color(0xfff44336));
  });

Julia Borkowska ***@***.***>, 23 Kas 2023 Per, 16:33
tarihinde şunu yazdı:

**Comment by jBorkowska** [comment]
What error did you get? Please post the logs :)
