### ISSUE TITLE
First build failed

### ISSUE THREAD

**Issue by sherrylin728** [leancodepl/patrol#1958]
### Steps to reproduce

I followed the process outlined in https://patrol.leancode.co/getting-started#configure-patrol-in-pubspecyaml, and encountered the following error

### Actual results

• Building apk with entrypoint test_bundle.dart...
        /Users/linyunxuan/flutter/android/app/src/androidTest/java/com/example/myapp/MainActivityTest.java:19: error: cannot find symbol
                instrumentation.setUp(MainActivity.class);
                                      ^
          symbol:   class MainActivity
          location: class MainActivityTest
        1 error
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:compileDebugAndroidTestJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 5s
✗ Failed to build apk with entrypoint test_bundle.dart (Gradle build failed with code 1) (19.6s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug - please report it.
Exception: Gradle build failed with code 1
#0      AndroidTestBackend.build.<anonymous closure> (package:patrol_cli/src/android/android_test_backend.dart:90:9)
<asynchronous suspension>
#1      DisposeScope.run (package:dispose_scope/src/dispose_scope.dart:46:7)
<asynchronous suspension>
#2      AndroidTestBackend.build (package:patrol_cli/src/android/android_test_backend.dart:42:5)
<asynchronous suspension>
#3      TestCommand._build (package:patrol_cli/src/commands/test.dart:234:7)
<asynchronous suspension>
#4      TestCommand.run (package:patrol_cli/src/commands/test.dart:167:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#6      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:321:18)
<asynchronous suspension>
#7      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:265:18)
<asynchronous suspension>
#8      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:77:20)
<asynchronous suspension>
#9      main (file:///Users/linyunxuan/.pub-cache/hosted/pub.dev/patrol_cli-2.2.2/bin/main.dart:6:20)
<asynchronous suspension>

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^2.3.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.2.2
Program adb found in /Users/linyunxuan/Library/Android/sdk/platform-tools//adb
Env var $ANDROID_HOME set to /Users/linyunxuan/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller not found (install with `brew install ideviceinstaller`)

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5.2 22G91 darwin-arm64, locale zh-Hant-TW)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

```

</details>

**Comment by piotruela** [comment]
Hi @sherrylin728. It seems to be more of a setup issue than a bug in the repository, so for now, I'll close it. However, after reviewing what you've written, please check whether the path to the `MainActivityTest.java` file matches the package name of your Android project (you find it in the `AndroidManifest.xml` file).
If you'll have any other questions feel free to join the patrol channel on Discord and describe your issue there. We'll try to help. Link to the discord channel: https://discord.gg/ukBK5t4EZg
