### ISSUE TITLE
Have the ability to mock device location

### ISSUE THREAD

**Issue by Buddybetadmin** [leancodepl/patrol#1961]
### Use case

We have an app for a very niche higly regulated industry. Its available on various app stores in different jurisdictions. Our app's behavior changes significantly based on the jurisdiction the app is accessed from primarily due to regulatory reasons. We need to test our app and its functionality from all these different jurisdictions. It will be really good to have a way to change the latitude and longitude of the device/emulator the app is being tested on similar to what we can do on native emulators and then test the functionality. 

### Proposal

May be at the start of the test, to have an api that allows us to pass the latitude and longitude which then the device mocks.

**Comment by piotruela** [comment]
Hi @Buddybetadmin. There is no known way for us to set the location from within the test/application code. If you have any idea on how this can be achieved, we would be more than happy to add it to our package :D 
If you want to test the app in various locations, I suggest to mock the service that you use for getting the location and return the desired lat and long there.

**Comment by piotruela** [comment]
We're closing it for now, as we don't see how this can be achieved. If anyone has an idea of how to implement this feature, feel free to reopen this issue.
