### ISSUE TITLE
Potential enhancements to new user / developer onboarding

### ISSUE THREAD

**Issue by thatdogmachine** [leancodepl/patrol#1978]
### Use case

Nice project :)

## Context

My entry point to Patrol was https://patrol.leancode.co/getting-started
I was initially using Flutter targetting Android. As part of an extension of scope to IOS, and a general improvement of testing, I started to explore Patrol.

## Current Status

I have functioning Patrol e2e tests on Android & IOS

## Considerations for improvement

I found getting Patrol working for IOS significantly more difficult than Android. The root of that issue appears to be specific to recent~ish xcode security evolution, and can be summarised as:

    // https://github.com/flutter/flutter/issues/128739#issuecomment-1590619555
    // 1.	Open the Xcode project.
    // 2.	Click on the project name in the left sidebar to open the project settings.
    // 3.	Select the target you want to check in the "Targets" section.
    // 4.	Click on the "Build Settings" tab.
    // 5.	In the search bar, type "ENABLE_USER_SCRIPT_SANDBOXING".
    // 6.	If the value of ﻿ENABLE_USER_SCRIPT_SANDBOXING is set to "No", then it is disabled. If it is set to "Yes", then it is enabled.

In the case of getting working Patrol tests, having this set to No seems necessary.

Eventually I realised that in https://github.com/leancodepl/patrol/tree/master/packages/patrol/example there is a fully worked example (though looks like that has significantly changed in recent days - commit e14d37c60c67613dd13da7f3f865af99098fe7ec is the version that helped me) but that example doesn't seem referenced by https://patrol.leancode.co/getting-started

### Suggestion 1
Consider if it is sensible to mention / reference / point out the implication of this ENABLE_USER_SCRIPT_SANDBOXING setting in your existing docs. The way I found this leads to a second suggestion...

### Suggestion 2
Make a (stronger?) call out from the getting started page to the example(s) - without the ability to inspect a working implementation, I may not have gotten this working

keep up the good work :)

**Comment by piotruela** [comment]
Hi @thatdogmachine, we updated the instruction recently and included your feedback. Thank you for the suggestion
