### ISSUE TITLE
Patrol CLI doesn't always use platform-native path separators

### ISSUE THREAD

**Issue by piotruela** [leancodepl/patrol#1980]
For now, we'are using unix-styled path separators in `patrol_cli` code. We should use platform-native path separators. Some work has been done [here](https://github.com/leancodepl/patrol/pull/1315).

**Comment by jBorkowska** [comment]
Also mentioned in #1256

**Comment by jBorkowska** [comment]
Size: S (need to check if still occurs)

**Comment by jBorkowska** [comment]
Closing as duplicate of #1256
