### ISSUE TITLE
Support Unicode symbols

### ISSUE THREAD

**Issue by shigomany** [leancodepl/patrol#1985]
### Steps to reproduce

1. Add in native iOS in **Info.plist** for example:
```
<key>NSPhotoLibraryUsageDescription</key>
    <string>$(APP_DISPLAY_NAME) запрашивает доступ к библиотеке фотографий, для того чтобы прикрепить фото.</string>
```

2. Use [image_picker](https://pub.dev/packages/image_picker) for request photo library.
3. When showed dialog with request image. In devtools we can see error with locale.

#### OR

Clone this [repo](https://github.com/shigomany/patrol_native_example)

### Actual results

Support russian symbols.

<img width="367" alt="image" src="https://github.com/leancodepl/patrol/assets/43740557/4142df05-2800-4a83-9be3-c0714809f167">

### Logs

<details>
<summary>Logs</summary>

```
 Patrol (native): tap() started
     Patrol (native): tap() failed
     ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
     The following PatrolActionException was thrown running a test:
     Patrol action failed: NativeAutomatorClientException: tap() failed with Invalid response: 400 ÐÐ´Ð°Ð»Ð¾ÑÑ Ð·Ð°Ð²ÐµÑÑÐ¸ÑÑ Ð¾Ð¿ÐµÑÐ°ÑÐ¸Ñ. (patrol.PatrolError, Ð¾ÑÐ¸Ð±ÐºÐ° 0)
     When the exception was thrown, this was the stack:
     #0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:225:7)
     <asynchronous suspension>
     #1      NativeAutomator.tap (package:patrol/src/native/native_automator.dart:494:5)
     <asynchronous suspension>
     #2      flow (file:///Users/shigomany/Documents/workingprojects/sdmarket/packages/sd_market/integration_test/auth/auth_as_tester_test.dart:43:5)
     <asynchronous suspension>
     #3      main.<anonymous closure> (file:///Users/shigomany/Documents/workingprojects/sdmarket/packages/sd_market/integration_test/cart/create_cart_test.dart:19:7)
     <asynchronous suspension>
     #4      patrolTest.<anonymous closure> (package:patrol/src/common.dart:120:7)
     <asynchronous suspension>
     #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:168:15)
     <asynchronous suspension>
     #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1013:5)
     <asynchronous suspension>
     #7      TestWidgetsFlutterBinding._createTestCompletionHandler.<anonymous closure> (package:flutter_test/src/binding.dart:804:12)
     <asynchronous suspension>
```

</details>

### Patrol version

patrol_finders: ^2.0.1+1
patrol: ^3.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.3.1+1
Program adb found in /Users/***/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/***/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.1.2 23B92 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by mateuszwojtczak** [comment]
Hi @shigomany, thanks for reporting this. Is it somehow blocking your UI tests? Or is it just a UI issue that is not related to actual test behavior? For now, I gave P2 label since it doesn't seem to interfere with testing.

**Comment by mateuszwojtczak** [comment]
Upgrading this to P1

**Comment by shigomany** [comment]
> Hi @shigomany, thanks for reporting this. Is it somehow blocking your UI tests? Or is it just a UI issue that is not related to actual test behavior? For now, I gave P2 label since it doesn't seem to interfere with testing.

This problem with UI

**Comment by bartekpacia** [comment]
I successfully reproduces this issue (I named some other iOS app to some russian text):

<img width="1440" alt="russian gibberish" src="https://github.com/leancodepl/patrol/assets/40357511/b23f2df3-5c38-46b7-8bdc-a857047c7742">
