### ISSUE TITLE
Test results aren't very useful when there is more than one exception causing a test failure

### ISSUE THREAD

**Issue by BSoD38** [leancodepl/patrol#1997]
### Use case

When a test fails because of an exception, the exception is displayed inside the HTML file.

This is good, but when there is more than one exception, only the message `Multiple exceptions (x) were detected during the running of the current test, and at least one was unexpected.` is displayed, which isn't very useful for debugging.

### Proposal

It would be better to display the whole exception stack inside the HTML file, so it can be more efficiently used for debugging.

**Comment by jBorkowska** [comment]
Closing as a duplicate of https://github.com/leancodepl/patrol/issues/951
