### ISSUE TITLE
The swipe method is unstable

### ISSUE THREAD

**Issue by EskinaKseniya** [leancodepl/patrol#2058]
I want to update the main page of my application, and for this I use the swipe(), but it does not work:((
I tried using pumpAndSettle before calling swipe() and  increase the number of steps, but none of this helped.
When the code is executed, the program outputs:
`Patrol (native): swipe() started`
`Patrol (native): swipe() succeeded`

But nothing really happens
Spotted on Android

**Comment by piotruela** [comment]
Hi @EskinaKseniya. Thanks for opening the issue. Can you please provide a reproducible example of a test where you spotted the problem?
