### ISSUE TITLE
Param for disabling the audio signal when the test runner is ready

### ISSUE THREAD

**Issue by adrian-moisa** [leancodepl/patrol#2085]
### Use case

I often have music on a lower volume in my headset just to be able to hear other pings from various apps. The audio effect from patrol is very loud and distracting. I don't feel the need to hear it each time I restart the tests.

### Proposal

Would be nice to have a param to disable it. Or even completely remove it. Cheers!

**Comment by bartekpacia** [comment]
If I understand correctly, that sound is just a notification from Android Test Orchestrator (~aka SpeakEasy) that the test is starting. You should be able to tap-and-hold the notification and disable the sound like for every other app.
I'm not sure there's anything that can be done about this in Patrol's code.

**Comment by piotruela** [comment]
I confirm that disabling the sound just like @bartekpacia suggested does the job. Then I'm closing this ticket as there is nothing to do from the patrol team side.
