### ISSUE TITLE
[patrol_cli] compatibility_checker.dart get's stuck when patrol is not installed

### ISSUE THREAD

**Issue by DrBu7cher** [leancodepl/patrol#2091]
### Steps to reproduce

I had a setup where patrol was installed with one flutter version, but wasn't with the one that was used when patrol ran. (I had 2 different versions with fvm).

I think it could be reproduced like this:
1. don't install patrol in `pubspec.yaml`s dev_dependencies
2. (run flutter pub get if necessary)
3. run `patrol test`

### Actual results

patrol get's stuck

### Logs

<details>
<summary>Logs</summary>
`patrol test -v -d emulator-5554`
```
Verbose mode enabled. More logs will be printed.
$ flutter --suppress-analytics --no-version-check pub deps --style=list
<nothing happens>
```

</details>

### Patrol version

patrol_cli: 2.6.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.2
Android: 
• Program adb found in /usr/bin/adb
• Env var $ANDROID_HOME is not set. (See the link: https://developer.android.com/tools/variables#set)
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 3.19.0-0.3.pre, on Ubuntu 22.04.3 LTS 5.19.0-051900-generic, locale de_DE.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from https://releases.llvm.org/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded from https://github.com/ninja-build/ninja/releases
    ✗ GTK 3.0 development libraries are required for Linux development.
      They are likely available from your distribution (e.g.: apt install libgtk-3-dev)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by piotruela** [comment]
Hi @DrBu7cher. Thanks for opening the issue. I was able to reproduce it. I think we should check if the patrol is in the dependency of the project we try to run it with, before actually executing the tests.

**Comment by DrBu7cher** [comment]
I opened a PR to fix it already. You are already checking for it, the check just has a minor flaw.

**Comment by piotruela** [comment]
I see it now 👍
