### ISSUE TITLE
patrol test command not returning an exit code in gitlab pipeline

### ISSUE THREAD

**Issue by daviddavis83** [leancodepl/patrol#2095]
### Steps to reproduce

I have a basic gitlab job that runs my patrol integration tests. The issue I'm having is the patrol command is not returning an exit code to the pipeline so the pipeline hangs. Here is my gitlab snippet

```
.run_patrol_tests: &run_patrol_tests
  - patrol test --target integration_test/patrol/tests
 ```
  
  In this particular situation the test is failing, which is fine, I would expect the exit code 1 to be passed to the pipeline
  
 ```
  Failed to execute tests of apk with entrypoint test_bundle.dart on emulator-5554 (Gradle test execution failed with code 1) (63.9s)
Exception: Gradle test execution failed with code 1
```

### Actual results

I would expect the patrol command to return the exit code to the parent process so the pipeline can exit accordingly

### Patrol version

patrol: ^3.5.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.4
Android: 
• Program adb found in /Users/ddavis/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/ddavis/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.3 23D56 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.2)
[✓] VS Code (version 1.86.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by piotruela** [comment]
Hi @daviddavis83. It's possible to get the exit code from running patrol tests on github actions. Take a look at how [we run](https://github.com/leancodepl/patrol/blob/db1470dfdc3df54df1515b803b16fee4444fcb83/.github/workflows/test-ios-simulator.yaml#L100-L101) the tests on iOS simulator in our repo. Let me know it this works in your case
