### ISSUE TITLE
[Android] "No instrumentation found for" after executing tests on BrowserStack

### ISSUE THREAD

**Issue by PiotrWpl** [leancodepl/patrol#2097]
### Steps to reproduce

Hi,

I followed the guide from the documentation and everything was working fine when I was running patrol run locally, but when I uploaded my app and test-suite from Azure DevOps to BrowserStack tests were not executed.

- I have an app with flavor and I defined it in pubspec.yaml file to don't have to pass the flavor argument into commands
- I have 'testInstrumentationRunner "pl.leancode.patrol.BrowserstackPatrolJUnitRunner"'
- It's a monorepo project with 'melos'
- To build the app on CI/CD I run 'flutter build apk --config-only' and 'patrol build android --verbose'
- Then I used BrowserStack API to successfully upload **the app**
'{"app_name":"app-dev-debug.apk","app_url":"bs://a4777a6bab1ac720da6bd61f994590608fdea74f","app_version":"3.0.0","app_id":"a4777a6bab1ac720da6bd61f994590608fdea74f","uploaded_at":"2024-02-08 14:15:33 UTC","expiry":"2024-03-09 14:15:33 UTC","custom_id":"mobile_app_3.0.0_17644","shareable_id":"***/mobile_app_3.0.0_17644"}'
<img width="604" alt="image" src="https://github.com/leancodepl/patrol/assets/1515300/a616a2cd-4b48-440d-90fe-1a05fbc7d48d">

and **test-suite**:
{"test_suite_name":"app-dev-debug-androidTest.apk","test_suite_url":"bs://4b1d08d6b09728e78574f3e1062ac6b472c861ab","test_suite_id":"4b1d08d6b09728e78574f3e1062ac6b472c861ab","uploaded_at":"2024-02-08 14:15:35 UTC","expiry":"2024-03-09 14:15:35 UTC","framework":"espresso","custom_id":"mobile_app_test_suite_3.0.0_17644","shareable_id":"***/mobile_app_test_suite_3.0.0_17644"}
<img width="606" alt="image" src="https://github.com/leancodepl/patrol/assets/1515300/50f69ffb-b188-4589-8572-82ca38c7193f">

and execute it:
{"message":"Success","build_id":"31ee836d148c018098576cb96f8f5decb85d72e5"}

### Actual results

Test are not executed:

<img width="1346" alt="image" src="https://github.com/leancodepl/patrol/assets/1515300/89db25f3-6099-437e-bb7a-8f64d32ab180">

### Logs

<details>
<summary>Logs</summary>

```
onError: commandError=true message=No instrumentation found for: tapsAround]
Activity manager (activity) commands:
```

</details>

### Patrol version

patrol: ^3.5.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.6.4
Android: 
• Program adb not found (install with `export PATH="$ANDROID_HOME/platform-tools:$PATH"`)
• Env var $ANDROID_HOME set to /usr/local/lib/android/sdk

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

**Comment by PiotrWpl** [comment]
I was able to run the tests on the BrowserStack. Will update this issue with the details after the weekend, to let you update the doc or for future reference of others.

**Comment by PiotrWpl** [comment]
After a long day of trial and error, I analyzed the `bs_android` script and discovered that I needed to add extra parameters to the body of my `curl` command, which is responsible for executing the build. I suspect (although I didn't thoroughly test it) that it was primarily due to `singleRunnerInvocation=true`, which defaults to `false`. I believe that such details should be documented in the Patrol documentation, as singleRunnerInvocation appears to be a "hidden" parameter in the BrowserStack documentation and seems crucial for ensuring the proper functioning of tests.

By the way, you did a great job with this package! My previous experience with integration tests in Flutter was very painful, but now it's a true pleasure (except for the integration with BrowserStack ;)).

**Comment by farizkah** [comment]
I was paying attention to your issue before I ran a test myself using bs_android, and fortunately, the test was executed well using command `bs_android -t .../..._test.dart --debug`.

The argument you mention above has default value to `true` as seen from the BS test report below
<img width="480" alt="image" src="https://github.com/leancodepl/patrol/assets/51899036/bd146f82-e5b7-443f-8e46-a6b15cd01072">

As patrol version from my side is still using 2.2.3, I don't know if there's some change in Patrol v3.x or the binary itself.

**Comment by PiotrWpl** [comment]
Hi @farizkah ,

before I checked `bs_android` script I was using my custom `curl` commands which were created based on docs mentioned here https://patrol.leancode.co/integrations/browserstack#upload-to-browserstack and as can be checked on the BS documentation mentioned on the Patrol website `singleRunnerInvocation` is `false` by default
<img width="890" alt="image" src="https://github.com/leancodepl/patrol/assets/1515300/eb37eb32-a8da-40d1-ac5f-f938dd086d1f">

Of course, it's not a problem if you are using `bs_android`, because it will automatically set `singleRunnerInvocation` to `true` for you, but if you are in the same situation as mine, that you decided to write those `curls` your own (I already had scripts to upload apps to BrowserStack App Live) you will encounter the same issue as me. That's why I think that this should be mentioned in the documentation.

**Comment by farizkah** [comment]
Ooh right, I understand what you're trying to do.
Thank you for your experience, I'm gaining some valuable insight from you 👍
