### ISSUE TITLE
Enable execution and reporting of multiple assertions within a test

### ISSUE THREAD

**Issue by kirksl** [leancodepl/patrol#2098]
### Use case

I have multiple state based assertions to perform per screen
Let's say I have 10 controls to validate state for
I'd like the test to execute all assertions regardless of failure and report all assertions that failed at the end of the test

https://www.linkedin.com/pulse/soft-asserts-better-way-test-your-code-serhat-u%C3%A7ar/

### Proposal

Alignment with other popular frameworks and packages that provide this capability

https://playwright.dev/docs/test-assertions#soft-assertions

**Comment by fylyppo** [comment]
Hi, currently we don't have any plans to implement such feature but you can try to do it on your own. [In this discussion](https://github.com/leancodepl/patrol/discussions/1460#discussioncomment-7800565) there's one of the methods to achieve that.
