### ISSUE TITLE
tester.element feature

### ISSUE THREAD

**Issue by AcarFurkan** [leancodepl/patrol#2099]
### Use case

I use `tester.element` to check how the `TextFormField` is focused on the screen. Is there an alternative to this on the `patrol` side?

### Proposal

    expect(FocusScope.of(tester.element($(TextFormField))).hasFocus, isTrue);

**Comment by jBorkowska** [comment]
Hi @AcarFurkan, yes, there is an alternative:
```
final element = $(TextFormField).evaluate();
```

**Comment by AcarFurkan** [comment]
thank you :) $(TextFormField).evaluate().elementAt(0), $(TextFormField).evaluate().first worked for me
