### ISSUE TITLE
How can I click the iOS internet permissions

### ISSUE THREAD

**Issue by yoni1988** [leancodepl/patrol#2104]
### Steps to reproduce

void main() {
  patrolTest(
    'app test',
    ($) async {

      await app.main();
      await $.pumpAndSettle();

      if (await $.native.isPermissionDialogVisible()) {
        await $.native.grantPermissionWhenInUse();
      }

      .....
   })
}

### Actual results

When launching an app for the first time on iOS, if it requires an internet connection then the default iOS dialog to request internet permissions pops up after starting the app. How can I use patrol to click the options?
<img width="333" alt="230818190-324a3f47-d731-4169-8d97-ea27517d34c6" src="https://github.com/leancodepl/patrol/assets/4382752/cdb829c8-208c-48e7-b331-f145bcb5468b">

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^3.5.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.6.4
Android: 
• Program adb found in /Users/yiwang/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/yiwang/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.1 23B2073 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.86.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by bartekpacia** [comment]
Permission dialogs often belong to `com.apple.springboard`, so try doing this:

```dart
await $.native.tap(
  Selector(text: 'WLAN & Mobile'),
  appId: 'com.apple.springboard',
);
```

**Comment by yoni1988** [comment]
@bartekpacia thanks. It works for me.
await $.native.tap(
      Selector(text: 'WLAN & Cellular'),
      appId: 'com.apple.springboard',
    );
