### ISSUE TITLE
Scenario always fails to start momentarily on first run

### ISSUE THREAD

**Issue by Yokoi-K** [leancodepl/patrol#2130]
### Steps to reproduce

I am trying to run the integration_test of the patrol example on an actual Android device.

However, as you can see in the video, the scenario drops out for a moment at the first startup.
The scenario that starts up for a moment is "android_app_test: taps around" as you can see in the red text in the upper left corner of the screen.

https://github.com/leancodepl/patrol/blob/patrol-v2.3.2/packages/patrol/example/integration_test/android_app_test.dart#L4

After that, the scenario starts up again, and after that, the scenario proceeds normally.

https://github.com/leancodepl/patrol/assets/29598247/38a79b3d-0734-4e6a-a9de-b768db9a4573

This phenomenon is reproduced in our app as well. 

It can be reproduced by running it in example dir.

https://github.com/leancodepl/patrol/tree/master/packages/patrol/example

The problem reproduces itself on Firebase Testlab as well.

### Actual results

I would like to eliminate this puzzling behavior.

Is there a solution?

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 2.3.2

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.2.2
Program adb found in /Users/yo/Library/Android/sdk/platform-tools/adb
Env var $ANDROID_HOME set to /Users/yo/.rbenv/shims:/Users/yo/.zplug/repos/zplug/zplug/bin:/Users/yo/.zplug/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/Library/Apple/usr/bin:/Users/yo/fvm/default/bin:/Users/yo/.pub-cache/bin:/Users/yo/Library/Android/sdk/platform-tools:/Users/yo/bin:/Users/yo/Library/Android/sdk
Program xcodebuild found in /usr/bin/xcodebuild
Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller```

</details>


### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.3.1 23D60 darwin-arm64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.85.2)
[✓] Connected device (3 available)
[✓] Network resources
```

</details>

**Comment by jBorkowska** [comment]
Hi @Yokoi-K, this is normal behavior - this first test run is a dummy run, that lets the native side discover all Dart tests that needs to be executed. It is result of so called test bundling, which you can read about here: https://leancode.co/blog/patrol-2-0-improved-flutter-ui-testing, in section Android implementation:

> It's worth mentioning that CalculatorTest constructor and the testCases() method are actually called 5 times. That's because [Android Test Orchestrator](https://developer.android.com/training/testing/instrumented-tests/androidx-test-libraries/runner#use-android) (a component responsible for executing tests) makes an initial run to collect the tests, so it can execute them later.

Feel free to reopen this issue or create new one of there are some more problems.
