### ISSUE TITLE
widgets that are not visible cannot be found

### ISSUE THREAD

**Issue by matanyos** [leancodepl/patrol#2146]
### Steps to reproduce

add a button with a text 'LOG IN' in the bottom of the screen and fill a text field to make the keyboard show up, then try to tap the button using await $('LOG IN').tap();

### Actual results

when i try to write a text in a text field the keyboard shows up. 
in portrait mode i try to:
 await $('LOG IN').tap();
 it works fine.
 
 in lanscape mode the keyboard is on top of the login button
 trying to:
  await $('LOG IN').tap();
  doesn't work.
  
  got this exception:
  
  java.lang.AssertionError: Dart test failed: login_test validation text visible after clicking login button with empty email
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following WaitUntilVisibleTimeoutException was thrown running
a test:
TimeoutException after 0:00:10.000000: Finder "Found 1 widget
with text "LOG IN": [
RichText(softWrap: wrapping at box width, textScaler: linear
(1.1x), maxLines: unlimited, text: "LOG IN", dependencies:
[Directionality, _LocalizationsScope-[GlobalKey#66e07]],
renderObject: RenderParagraph#3bd5a relayoutBoundary=up2),
]" did not find any visible (i.e. hit-testable) widgets

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

3.5.2

### Patrol Doctor output

Patrol doctor:
Patrol CLI version: 2.6.4
Android:
• Program adb found in C:\Users\matan\AppData\Local\Android\Sdk\platform-tools\adb.exe
• Env var $ANDROID_HOME set to C:\Users\matan\AppData\Local\Android\Sdk

### Flutter Doctor output

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.19045.4046], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.3)
[√] Android Studio (version 2023.1)
[√] VS Code (version 1.87.0)
[√] Connected device (4 available)
[√] Network resources

• No issues found!

**Comment by piotruela** [comment]
Hi @matanyos. This is an expected behaviour. We don't want to allow to click not visible widgets because the user couldn't do it either. You can just close the keyboard to make it visible before clicking on it

**Comment by matanyos** [comment]
@piotruela Thanks, Can you tell me know the keyboard is closed in a patrol test?
