### ISSUE TITLE
Render print statements during patrol test, similar to patrol develop

### ISSUE THREAD

**Issue by adrian-moisa** [leancodepl/patrol#2157]
### Use case

I am currently setting up my testing pipeline with gitlab runner. Managed to get patrol running in waydroid on debian. I'm running the tests in the pipeline with `patrol test`. In all my tests I have added print statements to be able to track during `patrol develop` what happens. They are extremely useful and function as a substitute for the lack of live output. For some reason these print statements don't show up when using `patrol test`. All I get is the final html report in case of failure. Which I can export as an gitlab pipeline artifact. But I'd like to be able to see the prints as well in the live pipeline. Is it possible to activate them at all during `patrol test`?  

### Proposal

Param to control prints visibility or just make them visible by default. Cheers!

**Comment by bartekpacia** [comment]
For now you can see logs by grepping output of `adb logcat` for `flutter: `.

related: #561, #528, #951, #1855 (also created by you, hehe)

**Comment by adrian-moisa** [comment]
I see that this question was asked one year ago [Link to reply](https://github.com/leancodepl/patrol/issues/951#issuecomment-1434735721). So far no change. Can you provide some feedback about the architecture with a hint to what is the process/reasoning that blocks prints during `patrol test`. Is it something small or some more complex technical considerations are behind it? For now I'm ok until the test runner gives a detailed report by itself, but seeing my own prints would be nice. If it's smth simple maybe I can do a PR. Right now I have no idea about how patrol runs it's business. So maybe it's not easy for me to anything there.

**Comment by adrian-moisa** [comment]
Any advice? Cheers!

**Comment by bartekpacia** [comment]
Hey, sorry - I somehow missed notification for this message. I no longer work on Patrol.

The main problem that I remember is that to get logs from the Flutter app, you need to connect to the Dart VM (of course excluding [the dummy approach to just grep `adb logcat`'s output](https://github.com/leancodepl/patrol/issues/2157#issuecomment-2005047200)).

And when you run `patrol test`, a new app process is started for every test, which would require reconnecting to Dart VM (the one that runs the Flutter app's Dart code) every time. This is something I didn't have time to research further. But that's the gist of it.

**Comment by adrian-moisa** [comment]
I find it odd that patrol develop does render the print statements. What's different about patrol test? I'm trying to read the codebase now to get a feeling of what does what. It's quite a puzzle. I found `/patrol/dev_docs/test_bundling.svg`. Any other resources that I can use to get a feeling of the architecture?

**Comment by piotruela** [comment]
Hi @adrian-moisa. I can confirm that Patrol is still being maintained. We have some stuff on our roadmap and printing more logs and doing it nicer is on that list but I don't think it will get there anytime soon. 

If you want to investigate the differences between `patrol test` and `patrol develop` start by looking at `test_bundle.dart` file which both those commands generate as their first step. You can see the difference in the execution steps. You can also look into `develop.dart` and `test.dart` files to see how `_execute` method is different.

**Comment by adrian-moisa** [comment]
Hi @piotruela! Thanks for taking the time to answer. You were right on the money guessing my subtext question. Glad to hear that's the case. I'm fully vested in this library. I believe it's a great product that's worth keeping in top condition.

I've been doing some deep reading of the codebase and beyond up to `AndroidJunitRunner` level trying to find a resolution for #2184. Still many of the hot points are not 100% clear but I have a rough sketch of what goes on. I'll look again at the files you indicated to see if I can infer anything useful regarding the prints. Otherwise I'll be back with more questions.
