### ISSUE TITLE
Possibility to take delay between doubleTap's taps through a parameter.

### ISSUE THREAD

**Issue by Akshatji800** [leancodepl/patrol#2164]
### Use case

Wanted to have a test where my usecase was replication of user behaviour who quickly click on back button twice. Thought of using doubleTap() but it doesn't serve the purpose due to the 300 ms delay given by default according to the below code snippet.

```
fun doubleTap(uiSelector: UiSelector, bySelector: BySelector, index: Int, timeout: Long? = null) {
        Logger.d("doubleTap(): $uiSelector, $bySelector")

        val uiObject = uiDevice.findObject(uiSelector)

        if (waitForView(bySelector, index, timeout) == null) {
            throw UiObjectNotFoundException("$uiSelector")
        }

        Logger.d("Double clicking on UIObject with text: ${uiObject.text}")
        uiObject.click()
        Logger.d("After first click")
        delay(ms = 300)
        uiObject.click()
        Logger.d("After second click")
        delay()
    }
```

### Proposal

If possible have the option to specify the delay by the user only through a parameter.

**Comment by piotruela** [comment]
This feature was released together with [`patrol`](https://pub.dev/packages/patrol) 3.7.0
