### ISSUE TITLE
await pumpWidgetAndSettle not awaiting?

### ISSUE THREAD

**Issue by bgintzairspace** [leancodepl/patrol#2180]
### Steps to reproduce

I have a test that goes through the setup process which ends with:

```
await $.pumpWidgetAndSettle(UncontrolledProviderScope(
        container: ProviderContainer(
          observers: [],
        ),
        child: const MyApp(),
      ));
```
      
For the test portion, I have a very simple login form that checks for the presence of the fields, fills them in and submits:

```
expect($('LOGIN'), findsOneWidget); 
await $(Keys.authEmailField).enterText('user');
await $(Keys.authPasswordField).enterText('password');     
await $('LOGIN').tap();
```
 

### Actual results

As it is shown it does not work for me.  However, if I move the order of when I check for the button it does work.  It is very strange.  It is like it doesn't render the screen until the first `await ($Keys.....)` line

```
//expect($('LOGIN'), findsOneWidget); 
await $(Keys.authEmailField).enterText('user');
await $(Keys.authPasswordField).enterText('password');     
expect($('LOGIN'), findsOneWidget);  //THIS WORKS??
await $('LOGIN').tap();
```

I even tried to put a delay in there to just see if the pumpAndSettle needed more time to settle

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

  patrol: ^3.6.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.19.5 • channel stable
Android: 
• Program adb found in /[PATH]/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /[PATH]/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller```

</details>

**Comment by bgintzairspace** [comment]
This was tested on a Pixel 7 only

**Comment by bgintzairspace** [comment]
Update:  If I put this:
`await $.waitUntilVisible($('LOGIN'), timeout: const Duration(seconds: 10));`
above the top `expect($('LOGIN'), findsOneWidget);`. It works correctly.

I thought the `pumpWidgetAndSettle()` handled this so maybe I am just writing tests wrong?

**Comment by pawlowskim** [comment]
Maybe there is something else rendered before login button is visible, like splash screen / auto log in page / some wrapper or something? I'm also waiting for first element on the sign in form before I proceed further with any tests.

**Comment by fylyppo** [comment]
Hi, I suppose settling ends before sign up form is being rendered. You could try to set longer `duration` in `pumpWidgetAndSettle()` or/and use `await $(Key).waitUntilExists()` and `await $(Key).waitUntilVisible()` instead of `expect()`.
