### ISSUE TITLE
Support for --dart-define-from-file

### ISSUE THREAD

**Issue by jaxnz** [leancodepl/patrol#2186]
### Use case

We currently use the argument `--dart-define-from-file` and keep environment variables inside a json file. This works for `flutter test` but isn't supported for `patrol test`.

### Proposal

As patrol is a wrapper for flutter test, we should be able to pass `patrol test --dart-define-from-file=xxxx.json`

**Comment by piotruela** [comment]
We already have a [issue](https://github.com/leancodepl/patrol/issues/1742) for this feature. Therefore closing this as duplicate.
