### ISSUE TITLE
Add privacy manifest for Apple

### ISSUE THREAD

**Issue by jtdLab** [leancodepl/patrol#2189]
### Use case

It's seems that patrol is requiring a privacy manifest.
See https://github.com/flutter/flutter/issues/131940 for context.

Apple announcement here: [developer.apple.com/support/third-party-SDK-requirements](https://developer.apple.com/support/third-party-SDK-requirements/)

May 1st deadline announcement here: [developer.apple.com/news/?id=3d8a9yyh](https://developer.apple.com/news/?id=3d8a9yyh)

This [analyzer](https://github.com/crasowas/app_store_required_privacy_manifest_analyser/tree/main) reported that patrol needs to add a privacy policy for these APIs:

```sh
🛠️  Descriptions for the following required API reason(s) may be missing: 1
[0] NSPrivacyAccessedAPICategoryFileTimestamp
```

### Proposal

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk

**Comment by piotruela** [comment]
Hi @jtdLab. Thanks for pointing this up. The reason for this warning to appear is the code of the package that we forked inside Patrol repository. Good news is that it seems like the [reason](https://github.com/Building42/Telegraph/issues/137) that made us fork this package has been fixed so we should try to bring back using the package as the dependency. 
If that won't be possible, we should follow the [documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393) of this API and add Privacy Manifest file to the package
