### ISSUE TITLE
Issue with Patrol Flutter tests

### ISSUE THREAD

**Issue by Vukan-Levi9** [leancodepl/patrol#2190]
### Steps to reproduce

It is hard to reproduce this issue, since it doesn't happen all the time...

### Actual results

I have a question regarding running tests in Flutter using Patrol framework. Sometimes when I run the test it passes and sometimes it just fails with this message in report.

### Logs

<details>
<summary>Logs</summary>

```
EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK
The following message was thrown: Multiple exceptions (3) were detected during the running of the current test, and at least one was unexpected.

at pl.leancode.patrol.PatrolJUnitRunner.runDartTest(PatrolJUnitRunner.java:135) 
at care.incision.teams.MainActivityTest.runDartTest(MainActivityTest.java:31)
```

</details>

### Patrol version

patrol: ^3.6.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.19.6 • channel stable
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.4)
[√] Android Studio (version 2021.3)
[√] Android Studio (version 2023.2)
[√] IntelliJ IDEA Community Edition (version 2022.2)
[√] VS Code (version 1.89.0)
[√] Connected device (4 available)
[√] Network resources
 
• No issues found!
```

</details>

**Comment by piotruela** [comment]
Hi. Please attach a logcat from failing tests run. 
Steps:
- clear logcat (adb logcat -c),
- run logcat in another tab and redirect it's output to some file (adb logcat > logcat.txt),
- run patrol test,
- after the test fails stop the logcat and share the logs file.
