### ISSUE TITLE
[patrol_cli] "target <target location> is invalid" - message is misleading

### ISSUE THREAD

**Issue by MarkOSullivan94** [leancodepl/patrol#2211]
### Steps to reproduce

1. Create a new Flutter project
2. Create a test called `patrol_test_trial.dart`
3. Add basic patrol test for demo purposes
4. Execute `patrol -t patrol_test_trial.dart`
5. See the error message

### Actual results

You will see an error message with `Error: target patrol_test_trial.dart is invalid` but the test is actually valid and it's only the naming which is the issue here.

Changing the name to `patrol_trial_test.dart` will stop the error message from appearing and so this should be suggested in the error message.

### Logs

<details>
<summary>Logs</summary>

Error: target integration_test/tests/super_admin/patrol_test_trial.dart is invalid
#0      throwToolExit (package:patrol_cli/src/base/exceptions.dart:7:3)
#1      TestFinder.findTests (package:patrol_cli/src/test_finder.dart:65:9)
#2      TestCommand.run (package:patrol_cli/src/commands/test.dart:94:23)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:347:18)
<asynchronous suspension>
#5      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:291:18)
<asynchronous suspension>
#6      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#7      main (file:///Users/mos/.pub-cache/hosted/pub.dev/patrol_cli-2.7.0/bin/main.dart:6:20)
<asynchronous suspension>
</details>

### Patrol version

patrol: 3.7.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

Patrol doctor:
Patrol CLI version: 2.7.0
Flutter command: flutter 
  Flutter 3.16.9 • channel stable
Android: 
• Program adb found in /Users/mos/Library/Android/sdk/platform-tools//adb
• Env var $ANDROID_HOME set to /Users/mos/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 13.5.1 22G90 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (version unknown)
    ✗ Unable to determine Android Studio version.
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.

</details>

**Comment by rekire** [comment]
I ran into the same error and totally ripped of my test until I checked the source code of the cli.
