### ISSUE TITLE
App Data not deleted in Firebase Cloud lab beween tests

### ISSUE THREAD

**Issue by rekire** [leancodepl/patrol#2248]
### Steps to reproduce

1. Create a test with two `patrolTest()` calls
2. Run the test in the firebase cloud test

### Actual results

In my case I depend on the fact that I have always a clear state on test startup, however when the first test failed, the second has the config of the first one which breaks my test.

On my local device the app data are always deleted since this is not the case for Firebase Cloud lab I call this a bug.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: ^3.7.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Activated patrol_cli 2.8.1.
Patrol doctor:
Patrol CLI version: 2.8.1
Flutter command: flutter 
  Flutter 3.22.1 • channel stable
Android: 
• Program adb found in /usr/local/lib/android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /usr/local/lib/android/sdk
```
(I am not really sure which parts are exactly from the logouput from `patrol doctor`.
</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
N/A
```

</details>

**Comment by lockieRichter** [comment]
Seeing similar things when running through the command line at the moment.

**Comment by rekire** [comment]
I just excected the test (again) locally with the cli version 2.8.1 on MacOS (yeah maybe a linux issue) and had not that behavior

**Comment by Kendru98** [comment]
Hi guys, thanks for creating an issue report. Can you provide minimum reproduction steps @rekire?

**Comment by rekire** [comment]
@Kendru98 I think this is not absolutely required anymore. I got a hint which I will test soon. Might be worth to update the docs with the switch if it works (which is likely out of my view)

For more context I call it like this:
```bash
gcloud firebase test android run \
    --project=<my-project-id> \
    --type instrumentation \
    --use-orchestrator \
    --app build/app/outputs/apk/debug/app-debug.apk \
    --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
    --device model=MediumPhone.arm,version=29,locale=en,orientation=portrait \
    --timeout 1m
```

I got this hint from @jBorkowska via Discord:
> Hi @rekire ! You have to add this line to this invocation:
> `--environment-variables clearPackageData=true \`
> It tells orchestartor to clear the package data between test runs
> Keep in mind that it clears only the data of your app, not other data on the device, eg. Chrome

**Comment by rekire** [comment]
Can confirm that flag works fine. So my suggestion is to add this flag to the docs

**Comment by Kendru98** [comment]
Great! You can make a commit to docs by yourself by using a button on the bottom of the page. https://patrol.leancode.co/ci/firebase-test-lab

**Comment by rekire** [comment]
PR is open
