### ISSUE TITLE
Add support for root integration test (default is still 'integration_test') (fix included)

### ISSUE THREAD

**Issue by shovelmn** [leancodepl/patrol#2251]
### Use case

When wanting to structure tests different then having integration_test folder
Also fixed issue where suffix with . would break test bundle generation (ex. `_text.patrol.dart`)

### Proposal

Solved here:

https://github.com/shovelmn12/patrol

**Comment by shovelmn12** [comment]
Maybe it's best to use https://pub.dev/documentation/path/latest/path/normalize.html to normalize paths... Will solve relative targets

**Comment by jBorkowska** [comment]
Hi @shovelmn, thank you for the proposal. There is already an issue about it, so I'm closing this one as duplicate of https://github.com/leancodepl/patrol/issues/743
