### ISSUE TITLE
Firebase TestLab Test Failed 

### ISSUE THREAD

**Issue by ib-8** [leancodepl/patrol#2269]
### Steps to reproduce

1. Upload app apk (flutter build apk)
2. Upload test app apk (patrol build android)

Setup has been done as per the document

### Actual results

The uploaded test APK does not contain the test runner class specified in the manifest file. This is probably because the test runner isn't built into the test APK (might be in the app APK instead).

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 3.0.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.0.0
Flutter command: flutter 
  Flutter 3.16.9 • channel stable
Android: 
• Program adb found in /Users/ibrahim/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/ibrahim/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Sathya. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

</details>

**Comment by jBorkowska** [comment]
Hi @ib-8! This is not how you should upload those APKs. Check out this page: https://patrol.leancode.co/ci/firebase-test-lab

Both APKs are build by `patrol build android` command. You can find those files in `build` folder in your project, under eg. this paths:
build/app/outputs/apk/debug/app-debug.apk - app apk
build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk - test app apk

Those paths may differ a bit if you have flavors - eg. there will be additional folder named after flavor you use.

If you have some more questions, we invite you to our Discord server: https://discord.gg/ukBK5t4EZg

**Comment by ib-8** [comment]
Thanks! It is working after uploading the apk built by patrol.
