### ISSUE TITLE
While trying to run the framework with recent patrol version, getting issues on type mismatch 

### ISSUE THREAD

**Issue by prezshahbaz96** [leancodepl/patrol#2279]
### Steps to reproduce

type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast
#0      PubspecReader.read (package:patrol_cli/src/pubspec_reader.dart:135:39)
#1      TestCommand.run (package:patrol_cli/src/commands/test.dart:87:35)
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#3      CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:84:18)
#4      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:348:30)
<asynchronous suspension>
#5      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:292:18)
<asynchronous suspension>
#6      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#7      main (file:///Users/ajaythakur/.pub-cache/hosted/pub.dev/patrol_cli-3.0.1/bin/main.dart:6:20)
<asynchronous suspension>

### Actual results

type 'String' is not a subtype of type 'Map<dynamic, dynamic>?' in type cast
#0      PubspecReader.read (package:patrol_cli/src/pubspec_reader.dart:135:39)
#1      TestCommand.run (package:patrol_cli/src/commands/test.dart:87:35)
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#3      CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:84:18)
#4      PatrolCommandRunner.runCommand (package:patrol_cli/src/runner/patrol_command_runner.dart:348:30)
<asynchronous suspension>
#5      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:292:18)
<asynchronous suspension>
#6      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:70:20)
<asynchronous suspension>
#7      main (file:///Users/ajaythakur/.pub-cache/hosted/pub.dev/patrol_cli-3.0.1/bin/main.dart:6:20)
<asynchronous suspension>

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 3.0.1

### Patrol Doctor output

No issues in patrol doctor

### Flutter Doctor output

no issues in flutter doctor

**Comment by Kendru98** [comment]
Hi @prezshahbaz96, thanks for creating an issue. Please create a Minimal reproducible example, clone a repo with this problem that I can easily reproduce. Did you try to clear a pub cache? Looks like issue with cache files. Also feel free to join our Discord, where community can help https://discord.com/invite/ukBK5t4EZg
PS. provide patrol/flutter doctor sections in bug report template please
