### ISSUE TITLE
What am I doing Wrong

### ISSUE THREAD

**Issue by lionsilva** [leancodepl/patrol#2281]
Hi,

I am trying to use Patrol but I am not achieving consistent results.

The tests fails or not depending on circunstantes that I am not being able to identify.

Right now, after many manipulation, I separated my tests in different files and in the folder where they are, I put a first file wit a setUpAll().

Can somebody explain to me how to make these tests reliably?

For instance, if group is async, it sticks while building AndroidTest. If not, it runs, but still some results also vary.

So right now I am not sure how to write proper tests.

Thanks

**Comment by Kendru98** [comment]
Hi @lionsilva,
please create a repository with some examples of issue. You totally overwrite bug report template, what is not good 😓. Provide some example what isn't working for you, then we can help. You can also look for help on our discord when community helps each other with first steps in patrol https://discord.com/invite/ukBK5t4EZg. Cheers.

There is an example of simple patrol test:
https://patrol.leancode.co/getting-started#create-a-simple-integration-test - test can be runned by patrol test -t 'path for test'

**Comment by lionsilva** [comment]
Hi, very sorry. Yes, let me paste here what I am trying to do right now:

          `void main() {
            setUpAll(() async {
              await Firebase.initializeApp();
              await di.init();
            });
          
            patrolTest('ConnectivityAwarenessCubit should go to connected state because Mobile', ($) async {
              await $.pumpWidgetAndSettle(const MyApp());
              await $.native.enableCellular();
              await $.pumpAndSettle();
              await $.pump(Duration(seconds: 5));
          
              // Check the result
              expect(find.text(kIsConnectedInformativeText), findsOneWidget);
            });
          
            patrolTest('ConnectivityAwarenessCubit should go to connected state because WiFi', ($) async {
              await $.pumpWidgetAndSettle(const MyApp());
              await $.native.enableWifi();
              await $.pumpAndSettle();
          
              // Check the result
              expect(find.text(kIsConnectedInformativeText), findsOneWidget);
            });
          
            patrolTest('ConnectivityAwarenessCubit should go from connected to disconnected state', ($) async {
              await $.pumpWidgetAndSettle(const MyApp());
              await $.native.enableWifi();
              await $.native.enableCellular();
              await $.pumpAndSettle();
          
              // Check the intermediate result
              expect(find.text(kIsConnectedInformativeText), findsOneWidget);
          
              await $.native.disableCellular();
              await $.native.disableWifi();
              await $.pumpAndSettle();
          
              // Check the result
              expect(find.text(kIsDisconnectedInformativeText), findsOneWidget);
            });
          
            patrolTest('ConnectivityAwarenessCubit should stay in disconnected state', ($) async {
              await $.pumpWidgetAndSettle(const MyApp());
              await $.native.enableWifi();
              await $.native.enableCellular();
              await $.pumpAndSettle();
          
              await $.native.disableWifi();
              await $.native.disableCellular();
              await $.pumpAndSettle();
          
              // Check the result
              expect(find.text(kIsDisconnectedInformativeText), findsOneWidget);
            });
          }
`

I had to remove the imports here to share the code. In the original, the imports are there and fine. 

I am not sure if doing like this is the proper way. 
With this code, what I get is to be stuck in the last patrolTest. In other words, it does not conclude the tests, it keep stuck in Task :app:connectedDebugAndroidTest

And this is something that is continuously happening. I separated the tests in a file each one, but then I was not able to make all of them concluded. 

It is a bit confusing to me what I am missing. Should be simple, I think.

Thank You for the help.

<img width="1134" alt="Captura de ecrã 2024-07-29, às 16 07 15" src="https://github.com/user-attachments/assets/3a39f133-8ce1-4a42-8e6d-26f49a131443">

**Comment by lionsilva** [comment]
Above there is my comment, the code and an image illustrating.

Thank You a lot

**Comment by bartekpacia** [comment]
A possible cause is that of `setUpAll` not being supported in Patrol tests. Instead of using it, copy code inside `setUpAll` to individual `patrolTest()` callbacks.

see also #1501

**Comment by lionsilva** [comment]
Hi, thank you for your answer.

What I want to say is that I don't know why, but running the tests with -t within a file worked for me.

What is the difference between:

"patrol test -t integration_test/feature_connectivity_awareness_test/feature_connectivity_awareness_test.dart --verbose"

and

"patrol test integration_test/feature_connectivity_awareness_test/feature_connectivity_awareness_test.dart --verbose" ?

I also discovered that I was not being careful because the device was the same during all run, the tests were triggering the app many times, however I was not resetting the connection state by turning off wifi or mobile before to start the next test. So the connection state was mixed up.

I also found that WiFi takes longer to turn on or off than Mobile, so I had to pump for 3 seconds turning WiFi on or off.

Thank You.

**Comment by Kendru98** [comment]
I'm glad that we can help, also thanks @bartekpacia for answer. Please next time if you are not sure that this is a patrol issue contact via our discord https://discord.com/invite/ukBK5t4EZg.
If you want skip parameter -t you can do this, probably it is some shortcut. But remember that you can also pass test paths after comma fe. `-t {test1Path},{test2Path}` or run whole folder by providing path: `patrol test -t integration_test/smoke_tests/`.
Also remember that you can use patrol finders when using patrol for example:
this: `expect(find.text(kIsDisconnectedInformativeText), findsOneWidget);`
can be this: `$('textToFind').waitUntilVisible(); or $(Key('keyName)).tap()` etc. more about finders are there https://patrol.leancode.co/finders/usage#finding-widgets
Cheers.
