### ISSUE TITLE
[Question] Correct procedures for running tests on Firebase Device Lab

### ISSUE THREAD

**Issue by ReubenTurner-esusu** [leancodepl/patrol#2282]
The docs advise building with a specific test target, like so:
```
patrol build android --target integration_test/example_test.dart
```
but do not specify whether it is required to do this rather than building with all tests included, like this:
```
patrol build android
```
Additionally, the docs say to use the gcloud CLI to run the tests, but do not mention uploaded the test files to the Firebase console on the web and running the tests there. 

My questions are therefore:
1. Can we run `build` with all tests for use in Device Lab?
2. Can we test on the web or are we required to use the gcloud CLI to run them?

**Comment by piotruela** [comment]
Closing this as this is not an issue in Patrol repository. If you'll have any other questions please ask on our [Discord channel](https://discord.com/invite/ukBK5t4EZg).
