### ISSUE TITLE
Only white screen

### ISSUE THREAD

**Issue by ioma8** [leancodepl/patrol#2284]
### Steps to reproduce

Versions:
patrol_cli v3.0.1 
patrol: 3.9.0

1. I have done android setup as described in the guide.
2. I have created simple test:
```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

void main() {
  patrolTest(
    'counter state is the same after going to home and switching apps',
    ($) async {
      await $.pumpWidgetAndSettle(
        MaterialApp(
          home: Scaffold(
            appBar: AppBar(title: const Text('app')),
            backgroundColor: Colors.blue,
          ),
        ),
        duration: const Duration(seconds: 10),
      );

      expect($('app'), findsOneWidget);

      await $.native.pressHome();
    },
  );
}
```
3. I try to run it with patrol test or patrol develop command. I am running it as follows:
```
patrol develop -t integration_test/experiments/mytest_test.dart
```

### Actual results

 In patrol develop I get those error messages:
```
	The Dart VM service is listening on http://127.0.0.1:38875/YxB7SRH_J_U=/
	Patrol (native): NativeAutomatorClient created, port: 8081
	Patrol (native): initialize() started
	Patrol (native): initialize() failed
```

In both patrol test and patrol develop I am getting just white screen in the android emulator:
<img width="386" alt="image" src="https://github.com/user-attachments/assets/2babd8c2-837c-476b-913f-34bddc5a8a4c">

Interesting thing is when my colleagues run the same command in the same codebase, it runs the tests for them.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol: 3.9.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.0.1
Flutter command: flutter
  Flutter 3.22.2 • channel stable
Android:
• Program adb found in /Users/myaccount/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/myaccount/Library/Android/sdk
iOS / macOS:
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale cs-CZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Dušan - iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

</details>

**Comment by ioma8** [comment]
Okay what fixed it after two days of debugging and trying to update SDKs etc, was wiping the android emulator. I still do not know what was the problem, but wiping the virtual device fixed it. I am writing it for future people who would encounter the same issue.

**Comment by Kendru98** [comment]
Hi, I'm glad that issue was solved by itself. If you have another not known issues that look more that something is wrong with simulator or config, don't hesitate to join our discord and ask community & our moderators. https://discord.com/invite/ukBK5t4EZg
