### ISSUE TITLE
Test gets stuck on the splash screen

### ISSUE THREAD

**Issue by dannmf** [leancodepl/patrol#2289]
### Steps to reproduce

1. Run patrol test -t integration_test\login_test.dart 

### Actual results

• Building apk with entrypoint test_bundle.dart...
        You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

        You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

        You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

        You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

✓ Completed building apk with entrypoint test_bundle.dart (35.0s)
• Executing tests of apk with entrypoint test_bundle.dart on device RQ8N708ETKV...

### Logs

It doesn't return any logs; it just stays like this:
✓ Completed building apk with entrypoint test_bundle.dart (35.0s)
• Executing tests of apk with entrypoint test_bundle.dart on device RQ8N708ETKV...

### Patrol version

patrol: ^3.9.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Patrol doctor:
Patrol CLI version: 3.0.1
Flutter command: flutter 
  Flutter 3.22.2 • channel stable
Android:
• Program adb found in C:\Users\daniel.manoel\AppData\Local\Android\Sdk\platform-tools\adb.exe
• Env var $ANDROID_HOME set to C:\Users\daniel.manoel\AppData\Local\Android\Sdk -->
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
<!-- Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [versÆo 10.0.19045.4651], locale pt-BR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.85.0)
[√] VS Code, 64-bit edition (version 1.58.2)
[√] Connected device (4 available)
[√] Network resources -->
```

</details>

**Comment by zoskar** [comment]
Hello @dannmf 
Unfortunately without [additional information](https://stackoverflow.com/help/minimal-reproducible-example) we can't check if the problem is caused by  Patrol framework of somehow faulty Patrol setup / your application. 
If you can't provide it for any reason I recommend reaching out to [Patrol Discord community](https://discord.gg/ukBK5t4EZg). Maybe someone there will recognise this problem and will be able to help you.
