### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by hailuongsl97** [leancodepl/patrol#2301]
### Steps to reproduce

Hello everyone, please support for me!
The error below occurred after I ran this command: patrol test -t integration_test/example_test.dart.

### Actual results

Can't load Kernel binary: Invalid kernel binary format version.
FINE: Pub 3.4.4
FINE: Package Config up to date.
FINE: Package Config up to date.
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _checkJavaVersion.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:patrol_cli/src/compatibility_checker.dart:137:48)
#2      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#3      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#4      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#5      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#6      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#7      _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#8      _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#9      _LineSplitterSink.close (dart:convert/line_splitter.dart:141:11)
#10     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#11     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#12     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#13     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#14     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#15     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#16     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#17     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#18     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
#19     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#20     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#21     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#22     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:418:13)
#23     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:428:7)
#24     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:317:7)
#25     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#26     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#27     _StreamController.close (dart:async/stream_controller.dart:640:5)
#28     _Socket._onData (dart:io-patch/socket_patch.dart:2456:21)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297:7)
#32     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#33     _StreamController._add (dart:async/stream_controller.dart:658:7)
#34     _StreamController.add (dart:async/stream_controller.dart:606:5)
#35     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1943:35)
#36     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1372:18)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#40     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
IO  : Writing 10046 characters to text file /Users/hailuong018/.pub-cache/log/pub_log.txt.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

Patrol CLI version: 3.1.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```
Can't load Kernel binary: Invalid kernel binary format version.
FINE: Pub 3.4.4
FINE: Package Config up to date.
FINE: Package Config up to date.
Patrol doctor:
Patrol CLI version: 3.1.0
Flutter command: fvm flutter
  Flutter 3.24.0 • channel stable
Android: 
• Program adb found in /opt/local/bin/adb
• Env var $ANDROID_HOME set to /Users/hailuong018/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
```
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.2 23C64 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.3.6)
[✓] VS Code (version 1.92.1)
[✓] Connected device (5 available)
[✓] Network resources
</details>

**Comment by chiphan-quickcare** [comment]
I've the same problems

**Comment by chiphan-quickcare** [comment]
Also the native run in IOS got crash

**Comment by zoskar** [comment]
Hi @hailuongsl97 
Could you please try to do those couple of steps?

1. Please recheck if your Patrol version is `3.10.0` - I see that you use CLI `3.1.0` and this version only works with latest Patrol.
2. Try doing `dart pub global deactivate patrol_cli`, then `dart pub global activate patrol_cli`
3. Try good old `flutter clean`

If none of those steps will help you please let us know and we will investigate you problem further.

**Comment by hailuongsl97** [comment]
> Hi @hailuongsl97 Could you please try to do those couple of steps?
> 
> 1. Please recheck if your Patrol version is `3.10.0` - I see that you use CLI `3.1.0` and this version only works with latest Patrol.
> 2. Try doing `dart pub global deactivate patrol_cli`, then `dart pub global activate patrol_cli`
> 3. Try good old `flutter clean`
> 
> If none of those steps will help you please let us know and we will investigate you problem further.

![Screenshot 2024-08-13 at 08 32 59](https://github.com/user-attachments/assets/fccec713-be99-4241-b6da-d40dfa497ecc)

![Screenshot 2024-08-13 at 08 33 53](https://github.com/user-attachments/assets/bd2f0d3d-ce81-4f42-8b53-fc57043adf17)

I tried following the steps you guided me through, but it’s still not working

**Comment by zoskar** [comment]
Thank you for trying these steps @hailuongsl97 
Could you also provide output of your `flutter doctor --verbose`?

**Comment by hailuongsl97** [comment]
> Thank you for trying these steps @hailuongsl97 Could you also provide output of your `flutter doctor --verbose`?

![Screenshot 2024-08-15 at 09 17 16](https://github.com/user-attachments/assets/e5c93d9a-9d64-4d3f-b863-e5bbe7118b06)
@zoskar  this is my output
