### ISSUE TITLE
compileFlutterBuildDevDebug failing on integration_test/test_bundle.dart:63:7: Error: No named parameter with the name 'tags'.

### ISSUE THREAD

**Issue by lewismainanala** [leancodepl/patrol#2306]
### Steps to reproduce

1. Do a pub clean / Delete .pub-cache folder. -> So that you can patrol build afresh on step 2
2. Run patrol test command with inputs

### Actual results

Task :app:compileFlutterBuildDevDebug FAILED

integration_test/test_bundle.dart:63:7: Error: No named parameter with the name 'tags'.
	      tags: null,
	      ^^^^
	../../.pub-cache/hosted/pub.dev/patrol-3.5.1/lib/src/common.dart:160:16: Context: Found this candidate, but the arguments don't match.
	DartGroupEntry createDartTestGroup(
	               ^^^^^^^^^^^^^^^^^^^
	Target kernel_snapshot failed: Exception

### Logs

	: > Task :android_id:bundleLibCompileToJarDebug UP-TO-DATE
	: 
	: > Task :app:compileFlutterBuildDevDebug
	integration_test/test_bundle.dart:63:7: Error: No named parameter with the name 'tags'.
	      tags: null,
	      ^^^^
	../../.pub-cache/hosted/pub.dev/patrol-3.5.1/lib/src/common.dart:160:16: Context: Found this candidate, but the arguments don't match.
	DartGroupEntry createDartTestGroup(
	               ^^^^^^^^^^^^^^^^^^^
	Target kernel_snapshot failed: Exception
	
	: 
	: > Task :app:compileFlutterBuildDevDebug FAILED
	
	FAILURE: Build failed with an exception.
	
	* What went wrong:
	Execution failed for task ':app:compileFlutterBuildDevDebug'.
	> Process 'command '../flutter/bin/flutter'' finished with non-zero exit value 1
	
	* Try:
	> Run with --stacktrace option to get the stack trace.
	> Run with --info or --debug option to get more log output.
	> Run with --scan to get full insights.
	
	* Get more help at https://help.gradle.org
	
	BUILD FAILED in 9s

### Patrol version

patrol: ^3.5.1

### Patrol Doctor output

Patrol doctor:
Patrol CLI version: 3.1.0
Flutter command: flutter 
  Flutter 3.19.3 • channel stable
Android: 
• Program adb found in /Users/lewis/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/user/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

### Flutter Doctor output

[✓] Flutter (Channel stable, 3.19.3, on macOS 14.5 23F79 darwin-arm64, locale
    en-KE)
    • Flutter version 3.19.3 on channel stable at /Users/lewis/Workspace/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (5 months ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version
    35.0.0-rc2)
    • Android SDK at /Users/lewis/Library/Android/sdk
    • Platform android-34, build-tools 35.0.0-rc2
    • ANDROID_HOME = /Users/lewis/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 14.5
      23F79 darwin-arm64
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 127.0.6533.100
    ! Error: Lewy’s iPhone is not available because it is unpaired. Pair with
      the device in the Xcode Devices Window, and respond to any pairing prompts
      on the device. (code -29)
    ! Error: Browsing on the local area network for iPhone. Ensure the device is
      unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by jBorkowska** [comment]
Hi @lewismainanala ! You have incompatible version of cli and patrol package - if you want to use `patrol: 3.5.1`, then you need to use patrol_cli 3.0.1 or older

**Comment by jBorkowska** [comment]
Let me know if it helped

**Comment by lewismainanala** [comment]
@jBorkowska how do I force patrol_cli 3.0.1 ? dart pub global activate patrol_cli is always auto-resolving to patrol_cli 3.1.0 
```
Building package executables... (5.1s)
Built patrol_cli:main.
Installed executable patrol.
Activated patrol_cli 3.1.0.
```

Also did anything change from your end? This was working as expected at least by Last week (From My CI(Bitrise) where I need to flutter build everytime)

**Comment by jBorkowska** [comment]
Anyway, closing as resolved. Feel free to reopen or create new issue
