### ISSUE TITLE
IOS App does not got delete after a test 

### ISSUE THREAD

**Issue by chiphan-quickcare** [leancodepl/patrol#2311]
### Steps to reproduce

Run with command `patrol test -d 'iPhone 15 Pro Max' --verbose -t $(TEST_FILES)`

### Actual results

The app doesn't get delete after each test

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

3.9.0

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.1.0
Flutter command: flutter 
  Flutter 3.22.2 • channel stable
Android: 
• Program adb found in /opt/homebrew/bin/adb
• Env var $ANDROID_HOME set to /Users/kyohuu/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-VN)
[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc4)
    ! Some Android licenses not accepted. To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.4)
[✓] IntelliJ IDEA Community Edition (version 2024.1.4)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for Nang’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

! Doctor found issues in 1 category.
```

</details>

**Comment by jBorkowska** [comment]
Hi @chiphan-quickcare, patrol doesn't delete the app between test runs. If you need to clear the app's data between runs on iOS, you have to do it by yourself - there is no API on iOS side that we can use to do it automatically.

Let me know if you have any other questions or check out our Discord server: https://discord.gg/ukBK5t4EZg

**Comment by chiphan-quickcare** [comment]
Thanks for the response @jBorkowska, but it the test does uninstall the app in the android run after each test?
