### ISSUE TITLE
Patrol Reports or Logging

### ISSUE THREAD

**Issue by MacaulayKoontz** [leancodepl/patrol#2315]
### Use case

I am writing patrol tests to walk through specific scenarios. I have expect statements throughout the test. I notice when the test fails it generates an HTML file for me to examine. But can it do the same with my log statements and also show the HTML report? Is there a patrol print? How would I use it?

### Proposal

Is there any guidance or something down the pipeline that you could provide me to help me log my tests better?

**Comment by Kendru98** [comment]
Hi, for now there is not logging for each patrol command in tests. You can always use prints in test if you want, for example with prefix patrol `print("patrol_TapLogginButton")`. Then you can collect them to some file.

**Comment by Kendru98** [comment]
I think that this issue is related to your proposal: https://github.com/leancodepl/patrol/issues/2287

**Comment by ahlstro** [comment]
What is your goal with the logging? If it is to pinpoint an error in the test, patrol develop + debugging will help you best.
If you want to see where the test fails it says so in the terminal (where in the code the test failed)

If you integrate firebase test labs you can get a video and see where it fails, but thats the same as patrol develop and debugging imo.

**Comment by Kendru98** [comment]
Please track https://github.com/leancodepl/patrol/issues/2287. For now, I will close this issue, if you have more questions don't hesitate to ask on our discord https://discord.com/invite/ukBK5t4EZg.
