### ISSUE TITLE
After the test completes, patrol-CLI does not terminate, causing Firebase Test Lab to fail

### ISSUE THREAD

**Issue by sherrylin728** [leancodepl/patrol#2326]
### Steps to reproduce

I previously noticed that WidgetsFlutterBinding.ensureInitialized(); might be causing the issue. However, even after commenting it out, the test still gets stuck on the final screen and does not properly terminate the patrol test. This problem is very frustrating because it also causes issues with Firebase Test Lab runs.

### Actual results

![Screenshot 2024-09-03 at 10 51 34 AM](https://github.com/user-attachments/assets/27c74289-aaca-47ad-bb93-465bf2b875bf)
![Screenshot 2024-09-03 at 11 38 19 AM](https://github.com/user-attachments/assets/c80b5c47-a4d4-4a14-9b25-5e905a0c1aca)

### Logs

<details>
<summary>Logs</summary>

```
 
[logcat.txt](https://github.com/user-attachments/files/16843767/logcat.txt)

```

</details>

### Patrol version

patrol ^3.6.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol doctor:
Patrol CLI version: 3.0.1
Flutter command: flutter 
  Flutter 3.16.5 • channel stable
Android: 
• Program adb found in /Users/linyunxuan/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/linyunxuan/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /opt/homebrew/bin/ideviceinstaller

```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.5 23F79 darwin-arm64, locale en-TW)
    • Flutter version 3.16.5 on channel stable at /Users/linyunxuan/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (9 months ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/linyunxuan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/linyunxuan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    ✗ Unable to get list of installed Simulator runtimes.
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.92.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter


```

</details>

**Comment by zoskar** [comment]
Hi @sherrylin728 
Thanks for sharing your logs. Based on the information included, I recommend updating Patrol/Patrol CLI to the latest version and checking if that resolves the issue. If the problem persists, it would be helpful if you could provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). This will help us determine whether the issue is related to Patrol or something specific to your local setup.

If you're unable to share your code publicly, you can also post your issue in our [Discord channel](https://discord.gg/ukBK5t4EZg), so the community will get a chance to help you.
