### ISSUE TITLE
Documentation or example on testing Biometrics with Patrol

### ISSUE THREAD

**Issue by cheuk0324** [leancodepl/patrol#2328]
### Use case

I am trying to add integration test for my app to login with faceID or password on both android and iOS. I was reading this issue https://github.com/leancodepl/patrol/issues?q=is%3Aissue+Biometrics+is%3Aclosed but it seems it is closed but it does not have a solution or couldnt find any documentation on that. So I am creating this issue/request to see if there is any working example.

### Proposal

Biometric login with face id and password enter after unsuccessful with face id

**Comment by zoskar** [comment]
Hi @cheuk0324 
Unfortunately Patrol does not provide any methods to work with faceID right now. If the discussion under the issue you linked was not helpful you can ask community on our [Discord channel](https://discord.gg/ukBK5t4EZg) how they handle such cases.

You can also add some more details to this issue, then we could treat it as a feature request.

**Comment by bartekpacia** [comment]
see also #7
