### ISSUE TITLE
Display a nice tests summary

### ISSUE THREAD

**Issue by pdenert** [leancodepl/patrol#2333]
At the end of execution, there should be a summary: 

- [x] how long the execution took, 
- [x] number of passed, failed and skipped tests, 
- [x] link to native report, 
- [x] paths to files with failed tests

**Comment by mateuszwojtczak** [comment]
@pdenert please update the title and the description 😅

**Comment by pdenert** [comment]
- [ ] Manage android report path on app with flavors
