### ISSUE TITLE
Support for Testing Background Notifications in Terminated State (Cross-Platform: Android & iOS)

### ISSUE THREAD

**Issue by valtbarbos** [leancodepl/patrol#2382]
### Use case

I'm currently developing a mobile app that requires handling notifications when the app is in a terminated state on both iOS and Android platforms. The core functionality involves receiving critical notifications that should trigger app behavior (such as opening a specific feature or action) even when the app has been manually closed or terminated by the OS.

For Android, I am using Firebase Cloud Messaging (FCM), and for iOS, I'm working with VoIP notifications via PushKit. I want to ensure that my tests cover these real-world scenarios where users may manually terminate the app. To address this, I'm integrating testing through Firebase TestLab, which supports Espresso, UI Automator (Android), XCTest, and Robo Test (iOS). However, I’m struggling with the following scenario:

    Installing the app
    Terminating the app
    Validating notification reception in this state
    Interacting with the notification and launching the app from terminated state
    Continuing app execution based on the notification interaction

I haven't found clear guidelines or examples on how to fully automate tests for handling notifications in the terminated state. I need to replicate manual app termination, validate that the app responds correctly when reopened via a notification, and then continue interacting with the app as expected—all within the same test sequence.

This is especially critical because users often terminate apps, and important notifications (like those requiring immediate user action) still need to function properly.

### Proposal

I would love to contribute by developing these tests, but I need some guidance or resources to better understand how to:

    Use Espresso and UI Automator to simulate app termination, handle system-level notification validation, and resume app execution on Android.
    Use XCTest for iOS to achieve similar results—terminating the app, testing notification handling, and then continuing app functionality based on the notification interaction.

If anyone has experience or insights on how to approach this type of testing, particularly using Firebase TestLab and these testing frameworks, your help would be greatly appreciated.

Thank you for considering this feature request and for your time!

**Comment by zoskar** [comment]
Hi @valtbarbos! 
Right now, there’s no way to kill the app. We’re have an [issue](https://github.com/leancodepl/patrol/issues/1787) for this feature which you can track. Unfortunately, it would require a lot of rework on Patrol.
