### ISSUE TITLE
[patrol_finders] enterText() only works the first time

### ISSUE THREAD

**Issue by josh-burton** [leancodepl/patrol#2395]
### Steps to reproduce

Write a widget test where 2 different texts fields have text entered.

### Actual results

patrol_finders can only input text into a text field once.

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. Do not remove the backticks! -->
```

</details>

### Patrol version

patrol_finders: 2.1.3

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>
</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>
</details>

**Comment by josh-burton** [comment]
It seems this is caused by this recent PR: https://github.com/leancodepl/patrol/pull/2314

Unregistering the testTextInput means any further interaction with text fields won't work.

It seems like the registering of the testTextInput is probably the root cause here, as the default widget tester doesn't do this and doesn't demonstrate the issue.

**Comment by josh-burton** [comment]
Related issue: https://github.com/leancodepl/patrol/issues/2313

**Comment by Kendru98** [comment]
Thanks for reporting issue @josh-burton we will look into it!

**Comment by piotruela** [comment]
Hi @josh-burton. Can you please provide reproducible example of a test in which it does not work? I think more factors need to come into play than just typing into the text field twice for this error to occur.

**Comment by GChanathip** [comment]
@piotruela you can reproduce by using this repo
` git clone https://github.com/GChanathip/patrol_example.git --branch patrol-issue `

This repo using Patrol 3.130 and Patrol cli 3.4.0

use this command to reproduce 
`patrol test --target integration_test/search_product_test.dart`

i'm not sure about the root cause, but it's seem relate with this PR https://github.com/leancodepl/patrol/pull/2314

**Comment by feiwhang** [comment]
I faced this when trying to enterText on the field that is autofocus. When I disable autofocus the issue is gone.

**Comment by Kendru98** [comment]
Issue still exists in one of my projects. Will create new issue with some reproducible steps in free time, because I assume that my case can be more complex.
