### ISSUE TITLE
Allow user to disable Patrol Logging

### ISSUE THREAD

**Issue by philipmjohnson** [leancodepl/patrol#2405]
### Use case

After updating to the latest version, by testing output now has hundreds of lines of patrol logging output.

### Proposal

Logging output can be helpful, but it can also be a distraction. One approach is to provide an option to PatrolTesterConfig that allows the user to enable or disable logging output (or even control the level of output).

**Comment by pdenert** [comment]
@philipmjohnson thanks for your suggestion. New version with that feature has just been released: https://pub.dev/packages/patrol_finders/changelog#230 by default we set printing to false.
