### ISSUE TITLE
Attaching Debugger to Dart VM Service fails (VSCODE)

### ISSUE THREAD

**Issue by FritzMatthaeus** [leancodepl/patrol#2454]
### Steps to reproduce

The Setup is a an Android 34 Emulator on MacOS 15.1.1 with VSCODE:

1. Clone the patrol-basics-tutorial and run ``flutter pub get``. If not merged yet, apply the fixes in this [Pull Request](https://github.com/ResoCoder/patrol-basics-tutorial/pull/1) as the example is broken for Android 34.
2. Add the recommended debugger launch config: 
```json
    {
      "name": "attach debugger to patrol",
      "request": "attach",
      "type": "dart",
      "cwd": "integration_test",
      "vmServiceUri": "${command:dart.promptForVmService}"
    }
```
4. Run in it develop mode ``patrol develop --target integration_test/app_test.dart --device=emulator-5554``
5. Copy the Dart VM Service Link from the Terminal: ``The Dart VM service is listening on http://127.0.0.1:41121/HIqQe_P_JZM=/``
6. Run the "attach debugger to patrol" command and enter the link
7. The Debugging Console will show an error

The error could be reproduced in other projects. But still the same Setup

### Actual results

nothing happens. The Debugging Console shows the following error:

``
Failed to start DDS for http://127.0.0.1:41121/HIqQe_P_JZM=/
DartDevelopmentServiceException: WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 52392
#0      DartDevelopmentServiceImpl.startService (package:dds/src/dds_impl.dart:87:7)
<asynchronous suspension>
#1      DartDevelopmentService.startDartDevelopmentService (package:dds/dds.dart:97:5)
<asynchronous suspension>
#2      DartDebugAdapter._startOrReuseDds (package:dds/src/dap/adapters/dart.dart:654:19)
<asynchronous suspension>
#3      DartDebugAdapter._connectDebuggerImpl (package:dds/src/dap/adapters/dart.dart:684:25)
<asynchronous suspension>
#4      DartDebugAdapter.connectDebugger (package:dds/src/dap/adapters/dart.dart:632:7)
<asynchronous suspension>

Exited.
``

### Logs

<details>
<summary>Logs</summary>

```
• Building apk with entrypoint test_bundle.dart...
✓ Completed building apk with entrypoint test_bundle.dart (12.3s)
• Executing tests of apk with entrypoint test_bundle.dart on emulator-5554...
Hot Restart: logs connected
[WARN] Hot Restart: not attached to the app yet
        The Dart VM service is listening on http://127.0.0.1:41121/HIqQe_P_JZM=/
        Patrol (native): NativeAutomatorClient created, port: 8081
        Patrol (native): initialize() started
        Patrol (native): initialize() succeeded
        PatrolBinding: Register Patrol service extensions
        Patrol (native): NativeAutomatorClient created, port: 8081
        Patrol (native): NativeAutomatorClient created, port: 8081
        00:00 +0: app_test signs in, triggers a notification, and taps on it
        Patrol (native): configure() started
        Patrol (native): configure() succeeded
🧪 signs in, triggers a notification, and taps on it
        ✅   1. enterText widgets with key [<'emailTextField'>].
        ✅   2. enterText widgets with key [<'passwordTextField'>].
        ⏳   3. tap widgets with key [<'signInButton'>].
        ✅   3. tap widgets with key [<'signInButton'>].
        ⏳   4. isPermissionDialogVisible (native)
        Patrol (native): isPermissionDialogVisible() succeeded
        ✅   4. isPermissionDialogVisible (native)
        ⏳   5. grantPermissionWhenInUse (native)
Hot Restart: attached to the app (press "r" to restart)
Patrol DevTools extension is available at http://127.0.0.1:9104/patrol_ext?uri=http://127.0.0.1:52263/F2-CH29gR1k=/
        ✅   5. grantPermissionWhenInUse (native)
        ⏳   6. tap widgets with key [<'notificationIcon'>].
        ✅   6. tap widgets with key [<'notificationIcon'>].
        ⏳   7. pressHome (native)
        ✅   7. pressHome (native)
        ⏳   8. openNotifications (native)
        Patrol (native): openNotifications() started
        Patrol (native): openNotifications() succeeded
        ✅   8. openNotifications (native)
        ⏳   9. tapOnNotificationBySelector (native)
        ✅   9. tapOnNotificationBySelector (native)
        ⏳  10. waitUntilVisible widgets with key [<'successSnackbar'>].
        ✅  11. waitUntilVisible widgets with key [<'successSnackbar'>].
        00:18 +1: All tests passed!
✓ App shut down on request (313.6s)
```

</details>

### Patrol version

patrol: 3.13.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
Patrol CLI version: 3.4.1
Flutter command: flutter 
  Flutter 3.24.4 • channel stable
Android: 
• Program adb found in /Users/fritz/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME set to /Users/fritz/Library/Android/sdk
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller found in /usr/local/bin/ideviceinstaller
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.4, on macOS 15.1.1 24B91 darwin-x64, locale de)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.94.2)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by jBorkowska** [comment]
Hi @FritzMatthaeus , you are using wrong link to vm service. The one you should use is part of green dev tools link:
`Patrol DevTools extension is available at http://127.0.0.1:9104/patrol_ext?uri=http://127.0.0.1:52263/F2-CH29gR1k=/`
So `http://127.0.0.1:52263/F2-CH29gR1k=/` is the right link

**Comment by jBorkowska** [comment]
I see that the instruction in our docs is incorrect, we'll fix it. Thanks for reporting :)

**Comment by FritzMatthaeus** [comment]
Great, thank you very much for your help. Issue solved
