### ISSUE TITLE
Add methods to enable and disable Location on Android

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#283]
This is already achievable by `$.native.tap()`, but is a bit, lengthy, and **device-dependent**.

We'd like to have a more high-level API (like we already have for Wi-Fi, Celluar, and Dark mode).

We want to get from this:

```dart
void main() {
  patrolTest(
    'toggles location',
    nativeAutomation: true,
    ($) async {
      await $.native.openQuickSettings();
      await $.native.tap(const Selector(text: 'Location'));
      await $.native.tap(const Selector(text: 'Location'));
      await $.native.pressBack();
    },
  );
}
```

to this:
```dart
void main() {
  patrolTest(
    'toggles location',
    nativeAutomation: true,
    ($) async {
      await $.native.enableLocation();
      await $.native.disableLocation();
    },
  );
}
```

### Siblings of this issue

- #282
- #326
- #1359

**Comment by apalala-dev** [comment]
Workaround mentioned didn't work for me since I don't have anything written on MIUI. I only have an icon, and depending on the device it might even be hidden (since Quick Settings can be edited).

Patrol could maybe open the Location settings screen which would be more easily accessible with text than the Quick Settings ?

**Comment by bartekpacia** [comment]
@apalala-dev You can open the Settings app yourself. It's not possible to solve this in a generic way since the system apps differ across OEMs and Android versions.


```dart
void main() {
  patrolTest(
    'toggles location',
    nativeAutomation: true,
    ($) async {
      await patrol.openApp('com.android.settings');
      await patrol.tap(const Selector(text: 'Location')); // or whatever text your Settings app has
    },
  );
}
```

**Comment by apalala-dev** [comment]
It is possible to open the location settings screen programmatically on the Android side (from my tests):
``` kotlin
val callGPSSettingIntent = Intent(Settings.ACTION_LOCATION_SOURCE_SETTINGS)
activity!!.startActivity(callGPSSettingIntent)
```
On iOS, something similar seems to be doable from what I read on [stackoverflow](https://stackoverflow.com/a/61383270/3545278) but I didn't test it.

If it is possible on both side, it might be a good idea to provide it directly from patrol, similarly to `$.native.openQuickSettings()`.
