### ISSUE TITLE
Add option for defining desired device capabilities

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#31]
What if the user wants to run tests on all Android devices?
What if the user wants to run tests on all devices that can be called "a tablet"?

Appium has [this kind of device capabilities](https://appium.io/docs/en/writing-running-appium/caps/) definition, maybe we want to do something like that, obviously in a simplified form (especially in the beginning)

AC: user can select any device with Android version 12

**Comment by bartekpacia** [comment]
Not relevant now.

We might take a fresh look at this features in a few months.
