### ISSUE TITLE
Toggle Wi-Fi on iOS

### ISSUE THREAD

**Issue by mateuszwojtczak** [leancodepl/patrol#322]

**Comment by edgarfroes** [comment]
Is this even possible? I can't see how one can interact with an iPhone's native platform, in both a Simulator or a physical device.

**Comment by bartekpacia** [comment]
@edgarfroes It wasn't possible – until Patrol :) We're using Apple's `XCTest` framework under the hood, which can interact with the native UI.

I'll implement this in the next few days.
