### ISSUE TITLE
How can i migrate into this framework

### ISSUE THREAD

**Issue by akramcshive** [leancodepl/patrol#334]
How can i migrate our current integration tests library into patrol, does it require any changes in the integration tests framework. Can you please help/suggest?

**Comment by bartekpacia** [comment]
Hi @akramcshive!

We've got some resources to help you with this task. Please see [the documentation website](https://patrol.leancode.co). We've also got [an example app](https://github.com/leancodepl/patrol/tree/master/packages/patrol/example) which demonstrates most of Patrol's features - I highly recommend you also take a look at it, maybe even clone the repo and run the example app on your machine so you can see how Patrol works :)

If you're having problems with migrating some integration tests to use Patrol, you can also post the `.dart` file here and I'll try to help you out :)
