### ISSUE TITLE
Simulate Internet connectivity issues

### ISSUE THREAD

**Issue by edgarfroes** [leancodepl/patrol#341]
Add the ability to simulate internet connectivity issues like low connection speed or no connection at all.

An idea that comes to mind is to use some kind of wrapper around the app that blocks/delays all HTTP requests to simulate internet connectivity issues. Is there a Flutter native way to capture and block HTTP requests in Flutter? If not, is there any native way to do it?

**Comment by bartekpacia** [comment]
Hi @edgarfroes! Thanks for creating the issue.

This would indeed be a very useful feature.

**Comment by iasiu** [comment]
@edgarfroes for now for ios simulator check out https://nshipster.com/network-link-conditioner/

**Comment by bartekpacia** [comment]
And for the Android emulator, check out [this question on StackOverflow ](https://stackoverflow.com/a/7026341/7009800). The emulator has a built-in feature of simulating different types of connection quality. It's not perfect but it's a fair workaround.
