### ISSUE TITLE
Add changing font size/scale in device settings

### ISSUE THREAD

**Issue by edgarfroes** [leancodepl/patrol#342]
Add the ability to change the device font sizing during tests. This feature should make it possible to change the device's font size just like we would when accessing the device's accessibility options.

This feature is extremely useful to detect bugs in the UI when the app has smaller or bigger fonts.

If it's not possible to do it using native functionalities, then maybe we can take a look if it's possible to change [Flutter's textScale](https://api.flutter.dev/flutter/widgets/Text/textScaleFactor.html) when running tests.

**Comment by bartekpacia** [comment]
Thanks for requesting this feature – very useful!
