### ISSUE TITLE
Add basic navigation for VoiceOver and TalkBack

### ISSUE THREAD

**Issue by edgarfroes** [leancodepl/patrol#343]
Add the ability to toggle screen readers, while also being able to perform screen reader actions like:

- Swipe left and right to navigate through semantic nodes;
- Swipe up and down to navigate through heading semantic nodes;
- Double tap to activate buttons, links, or anything with semantics' [onTap](https://api.flutter.dev/flutter/semantics/SemanticsProperties/onTap.html) callback;
- Being able to know which semantic node is being currently focused on by the screen reader.

**Comment by bartekpacia** [comment]
Thanks @edgarfroes!
