### ISSUE TITLE
Add file managing capability

### ISSUE THREAD

**Issue by edgarfroes** [leancodepl/patrol#344]
Add the ability to download and manage files in the native OS.

Usage: test if the app is downloading a specific file properly by ensuring that it's stored in the device's file system. We can go one step further and ensure that the downloaded file is the one we expected by analyzing if the file properly opens, checking the file size, and validating the content within the file

**Comment by bartekpacia** [comment]
Hi @edgarfroes! Thanks for creating another issue, we really appreciate that.

I'd risk a statement that this is already possible (though cumbersome) using `$.native.tap()`. Off the top of my head, you could try opening, for example, [Google's Files](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files&hl=en&gl=US) app:

```dart
void main() {
  // https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files
  final filesAppId = 'com.google.android.apps.nbu.files';
  
  patrolTest(
    'counter state is the same after going to Home and switching apps',
    nativeAutomation: true,
    ($) async {
      await $.pumpWidgetAndSettle(ExampleApp());
      
      await $.native.pressHome();
      await $.native.openApp(appId: filesAppId);
      await $.native.tap(Selector(text:"Local storage")); // tap on visible text
      await $.native.tap(Selector(textContains: "App data"));

      // and so on
    },
  );
}
```

**Comment by edgarfroes** [comment]
Awesome, I'll do my best to see if I can invest some time learning how Patrol works under the hood and open some PRs, but I can't commit to anything now.

**Comment by bartekpacia** [comment]
Related: example file picker screen test in #514
