### ISSUE TITLE
Ability to run in profile / release mode

### ISSUE THREAD

**Issue by borjandev** [leancodepl/patrol#346]
Hi! Thank you for the package!

I would like to run the test suite via Patrol in profile / release mode on a connected physical device, 

Is there currently a way to do this via the CLI?

**Comment by bartekpacia** [comment]
Hi @borjandev!

Currently there's no such possibility, but if you feel like hacking a bit, you can [edit these lines in the FlutterDriver class](https://github.com/leancodepl/patrol/blob/master/packages/patrol_cli/lib/src/features/drive/flutter_driver.dart#L162-L180) to add the options you need. After making the changed, you need to recompile `patrol_cli` with `dart pub global activate --source path .`. Let me know how it went!

This is definitely a useful feature and should be cheap to do. Thanks for creating the issue!

**Comment by bartekpacia** [comment]
@borjandev I'm curios, what's your use case of running integration tests in profile or release mode?

**Comment by borjandev** [comment]
@bartekpacia It’s mainly for benchmarking performance, as well as identifying regressions across different flutter channels like master / stable 

https://docs.flutter.dev/cookbook/testing/integration/profiling

In the official example above they run the test in profile mode to get a rather accurate benchmark

```
flutter drive \
  --driver=test_driver/perf_driver.dart \
  --target=integration_test/scrolling_test.dart \
  --profile
```

Release mode would be even better, as before actually releasing the app, running all of the integration tests on real target devices would increase confidence dramatically on the performance that can be expected, especially with the new Impeller rendering backend which only runs on real devices as of this moment as far as I am aware

**Comment by bartekpacia** [comment]
Running in release mode is possible now with the `--release` flag.

We don't have any plans to add support for `--profile` as of nos.
