### ISSUE TITLE
Undefined name `Patrol`

### ISSUE THREAD

**Issue by iamnijat** [leancodepl/patrol#347]
<img width="761" alt="Screen Shot 2022-09-23 at 10 50 10" src="https://user-images.githubusercontent.com/42466886/191907765-2ed631b2-1ae7-4205-aa9a-f28bceca0ed6.png">

Even though I added dependency correctly, it is unable to find the Patrol class inside the dependencies. The correct implementation is shown in this link: https://pub.dev/packages/patrol

**Comment by bartekpacia** [comment]
Hi @iamnijat! The `Patrol` class has been renamed to `NativeAutomator`.  Let us know if this solves your problems.

Sorry for the problems, we'll try to better communicate breaking changes in the future.

**Comment by iamnijat** [comment]
Thanks for your attention, I know it is not a stable version yet, but I had a chance to try it today. To be honest, it looks efficient tool at first glance, Keep it up guys 👍

**Comment by bartekpacia** [comment]
Thanks a lot! If you encounter any more problems or have questions, don't hesitate do create Issues/Discussions :)
