### ISSUE TITLE
Cannot `patrol drive` on devices with iOS older than 15.5

### ISSUE THREAD

**Issue by borjandev** [leancodepl/patrol#381]
When trying to run it on iOS 12.6.5 it produced an error message like the one below: 

The run destination is not valid for Testing the scheme 'AutomatorServer'.
iOS 12.5.6 doesn’t match AutomatorServer.app’s iOS 15.5 deployment target. Upgrade the iOS version or lower AutomatorServer.app’s deployment target.

The maximum iOS version that this iPhone (5s) can install is 12.6.5 so updating is not an option

The flutter app that I am trying to test, runs properly on it

**Comment by bartekpacia** [comment]
Hi @borjandev.

Yeah, the minimum version is way to low. We'll relax it soon.

As a workaround, you can run:

```
$ patrol --version
patrol_cli v0.6.8
```

and then:

```
open ~/.cache/patrol/ios-0.6.8/AutomatorServer.xcodeproj
``` 

and use Xcode to manually lower the minimum iOS deployment target. I'm not sure if something as old as 12.6.5 will work properly, but you can always try :)

**Comment by bartekpacia** [comment]
Patrol (the new `patrol test` command) works on iOS 13+.
