### ISSUE TITLE
Patrol CLI | After successful update from 0.6.11 → 0.6.12 no active package patrol_cli

### ISSUE THREAD

**Issue by lmlikota** [leancodepl/patrol#422]
## Prerequisites
1. Windows 11 x64
2. Patrol CLI 0.6.11
3. VSCode 

## Steps to reproduce
1. User is running update from terminal inside VSCode from the root of Flutter project using `patrol update` 
2. There is success message in CLI aka terminal window:
`✓ Updated patrol_cli to version 0.6.12 (11.0s)`

**but there is also error message** 👇 

```
The system cannot find the batch label specified - error
No active package patrol_cli.
```
3. If you write command `patrol` there is error message `No active package patrol_cli.`

## Screenshot
![image](https://user-images.githubusercontent.com/10289319/194577014-05dd8dab-ab56-4fb3-a5cb-fc51fb9771b5.png)

**Comment by lmlikota** [comment]
`PS C:\Users\lmlikota\haven-bridge-mobile> patrol drive --flavor development .\integration_test\patrollogin.dart
No active package patrol_cli.`

I have tried to activate `patrol_cli` manually and it didn't help 😞 

```
PS C:\Users\lmlikota\haven-bridge-mobile> dart pub global activate patrol_cli
Resolving dependencies...
+ _fe_analyzer_shared 49.0.0
+ adb 0.2.1+2
+ analyzer 5.1.0`
+ ansi_styles 0.3.2+1
+ archive 3.3.1
+ args 2.3.1
+ async 2.9.0
+ boolean_selector 2.1.0
+ collection 1.16.0
+ convert 3.0.2
+ coverage 1.6.1
+ crypto 3.0.2
+ dispose_scope 2.0.0
+ file 6.1.4
+ freezed_annotation 2.1.0
+ frontend_server_client 3.0.0
+ glob 2.1.0
+ http 0.13.5
+ http_multi_server 3.2.1
+ http_parser 4.0.1
+ shelf 1.4.0
+ shelf_packages_handler 3.0.1
+ shelf_static 1.1.1
+ shelf_web_socket 1.0.2
+ source_map_stack_trace 2.1.0
+ source_maps 0.10.10
+ source_span 1.9.1
+ stack_trace 1.10.0
+ stream_channel 2.1.1
+ string_scanner 1.1.1
+ term_glyph 1.2.1
+ test 1.21.6
+ test_api 0.4.14
+ test_core 0.4.18
+ typed_data 1.3.1
+ vm_service 9.4.0
+ watcher 1.0.1
+ web_socket_channel 2.2.0
+ webkit_inspection_protocol 1.2.0
+ yaml 3.1.1
Building package executables...
Built patrol_cli:main.
Installed executable patrol.
Activated patrol_cli 0.6.12.

PS C:\Users\lmlikota\haven-bridge-mobile> patrol
No active package patrol_cli.
```

**Comment by bartekpacia** [comment]
Thanks for raising the issue @lmlikota!

This looks like a problem with `pub`, though I've no idea what might be the cause.

Try to reinstall:

```
dart pub global deactivate patrol_cli
```

```
dart pub global activate patrol_cli
```

Try also removing `pub`'s cache directory:

```
rmdir %USERPROFILE%\AppData\Local\Pub\Cache
```

(or something like this, I'm not a Windows user and don't know its commands).

**Comment by lmlikota** [comment]
Confirming that deleting ` %USERPROFILE%\AppData\Local\Pub\Cache` resolved the issue. Thanks.
