### ISSUE TITLE
Unable to interact with native for permissions 

### ISSUE THREAD

**Issue by Choups2** [leancodepl/patrol#423]
Hello,

I'm having trouble interacting with iOS native permissions views and I don't understand why.

Here is a video:
https://user-images.githubusercontent.com/27292031/194582243-a94f35ad-2288-4b81-a6e8-5c9171c8b9a2.mov

As you can see, everything is fine with the app but nothing seems to happen with native.
Everything is going well according to the logs though. The test fails when it can't find the next element.
```
Patrol: denyPermission() started
Patrol: denyPermission() succeeded

TimeoutException after 0:00:10.000000: Finder zero widgets with text "Autorisez-nous à vous guider"
```

Here is my test:
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:invictus/main.dart';
import 'package:patrol/patrol.dart';

import 'config.dart';

Future<void> processOnBoarding(PatrolTester $) async {
  await $('Bienvenue sur SNCF Connect').waitUntilVisible();
  await $('Découvrir').tap();

  // Notifications access
  await $('L\'information au bon moment').waitUntilVisible();
  await $('Suivant').tap();
  await $.pump(const Duration(seconds: 2));
  await $.native.denyPermission();
  await $.pump(const Duration(seconds: 2));

  // Position access
  await $('Autorisez-nous à vous guider').waitUntilVisible();
  await $('Suivant').tap();
  await $.native.denyPermission();

  await $('Plus tard').tap(); // Skip connection
  await $('Ignorer').tap(); // Skip tutorial
}

void main() {
  patrolTest('app does launch', config: patrolConfig, nativeAutomation: true, ($) async {
    await launchApp();

    await processOnBoarding($);

    // Should be home
    expect($('Une destination, une demande...'), findsOneWidget);
  });
}
```

Maybe I'm missing something. But I can't manage to see what's wrong.

Thank you

**Comment by bartekpacia** [comment]
Hi @Choups2,

I see on your video that the language of your Simulator is not English. Unfortunately, we only support English at the moment – this is because there's no other way to find and tap on the buttons in the native permission dialog on iOS. That's why we have to find the button by text, and English is by far more popular.

We'd like to fix this and we're very open to suggestions and contributions :)

Sorry for the problem :(

**Comment by bartekpacia** [comment]
Try this workaround:

```dart
await $.native.tap(Selector(text: 'Refuser')); // or 'Autoriser' ;)
```

**Comment by Choups2** [comment]
Thank you. It makes sense now.
I already tested with a tap on Selector, without success... Same behaviour

**Comment by bartekpacia** [comment]
That's strange...

I've just released `patrol_cli` v0.6.13 which should print more info about errors like this. Please try updating and let me know how it went, what's the error etc.

**Comment by bartekpacia** [comment]
I suspect that the problem might be that `denyPermission()` gets called before the dialog shows up. The time difference between `denyPermission()` and the dialog showing up might be invisible to our human eye, but it's there.

I've drafted issue #409 which describes how we could fix this problem.

PS:

What are these `pump()`s for?

```dart
await $.pump(const Duration(seconds: 2));
await $.native.denyPermission();
await $.pump(const Duration(seconds: 2));
```

**Comment by Choups2** [comment]
These `pump()`s are me trying to delay `denyPermission()` and making sure it is called after the dialog shows up. But now that I'm reading the doc I realize I should be using `pumpAndSettle()`

**Comment by bartekpacia** [comment]
Let me know if calling `pumpAndSettle()` fixed your problem.

**Comment by Choups2** [comment]
Here's what I get
```
Patrol: tap() started
Patrol: tap() failed
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: tap() failed with code INTERNAL (Invalid state: view with text "Refuser" in
app "com.vsc.mobilehorairesetresa" doesn't exist)
When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:119:7)
<asynchronous suspension>
#1      NativeAutomator.tap (package:patrol/src/native/native_automator.dart:352:5)
<asynchronous suspension>
#2      processOnBoarding (file:///Users/alexis_choupault/Projects/invictus-root/invictus-mobile/integration_test/app_test.dart:16:3)
<asynchronous suspension>
#3      main.<anonymous closure> (file:///Users/alexis_choupault/Projects/invictus-root/invictus-mobile/integration_test/app_test.dart:34:5)
<asynchronous suspension>
#4      patrolTest.<anonymous closure> (package:patrol/src/custom_finders/common.dart:58:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:833:5)
<asynchronous suspension>
The test description was:
  app does launch
════════════════════════════════════════════════════════════════════════════════════════════════════
00:12 +0: app does launch [E]
  'package:flutter_test/src/binding.dart': Failed assertion: line 802 pos 14: '_pendingExceptionDetails != null': A test overrode FlutterError.onError but either failed to return it to its original state, or had unexpected additional errors that it could not handle. Typically, this is caused by using expect() before restoring FlutterError.onError.
  dart:core-patch/errors_patch.dart 51:61       _AssertionError._doThrowNew
00:12 +0 -1: (tearDownAll)
Warning: integration_test plugin was not detected.
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:
https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
00:12 +1 -1: Some tests failed.
Failed to stop app
flutter_driver exited with code 0
```

**Comment by AlexisDeslandes** [comment]
Hello, i have a similar issue with login.
I use the package flutter_appauth which work with a webview to authenticate.
I have to fill a web form to log, enterText works with the username but not for the password.
There is a placeholder with the word: Password

I tried 2 ways to do:
await $.native.enterText(Selector(text: 'Password'), text: '***');
await $.native.enterTextByIndex('***', index: 1);

Got: Patrol action failed: enterText() failed with code NOT_FOUND
And the second one says that index 1 doesn't exists.

Here is the capture of the inspector:
![Capture d’écran 2022-10-10 à 15 04 12](https://user-images.githubusercontent.com/22497285/194872777-fd2b8daa-80b9-4426-aefd-964673aa439d.png)

Would you have a solution?

**Comment by bartekpacia** [comment]
Hi @AlexisDeslandes 👋

A common cause is that the keyboard (which is shown after tapping on the first – email - text field) obscures the second text field. Please try doing `await $.native.pressBack()` to hide the keyboard.

Let me know if this helps!

**Comment by AlexisDeslandes** [comment]
@bartekpacia Yes I already done this using the 'Done' button of the keyboard. 
So the password field is clearly visible.

**Comment by bartekpacia** [comment]
Okay, thanks.

Try using `Selector(textContains: 'Password')` or `Selector(contentDescriptionContains: 'Password')`.

Please also [make a view hierarchy dump](https://patrol.leancode.co/tips-and-tricks#android) of your login screen and share it here.

**Comment by AlexisDeslandes** [comment]
Thanks for your response.
I tried with your contains solutions but it doesn't work :/

I did the dump and got:

[...
{
          "AXFrame": "{{74, 372}, {227, 40}}",
          "AXUniqueId": null,
          "frame": {"y": 372, "x": 74, "width": 227, "height": 40},
          "role_description": "text field",
          "AXLabel": null,
          "content_required": false,
          "type": "TextField",
          "title": null,
          "help": "",
          "custom_actions": [],
          "AXValue": "Username",
          "enabled": true,
          "role": "AXTextField",
          "subrole": null
        },
        {
          "AXFrame": "{{74, 427}, {57, 15}}",
          "AXUniqueId": null,
          "frame": {"y": 427, "x": 74, "width": 57, "height": 15},
          "role_description": "text",
          "AXLabel": "Password",
          "content_required": false,
          "type": "StaticText",
          "title": null,
          "help": "",
          "custom_actions": [],
          "AXValue": "",
          "enabled": true,
          "role": "AXStaticText",
          "subrole": null
        },
        {
          "AXFrame": "{{74, 448}, {227, 41}}",
          "AXUniqueId": null,
          "frame": {"y": 448, "x": 74, "width": 227, "height": 41},
          "role_description": "secure text field",
          "AXLabel": null,
          "content_required": false,
          "type": "TextField",
          "title": null,
          "help": "",
          "custom_actions": [],
          "AXValue": "Password",
          "enabled": true,
          "role": "AXTextField",
          "subrole": "AXSecureTextField"
        },
...]

**Comment by bartekpacia** [comment]
Okay, so that's definitely a bug. Sorry for the problems and thanks for reporting.

Could you create a new issue with all the info that you've provided? So that we don't clutter this one.

I know it might not be possible but sharing the URL that you're displaying would definitely help.

**Comment by bartekpacia** [comment]
> I updated to patrol_cli v0.6.13 and here's what I get (...)

Okay, this is strange and definitely a bug. Thanks for reporting and sorry for the problems.

**Comment by Choups2** [comment]
`pumpAndSettle()` didn't solve my problem. But switching the device language to english did

**Comment by bartekpacia** [comment]
> Still can't do `await $.native.tap(Selector(text: 'Allow'));` though

That's because you need to specify the appID of Springboard (the built-in iOS launch screen app).

Try this:

```dart
await $.native.tap(
  Selector(text: 'Allow'),
  appId: 'com.apple.springboard',
);
```

**Comment by bartekpacia** [comment]
Also, the reliability of interaction with native permission was greatly improved in https://github.com/leancodepl/patrol/pull/437 and https://github.com/leancodepl/patrol/pull/448.

Let me know if I can close this issue.

**Comment by bartekpacia** [comment]
Friendly ping @Choups2 :)

**Comment by Choups2** [comment]
Sorry I've been busy lately. I'll look into it and let you know next week @bartekpacia  :)

**Comment by Choups2** [comment]
Hello, interaction with native permission has improved indeed. I can now pass through native permission dialogs. Thank you :)
