### ISSUE TITLE
`integration_test plugin was not detected` is always shown after `patrol drive`

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#425]
A message like this is always shown after a executing a single test file completes (either successfully or not).

```
Warning: integration_test plugin was not detected.
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
If you're running the tests with Android instrumentation or XCTest, this means
Failed to stop app
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:
https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
00:32 +2: All tests passed!
flutter_driver exited with code 0
```

Looks like this bug was previously reported to the Flutter team, but they forgot about it. See https://github.com/flutter/flutter/issues/71594 for more.

<details>
  <summary>More logs</summary>
  
```
Running dark_mode_test.dart with flutter_driver on iPhone 14...
VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:59380/GRCp7KnxgSY=/
VMServiceFlutterDriver: Isolate found with number: 3249908297110195
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
Patrol: creating NativeAutomator, host: localhost, port: 8081, packageName: pl.leancode.patrol.example, bundleId: pl.leancode.patrol.Example
Patrol: Initializing PatrolBinding...
00:00 +0: disables and enables dark mode twice
VMServiceFlutterDriver: Connected to Flutter application.
Patrol: disableDarkMode() started
Patrol: disableDarkMode() succeeded
Patrol: enableDarkMode() started
Patrol: enableDarkMode() succeeded
Patrol: disableDarkMode() started
Patrol: disableDarkMode() succeeded
Patrol: enableDarkMode() started
Patrol: enableDarkMode() succeeded
00:32 +1: (tearDownAll)
Warning: integration_test plugin was not detected.
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
If you're running the tests with Android instrumentation or XCTest, this means
Failed to stop app
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:
https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
00:32 +2: All tests passed!
flutter_driver exited with code 0
```
</details>

**Comment by bartekpacia** [comment]
This should be fixed when we replace `flutter drive` with `flutter test` in #421.

**Comment by Yokoi-K** [comment]
@bartekpacia 
Hi!

I have the same problem. How can I solve this?
I can't do ```patrolTest``` method.

## Detail

Execute the following command.

```
patrol drive --target=integration_test/all_test.dart --driver=test_driver/integration_test_driver.dart
```

The following log will then be output.
The process ends without actually executing the contents of ```patrolTest```.

```
Patrol: creating NativeAutomator
Patrol: Initializing PatrolBinding...
00:00 +0: (tearDownAll)
VMServiceFlutterDriver: Connected to Flutter application.
Warning: integration_test plugin was not detected.
Failed to stop app
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:
https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
00:00 +1: All tests passed!
```

Please help me, thanks😭

**Comment by bartekpacia** [comment]
Hi @Yokoi-K!

This issue is about only a false positive warning being printed at the end of the test – it does not affect running the test in any way. So, I'm pretty sure your problem with contents of `patrolTest()` not executing is not related to this problem.

Do you mind sharing your test with me so I can take a look and maybe see what's wrong with your test?

**Comment by Yokoi-K** [comment]
@bartekpacia 

Sorry, This problem has been resolved!
No problem.

**Comment by bartekpacia** [comment]
@Yokoi-K Great! How did you resolve it?

**Comment by Yokoi-K** [comment]
@bartekpacia 

The problem I had was different from the following. I misunderstood the use of ```patrolTest```.

> If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:
https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
00:00 +1: All tests passed!

So I have not been able to solve the issue problem.
Sorry for not being able to help.

**Comment by bartekpacia** [comment]
Not relevant anymore in Patrol 1.0.
