### ISSUE TITLE
Tests using native features can leave the device in an unexpected/broken state

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#430]
### Synopsis

Some native methods obscure the UI, for example:

```dart
await $.native.openQuickSettings(); // opens quick settings on Android and Control Center on iOS
await $.native.openNotifications();
```

### Example

The following test will exit and leave Quick Settings/Control Center opened, breaking all the tests that will be run after it (because the view will be obscured by the Quick Settings/Control center).

```dart
import 'package:example/main.dart';
import 'package:patrol/patrol.dart';

import '../config.dart';

void main() {
  patrolTest(
    'opens quick settings',
    config: patrolConfig,
    nativeAutomation: true,
    ($) async {
      await $.pumpWidgetAndSettle(ExampleApp());

      await $.native.openQuickSettings();
    },
  );
}
```

I don't have a good idea on how we could solve this.

Not-so-good ideas:
- take emulator snapshot at the beginning of each test, and restore it after the tests ends
  - complex
  - Android emulator only
- press back 100x times after each test
  - sounds stupid and hacky
  - no back button on iOS (on iOS we could try killing all the running apps – requires research if possible and feasible)
  - complex as well 

Or we could just warn users about this and say that this is not our problem ¯\\_(ツ)_/¯

cc: @jBorkowska @jakubfijalkowski @mateuszwojtczak

**Comment by jBorkowska** [comment]
I noticed similar problem when a test enables bluetooth - there is additional pop up about it on my device and it breaks tests that are performed after this. I think that user should handle such a situation by himself - there are many possibilities here depending on specific cases. User should write the test in such a way, that is predictable and doesn't leave the device in a weird state :).

**Comment by lmlikota** [comment]
Hi, I have tried this approach to close `openQuickSettings()` on Android [how-to-close-the-quick-settings-system-panel-using-uiautomator](https://stackoverflow.com/questions/52825639/how-to-close-the-quick-settings-system-panel-using-uiautomator) and it works but what I can't get to work is to continue with my test 😞 

```dart
//import 'package:example/main.dart';
import 'package:patrol/patrol.dart';
import 'package:haven_bridge/main_qa.dart' as app;
import 'config.dart';

void main() {
  patrolTest(
    'open and close quick settings, enter text in app',
    config: patrolConfig,
    nativeAutomation: true,
    ($) async {
      app.main();

      // Tap on the button to progress to next screen
      await $('Prijava').tap();

      await $.native.openQuickSettings();
      // Close QuickSettings
      await $.native.pressBack();
      // On some devices we need to call pressBack() again
      var pressAgain = false;
      for ($.native.tap(Selector(contentDescriptionContains: "Airplane mode"));
          pressAgain = true;) {
        if (pressAgain) {
          await $.native.pressBack();
        }
      }

      // Bring focus back to my app? => This is not helping. Why I can't continue after closing QuickSettings?
      await $.pumpAndSettle();
      // This is also not helping is there any way to continue with test?
      await $(#emailTextField).tap();

      await $(#emailTextField).enterText('luka.mlikota.zapovjednik@biss.hr');
      await $(#passwordTextField).enterText('password');
      await $(#loginButton).tap();
    },
  );
}

```
Maybe to write it as Tips & Tricks for each platform @bartekpacia

**Comment by bartekpacia** [comment]
Thanks for reporting @lmlikota. It would be helpful to attach a video recording of the test failing.

**Comment by lmlikota** [comment]
I have attached video recording @bartekpacia

**Comment by bartekpacia** [comment]
It looks like the last `pressBack()` is closing the app. Is the last `pressBack()` necessary? It looks as if that last `pressBack()` was doing 2 things: hiding the notification shade and exiting the app.

If you want to open the app under test, use:

```
await $.native.openApp(); // assuming you have set correct packageName/bundelId in PatrolTestConfig
```

Also:

> On some devices we need to call pressBack() again

Yeah, it depends on the OS version and launcher. So annoying.

**Comment by lmlikota** [comment]
>If you want to open the app under test, use:

>await $.native.openApp(); // assuming you have set correct packageName/bundelId in PatrolTestConfig

I can't or don't know how to, only way I could open my app is importing `import 'package:haven_bridge/main_common.dart';` and then call `app.main()`. I have everything correctly in `config.dart`:

```dart
import 'package:patrol/patrol.dart';

// TODO: Replace with values specific to your app.
const patrolConfig = PatrolTestConfig(
  appName: '[QA] Haven First Responders',
  packageName: 'hr.biss.haven_bridge.dev',
  bundleId: 'hr.biss.havenBridge',
);
```
My devs explained that we need to use it like that because we are using flavors and that our `main_common.dart` is just a "router" to `main_qa.dart` and `main_uat.dart`

**Comment by lmlikota** [comment]
>. Is the last pressBack() necessary?
I would say it is since I need ti `pressBack()` twice to get rid of QuickSettings panel. I wasn't aware that `pressBack()` is closing the app. 😕

**Comment by bartekpacia** [comment]
> I can't or don't know how to, only way I could open my app is importing import 'package:haven_bridge/main_common.dart'; and then call app.main()

That's a good way to do this. Everything is OK :) `$.native.openApp()` acts as if you tapped the app icon in the launcher – and only that. It doesn't do any of the Flutter-things like `pump()` etc.

Your `app.main()` and `$.native.openApp()` do different things. For example, try running this test to see it in action:

```dart
import 'package:patrol/patrol.dart';
import 'package:haven_bridge/main_qa.dart' as app;
import 'config.dart';

void main() {
  patrolTest(
    'open and close quick settings, enter text in app',
    config: patrolConfig,
    nativeAutomation: true,
    ($) async {
      app.main();

      await $.native.pressHome();
      await $.native.openApp();

      await $('Prijava').tap();
    
      await $.native.pressHome();
      await $.native.openApp();
    },
  );
}
```

I hope this example demonstrates what `openApp()` is about. Feel free to ask if something is unclear.

> My devs explained that we need to use it like that because we are using flavors and that our main_common.dart is just a "router" to main_qa.dart and main_uat.dart

That's a fair approach 👍 At LeanCode we do it roughly the same way: we have `main_dev.dart`, `main_tst.dart`, and `main_prod.dart`, all of which finally just call `main_common.dart`.

**Comment by lmlikota** [comment]
Thank you very much, I'm learning a lot using Patrol 😃 . Looks like this is not working as I would expect based on the provided code. I see that app opened only once because of `app.main()` call but didin't opened twice.

https://user-images.githubusercontent.com/10289319/195099993-14c1c270-8132-4cd3-b58c-ebfd657380ab.mp4

**Comment by bartekpacia** [comment]
After watching the video, I'd add a `pumpAndSettle()` after `app.main()` to wait for the app to fully load. 

```dart
app.main();
await $.pumpAndSettle();
```

If you have the capacity, I'd be happy to see the recording of the test with added `pumpAndSettle()`.

**Comment by lmlikota** [comment]
Here is recording with added `pumpAndSettle()`.

https://user-images.githubusercontent.com/10289319/195130007-6582d05b-ab00-48eb-aecd-873b3744c37c.mp4

I was able to solve my problem by commenting out 
```dart
   // On some devices we need to call pressBack() again
      var pressAgain = false;
      for ($.native.tap(Selector(contentDescriptionContains: "Airplane mode"));
          pressAgain = true;) {
        if (pressAgain) {
          await $.native.pressBack();
        }
      }
```

What was necessary to do is to call 
```dart
      await $.native.openQuickSettings();
      // Close QuickSettings
      await $.native.pressBack();
      await $.native.pressBack();
```
