### ISSUE TITLE
Xcode couldn't find any iOS App Development provisioning profiles matching 'pl.leancode.AutomatorServer'

### ISSUE THREAD

**Issue by Yokoi-K** [leancodepl/patrol#471]
## Summary
I would like to use this library called patrol for ```integration_test``` in Flutter, as I need to tap on native iOS dialogs.

## Cannot execute

However, when I try to install and run it, I get the following error when I hit the following command

### Command

```shell
patrol drive --flavor=development --dart-define=FLAVOR=development --bundle-id=<My app id> --package-name=<My app id>
```

### Error log
```
Passed --dart-define: FLAVOR=development
No device specified, using the first one (ios se3)
✓ Forwarded ports (25ms)

Testing failed:
No profiles for 'pl.leancode.AutomatorServer' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'pl.leancode.AutomatorServer'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
No profiles for 'pl.leancode.AutomatorServerUITests.xctrunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'pl.leancode.AutomatorServerUITests.xctrunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Testing cancelled because the build failed.

** TEST FAILED **
Unhandled exception:
Exception: Test failed. See logs above. Also, consider running with --verbose.
#0      IOSDriver._runServer.<anonymous closure> (package:patrol_cli/src/features/drive/platform/ios_driver.dart:174:9)
#1      List.forEach (dart:core-patch/growable_array.dart:416:8)
#2      ProcessListeners.listenStdErr.<anonymous closure> (package:patrol_cli/src/common/extensions/process.dart:50:14)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#7      _StreamController._add (dart:async/stream_controller.dart:648:7)
#8      _StreamController.add (dart:async/stream_controller.dart:596:5)
#9      _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#14     _StreamController._add (dart:async/stream_controller.dart:648:7)
#15     _StreamController.add (dart:async/stream_controller.dart:596:5)
#16     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
#17     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
```

## Help

The reason why provisioning profiles is required is.

What can you tell us about it?
I would like to use this library, but I can't get it to run.

Thanks.

**Comment by bartekpacia** [comment]
Hi @Yokoi-K, thanks for creating the issue.

The provisioning profile is required to install any app on a physical iOS device. It's an Apple requirement and we can't do anything about this.

To set up the provisioning profile, go to ~/.cache/patrol/` and open the newest iOS project with Xcode:

```console
$ open ios-0.7.1+3/AutomatorServer.xcodeproj
```

And then select "Automatically manage signing":

<img width="1552" alt="Screenshot 2022-10-18 at 12 08 55 PM" src="https://user-images.githubusercontent.com/40357511/196401832-e5cda93b-355c-421b-b05a-92d43730eef3.png">

We're working on making this process more seamless, but currently, you have to set up code signing manually.

**Comment by Yokoi-K** [comment]
@bartekpacia 
Thank you for your response.

I checked in the specified ```xcodeproj``` and "Automatically manage signing" was already selected.

<img width="1147" alt="スクリーンショット 2022-10-19 11 09 30" src="https://user-images.githubusercontent.com/29598247/196580690-d24627f9-f060-49d8-b6fb-1919226ae5d2.png">

The xcode display is below.

Is there anything else I should do?

**Comment by bartekpacia** [comment]
You also have to select a development team. Click on Add Team and follow the instructions until the red warning sign disappears.

**Comment by Yokoi-K** [comment]
hmm,

I am not on the development team for ```pl.leancode.AutomatorServerUITests```, so I can't make a choice.

Can't you run it on the actual iOS device using patrol?
only iOS simulator?

**Comment by Yokoi-K** [comment]
I Understood.
So I need to create this team myself.

This issue is closed for the moment, no problem.

**Comment by bartekpacia** [comment]
Sure, happy to help.

Let me know if you were able to run it.

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment and I'll be happy to continue the discussion :)
