### ISSUE TITLE
Add support for test tags to the CLI

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#492]
The built-in [test](https://pub.dev/packages/test) package lets developers add _tags_ to their test files, groups, and individual tests.

I won't ramble about tags here, instead I'll send you to the official docs:
- [Tagging tests](https://pub.dev/packages/test#tagging-tests) in `package:test`'s readme
- [Configuring tags](https://github.com/dart-lang/test/blob/master/pkgs/test/doc/configuration.md#configuring-tags) in `package:test`'s docs

We should research:
- if tags are good for marking platform-specific tests
- if there are any problems with them. If not, we should add support for running tests by tags to `patrol_cli`, and update docs to let our users know about this feature.

cc: @jakubfijalkowski @mateuszwojtczak @jBorkowska, wdyt?

**Comment by bartekpacia** [comment]
`flutter drive` (which we currently use) doesn't support test tags. We'll get them for free once we migrate to `flutter test`. This migration is tracked in #421.

**Comment by jBorkowska** [comment]
Related to this PR: https://github.com/leancodepl/patrol/pull/2052
