### ISSUE TITLE
Make it possible to check and wait for existence of a native widget

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#499]
Patrol makes it easy to check if a finder finds at least 1 existing widget:

```dart
bool doesWidgetExist = $('Sign in').exists;
```

or at least 1 visible widget:

```dart
bool isWidgetVisible = $('Sign in').visible;
```

There's no equivalent functionality that would let users check if a native view exists. I think adding it would be useful.

API idea:

```
bool nativeViewExists = await $.native.doesViewExist(Selector(text: 'Allow while in use'));
bool isNativeViewVisible = await $.native.isViewVisible(Selector(text: 'Allow while in use'));
```

We should also introduce an equivalent of `waitUntilExists()`/`waitUntilVisible()`.

**Comment by RamithRD** [comment]
Hi @bartekpacia, Is there any workaround to this atm?

**Comment by bartekpacia** [comment]
Hi @RamithRD, you can try using [getNativeViews()](https://pub.dev/documentation/patrol/latest/patrol/NativeAutomator/getNativeViews.html) in a loop, see [an example here](https://github.com/leancodepl/patrol/discussions/1071#discussioncomment-5290365)

**Comment by fylyppo** [comment]
Yes, we should have it. It will speed up my test runs a lot :zap: cc @jBorkowska

**Comment by katarzyna-juszczak** [comment]
I would love to see this feature in Patrol :) (currently using workarounds for that)

**Comment by ziadsarour** [comment]
Would be awesome !
I Hope it will be available in v2

**Comment by bartekpacia** [comment]
Thanks for expressing your interest! We'll try to squeeze it in v 1.x :)

**Comment by DrBu7cher** [comment]
Could you kindly explain to me how I could currently enter text in a text field that is itself inside a WebView to log in to my app with OAuth?
I have no ID on the HTML Input tag, is it necessary? Or does the `resource-id` you are talking about have nothing to do with the ID in an HTML tag? And if it doesn't, how would I select the text field - aka get its correct `resource-id`?
Thank you in advance!

**Comment by DrBu7cher** [comment]
Ok, I found your debugging steps [here](https://github.com/leancodepl/patrol/issues/922#issuecomment-1432222218), thank you.

**Comment by wheeOs** [comment]
>  Hi @RamithRD, you can try using [getNativeViews()](https://pub.dev/documentation/patrol/latest/patrol/NativeAutomator/getNativeViews.html) in a loop, see https://github.com/leancodepl/patrol/discussions/1071#discussioncomment-5290365

hi @bartekpacia, but this is not supported on iOS yet, right?

Because I get: 
```
Patrol action failed: GrpcError: getNativeViews() failed with code INTERNAL (getNativeViews() is not
        supported on iOS)
```
