### ISSUE TITLE
Introduce `AndFinder` and `OrFinder`

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#529]
One of the customers requested the need for:
- ensuring that multiple given widgets at visible simultaneously
- ensuring that at least one of the given widgets is visible

### checking existence/visibility

For simply ensuring that multiple widgets are visible simultaneously, we can currently get away with:

```dart
expect($(#offersCard).visible, equals(true));
expect($(#messagesCard).visible, equals(true));
```

Or alternatively:

```dart
expect($(#offersCard).visible && $(#messagesCard).visible, equals(true));
```

This is OK, but as part of this feature we could provide a bespoke API to make it read and compose better:

```
expect($(#offersCard).and(#messagesCard).visible, equals(true));
```

### waiting until existing/visible

We currently don't support `waitUntilVisible()` for more than 1 widget. If anybody wants this, they have to manually hack their way.

**Proposed API**

Let's say that we want to wait until at least of the following widgets becomes visible (that is, [hitTestable](https://api.flutter.dev/flutter/flutter_test/Finder/hitTestable.html)):
- `#helloText `
- `Icons.front_hand`

```dart
$(#helloText).or(Icons.front_hand).waitUntilVisible();
```

### scrolling

We currently don't support this, if anybody wants this they have to manually hack their way.

**Proposed API**

Let's say that we want to scroll until at least of the following widgets becomes visible (that is, [hitTestable](https://api.flutter.dev/flutter/flutter_test/Finder/hitTestable.html)):
- `#helloText `
- `Icons.front_hand`
- `"Hello there!"`

We would scroll to the (whichever becomes visible first) widget by:

```dart
$(#helloText).or(Icons.front_hand).or("Hello there!").scrollTo();
```

### tapping 

This is more a side-effect of introducing `AndFinder` and `OrFinder` 😛 

It will be possible to do this:

```dart
$(#helloText).and(Icons.front_hand).tap();
$(#helloText).or(Icons.front_hand).tap();
```

What then?

## implementation

Currently we have a [PatrolFinder](https://pub.dev/documentation/patrol/latest/patrol/PatrolFinder-class.html) class.

Class hierarchy after the changes:
`Finder` (abstract)
-> `MatchFinder` (abstract)
---> `PatrolFinder`
-----> `AndPatrolFinder`
-----> `OrPatrolFinder`

**Comment by bartekpacia** [comment]
cc: @jBorkowska @mateuszwojtczak @jakubfijalkowski, I'd be happy to hear for your thoughts on this.

**Comment by jBorkowska** [comment]
I wonder if this can be achieved by using standard finders and some `if`s or exepction-catching. If yes, then maybe we shouldn't give users a tool to write code that is hard to understand (documenting the behaviour of those finder can be tricky).

**Comment by jakubfijalkowski** [comment]
I'm against `AndFinder`.
This
```dart
expect($(#offersCard).and(#messagesCard).visible, equals(true));
```
reads worse and is harder to understand. What does it do? Checks if `#offersCard` exist and if `#messagesCards` is visible? If both are visible? It's not really clear.

The story with `OrFinder` is slightly different. I can see why we would want to have that, but I also think that _we should not be in that place_. All `if`s in tests are bad, whether they are explicit or implicit and tests should not do that (only in exceptional situations).

**Comment by bartekpacia** [comment]
We've decided to not implement this now.

We might come back to it in the future.
