### ISSUE TITLE
Doubt on how to end the test correctly[IOS]

### ISSUE THREAD

**Issue by henriquejunqbraga** [leancodepl/patrol#530]
Good afternoon @bartekpacia how are you?
I have a question regarding Patrol.
My code is this,

```dart
void main() {
  patrolTest(
    'open app and login and search air jordan',
    config: patrolConfig,
    nativeAutomation: true,
    ($) async {
      app.main();
      await $.pumpAndSettle();
      await $.native.tap(Selector(text: 'Login'));
      await $.pump(const Duration(seconds: 3));
      await $.pump(const Duration(seconds: 3));
      await $.pump(const Duration(seconds: 2));
      await $.native.enterTextByIndex('AAAAAA', index: 0);
      await $.native.enterTextByIndex('AAAAA', index: 1);
      await $.native.tap(Selector(text: 'ENTRAR'));
      await $(#lupa).tap();
      await $.pump(const Duration(seconds: 2));
      await $(#buscar).enterText('hiiiii');
      await $.pump(const Duration(seconds: 2));
      await $('hiiiii').tap();
    },
  );
}
```

And it is running correctly with the patrol drive command,  but how do I close the test passing?
Currently it just closes the app after running the test and gives an error message: 
LateInitializationError: Field '_subscriptionLink@776036435' has not been initialized.
and just below:
Failed to stop app
✗ app_test.dart failed

**Comment by bartekpacia** [comment]
Hi @henriquejunqbraga, I'm fine, actually I'm happy to be working on Patrol :)

Thanks for creating this issue. I see this for the first time, and it is strange enough for me to say that I'm pretty sure it's your app that tries to access the private `late _subscriptionLink` field somewhere after the test finishes. Search for it and try to make sure that the `_subscriptionLink` field is non-null when it is first used.

So, this is probably not a Patrol-related problem.

If possible, seeing full logs would help :)

**Comment by henriquejunqbraga** [comment]
Congrats on the beautiful work!
Below is the log

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following LateError was thrown while finalizing the widget tree:
LateInitializationError: Field '_subscriptionLink@776036435' has not been initialized.
When the exception was thrown, this was the stack:
#0      AppState._subscriptionLink (package:nike/app.dart)
#1      AppState.dispose (package:nike/app.dart:36:5)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5105:11)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1917:13)
#4      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#5      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1926:25)
#6      BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2523:15)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2947:7)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:885:19)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#12     LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1559:13)
#13     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
00:25 +0: open app and login and go to search and go back to home [E]
  Test failed. See exception logs above.
00:25 +0 -1: (tearDownAll)
Warning: integration_test plugin was not detected.
If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.
If you're running the tests with Android instrumentation or XCTest, this means
that you are not capturing test results properly! See the following link for
how to set up the integration_test plugin:
https://flutter.dev/docs/testing/integration-tests#testing-on-firebase-test-lab
00:25 +1 -1: Some tests failed.
Failed to stop app
✗ app_test.dart failed
flutter_driver exited with code 1
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.

**Comment by bartekpacia** [comment]
Thanks for sharing these logs. Now I'm quite confident that the problem lies in your app in the `AppState` class. When `AppState.dispose()` is called, the `late _subscriptionLink` field is accessed, but it is unassigned, which results in the [LateInitializationError](https://api.dart.dev/stable/dart-core/LateInitializationError-class.html) being thrown.

**Comment by henriquejunqbraga** [comment]
OK!! 
I will try to solve this error here, and thank you very much for the support!

**Comment by bartekpacia** [comment]
No problem :)
