### ISSUE TITLE
Run main instead of creating Widget

### ISSUE THREAD

**Issue by GustekDev** [leancodepl/patrol#543]
With current approach of setting up an App by creating the widget that would be passed on to `runApp` we are effectively unable to setup the app if there are some setup steps in the main before `runApp`

For example, this is the recommended way to point your app at Firebase Emulator
https://firebase.google.com/codelabs/get-started-firebase-emulators-and-flutter#3
so now it is not possible to have your tests use an emulator unless you somehow change it when WIdgets are created.

In my case additionally, I request location permissions at that time, when the splash screen is still visible, as my app won't work without them.  

Is there a way I can call app.main() and use patrol?

**Comment by bartekpacia** [comment]
Hi @GustekDev,

What you're describing is possible. We're not mentioning it in the docs, but you can see people doing it and Patrol works just fine in such cases.

For example, see:
- https://github.com/leancodepl/patrol/issues/530
- https://github.com/leancodepl/patrol/issues/477

Hope this helps! :)

**Comment by GustekDev** [comment]
Thank you,
I got it working, but I had to refactor the permissions request to be part of the `runApp`.
When I was requesting permissions with the splash screen still visible before runApp patrol would get stuck on
```
Patrol: configure() started
Patrol: configure() succeeded
```

**Comment by bartekpacia** [comment]
Glad you got it working (with a workaround, but still 😉)

Could you show me the code of your app's `main()`?

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment and I'll reopen.
