### ISSUE TITLE
Stuck on Installing Server...

### ISSUE THREAD

**Issue by arashgm** [leancodepl/patrol#549]
Hi,
just started to try patrol in our project and patrol stuck on the Installing server part : 
```
Forwarding ports...
Forwarded ports
Installing server...

```

Patrol doctor : 
```
✓ adb found in /***/adb
✓ $ANDROID_HOME env var set to /Users/***/Library/Android/sdk
✓ xcodebuild found in /usr/bin/xcodebuild
✓ iproxy found in /usr/local/bin/iproxy
✓ stdbuf found in /usr/local/bin/stdbuf
✓ ideviceinstaller found in /usr/local/bin/ideviceinstaller

```

Same result happening on a fresh new flutter project with command patrol drive

**Comment by bartekpacia** [comment]
Hi @arashgm, thanks for creating the issue. Could you share more details?

- What device are you trying to run tests on? Android or iOS? What version?
- Run `pgrep iproxy` and share the output

**Comment by arashgm** [comment]
I have tried on Android real device (one plus android 11) and emultor , both same result.

```
Verbose mode enabled. More logs will be printed.
Forwarding ports...
Forwarded ports
Installing server...
```
pgrep iproxy does not print any output

**Comment by bartekpacia** [comment]
Strange... will investiage soon.

**Comment by arashgm** [comment]
```
Android Debug Bridge version 1.0.41
Version 33.0.3-8952118
```

**Comment by bartekpacia** [comment]
This is strange. Unfortunately, I don't have enough info to reproduce the issue.

What version of Android are you using on the emulator? Please share as much details as possible.

**Comment by arashgm** [comment]
i am using Android 11 on Emultaro as well , Api 30 , i am suspecting that when there are two devices attached (in my case real device and emulator) to the adb, the patrol drive getting stuck . it stucks even `patrol drive -d emulator-5554` . ok this is the case i disconnected the real device and the test was successful on emulator

**Comment by bartekpacia** [comment]
OK, that's a very important and helpful info that Patrol works with 1 device connected, but fails with 2.

I think I know where the cause might lie (a bug `adb` package with no device being explicitly selected). Will release a fix today.

**Comment by bartekpacia** [comment]
LMK if `patrol_cli` v0.7.5 fixes this for you :)

**Comment by arashgm** [comment]
Yes it is working now thanks for the fast fix.
