### ISSUE TITLE
[Feature]: Adding Shader compilation jank option

### ISSUE THREAD

**Issue by Kiruel** [leancodepl/patrol#572]
Should be nice to add: `--cache-sksl --write-sksl-on-exit` from `flutter drive`, into `patrol` command.

```bash
    --cache-sksl          Cache the shader in the SkSL format instead of in binary or GLSL formats.
    --write-sksl-on-exit  Attempts to write an SkSL file when the drive process is finished to the provided file, overwriting it if necessary.
```

So we could automate the jank sksl file, on every new test.

From https://docs.flutter.dev/perf/shader it's for performance issue.

**Comment by bartekpacia** [comment]
Thanks for reporting, we'll consider this.

**Comment by bartekpacia** [comment]
Since we're not using `flutter_driver` anymore, this can't be done :(

See also #646.
