### ISSUE TITLE
Unable to tap `OK` popup in native app

### ISSUE THREAD

**Issue by jagadeeshpurplle** [leancodepl/patrol#582]
Hi patrol team,

I'm using google flutter integration driver to automate mobile flutter app.

I have a use case where clicking on `Mail us` button opens the gmail app. And i need to use traditional way of `testWidgets(...)` instead of `patrolTest(...)` as i need to run the tests on firebase test lab. Because firebase test lab failing to configure the patrol config.!

Here is my `app_test.dart`
```
// ignore_for_file: avoid_print
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:patrol/patrol.dart';
import 'package:sparrowmobile/commons/utils/logger.dart';

import 'package:sparrowmobile/flavor/uat.dart' as app;


void main() {

  final automator = NativeAutomator(
    packageName: 'com.sparrowcard.app',
    bundleId: 'com.sparrowcard.app',
  );

  testWidgets('sample external app test', (tester) async {
    app.main();
    await tester.pumpAndSettle(const Duration(seconds: 10));
    .
    .
    .
    await tester.tap(find.byKey(const ValueKey('mailUs')));
    // await tester.pumpAndSettle(const Duration(seconds: 10));
    await tester.pumpAndSettle(const Duration(seconds: 5));
    await automator.tap(
      Selector(text: 'OK'),
      appId: 'com.sparrowcard.app',
    );
  });
}
```
When i execute the tests with 
```
flutter drive \
--driver=test_driver/integration_test.dart \
--target=integration_test/app1_test.dart --flavor uat
```
its throwing `I/flutter (12080): Patrol: tap() failed`
Here is the screenshot: 
 
<img width="1440" alt="Screenshot 2022-11-08 at 4 20 09 PM" src="https://user-images.githubusercontent.com/25878053/200547292-4356048a-c36f-475c-8b50-462b1e6c3146.png">

Any help @bartekpacia

**Comment by bartekpacia** [comment]
Hi @jagadeeshpurplle,

Unfortunately, Patrol doesn't support Firebase Test Lab. See #332 for more info. 

> flutter drive \\
--driver=test_driver/integration_test.dart \\
--target=integration_test/app1_test.dart --flavor uat

You have to use `patrol drive`, it sets up all things required to be able to interact with the native platform.

**Comment by jagadeeshpurplle** [comment]
@bartekpacia 

However as documentation says, we can still achieve native element interaction using patrol within flutter `testWidgets` right?

<img width="945" alt="Screenshot 2022-11-08 at 6 20 10 PM" src="https://user-images.githubusercontent.com/25878053/200568519-91888f73-0ab1-4e66-8a9c-a4b486b73704.png">

**Comment by bartekpacia** [comment]
Yes you can, but if you want to interact with the native platform? you have to run tests with `patrol drive`.

**Comment by jagadeeshpurplle** [comment]
Yeah initially i ran that above script by `patrol drive` only, but no test was ran. It simply returned `All tests passed.!`.

I'm assuming that,  it was due to there are no `patrolTest` tests written.  Is it true?

**Comment by jagadeeshpurplle** [comment]
Does `Patrol` supports running the tests on any other cloud device farms such as browserstack, kobiton, etc?

**Comment by bartekpacia** [comment]
I'm not aware of any. If you can use shell scripts on these platforms you should be able to do `patrol drive` manually
