### ISSUE TITLE
Enable tests to perform actions on behalf of the host (using service extensions)

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#584]
I want to embed an HTTP server in `patrol_cli`. Requests to that server would run shell commands (e.g `adb`, `flutter screenshot`) from within Dart test code running on a device.

This will enable us to solve the following:
- #534
- #73
- #66
- #556
- #606

I'd like to use gRPC for this (we already use it for `Flutter <--> native` communication within a device).

See also:
- [this comment](https://github.com/leancodepl/patrol/issues/66#issuecomment-1155687176) where the initial idea for this proposal was born

cc: @mateuszwojtczak, @jakubfijalkowski, @shilangyu

**Comment by bartekpacia** [comment]
Could you elaborate?

**Comment by jakubfijalkowski** [comment]
gRPC is unidirectional with a single exception - client streaming. You then don't need to open additional connection to send limited commands to the client.

I think this comment is somewhat irrelevant - I missed what parties you want to be connected. Sorry!

When it comes to CLI <-> Dart's part of the app comms, I personally would go with Dart VM's observatory service extension - there already is CLI <-> Dart communication (although somewhat hidden - it is maintained by the Flutter Driver but, if FD is used directly, you can attach to it) and then you can use events to send requests from tests to the CLI. This will be, IMO, much more Dart-native.

**Comment by bartekpacia** [comment]
@jakubfijalkowski Whoa, this is exactly the big-brain kind of idea I'd expect from you. :D

This approach sounds very interesting, and I think I like it. 

It'll require more research from me than wrote I wrote in the first post (embedding a gRPC in the CLI), and I'm not sure what benefits we'll gain aside from being more Dart-native.

**Comment by jakubfijalkowski** [comment]
The main big advantage here is that you will need to maintain only one connection. With separate gRPC server you will have to have two of them, which gets _funny_ when only one of them breaks in a silent manner ;P

**Comment by bartekpacia** [comment]
Another use case for the HTTP server:
- https://github.com/leancodepl/patrol/issues/556

**Comment by bartekpacia** [comment]
Patrol 1.0 works only inside the host app, so this is not longer relevant. In the future, we'll research how we can add host feautres back, but they will only work when the host is available (so, for example, not on Firebase Test Lab).

See also #661.
