### ISSUE TITLE
Manual initialiazation doe snot appear to work

### ISSUE THREAD

**Issue by neiljaywarner** [leancodepl/patrol#592]
used example in docs

```dart
void main() {
  //IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  PatrolBinding.ensureInitialized();
  final automator = NativeAutomator(
    packageName: 'com.everbridge.cc.responder.dev',
    bundleId: 'your.app.id.on.ios',
  );

  testWidgets(
    'test description',
    (WidgetTester tester) async {
      await tester.pumpAndSettle();

      await automator.pressHome();
      await tester.pumpAndSettle();

      // more test code
    },
  );
}
```

Receive error
 'package:flutter/src/foundation/binding.dart': Failed assertion: line 146 pos 12: '_debugInitializedType == null': is not true.

**Comment by bartekpacia** [comment]
Hi @neiljaywarner, thanks for using Patrol!

You mustn't initialize binding yourself, because `NativeAutomator`'s constructor does it itself. Let me know if removing `PatrolBinding.ensureInitialized()` helps.

**Comment by neiljaywarner** [comment]
I tried that first. The sample copy pasted as is
It gave, the air inbinding.dart

If Manua  initialization works, why couldn't that be used for firebase test
Lab

Thank you for the quick response

....sent from my phone

**Comment by neiljaywarner** [comment]
No, I'm using flutter test.

I realize there's another issue discussing that

What would be the point of manual initialization if not to use flutter test

I don't suppose anybody did a gitlab yamp file or makefile command for it
did they? :)



....sent from my phone

**Comment by neiljaywarner** [comment]
I am considering that and it sounds nice. Intuitively but I'm wondering
what value it brings.

Easier to combine coverage reports?
Patrol test Don't increase coverage reports that do they now that I think
about it

So it does sound nice. I'm just wondering what the pros are to not
migrating.

Just curious. Thank you again for your time.

You don't have an ETA for figuring out a way with firebase test lab do you?

I got the impression that maybe you would figure it out..

But maybe that flutter git hub issue is blocking?

....sent from my phone

**Comment by bartekpacia** [comment]
>  I'm wondering what value it brings

It lets you interact with the native platform. You can definitely not use `patrol drive` and do everything yourself:
- download 6 different artifacts for Android and iOS, build some of them
- forward ports between your computer and device
- (Android only) install dummy app under test
- install test instrumentation, where our server lives
- make it work nicely

Feel free to look into `patrol_cli`'s code if you're feeling adventurous and want to do all of it yourself 😛 
We'd like our users to be able to use `flutter test integration_test`, but unfortunately it wouldn't be a pleasant experience.

> You don't have an ETA for figuring out a way with firebase test lab do you?

No ETA.

> I got the impression that maybe you would figure it out..

Hahah thanks but my day is only 24 hrs.

**Comment by neiljaywarner** [comment]
No, I understand. Patrol drive does a lot. I'm not quite sure why someone
would want to not migrate to it 🙂

You're doing a great job. I didn't mean to sound disrespectful or anything.

A lot of us have a lot on our plates. I get it and again you're doing great.
I'm guessing it won't be hard to run on GitLab and you already got it
running on GitHub actions

....sent from my phone

**Comment by bartekpacia** [comment]
> I'm guessing it won't be hard to run on GitLab and you already got it
running on GitHub actions

Yeah, some YAML-rewriting and you should be good to go.

>  I didn't mean to sound disrespectful or anything.

No problem, no offense taken. if I sounded bad or anything, sorry as well:)
