### ISSUE TITLE
Migration from Integration tests to Patrol

### ISSUE THREAD

**Issue by akramcshive** [leancodepl/patrol#599]
Hello team,

PROBLEM: Integration tests doesn't support native elements interaction. 

I'm currently using integration tests library for all the automation tests, and we have almost 40% coverage. Is there a easy way to migrate this or should we basically be rewriting all our scripts? 

If we will have to migrate whats the easiest approach you would suggest.

**Comment by bartekpacia** [comment]
You don't have to migrate all your tests.

You can simply [follow these steps](https://patrol.leancode.co/native/getting-started#initializing-nativeautomator) (see "Manually" paragraph) to use only Patrol's native interaction features.

**Comment by bartekpacia** [comment]
Closing because of lack of response.
