### ISSUE TITLE
App launches wieredly

### ISSUE THREAD

**Issue by akramcshive** [leancodepl/patrol#600]
Hello, I have performed all the setup but the app launches wieredly. As on how it should launch normally, it now opens like a web view. I have performed everything that should be done in the documentation. Screenshot is attached for your ref. You can ignore the error but focus on the way the app launched. 

<img width="457" alt="Screenshot 2022-11-11 at 3 31 40 PM" src="https://user-images.githubusercontent.com/55432474/201316367-9d442895-3a46-4a7b-bfcd-a1d19fea1fe8.png">

**Comment by bartekpacia** [comment]
Hi @akramcshive, thanks for using Patrol and creating this issue.

Can you share your integration test file? The problem you're seeing is the result of test bindings not being initialized.

**Comment by akramcshive** [comment]
`import 'package:app2/main.dart' as app;
import 'package:flutter_test/flutter_test.dart';

import '../fixtures/common_test_data.dart';
import '../screens/login_screen.dart';
import '../utils/common.dart';

void main() {
  group('Running login_test', () {
    testWidgets('Verify valid login test and enable login button',
        (WidgetTester tester) async {
      app.init(e2eTest: true);
      await tester.pumpAndSettle();
      bool found = await Common.waitForWidget(
          tester: tester, finder: LoginScreen.loginBtn);
      expect(found, true);
      await LoginScreen.signIn(tester);
      await LoginScreen.signOut(tester);
    });

    testWidgets(
        'Verify alert dialog  title text when user enters invalid password credentials test',
        (WidgetTester tester) async {
      app.init(e2eTest: true);
      bool found = await Common.waitForWidget(
          tester: tester, finder: LoginScreen.loginBtn);
      expect(found, true);

      await LoginScreen.signIn(tester, fail: true);
      expect(LoginScreen.loginFailedAlertTitle, findsOneWidget);
      expect(LoginScreen.alertPromptCloseBtn, findsOneWidget);
      await tester.tap(LoginScreen.alertPromptCloseBtn);
    });

    testWidgets(
        'Verify alert dialog message text when user enters invalid email credentials test',
        (WidgetTester tester) async {
      app.init(e2eTest: true);
      bool found = await Common.waitForWidget(
          tester: tester, finder: LoginScreen.loginBtn);
      expect(found, true);

      await LoginScreen.signIn(tester, fail: true);
      expect(LoginScreen.userNamePasswordIncorrectAlertMsg, findsOneWidget);
      expect(LoginScreen.alertPromptCloseBtn, findsOneWidget);
      await tester.tap(LoginScreen.alertPromptCloseBtn);
      await tester.pumpAndSettle();
    });

    testWidgets('Verify disabled login button', (WidgetTester tester) async {
      app.init(e2eTest: true);
      bool found = await Common.waitForWidget(
          tester: tester, finder: LoginScreen.loginBtn);
      expect(found, true);

      expect(tester.widget<WrenchButton>(LoginScreen.loginBtn).onPressed, null);
    });

    testWidgets('Verify forgot password screen and password reset screen',
        (WidgetTester tester) async {
      app.init(e2eTest: true);
      bool found = await Common.waitForWidget(
          tester: tester, finder: LoginScreen.loginBtn);
      expect(found, true);

      expect(LoginScreen.forgotPasswordBtn, findsOneWidget);
      await tester.tap(LoginScreen.forgotPasswordBtn);
      await tester.pumpAndSettle();
      await tester.enterText(
          LoginScreen.forgotPassTxtField, CommonTestData.emailID);
      await tester.pumpAndSettle();
      await tester.tap(LoginScreen.submitBtn.first);
      await tester.pumpAndSettle();
      expect(LoginScreen.resetPasswordScreen, findsOneWidget);
      await tester.pumpAndSettle();
      await tester.tap(LoginScreen.returnToLogin);
      await tester.pumpAndSettle();
    });
  });
}
`

**Comment by bartekpacia** [comment]
You're not initializing the bindings.

Also, is this related to Patrol at all? I don't see any Patrol code.

**Comment by akramcshive** [comment]
Thanks, i guess once we do that it works. Any idea how to create smoke/regression suites configs using patrol? Also any report generation that you have in your demo app would help.

**Comment by bartekpacia** [comment]
> Any idea how to create smoke/regression suites configs using patrol?

The example app has integration tests. What are you asking about, specifically?

>  Any report generation?

Currently, it's not available, because we use `flutter drive` under the hood and it doesn't have any test reporting capabilities. But this feature is high on our priorities list, see #421 and #495 to learn more.

**Comment by akramcshive** [comment]
Thanks adding bindings worked.
