### ISSUE TITLE
Restart the app between tests

### ISSUE THREAD

**Issue by viniciusmo** [leancodepl/patrol#601]
Hi,

How to restart the app between integration tests? The native automator has any method to do this?

Thank you

**Comment by bartekpacia** [comment]
Hi @viniciusmo,

The app is always automatically restarted between test target runs. For example, let's say that you have 2 test targets:
1. `integration_test/login_test.dart`
2. `integration_test/logout_test.dart`

Now, if you run `patrol drive`, the app is first installed, the first test target will be run, then the app is uninstalled, the second test target is run, the app is uninstalled again, and that's it.

Is this what you mean?

**Comment by viniciusmo** [comment]
Ohhh thank you @bartekpacia ! 🚀
