### ISSUE TITLE
SocketException occurs when test is executed

### ISSUE THREAD

**Issue by Yokoi-K** [leancodepl/patrol#607]
## Error detail

The following error occurs.

```
Test Case '-[RunnerTests testSample]' failed (0.212 seconds).
Test Case '-[RunnerTests testSample]' started.
/Users/distiller/workspace/packages/app/ios/RunnerTests/RunnerTests.m:4: error: -[RunnerTests testSample] : ((success) is true) failed - ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PatrolActionException was thrown running a test:
Patrol action failed: configure() failed with code UNAVAILABLE
(Error connecting: SocketException: Connection refused (OS Error:
Connection refused, errno = 61), address = localhost, port =
49919)

When the exception was thrown, this was the stack:
#0      NativeAutomator._wrapRequest (package:patrol/src/native/native_automator.dart:159:7)
<asynchronous suspension>
#1      NativeAutomator.configure (package:patrol/src/native/native_automator.dart:170:5)
<asynchronous suspension>
#2      patrolTest.<anonymous closure> (package:patrol/src/custom_finders/common.dart:55:7)
<asynchronous suspension>
#3      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:15)
<asynchronous suspension>
#4      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:5)
<asynchronous suspension>
```

Here's the code.
https://github.com/leancodepl/patrol/blob/master/packages/patrol/lib/src/native/native_automator.dart#L143

## Cause

This is the cause, but I don't know the solution.
```
(Error connecting: SocketException: Connection refused (OS Error:
Connection refused, errno = 61), address = localhost, port =
49919)
```

I'm looking for a solution.
Do you know what it is?

## Supplement

I have no problem on my Mac in the local environment.
I get this error only on CircleCI. Also macOS.

**Comment by Yokoi-K** [comment]
@bartekpacia 

> Are you running the test on Android, or iOS? If iOS, physical or simulator?

Running on macOS iOS simulator on CircleCI.

Here is the version of macOS we use with CircleCI.
```
macos:
  xcode: 14.0.1
```
https://circleci.com/docs/using-macos/

> Also, where do these lines come from?

Sorry..., nothing more.

> What's in the /Users/distiller/workspace/packages/app/ios/RunnerTests/RunnerTests.m file?

Here is code.

```
@import XCTest;
@import integration_test;

INTEGRATION_TEST_IOS_RUNNER(RunnerTests)
```

**Comment by bartekpacia** [comment]
That's a bit strange – why do you have this file there? Can you delete it (and the whole `RunnerTests` folder) and show me the logs again?

**Comment by Yokoi-K** [comment]
RunnerTests is a file required to run integration_test on an actual iOS device, as described in the official Flutter documentation.

https://github.com/flutter/flutter/tree/main/packages/integration_test#ios-device-testing

It is also necessary because without this setting, it is not possible to make it work in the Firebase Test Lab.

**Comment by Yokoi-K** [comment]
I saw this reply on another issue.
https://github.com/leancodepl/patrol/issues/622#issuecomment-1319780823

I am in the same situation, so I have no problem ignoring this issue for the time being!

**Comment by bartekpacia** [comment]
Okay then. I'm glad that we've found the cause. Thanks again for raising this issue :)

**Comment by sunesis2018** [comment]
Has a fix been found yet. Am facing the same error. Thanks

**Comment by bartekpacia** [comment]
Hi @sunesis2018 👋🏾

Unfortunately, I can't help you without more details. Feel free to create a new issue and fill it out according to the bug report template.
