### ISSUE TITLE
Run in Device Farm Tools

### ISSUE THREAD

**Issue by ostk0069** [leancodepl/patrol#622]
This package looks very cool and easy to use!
Thanks for open sourcing this!

feature request to make patrol works on 
 - Firebase Test Lab: https://github.com/flutter/flutter/tree/main/packages/integration_test#firebase-test-lab
 - BrowserStack: https://www.browserstack.com/docs/app-automate/flutter-integration-tests/getting-started-ios
 - or any other tools such as saucelabs, headspins

I see https://github.com/leancodepl/patrol/issues/332 but looks like discussing about ios not android.

Do you have any plans to support android and ios for these tools?

**Comment by bartekpacia** [comment]
Hi @ostk0069, we're happy that you like Patrol :)

> Do you have any plans to support android and ios for these tools?

Yes.

Running Patrol on CI platforms is very important for us. We're currently focusing on making it work [on GitHub Actions](https://github.com/leancodepl/patrol/blob/master/.github/workflows/run-integration-tests.yaml) and on Bitrise (we use it at LeanCode), and we're pretty close. After we figure these 2 out, I think the next steps will be bringing support to more platforms like Firebase Test Lab.

**Comment by Yokoi-K** [comment]
@bartekpacia 

Thank you!
Our team is looking forward to that feature as well.
We would like to be able to run it in the Firebase Test Lab.

**Comment by ostk0069** [comment]
Sorry for the late response.

> Running Patrol on CI platforms is very important for us. We're currently focusing on making it work [on GitHub Actions](https://github.com/leancodepl/patrol/blob/master/.github/workflows/run-integration-tests.yaml) and on Bitrise (we use it at LeanCode), and we're pretty close. After we figure these 2 out, I think the next steps will be bringing support to more platforms like Firebase Test Lab.

I so exited and grateful about this!

**Comment by bartekpacia** [comment]
It's great to see so many reactions to my above comment :) This helps us prioritize issues.

The problems with CI are basically the main reason why we aren't 1.0 yet.

**Comment by bartekpacia** [comment]
Hi all :)

Last week we've merged initial support for running Patrol tests natively. This means you can use Firebase Test Lab, BrowserStack, and basically every other tool that supports native Xcode UI tests and Android UIAutomator2 tests!

I'm still in the process of writing documentation – you can see it [here](https://patrol.leancode.co/ci), There's quite a lot of overlap with `package:integration_test`'s [README](https://github.com/flutter/flutter/blob/master/packages/integration_test/README.md), so if something is missing from Patrol's docs, you can try to use integration_test's readme.

**Comment by bartekpacia** [comment]
Since this use case is now officially supported I'm going to close this issue. Thanks for all the emojis! 🤩

Please create new issues in case you encounter problems with set up etc.
