### ISSUE TITLE
Example app: run patrol tests on iOS in addition to Android

### ISSUE THREAD

**Issue by ostk0069** [leancodepl/patrol#623]
feature request for ios version of https://github.com/leancodepl/patrol/blob/master/.github/workflows/run-integration-tests.yaml

**Comment by bartekpacia** [comment]
Excellent idea.

I want to run these tests on real iOS devices (since Simulator is pretty constrained), but I doubt it's easy to set up with GitHub Actions.

For iOS Simulator, [this Action](https://github.com/futureware-tech/simulator-action) looks OK.

cc: @mateuszwojtczak

**Comment by ostk0069** [comment]
Thanks! 

> but I doubt it's easy to set up with GitHub Actions.

I thought the same! I'm looking forward to it.

**Comment by bartekpacia** [comment]
It's done! :)

Take a look at:
- [integration-test-android](https://github.com/leancodepl/patrol/blob/master/.github/workflows/integration-test-android.yaml)
- [integration-test-ios](https://github.com/leancodepl/patrol/blob/master/.github/workflows/integration-test-ios.yaml)
