### ISSUE TITLE
Granting permissions when starting the app

### ISSUE THREAD

**Issue by PiotrMitkowski** [leancodepl/patrol#628]
Hello!
First of all - great idea with this package, I really appreciate your work!

In my app I have a case, where it requests for the current location while initializing (in `main()`, before calling `runApp`). I'd like to use the same flow in the test case. Let's consider a simplified code for my case:
```dart
  patrolTest(
    'Should correctly open the app',
    nativeAutomation: true,
    (PatrolTester $) async {
      final permission = await Geolocator.requestPermission();
      await $.native.grantPermissionWhenInUse();
      expect(permission, equals(LocationPermission.whileInUse));
      final position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.medium,
      );
      await $.pumpWidgetAndSettle(MyApp(position: position));
      expect($(#position_label), findsOneWidget);
    },
  );
```
In the above example, `$.native.grantPermissionWhenInUse()` never gets called, because awaiting `requestPermission` blocks the program from further execution. I can use a temporary workaround and not await the `requestPermission` method, but it would be a little "hacky" in my case - I'd need to request permissions first, then proceed with my normal initialization flow.

Would it be possible to grant permission in such case, without using workarounds?

**Comment by bartekpacia** [comment]
Hi @PiotrMitkowski 👋

Can you try if this works?

```dart
 patrolTest(
    'Should correctly open the app',
    nativeAutomation: true,
    (PatrolTester $) async {
      final permissionRequestFuture = Geolocator.requestPermission();
      await $.native.grantPermissionWhenInUse();
      await permissionRequestFuture;
      expect(permission, equals(LocationPermission.whileInUse));
      final position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.medium,
      );
      await $.pumpWidgetAndSettle(MyApp(position: position));
      expect($(#position_label), findsOneWidget);
    },
  );
```

The `$.native.grantPermissionWhenInUse()` method tries to be flaky-aware, so even if the permission request dialog is not visible at the time you call `grantPermissionWhenInUse()`, it won't crash, but wait until that permission dialog appears (by default, it'll wait for 10 seconds for the dialog to appear, and then crash).

Let me know if this helps.

**Comment by bartekpacia** [comment]
@PiotrMitkowski If the solution above helped, please close this issue :)

**Comment by PiotrMitkowski** [comment]
@bartekpacia sorry, I've temporarily switched to a different task 😅
I've tested this solution, and it works like a charm, even for a more complex case, where the permission request is deeply inside the app's `main` method. Thanks!

Is it anything worth mentioning in the documentation, e.g. in the `Tips & tricks` section? I can add it, if you say so.

**Comment by bartekpacia** [comment]
Happy to hear that!

> Is it anything worth mentioning in the documentation, e.g. in the Tips & tricks section? I can add it, if you say so. If not, I'll just close this issue :)

I think it's quite a common case and it'd be helpful for others to document it in that section. If you feel like doing it, I'll be happy to review and merge your PR.
