### ISSUE TITLE
How to check which test case passed and which got failed?

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [leancodepl/patrol#649]
I am having several test cases in a dart file, when I run the tests, 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/113885801/204978343-75cc3241-fa46-4074-bbc2-dc804561d9dc.png">
I just get this, is it possible to show the names of test that passed or failed?

**Comment by Gaurav-CareMonitor** [comment]
Like which 3 case passed and which one got failed.

**Comment by bartekpacia** [comment]
Hi @Gaurav-CareMonitor,

Unfortunately, this is not possible currently, but we're aware of the problem. Can't give you any exact dates though.
