### ISSUE TITLE
Test freezes on taking screenshot

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [leancodepl/patrol#650]
Whenever I try to take a screenshot, the test freezes .

<img width="552" alt="image" src="https://user-images.githubusercontent.com/113885801/205030634-d2330cf7-7d05-48de-8a12-c212f9f53b95.png">

**Comment by Gaurav-CareMonitor** [comment]
The app still responds to touch events but the test gets stuck 
<img width="777" alt="image" src="https://user-images.githubusercontent.com/113885801/205030850-0d5eb37e-c4f2-4f92-9a0f-c04e44fb2a1c.png">

**Comment by bartekpacia** [comment]
Hi @Gaurav-CareMonitor, sorry about the problem. Can you show me your `test_driver/integration_test.dart`?

**Comment by Gaurav-CareMonitor** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/113885801/205207640-097f91ad-82f8-4c26-8752-6372fcbb7d4f.png">

patrol: ^0.7.6
patrol_cli is up to date as well
Flutter v 3.3.9

**Comment by Gaurav-CareMonitor** [comment]
<img width="669" alt="image" src="https://user-images.githubusercontent.com/113885801/205207867-5988cd78-aaea-4e0f-a3b9-9c06e120bda0.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/113885801/205207975-3f1c0736-ff63-4f33-aaeb-6ee6ab5bb052.png">
Binding is Patrol Binding

**Comment by bartekpacia** [comment]
Please replace `Future<void> main() => integrationDriver()` with `Future<void> main() => patrlntegrationDriver()`. Should work then. Sorry about the problem, it isn't mentioned in the docs.

**Comment by Gaurav-CareMonitor** [comment]
Works fine now, Thanks

Although is there any way to capture screenshots while using BindingType.integrationTest?

**Comment by bartekpacia** [comment]
> Although is there any way to capture screenshots while using BindingType.integrationTest?

It's not possible. Taking screenshots is implemented by `PatrolBinding`.

The root of this problem is #https://github.com/flutter/flutter/issues/113097.
