### ISSUE TITLE
Make `dragUntilVisible` execution look like `scrollTo`

### ISSUE THREAD

**Issue by jBorkowska** [leancodepl/patrol#653]
Currently, when you use `scrollTo`, you can see that after each iteration `pump()` or `pumpAndSettle()` is called, which results in animation-like look on the screen during test run. Unfortunately, `scrollTo` can't be used, when a widget is scrollable in two direction and there is need for scrolling in both of them. In such a case you must use `dragUntilVisible`, but it doesn't "scroll live" on the screen. If it did (like `scrollTo` does), it would help in debugging.

**Comment by bartekpacia** [comment]
This looks like a bug in `dragUntilVisible()`'s implementation. Thanks for reporting :)

**Comment by bartekpacia** [comment]
All that `PatrolFinder.scrollTo()` is call `PatrolTester.scrollUntilVisible()`, which in turn basically calls `PatrolTester.dragUntilVisible()` (which pumps after every drag). So it's not the cause of your problem. I'd like to see a reproducible demo of it.

Maybe what you're missing from `PatrolTester.dragUntilVisible()` are [these lines](https://github.com/leancodepl/patrol/blob/master/packages/patrol/lib/src/custom_finders/patrol_tester.dart#L533-L536) from `PatrolTester.scrollUntilVisible()`.

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment with more info @jBorkowska and I'll reopen.
