### ISSUE TITLE
Swift Compiler Errors with Xcode 14.2

### ISSUE THREAD

**Issue by Mitagki** [leancodepl/patrol#679]
Getting this and other similar errors since I updated to Xcode 14.2: `Swift Compiler Error (Xcode): 'GRPCAsyncServerCallContext' is only available in iOS 13 or newer`
I expected that 0.10.1 will fix it but it is still present  even in 0.10.2

**Comment by Mitagki** [comment]
Building a brand new flutter project that has patrol in dev_dependencies fails as well. 
`CocoaPods could not find compatible versions for pod "patrol"`
`Specs satisfying the patrol (from .symlinks/plugins/patrol/ios) dependency were found, but they required a higher minimum deployment target.`

**Comment by bartekpacia** [comment]
What's your minimal iOS SDK version? Make sure that both in your Xcode projects settings and in your `Podfile` you have the minimum iOS version set to 13.

Our internal project using Patrol v0.10.2, which has iOS set to 14.0 builds just fine.

**Comment by Mitagki** [comment]
This is what I managed to figure out.
Flutter 3.3.10 creates new projects with support for minimum iOS 11 and minimum Android SDK version 16. Patrol 0.10.2 requires minimum iOS 13 and minimum Android SDK version 21 which means that for anyone who wants to try patrol in a simple new Flutter project building will fail. I can confirm that changing the minimum version of the iOS and Android projects fixes the problems. 
I guess you had to change the patrol minimum iOS to 13 because now some Swift things in Xcode 14.2 require iOS 13 right? 
It would be nice to mention the iOS and Android minimum versions in the documentation of patrol.

**Patrol is awesome!** 👏

**Comment by Mitagki** [comment]
All the time I thought the problem came because I updated Xcode to 14.2. 
I just figured out that patrol 0.9.1 works without a problem with Xcode 14.2. Building with minimum iOS 11 and minimum Android SDK version 16 also works without a problem.
Looks like that the changes with patrol 0.10.0 create all the problems with minimum iOS and Android SDK versions as well as this [issue](https://github.com/leancodepl/patrol/issues/680).

**Comment by bartekpacia** [comment]
The fix is to bump the minimum iOS version to 13.0, like this:

```
# in ios/Podspec
platform :ios, '13.0'
```

This is required because Patrol takes advantage of [Swift's async-await](https://www.hackingwithswift.com/swift/5.5/async-await).

**Comment by bartekpacia** [comment]
I'm gonna close this, please comment and I'll reopen in case the issue persists.
