### ISSUE TITLE
After upgrading to patrol 0.10.2 android build get Execution failed for task ':app:checkDevDebugDuplicateClasses'

### ISSUE THREAD

**Issue by KonAtPropertyMe** [leancodepl/patrol#680]
I upgraded to patrol 0.10.2 from 0.9.1 and now the android build gets failures:

![image](https://user-images.githubusercontent.com/52645081/208026089-53657d3f-bfae-4df7-ab52-a6ec3d267e37.png)
It goes on for almost 1k lines.

Going back to 0.9.1 and all is ok. It seems like going to 0.10.0+ introduces the problem.

It seems like there is something that I need to do if I upgrade to 0.10.0+, but there was nothing in the doc to indicate what I need to do. Any suggestions would be helpful.

Thanks for the package it is greatly appreciated.

**Comment by bartekpacia** [comment]
Hi @KonAtPropertyMe,

Thank you for creating an issue and sorry for the problem.

> It seems like there is something that I need to do if I upgrade to 0.10.0+, but there was nothing in the doc to indicate what I need to do.

Yes, version 0.10.x lets you use a completely redesigned Patrol (["Patrol Next"](https://github.com/leancodepl/patrol/issues/661)). But there should not be any breaking changes to you as of now, all changes are made silently under the hood.

**Comment by Mitagki** [comment]
I get exactly the same error when trying to build the Android version of our app.

**Comment by bartekpacia** [comment]
What's your `minSdkVersion` in `build.gradle`?

**Comment by Mitagki** [comment]
Mine is 29.
I think this issue is not related to the minimum versions.

**Comment by bartekpacia** [comment]
Right, sorry, I must've misunderstood [your comment](https://github.com/leancodepl/patrol/issues/679#issuecomment-1354715021):

> Looks like that the changes with patrol 0.10.0 create all the problems with minimum iOS and Android SDK versions as well as this https://github.com/leancodepl/patrol/issues/680.

@KonAtPropertyMe Can you share/create new a sample reproduction repository? Or, if not, I'd like to see whole logs that you got. 

Sorry for the problem, Patrol 0.10.0 brings many changes under the hood but none of them should impact users of this plugin. In none of the 3 internal projects have we experienced this problem :/

**Comment by Mitagki** [comment]
The first failure is this:
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.api.Advice found in modules jetified-proto-google-common-protos-2.9.0 (com.google.api.grpc:proto-google-common-protos:2.9.0) and jetified-protolite-well-known-types-18.0.0-runtime (com.google.firebase:protolite-well-known-types:18.0.0)

Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```
There are hundreds Duplicate class errors

Second failure is this:
```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'google/protobuf/field_mask.proto'.
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
```

**Comment by bartekpacia** [comment]
Are you using protobuf in your apps?

**Comment by bartekpacia** [comment]
Let me know if [v0.10.3](https://pub.dev/packages/patrol/changelog#0103) fixes this.

**Comment by kameshWB** [comment]
I too got the same error with v0.10.3.

**Comment by Mitagki** [comment]
0.10.3 fixed the second failure:
```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'google/protobuf/field_mask.proto'.
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
```
But I still get the first failure with the many Duplicate class errors:
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.api.Advice found in modules jetified-proto-google-common-protos-2.9.0 (com.google.api.grpc:proto-google-common-protos:2.9.0) and jetified-protolite-well-known-types-18.0.0-runtime (com.google.firebase:protolite-well-known-types:18.0.0)

Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

**Comment by bartekpacia** [comment]
I can reproduce this error in my private app using Firebase.

**Comment by bartekpacia** [comment]
I'll try using `*-lite` variants of protobuf and gRPC in Patrol. This should resolve this.

**Comment by bartekpacia** [comment]
Patrol v0.10.4 fixes this problem for me. @KonAtPropertyMe @kameshWB if this works for you as well, then please close the issue :)

**Comment by KonAtPropertyMe** [comment]
Works for me - thanks for the quick turnaround @bartekpacia, really appreciated.
