### ISSUE TITLE
Cannot run on iOS 

### ISSUE THREAD

**Issue by g-apparence** [leancodepl/patrol#693]
Hi,
maybe there is something I'm missing but it seems that I can't change the provisionning profile used by Patrol. 
I'm getting this error which I can't fix.

Am I missing something?

![Capture d’écran 2022-12-20 à 10 39 42](https://user-images.githubusercontent.com/48241546/208634893-11da6bf5-0798-4a07-832e-0f4262af3006.png)

Device is iPhone X running on iOS 16

**Comment by bartekpacia** [comment]
Hi,

When running on physical iOS you need to manually sign Patrol's AutomatorServer. Open the Xcode project at ~/.cache/patrol/ios-0.10.4 and set up code signing.

**Comment by g-apparence** [comment]
Worked like a charm. 

Thank you. 
Could be amzing to add on doc under iOS setup. (Even if that's temporary, this is a bit frustrating 😅)
