### ISSUE TITLE
Documentation request: How to exit from pipeline step upon failure

### ISSUE THREAD

**Issue by neiljaywarner** [leancodepl/patrol#700]
I notice https://github.com/leancodepl/patrol/blob/master/packages/patrol/example/run_android_testlab
has usage instructions and a variable called pipelinefail

How do we get it to stop the pipeline with exit 1 or similar upon testlab run failure? or is this automatic bc gcloud exit codes? https://cloud.google.com/sdk/docs/scripting-gcloud

Bonus for instructions on how to dump coverage reports somewhere useful :)

**Comment by bartekpacia** [comment]
The `set -euo pipefail` enables ["Bash Strict Mode"](http://redsymbol.net/articles/unofficial-bash-strict-mode). It doesn't have anything to do with Patrol and running tests – it's just a good practice to do when writing Bash scripts.

> How do we get it to stop the pipeline with exit 1 or similar upon testlab run failure? or is this automatic bc gcloud exit codes? https://cloud.google.com/sdk/docs/scripting-gcloud

I'm not sure I understand what you want to do. Do you wish to stop running all tests on Firebase Test Lab as soon as one test fails?

> Bonus for instructions on how to dump coverage reports somewhere useful :)

This is currently not supported, sorry :(

**Comment by neiljaywarner** [comment]
if we have a pipeline step
patrol_test that is in stage test
and stage test has to pass for the merge request to be allowed
then can the patrol_test step fail and the stage test fail and the Merge
request/pull request step be blocked if firebase test lab has any failing
tests?

No, it doesnt need to stop running the tests, but if "the tests" fail then
exit code should handle it i hope

**Comment by bartekpacia** [comment]
I'm not sure I understand well but it sounds to me that it should definitely be possible. Throw in some bash and make things stick.

Closing as it doesn't seem to be actionable on our side.
