### ISSUE TITLE
`takeScreenshot()` registered in `addTearDown()` apparently causes the app to die

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#718]
We have the following _patrol helper_ in our projects:

```dart
void patrol(
  String description,
  Future<void> Function(PatrolTester) callback,
) {
  patrolTest(
    description,
    config: patrolConfig,
    nativeAutomatorConfig: nativeAutomatorConfig,
    nativeAutomation: true,
    framePolicy: LiveTestWidgetsFlutterBindingFramePolicy.benchmarkLive,
    ($) async {
      await $.host.takeScreenshot(name: 'START_$description');
      addTearDown(() async {
        // This is a good enough workaround for now.
        const runningAsNativeTest = bool.fromEnvironment(
          'INTEGRATION_TEST_SHOULD_REPORT_RESULTS_TO_NATIVE',
          defaultValue: true,
        );

        if (runningAsNativeTest) {
          return;
        }

        await $.host.takeScreenshot(name: 'TEARDOWN_$description'); // <-- causes this error
      });
      await callback($);
    },
  );
}
```

This, for reasons currently unknown to me, causes the test to be very flaky:

<details>
<summary>Crash logs</summary>

```
$ patrol drive --flavor dev -t integration_test/hsv_test.dart
Got --dart-define EMAIL
Got --dart-define PASSWORD
Got --dart-define CTS_DISABLE_MAP_PRELOADING
No device specified, using the first one (emulator-5554)
• Building apk for hsv_test.dart...
✓ Built apk for hsv_test.dart (13.9s)
• Running hsv_test.dart on emulator-5554...
	VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:54005/1jWn3iRuih8=/
	VMServiceFlutterDriver: Isolate found with number: 3860102024993679
	VMServiceFlutterDriver: Isolate is paused at start.
	VMServiceFlutterDriver: Attempting to resume isolate
	00:00 +0: Perform a HSV test
	VMServiceFlutterDriver: Connected to Flutter application.
	Unhandled exception:
	DriverError: Failed to fulfill RequestData due to remote error
	Original error: ext.flutter.driver: (112) Service has disappeared
	Original stack trace:
	#0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1746:45)
	#1      VmService._call (package:vm_service/src/vm_service.dart:2262:21)
	#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2233:14)
	#3      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:322:66)
	#4      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:522:45)
	#5      patrolIntegrationDriver (package:patrol/patrol_driver.dart:28:35)
	<asynchronous suspension>
	#0      VMServiceFlutterDriver.sendCommand (package:flutter_driver/src/driver/vmservice_driver.dart:334:7)
	<asynchronous suspension>
	#1      FlutterDriver.requestData (package:flutter_driver/src/driver/driver.dart:522:39)
	<asynchronous suspension>
	#2      patrolIntegrationDriver (package:patrol/patrol_driver.dart:28:22)
	<asynchronous suspension>
✗ hsv_test.dart failed (67.8s)
`flutter drive` exited with code 1
See the logs above to learn what happened. If the logs above aren't useful then it's a bug – please report it.
```
</details>

Seen in `customer: budowa` and`customer: brumbrum`.

**Comment by bartekpacia** [comment]
Taking screenshots is removed in 1.0. See also #661.

We'll reimplement this later on.

**Comment by Shrirama-Upadhya-A** [comment]
Hey @bartekpacia 
I'm currently writing integration tests for our app which uses a Flutter plugin (more of a wrapper on top of native android and native iOS SDKs) & Patrol's native automation has been super helpful so far 🙏 

Now, `takeScreenshot()` feature has become super critical considering our test requirements.

Tried integrating [screenshots](https://pub.dev/packages/screenshots) package alongside Patrol as a temporary workaround, but looks like `screenshots` package requires `driver` & I'm currently blocked due to this.

I completely understand that you have moved `takeScreenshot()` to `not planned` & you have mentioned that the feature will be reintroduced later on, but 
- would it be possible for you to share some kind of timeline for the feature rollout?
- in the meantime, I would be very grateful if you could share a temporary workaround to implement `takeScreenshot()` functionality which would work alongside Patrol

**Comment by bartekpacia** [comment]
@Shrirama-Upadhya-A Hi :)

> would it be possible for you to share some kind of timeline for the feature rollout?

We can't, but I'll try to get this done over the next few days. You're not the first person requesting this, so I think it makes sense to work on it.

It shouldn't be too hard, because it's already implemented in [integration_test](https://github.com/flutter/flutter/blob/3.7.5/packages/integration_test). We basically need to backport [this method](https://github.com/flutter/flutter/blob/3.7.5/packages/integration_test/ios/Classes/IntegrationTestPlugin.m#L85-L105) to Patrol.

BTW, which CI provider are you using? Do you have access to shell? Would video recording fulfill your needs?

**Comment by Shrirama-Upadhya-A** [comment]
> We can't, but I'll try to get this done over the next few days. You're not the first person requesting this, so I think it makes sense to work on it.

Thank you so much ✌️ 
Eagerly waiting for this rollout 🤩

> Which CI provider are you using?

Haven't moved to CI as of now.

> Do you have access to shell?

Yup.

> Would video recording of emulator's/simulator's/device's screen fulfill your needs?

Actually, I'm trying to perform `Screenshot testing` with master screenshot to obtain all pixel changes. AFAIK, screen recording would not be of any use here.
Just to give it a try, I tried running `adb shell screenrecord /sdcard/file/path/name.mp4` & looks like it might not work in all android devices.
- In one of my test devices (Realme device), got the output `screenrecord is inaccessible or not found` (`screenrecord` is definitely present, but it's inaccessible)
- Whereas the same command ran perfectly fine in other test devices (real devices)

**Comment by Shrirama-Upadhya-A** [comment]
Hey @bartekpacia 
Just wanted to understand that once you guys roll-out `takeScreenshot()` functionality, we'll be able to take screenshots of native views also, right?

**Comment by bartekpacia** [comment]
@Shrirama-Upadhya-A Yes, that's what we're aiming for.

**Comment by bartekpacia** [comment]
Hi @Shrirama-Upadhya-A, just wanted to keep you up to date. I'm sad to say this but I won't be able to work on re-adding `takeScreenshot()` in the coming weeks, because we've decided to go with 2 epics: #982 and #1004. Sorry about that.

At LeanCode, we're not hurt by the lack of `takeScreenshot()` that much because we record our tests anyway. 

There are often problems with chinese smartphones like Huawei, Realme, Xiaomi etc. Nothing we can do about that.

**Comment by Shrirama-Upadhya-A** [comment]
Hey @bartekpacia, thanks a lot for the update 👍 
Not the update I was waiting for 🙈 but yeah, I completely understand man. Hope you pick this up in the near future & we're really looking forward for all the exciting features you are working on. Thank you 🙏

**Comment by bertuz** [comment]
+1 on this feature. it's key important for golden tests! ❤️ waiting for this 
I was wondering: isn't there any workaround to take a snapshot via the integration test library while using patrol at the same time? Keep in mind I'm using as a black box and what I'm saying could not make any sense 

```
import 'package:integration_test/integration_test.dart';

...
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();


  patrolTest(
    'crazy test',
    nativeAutomation: true,
    (PatrolTester $) async {
      app_main.main(envFileName: 'assets/.test.env');

      if (await $.native
          .isPermissionDialogVisible(timeout: Duration(seconds: 10))) {
        await $.native.grantPermissionWhenInUse();
      }

      await $.pumpAndSettle();

      var bytes = await binding.takeScreenshot('screen1');
...
```

**Comment by bertuz** [comment]
@bartekpacia do you have an issue for the screenshot functionality already? just to keep track of it and get ready when it's merged 😉
