### ISSUE TITLE
xcodebuild fails with external dependencies

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [leancodepl/patrol#721]
## Build error

When following https://patrol.leancode.co/ci#run-on-firebase-test-lab to run an iOS app on Firebase Test Lab, I encounter the following error during `xcodebuild build-for-testing` command:

```
./app/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'cloud_functions' not found
@import cloud_functions;
 ~~~~~~~^~~~~~~~~~~~~~~
1 error generated.

...

The following build commands failed:
	CompileC ./app/build/ios_integ/Build/Intermediates.noindex/Runner.build/Release-dev-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.o ./app/ios/Runner/GeneratedPluginRegistrant.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Runner' from project 'Runner')
(1 failure)
```

The exact command used is the following (note the adjusted scheme for multiple flavors):

```sh
xcodebuild build-for-testing \
  -workspace Runner.xcworkspace \
  -scheme dev \
  -config Flutter/Release.xcconfig \
  -derivedDataPath ../build/ios_integ \
  -sdk iphoneos
```

## Other builds

This **only** happens with the `xcodebuild build-for-testing` command. When using `Product -> Test` in Xcode, the tests run totally fine. And `flutter build ipa` also works properly.

### Dependencies

Note that this happens for all Firebase dependencies (I have not tested other plugins), i.e. when removing the `cloud_functions` dependency, the compile command will throw at the next import statement in `GeneratedPluginRegistrant.m`.

---

I have tried many proposed solutions to this issue and completely re-setup the `Podfile` as well as the `RunnerUITests` target numerous times - there has to be something wrong with the setup. I have also ensured that the iOS Deployment Target is the same in `Runner`, in the `Podfile` (`platform :ios, '13.0'`), and in `RunnerUITests`.

@bartekpacia do you have any idea what the issue could be here?

**Comment by mateuszwojtczak** [comment]
Hi @creativecreatorormaybenot! AFAIK `Product -> Test` may run tests without performing a build. Do you encounter the same error when using `Product -> Build for -> Testing`? It looks like the iOS test target is not configured properly or doesn't inherit plugin targets properly.

**Comment by creativecreatorormaybenot** [comment]
Hi @mateuszwojtczak - `Product -> Build for -> Testing` also succeeds.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/19204050/209954498-f2a0cfa1-58f4-4e2e-a159-ca7cd6028ac2.png">

**Comment by bartekpacia** [comment]
Hi @creativecreatorormaybenot, thanks for reporting this and sorry for the problem.

> This **only** happens with the `xcodebuild build-for-testing` command. When using `Product -> Test` in Xcode, the tests run totally fine. And `flutter build ipa` also works properly.

This is what I find very strange as well! I'd expect that `Product -> Test` in Xcode would behave the same as `xcodebuild` on the command, but (for some reason I don't know about) it doesn't.

**Comment by bartekpacia** [comment]
@creativecreatorormaybenot, please try the following and see if the result is any different:

```
xcodebuild build-for-testing \
  -workspace Runner.xcworkspace \
  -scheme dev \
  -xcconfig Flutter/Release.xcconfig \
  -configuration Release \
  -derivedDataPath ../build/ios_integ \
  -sdk iphoneos
```

The docs were wrong, see #728.

**Comment by rgrapes** [comment]
I was having this problem. Fixed it for me by changing `Use XXXXX for command-line builds` for both the Runner project and the Pods project to the same value.

**Comment by bartekpacia** [comment]
Since this issue is old and has no new activity, I'm going to close it. Please create a new issue if you experience a similar problem.
