### ISSUE TITLE
Error while installing pod after adding patrol to dependencies

### ISSUE THREAD

**Issue by icodelifee** [leancodepl/patrol#723]
Adding the latest version of `patrol [^0.10.6]` to dev_dependencies and running pod install causes the error below.
`[!] The 'Pods-Runner' target has frameworks with conflicting names: grpc.`

Full error log : https://katb.in/vagejozupem

**Comment by bartekpacia** [comment]
Hi @icodelifee, thanks for using Patrol and creating this issue. 

I haven't encountered this issue before.
Could you create a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) of this problem in a separate GitHub repo? It'd help a lot.

**Comment by icodelifee** [comment]
> Hi @icodelifee, thanks for using Patrol and creating this issue.
> 
> I haven't encountered this issue before. Could you create a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) of this problem in a separate GitHub repo? It'd help a lot.

Hey @bartekpacia, sorry for lack of more info but i did some digging and seems like issue is when you have both patrol and cloud_firestore in dependencies

if you test a project with both of them you will encounter this issue

```
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  patrol:
```

**Comment by bartekpacia** [comment]
Thanks for this info. I tried to reproduce it but couldn't.

Are you using [precompiled Firestore iOS SDKs](https://github.com/invertase/firestore-ios-sdk-frameworks)? I am and I see no problems in the app on which I tried to reproduce this issue. It should also greatly reduce your build times :)

**Comment by icodelifee** [comment]
> 

Yea i know about the precompiled. if i use precompiled sdk, my app crashes on launch, i think it might be an issue with m1 pro cpus

**Comment by icodelifee** [comment]
> Thanks for this info @icodelifee.
> 
> Are you using [precompiled Firestore iOS SDKs](https://github.com/invertase/firestore-ios-sdk-frameworks)? I am and I see no problems in the app on which I tried to reproduce this issue. It should also greatly reduce your build times :)
![Screenshot 2023-01-09 at 6 14 56 PM](https://user-images.githubusercontent.com/18023153/211310974-b01ae0a1-56e1-4018-a818-4a851c196776.png)
Not sure what the issue is here

**Comment by bartekpacia** [comment]
No idea as well. But what did you do?

**Comment by icodelifee** [comment]
> No idea as well. But what did you do?

Nothing, other than just running the app using the precompiled sdk

**Comment by icodelifee** [comment]
I have created an issue at [firestore-ios-sdk-frameworks(#69)](https://github.com/invertase/firestore-ios-sdk-frameworks/issues/69), for now i'll just be testing patrol on android.

**Comment by bartekpacia** [comment]
Can you attach the whole logs?

**Comment by jacobokoenig** [comment]
Same issue. Here are my logs:

[!] The 'Pods-Runner' target has frameworks with conflicting names: grpc.

/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:67:in `verify_no_duplicate_names'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:54:in `block (2 levels) in verify_no_duplicate_framework_and_library_names'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:48:in `each_key'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:48:in `block in verify_no_duplicate_framework_and_library_names'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:47:in `each'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:47:in `verify_no_duplicate_framework_and_library_names'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:597:in `validate_targets'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:163:in `install!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'

**Comment by bartekpacia** [comment]
Hi @jacobokoenig, can you edit your message to include the command you invoked and also include the whole logs?

**Comment by icodelifee** [comment]
> Same issue. Here are my logs:
> 
> [!] The 'Pods-Runner' target has frameworks with conflicting names: grpc.
> 
> /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:67:in `verify_no_duplicate_names' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:54:in `block (2 levels) in verify_no_duplicate_framework_and_library_names' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:48:in `each_key' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:48:in `block in verify_no_duplicate_framework_and_library_names' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:47:in `each' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:47:in `verify_no_duplicate_framework_and_library_names' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:597:in `validate_targets' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:163:in `install!' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load' /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `
> 
> '

just use the pre compiled firebase sdk, it solves the issue

**Comment by jacobokoenig** [comment]
Updated @bartekpacia 

@icodelifee can you clarify or explain how I can do this?

**Comment by bartekpacia** [comment]
@jacobokoenig I'm pretty sure they mean this: https://github.com/invertase/firestore-ios-sdk-frameworks

Let me know if this helps you.

**Comment by bartekpacia** [comment]
@jacobokoenig Did you try using the precompiled Firebase SDKs?

**Comment by dwievermos** [comment]
hello @bartekpacia i really have no idea whats wrong with precomiled Firebase SDKs, can you explain it to me ? i try to remove all of my precompile SDKs and it's still giving me an error when running `pod update` or `pod install` on my project
```sh
apple@ip-192-168-1-2 ios % pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
firebase_auth: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
firebase_remote_config: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "patrol":
  In Podfile:
    patrol (from `.symlinks/plugins/patrol/ios`)

Specs satisfying the `patrol (from `.symlinks/plugins/patrol/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by bartekpacia** [comment]
Hi @dwievermos,

I get this problem sometimes as well – it usually means that the version of precompiled Firebase SDKS that you defined in `Podfile` isn't compatible with the versions of Firebase Dart packages defined in `pubspec.yaml`.

I recommend you makes sure you're using the latest.

For example, here're the versions I use in my [private app](url) 😁:

```ruby
pod 'FirebaseFirestore', git: 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', tag: '10.3.0'
```

and:

```yaml
cloud_firestore: 4.3.1
firebase_auth: 4.2.5
firebase_core: 2.4.1
firebase_crashlytics: 3.0.11
firebase_storage: 11.0.10
```

PS Mind the lack of `^` before Dart packages versions - this force `pub` to use _this exact version_. Learn more [here](https://dart.dev/tools/pub/dependencies#version-constraints).

**Comment by dwikurniantom** [comment]
hello, thanks for the fast response @bartekpacia  I try to add a line on my `Podfile` & change my dependency versions as you refer to without the caret as well. Unfortunately, the error still occurs. I think I will dig into this problem, and waiting for the others to come with solution
```podspec
pod 'FirebaseFirestore', git: 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', tag: '10.3.0'
```
And
```yaml
  cloud_firestore: 4.3.1
  firebase_auth: 4.2.5
  firebase_core: 2.4.1
  firebase_remote_config: 3.0.9
  firebase_messaging: 14.2.1
```

**Comment by MathiasTP** [comment]
> hello @bartekpacia i really have no idea whats wrong with precomiled Firebase SDKs, can you explain it to me ? i try to remove all of my precompile SDKs and it's still giving me an error when running `pod update` or `pod install` on my project
> 
> ```shell
> apple@ip-192-168-1-2 ios % pod update
> Update all pods
> Updating local specs repositories
> Analyzing dependencies
> firebase_auth: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
> firebase_core: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
> firebase_messaging: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
> firebase_remote_config: Using Firebase SDK version '10.3.0' defined in 'firebase_core'
> [!] CocoaPods could not find compatible versions for pod "patrol":
>   In Podfile:
>     patrol (from `.symlinks/plugins/patrol/ios`)
> 
> Specs satisfying the `patrol (from `.symlinks/plugins/patrol/ios`)` dependency were found, but they required a higher minimum deployment target.
> ```

Had the same problem as you, but bumping my iOS deployment target to 16.2 for my Pods project in Xcode solved the problem.

**Comment by river2202** [comment]
Will it solve the problem if patrol upgrade to latest grpc-swift using SPM?

**Comment by cl0v** [comment]
Simplest solution:
Go to the example project in the dir:
https://github.com/leancodepl/patrol/blob/master/packages/patrol/example/ios/Podfile

then copy the lines 2 and 3:
```
ios_deployment_target = '13.0'
platform :ios, ios_deployment_target
```

Replace in your ios/Podfile lines 2 and 3 with this

**Comment by promops** [comment]
@river2202 Working for me:


`grpc_swift_override_name = 'Custom_Name'
pre_install do |installer|
  patrol_pod = installer.pod_targets.find{|target| target.name == 'patrol'}
  grpc_swift_pod = installer.pod_targets.find{|target| target.name == 'gRPC-Swift'}

  next if patrol_pod.nil? || grpc_swift_pod.nil?
  grpc_swift_pod.root_spec.module_name = grpc_swift_override_name

  patrol_srcroot_dir = patrol_pod.pod_target_srcroot
  symlink_patrol_dir = File.dirname(File.expand_path(patrol_srcroot_dir))
  pub_cache_patrol_dir = File.readlink(symlink_patrol_dir)

  File.unlink(symlink_patrol_dir)
  FileUtils.cp_r(pub_cache_patrol_dir, symlink_patrol_dir)

  Dir.glob("#{symlink_patrol_dir}/**/*.swift").each do |file_path|
    content = File.read(file_path).gsub(/(\s)GRPC([\s.])/, "\\1#{grpc_swift_override_name}\\2")
    File.open(file_path, 'w') {|file| file.write(content)}
  end
end`

**Comment by Codeaview** [comment]
> @river2202 @icodelifee Podfile fix working for me:
> 
> ```
> grpc_swift_override_name = 'Custom_Name'
> pre_install do |installer|
>   patrol_pod = installer.pod_targets.find{|target| target.name == 'patrol'}
>   grpc_swift_pod = installer.pod_targets.find{|target| target.name == 'gRPC-Swift'}
> 
>   next if patrol_pod.nil? || grpc_swift_pod.nil?
>   grpc_swift_pod.root_spec.module_name = grpc_swift_override_name
> 
>   patrol_srcroot_dir = patrol_pod.pod_target_srcroot
>   symlink_patrol_dir = File.dirname(File.expand_path(patrol_srcroot_dir))
>   pub_cache_patrol_dir = File.readlink(symlink_patrol_dir)
> 
>   File.unlink(symlink_patrol_dir)
>   FileUtils.cp_r(pub_cache_patrol_dir, symlink_patrol_dir)
> 
>   Dir.glob("#{symlink_patrol_dir}/**/*.swift").each do |file_path|
>     content = File.read(file_path).gsub(/(\s)GRPC([\s.])/, "\\1#{grpc_swift_override_name}\\2")
>     File.open(file_path, 'w') {|file| file.write(content)}
>   end
> end```
> ```

This fix is also working for me. Otherwise, while using precompiled Firestore, the Runner instantly crashes with:
`Termination Reason: DYLD 1 Library missing
Library not loaded: @rpath/GRPC.framework/GRPC`

**Comment by promops** [comment]
@Codeaview Check your Target Dependencies in Build phases (on your test target), include something similar to Runner (maybe you have services that are used native GRPC library)

**Comment by bartekpacia** [comment]
FYI: https://github.com/leancodepl/patrol/issues/1660#issuecomment-1693355936

Once we're done with it, the workarounds shouldn't be needed.
