### ISSUE TITLE
`host.takeScreenshot` & `host.runProcess` (do not) time out

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [leancodepl/patrol#724]
When running this code from the examples:

```dart
await $.host.runProcess(
  'bash',
  arguments: ['-c', 'echo "hello world" > hello.txt'],
);
```

Or this code:

```dart
await $.host.takeScreenshot(name: '1_before_run');
```

On macOS on an iOS simulator using `patrol drive`, the tests continue running forever.
That is the screenshot is never taken (no file is generated) and the host process is never executed (does not take action).

It seems that this line:

https://github.com/leancodepl/patrol/blob/a7dfa43d2e47d44fc8cf9f61f8ae4ce30ddd1c15/packages/patrol/lib/src/binding.dart#L161

Halts the tests forever. I did notice this comment:

https://github.com/leancodepl/patrol/blob/a7dfa43d2e47d44fc8cf9f61f8ae4ce30ddd1c15/packages/patrol/lib/src/host/host_automator.dart#L38

However, the process is also never executed. So adding a timeout would not fix the underlying problem in my case.

**Comment by bartekpacia** [comment]
Hi! Thanks for reporting this issue.

I've just run `patrol drive -t integration_test/process_test.dart` (in the example app) and it worked (patrol 0.10.6, patrol_cli v0.8.1).

I'm going to keep this open but I cannot reproduce this. I'd be happy if we had more info on this.

**Comment by bartekpacia** [comment]
This feature is no longer available because of our massive architectural change in #661.

We plan to bring it back sometime in the future, but it won't be in our 1.0 release.

See also:
- #788
