### ISSUE TITLE
Not able to tap on flutter button after using native tap

### ISSUE THREAD

**Issue by icodelifee** [leancodepl/patrol#725]
I have a dialog after google sign in is done, native tap works fine and it opens up a dialog, which cannot to be tapped for some unknown reason.
```dart
await $('Login with Google').tap(andSettle: false);
await $.pump(const Duration(seconds: 1));
await $.native.tap(Selector(textContains: 'mobile'));
await $.pumpAndSettle();
await $.waitUntilVisible(find.byType(PrivacyPolicyDialog));
expect(find.text('Privacy Policy'), findsWidgets);
await $('Accept').tap();
expect(find.byType(DashboardScreen), findsOneWidget);
```

**Comment by bartekpacia** [comment]
Hi @icodelifee, thanks for reporting this issue.

To be able to help you and fix it, I need more info. Please [create a minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), but if it's not possible, at least share the following info:
- flutter version (`flutter --version`), patrol version
- video recording of what happens
- logs

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment and I'll be happy to continue the discussion :)
