### ISSUE TITLE
iOS: No such module 'XCTest'

### ISSUE THREAD

**Issue by jakeBrightHR** [leancodepl/patrol#779]
I've been following the set up steps here: https://patrol.leancode.co/ci

But I am getting this error in `Automator` when trying to build and run the tests:
`No such module 'XCTest'`

Any help would be appreciated.

<img width="1440" alt="Screenshot 2023-01-17 at 14 34 57" src="https://user-images.githubusercontent.com/112476079/212927375-1eb03a35-60ca-44f8-acd9-bedfbd293520.png">

**Comment by bartekpacia** [comment]
Hi @jakeBrightHR 👋 Sorry for the problems.

Can you show me your Podfile, and your `RunnerUITests.m` file?

**Comment by bartekpacia** [comment]
@jakeBrightHR Friendly ping :)

**Comment by eliasteeny** [comment]
Hi @bartekpacia I'm facing the same issue when running `patrol drive` with the following error : 

```
        Swift Compiler Error (Xcode): No such module 'XCTest'
/Users/eliasteeny/.pub-cache/hosted/pub.dartlang.org/patrol-0.10.8/ios/Classes/AutomatorServer/Automator.swift:0:7
``` 

<details><summary>Podfile</summary>
<p>

```
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'
use_modular_headers!
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

</p>
</details>



<details><summary>RunnerUITests.m</summary>
<p>

```
@import XCTest;
@import patrol;

PATROL_INTEGRATION_TEST_IOS_RUNNER(RunnerUITests)


```

</p>
</details>

**Comment by eliasteeny** [comment]
Adding `use_frameworks!` to the target Runner in the Podfile will solve the issue.
This is my updated Podfile:
<details><summary>Podfile</summary>
<p>

```
# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end


```

</p>
</details>

**Comment by jakeBrightHR** [comment]
@bartekpacia sorry for my late reply. After failing to get this running on Android and iOS all day I actually deleted my branch and thought I'd come back to it at another time. So sorry I don't have any files to share with you!

@eliasteeny thanks for your comment. Is it working for you now?

I'm a bit confused as to why your `podfile` contains:

```
target 'Runner' do
  use_frameworks!
```

but in the documentation it says to do:

```
target 'Runner' do
  # Do not change existing lines.
  ...

  target 'RunnerUITests' do
    inherit! :complete
  end
end
```

**Comment by bartekpacia** [comment]
@jakeBrightHR I'm truly sorry to hear about your problems – we try to make the docs as clear as possible, but the process of setting this up is unfortunately what it is - quite long and easy to mess up.

> I'm a bit confused as to why your podfile contains:

Yeah, I'm also confused about this 😅 In projects using Patrol at LeanCode, we have the following lines and it works:

```ruby
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  target 'RunnerUITests' do
    inherit! :complete
  end

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

This repository also [has an example app](https://github.com/leancodepl/patrol/tree/master/packages/patrol/example/ios), so feel free to check out how it's set up.

**Comment by jakeBrightHR** [comment]
@bartekpacia that's okay no worries! I'm also using a pretty old version of Flutter right now (2.5.3). So after I've done work on upgrading to the latest version I want to give it another go.

Thanks for that link. I'll be sure to use it next time 😄

**Comment by bartekpacia** [comment]
@jakeBrightHR 2.5.3 is pretty old :) I recommend always using the latest version.

If there's nothing more to do, please close this issue :)

**Comment by jakeBrightHR** [comment]
Hi @bartekpacia, I just thought I'd leave a message to let you know that I upgraded to Flutter `3.3.10` and followed the set up steps again and I've got it working now!

Android was very simple to set up just like in your documentation.

However for iOS I did have to use @eliasteeny 's trick to get it working. So my `podfile` looks like this:

```
target 'Runner' do
  use_frameworks!
  
  target 'RunnerUITests' do
    inherit! :complete
  end
end
```

Thanks!

**Comment by pandoras-toolbox** [comment]
@bartekpacia For our mobile app we cannot configure "use_frameworks!" because of a 3rd party module which would not work then. The mobile developers try to push the supplier to make it possible, but it is uncertain. So I am stuck right now with running Patrol tests on iPhone.

Is there a workaround for such a scenario?

**Comment by bartekpacia** [comment]
I'm not aware of a workaround. Sorry.

cc @mateuszwojtczak @jBorkowska, this is a rare but legit use case that requires investigation
