### ISSUE TITLE
Example app's iOS tests always stall after opening the app

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#786]
Reproduce by running `patrol test -v` in `packages/patrol/example` on a connected iOS Simulator.

Sometimes, the test execution stalls at:

```
	2023-01-18 11:14:51.733360+0100 RunnerUITests-Runner[71792:6016173] PatrolServer: INFO: Server started on http://localhost:8081
	t =      nans     Launch pl.leancode.patrol.Example
	t =      nans         Setting up automation session
	t =      nans         Wait for pl.leancode.patrol.Example to idle
```

This particular problem did not happen with `flutter drive`. No idea why it happens as well.

**Comment by DimitarStoyanov91** [comment]
Hello @bartekpacia,
I am currently encountering this issue when running tests for our application on real IoS device.
I followed all the setup steps. Is there something else to configure that i have missed?
