### ISSUE TITLE
`patrol test` feature parity

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#788]
This issue tracks feature parity of the new `patrol test` command, compared to `patrol drive`.

## Features

- [x] #816
- [ ] host features (doing things on the computer to which the device is connected). This includes access to the host's shell and taking screenshots with `flutter screenshot`. See [this issue](https://github.com/leancodepl/patrol/issues/584) for a list of use-cases that will become invalidated.
- [ ] no Flutter-side logs (workaround: use `flutter logs`)

## Bugs
- [ ] #765
- [x] #786
- [ ] #681

## Inconveniences

- Setting up the native automation feature got harder. Hot take @mateuszwojtczak: maybe we should let our users use `flutter run` for test development (convenient_test does that, it also enables hot reload), and require the more complex native Android/iOS setup only if running on devicelab platforms is needed? The obvious problem is how are we going to build and install the second .apk/.app containing the native tests. After giving it some thought, it seems to be a no-go, unfortunately.

**Comment by mateuszwojtczak** [comment]
This should be covered in the migration guide

**Comment by bartekpacia** [comment]
See also #1341

**Comment by jBorkowska** [comment]
I think it's out-of-date, closing
