### ISSUE TITLE
Taking screenshots and recording videos

### ISSUE THREAD

**Issue by kubawojtczakLC** [leancodepl/patrol#8]
- [x] #24

**Comment by bartekpacia** [comment]
> Maybe recording screen as well?

This is very easy to do on Android:

```console
$ adb shell screenrecord /sdcard/test_recording.mp4
```

**Comment by bartekpacia** [comment]
Was implemented with `patrol drive` (with `flutter screenshot)`, in Patrol 1.0 we'll lose this feature.
