### ISSUE TITLE
Example WebView test does not work on iOS or Android

### ISSUE THREAD

**Issue by jakeBrightHR** [leancodepl/patrol#823]
Hi, I've been trying to get Patrol to interact with my sites login page from an in-app WebView. I failed to get this to work so tried to recreate your example WebView tests, however these also are not working for me.

Here is the widget I am pumping:

```
return Scaffold(
    appBar: AppBar(title: Text('title')),
    body: WebView(
    debuggingEnabled: true,
    initialUrl: 'https://stackoverflow.com',
    javascriptMode: JavascriptMode.unrestricted,
    onWebViewCreated: (controller) => print('Webview created'),
    onPageFinished: (url) => print('Webview  finished'),
  ),
);
```

Here is my test code:

```
void main() {
  patrolTest('test 1', (PatrolTester $) async {
    app.main();
    await $.pumpAndSettle();

    await $('Open webview screen C').scrollTo().tap();

    await $.native.tap(Selector(text: 'Accept all cookies'));
    await $.native.tap(Selector(text: 'Log in'));

    await $.pump(Duration(seconds: 2));
  },
  nativeAutomation: true,
  );
}
```

I can't get it to tap on anything inside of the WebView. Here is a video:

https://user-images.githubusercontent.com/112476079/214867303-cb1d395c-ba32-44d0-8798-e50de5da102a.mov

**Comment by bartekpacia** [comment]
Hi, thanks for this bug report. Indeed something has broken and they don't work anymore.

I'm focusing entirely on bugfixing these days, and setting up CI on Firebase Test Lab so they won't come back.

Thanks again!

**Comment by bartekpacia** [comment]
@jakeBrightHR Example app had wrong package name. Please pull the latest `master` and example app should work.

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment and I'll be happy to continue the discussion :)
