### ISSUE TITLE
Test passes even when expected text is wrong

### ISSUE THREAD

**Issue by jakeBrightHR** [leancodepl/patrol#825]
Hi, I've got a very simple test that is being marked as passed even though it should fail.

Code I'm pumping:

```
return Scaffold(
    body: Center(
    child: Text('hello jake'),
  ),
);
```

Test code:

```
patrolTest('test 1', (PatrolTester $) async {
    app.main();
    await $.pumpAndSettle();

    expect($('hello tony'), findsOneWidget);
  },
  nativeAutomation: true,
  );
}
```
![Screenshot 2023-01-26 at 15 12 31](https://user-images.githubusercontent.com/112476079/214873278-960a0fa5-7592-4630-9e12-ece072623ae8.png)

**Comment by bartekpacia** [comment]
Hi @jakeBrightHR,

I can't reproduce this issue with the information you've provided. I'm getting a test fail:

<img width="796" alt="Screenshot 2023-01-29 at 2 40 56 AM" src="https://user-images.githubusercontent.com/40357511/215299447-b6ae44cf-892b-4853-be3d-5ab47006ccc1.png">


I've just set up a bug report issue template – please create a new issue and follow it so I can have all the info required to reproduce it.
