### ISSUE TITLE
SwiftNIO dependency causes build to fail

### ISSUE THREAD

**Issue by andersonfds** [leancodepl/patrol#828]
Installed patrol and followed the install guide and after that I'm unable to build my application, seems that SwiftNIO is causing this error

<img width="523" alt="image" src="https://user-images.githubusercontent.com/25344723/215068473-9c34dba4-9efb-4886-aa13-73649533b57c.png">

Is there any fix or workaround?

Thanks.

**Comment by bartekpacia** [comment]
Hi @andersonfds, thanks for reporting this,

It indeed looks strange – I havne't seen this before. What's your minimum iOS version (in `Podfile` and Xcode project settings?)

**Comment by andersonfds** [comment]
Minimum iOS prior to patrol was 12.1, I've changed to 13.0 as patrol requires 13.0

**Comment by andersonfds** [comment]
To reproduce the problem you just have to add this to your Podfile:

```ruby
target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
   config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES' # This line seems to make it stop working
   config.build_settings['SWIFT_VERSION'] = '5.4'
end
```

**Comment by bartekpacia** [comment]
Can you share the repository with me or create a minimal, reproducible example? It really helps me get up to speed with such bugs :)

**Comment by bartekpacia** [comment]
Thank you, I'll take a look at it soon.

**Comment by wheeOs** [comment]
I'm also facing this issue. During my research for a solution I came across this here https://github.com/grpc/grpc-swift/issues/1274 and it seems like the bug is related to `protobuf` which `patrol` uses as a dependency.

**Comment by wheeOs** [comment]
@andersonfds 

this is what helps me out. But I hope there will be a solution within the project of patrol rather than on application level:

```
post_install do |installer|
  excluded_pods = [
  '_NIODataStructures',
  'gRPC-Swift',
  'SwiftNIO',
  'SwiftNIOCore',
  'SwiftNIOPosix',
  'SwiftNIOConcurrencyHelpers',
  'SwiftNIOExtras',
  'SwiftNIOFoundationCompat',
  'SwiftNIOHPACK',
  'SwiftNIOHTTP1',
  'SwiftNIOHTTP2',
  'SwiftNIOSSL',
  'SwiftNIOTLS',
  'SwiftNIOTransportServices'
  ]
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      unless excluded_pods.include?(target.name)
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
    flutter_additional_ios_build_settings(target)
  end
end
```

**Comment by bartekpacia** [comment]
>  still, I need that flag for some other plugins on my application

What plugins require that flag?

**Comment by andersonfds** [comment]
Hey the plugins I'm using that requires that flag are intellectual property of one of my company's partner so I can't really talk about 'em but as @wheeOs said, there are some plugins out there that also requires that flag.

**Comment by bartekpacia** [comment]
SwiftNIO is no longer our dependency as of #1681.
