### ISSUE TITLE
native automator is null

### ISSUE THREAD

**Issue by Phuong1310** [leancodepl/patrol#854]
Exception has occurred.
_AssertionError ('package:patrol/src/custom_finders/patrol_tester.dart': Failed assertion: line 127 pos 12: 'nativeAutomator != null': native automator is null)
When I use: await $.native.tap(Selector(text: 'Card information'));
![image](https://user-images.githubusercontent.com/117194632/215530864-7fe06d3f-3e3e-4354-83aa-bbd026b252b2.png)

Thanks

**Comment by bartekpacia** [comment]
Hi @Phuong1310,

Do you have `nativeAutomation: true` set in `patrolTest()` call?

In the future, please also follow the bug report template.

**Comment by Phuong1310** [comment]
> Hi @Phuong1310,
> 
> Do you have `nativeAutomation: true` set in `patrolTest()` call?
> 
> In the future, please also follow the bug report template.

Hi @bartekpacia ,
Thanks for reply.
I add `nativeAutomation: true`
![image](https://user-images.githubusercontent.com/117194632/215537848-ea27f8e9-cf30-4e17-9364-c5476d57c28d.png)

I have error
Exception has occurred.
_AssertionError ('package:flutter/src/foundation/binding.dart': Failed assertion: line 146 pos 12: '_debugInitializedType == null': is not true.)

**Comment by bartekpacia** [comment]
Can you please show me the entire test? I'm pretty sure you've got `IntegrationTestWidgetsFlutterBinding.ensureInitialized()` in your Dart test file, which is invalid because Patrol uses its own binding.

**Comment by bartekpacia** [comment]
I improved the error message in #856.

**Comment by heitor598** [comment]
Failed to load "/Users/heitorgomes/Documents/Projects/lecupon-flutter/integration_test/example_test.dart": 'package:flutter/src/foundation/binding.dart': Failed assertion: line 146 pos 12: '_debugInitializedType == null': is not true.

**Comment by heitor598** [comment]
I'm having the same problem, I set `nativeAutomation: true`, and I'm not using `IntegrationTestWidgetsFlutterBinding.ensureInitialized()`

**Comment by findmanish** [comment]
THis is still being faced. can we have a look please.Using `nativeAutomation: true` and `IntegrationTestWidgetsFlutterBinding.ensureInitialized()` is there in listener.dart file in flutter SDK.
![image](https://github.com/leancodepl/patrol/assets/31733022/1d44ba4e-4626-46b6-b255-7d457eac9e92)

**Comment by bartekpacia** [comment]
Hi @findmanish, are you running your tests with `flutter test integration_test`?

Patrol tests that use native automation must be run with [`patrol test` command](https://patrol.leancode.co/cli-commands/test), because there's quite a lot of custom set up to make it work.

**Comment by findmanish** [comment]
Hi @bartekpacia , No I am running my tests as `patrol test --target integration_test` and I followed the mentioned link while setting this up.

**Comment by bartekpacia** [comment]
Please open a new issue and provide full reproduction steps (i.e. simply follow the "Bug Report" issue template).
