### ISSUE TITLE
Notifications permission

### ISSUE THREAD

**Issue by crisboarna** [leancodepl/patrol#880]
**Describe the bug**
Missing method to grant notification permission.

**To Reproduce**
1. Request Android/iOS notification permissions
![image](https://user-images.githubusercontent.com/12763781/216836075-dc2ca0de-44cc-4c5d-afa1-42dc7d044f1e.png)
2. Tried both 
```dart
      if (await tester.native.isPermissionDialogVisible()) {
        print('Dialog is visible');
        await tester.native.grantPermissionOnlyThisTime();
      }
```
and
```dart
      if (await tester.native.isPermissionDialogVisible()) {
        print('Dialog is visible');
        await tester.native.grantPermissionWhenInUse();
      }
```

I also tried calling directly `grantPermissionWhenInUse` and `grantPermissionOnlyThisTime` without `isPermissionDialogVisible` guard with no success either.
with no success, as expected as they are for the other permission window.
4. Tests hang as it is waiting for the permission to be granted.

**Expected behavior**
Allow button to be clicked, permission to be granted.

**Device information**
 - Device: any
 - OS: Android/iOS

<details>
<summary>Additional information</summary>

3.10.0

0.10.9

0.9.0
</details>

**Additional context**

I see there are methods for pulling down the notification shade and pressing notifications, how can you reach that step without granting permissions first, am I missing something in the documentation or is the method just not present ?

**Comment by bartekpacia** [comment]
Hi @crisboarna, thanks for creating this issue.

Unfortunately I cannot reproduce this problem on my Pixel 6 emulator with API 33 (the first where `POST_NOTIFICATIONS` permission is available). Here's the video of my run:

https://user-images.githubusercontent.com/40357511/216839779-cbb41a41-999a-4492-8b75-949dd6639051.mov

**Comment by crisboarna** [comment]
Hi @bartekpacia ,

What is the driver code you used to click on that permission ?

**Comment by bartekpacia** [comment]
It's the [notifications_test.dart](https://github.com/leancodepl/patrol/blob/master/packages/patrol/example/integration_test/notifications_test.dart) from the example app.

**Comment by crisboarna** [comment]
Issue with my configuration, got it working, thank you.
