### ISSUE TITLE
Patrol CLI 0.9.1 Integration regression

### ISSUE THREAD

**Issue by crisboarna** [leancodepl/patrol#891]
**Describe the bug**
Basic Patrol integration test fails

**To Reproduce**
1. Follow [native setup](https://patrol.leancode.co/native/setup)
2. Skip `pubspec.yaml` segment
3. Use given `integration_test/example_test.dart` test file sample
4. Run `patrol test --target integration_test/example_test.dart --flavor development`
5. Fail with process crashed

**Expected behavior**
Test success.

It fails on `patrol_cli` `0.9.1` but worked ok on `0.9.0`

**Device information**
 - Device: Any
 - OS version: Android
 - Does it also both on physical and virtual devices? no, didn't check
 - Please include as much detail as possible

<details>
<summary>Additional information</summary>

3.10.0

0.10.8

0.9.1

</details>

**Additional context**

Part of output with --verbose

        : Starting 0 tests on Pixel_4_API_33(AVD) - 13
        Test run failed to complete. Instrumentation run failed due to Process crashed.
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:connectedDevelopmentDebugAndroidTest'.
        > There were failing tests. See the report at: file:///Users/cris/Projects/alstasia/inneri/apps/inneri/build/app/reports/androidTests/connected/flavors/development/index.html
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 12s
        : 
        : > Task :app:connectedDevelopmentDebugAndroidTest FAILED
        : 
        : Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
        : 
        : You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
        : 
        : See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
        : 
        : Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
        : Please consult deprecation warnings for more details.
        : 209 actionable tasks: 8 executed, 201 up-to-date
✗ Failed to execute tests of apk with entrypoint example_test.dart on emulator-5554 (Gradle test execution failed with code 1) (13.0s)
Exception: Gradle test execution failed with code 1

**Comment by bartekpacia** [comment]
I can't reproduce your problem in the example app. I'm getting:

```
No device specified, using the first one (emulator-5556)
• Building apk with entrypoint example_test.dart...

	FAILURE: Build failed with an exception.

	* What went wrong:
	Cannot locate tasks that match ':app:assembleDevelopmentDebug' as task 'assembleDevelopmentDebug' not found in project ':app'.

	* Try:
	> Run gradlew tasks to get a list of available tasks.
	> Run with --stacktrace option to get the stack trace.
	> Run with --info or --debug option to get more log output.
	> Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 5s
✗ Failed to build apk with entrypoint example_test.dart (Gradle build failed with code 1) (6.2s)
Exception: Gradle build failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug – please report it.
 FAIL  example_test.dart on emulator-5556
```

I also checked a few other projects (my company's internal ones) and they work just fine as well. Can you share more details or a repo that I can clone to see your problem?

Patrol CLI 0.9.2.

**Comment by crisboarna** [comment]
Your error in the example app is due to running with flavour while the app is vanilla flavourless as there is no assembleDevelopmentDebug gradle task. 

I am attempting to reproduce the issue with the most basic example but am having issue getting it to throw the same error. 

I am basing my project from a [very_good_cli](https://github.com/VeryGoodOpenSource/very_good_cli) flavoured project template and cannot get it to run successfully there as well, albeit with a different error. 

I will raise another issue tomorrow regarding it to hopefully get this remediated first. 

Project I am getting this issues error in has several Firebase dependencies which may or may not play nice with the build. Is there a way to pass the '--stacktrace' parameter to gradle through patrol to gain more info on this ?

**Comment by bartekpacia** [comment]
> Your error in the example app is due to running with flavour while the app is vanilla flavourless as there is no assembleDevelopmentDebug gradle task.

Yeah, because that's what is included in this issue repro steps :P

> Steps to reproduce the behavior:
> 
> Follow [native setup](https://patrol.leancode.co/native/setup)
> Skip pubspec.yaml segment
> Use given integration_test/example_test.dart test file sample
> Run patrol test --target integration_test/example_test.dart --flavor development
> Fail with process crashed

> I am basing my project from a [very_good_cli](https://github.com/VeryGoodOpenSource/very_good_cli) flavoured project template and cannot get it to run successfully there as well, albeit with a different error.

Unfortunately I haven't ever used very_good_cli, so can't help you with that.

> Project I am getting this issues error in has several Firebase dependencies which may or may not play nice with the build.

We had problems with this in first versions of `patrol test`, but it should be fixed now. If you're still encountering problems because of Firebase dependencies then it's most probably a bug we should fix :)

> Is there a way to pass the '--stacktrace' parameter to gradle through patrol to gain more info on this

Not directly, but you can run `patrol test` with `--verbose` flag and then it will all `./gradlew` invocation it does, so you'll simply copy-paste them and pass `--stacktrace` flag then.

> I will raise another issue tomorrow regarding it to hopefully get this remediated first.

Sure :)

**Comment by crisboarna** [comment]
Opened #901 that narrows down the issue.
