### ISSUE TITLE
activityRecognition permission missing in native methods

### ISSUE THREAD

**Issue by PollyGlot** [leancodepl/patrol#897]
I use `ActivityRecognition` permission in my app and unfortunately it doesn't exist in a list of native methods. I was thinking to try something like this: 

```
if (!await Permission.activityRecognition.isGranted) {
    if (await $.native.isPermissionDialogVisible(timeout: _timeout)) {
        await $('Allow').tap();
    }
}
```
But it is not a good solution as the wording  can be in different languages. Is there any advise how can I test it ?

**To Reproduce**
1. ask for `<uses-permission android:name="android.permission.ACTIVITY_RECOGNITION"/>` in manifest file

**Additional context**

![android_permissions](https://user-images.githubusercontent.com/3662505/217330623-990e9dc3-a20d-4bad-8ce4-e8ce0fb68670.png)

**Comment by bartekpacia** [comment]
Hi @PollyGlot 👋

You should be already able to grant this permission – try the code below:

```dart
// https://pub.dev/documentation/patrol/latest/patrol/NativeAutomator/grantPermissionWhenInUse.html
await $.native.grantPermissionWhenInUse();

// or alternatively

// https://pub.dev/documentation/patrol/latest/patrol/NativeAutomator/grantPermissionOnlyThisTime.html
await $.native.grantPermissionOnlyThisTime();
```

If it doesn't work, then it's a bug and we should fix it.

`Permission.activityRecognition` is indeed not available - I recommend you create an issue about it in [permission_handler](https://github.com/baseflow/flutter-permission-handler) plugin repository. There's nothing we can do about it.

**Comment by bartekpacia** [comment]
I created an issue on `permission_handler` repository: https://github.com/Baseflow/flutter-permission-handler/issues/989

**Comment by PollyGlot** [comment]
Sorry for a late answer. I used `grantPermissionWhenInUse` for Activity permission and it seems to work. I will continue checking it as I have a lot of different permissions to accept in my app. Thanks for your reply.

**Comment by bartekpacia** [comment]
What Android version did you use? I'd like to reproduce this error.

**Comment by PollyGlot** [comment]
I am on Android 13

**Comment by PollyGlot** [comment]
I confirm that `grantPermissionWhenInUse` is working fine with this type of permission, I think we can close the issue.

**Comment by bartekpacia** [comment]
Thanks a lot for confirming :)
