### ISSUE TITLE
Android Gradle Plugin 7.3.1 causes 'Instrumentation run failed due to Process crashed'

### ISSUE THREAD

**Issue by crisboarna** [leancodepl/patrol#901]
**Describe the bug**
Running instrumentation test with upgraded Android Gradle build tools results in error.

**To Reproduce**
1. In provided `packages/patrol/example/android/build.gradle` change `classpath "com.android.tools.build:gradle:7.2.2"` to `classpath "com.android.tools.build:gradle:7.3.1"`
2. Run `patrol test --target integration_test/notifications_test.dart`
3. At the end of the test you will get `Test run failed to complete. Instrumentation run failed due to Process crashed.`
4. See error.

**Expected behavior**
Exit code 0.

**Device information**
 - Device: Any
 - OS version: Android 33
 - Does it also both on physical and virtual devices? didn't check
 - Please include as much detail as possible

<details>
<summary>Additional information</summary>

Flutter 3.7.1 • channel stable • git@github.com:flutter/flutter.git
Framework • revision 7048ed95a5 (7 days ago) • 2023-02-01 09:07:31 -0800
Engine • revision 800594f1f4
Tools • Dart 2.19.1 • DevTools 2.20.1

0.10.9

patrol_cli v0.9.3
</details>

**Additional context**

**Comment by bartekpacia** [comment]
Thanks for the report - I reproduced it.

<img width="755" alt="Screenshot 2023-02-08 at 12 23 54 PM" src="https://user-images.githubusercontent.com/40357511/217516487-70d81e42-dbba-43e3-ad8c-ef46d59fc71c.png">

**Comment by crisboarna** [comment]
Yes, it is a bug that got introduced in `patrol_cli` `0.9.1` specifically, hence my previous issue #891 .

**Comment by bartekpacia** [comment]
[Here's a diff](https://github.com/leancodepl/patrol/compare/patrol_cli-v0.9.0...patrol_cli-v0.9.1) between tag `patrol_cli-0.9.0` and tag `patrol_cli-v0.9.1`.

I'll investigate it.

**Comment by bartekpacia** [comment]
I think it's something caused by us passing --dart-defines:

This works:

```
./gradlew :app:connectedDebugAndroidTest -Ptarget=/Users/bartek/dev/leancode/patrol/packages/patrol/example/integration_test/notifications_test.dart
```

This crashes:

```
./gradlew :app:connectedDebugAndroidTest -Ptarget=/Users/bartek/dev/leancode/patrol/packages/patrol/example/integration_test/notifications_test.dart -Pdart-defines=UEFUUk9MX1dBSVQ9MA==,UEFUUk9MX1ZFUkJPU0U9dHJ1ZQ==,UEFUUk9MX0FQUF9QQUNLQUdFX05BTUU9cGwubGVhbmNvZGUucGF0cm9sLmV4YW1wbGU=,UEFUUk9MX0FQUF9CVU5ETEVfSUQ9cGwubGVhbmNvZGUucGF0cm9sLkV4YW1wbGU=,UEFUUk9MX0FORFJPSURfQVBQX05BTUU9UGF0cm9sIGV4YW1wbGU=,UEFUUk9MX0lPU19BUFBfTkFNRT1QYXRyb2wgZXhhbXBsZQ==,UEFUUk9MX1RFU1RfTEFCRUw9bm90aWZpY2F0aW9uc190ZXN0LmRhcnQ=
```
