### ISSUE TITLE
The function 'patrolIntegrationDriver' isn't defined.

### ISSUE THREAD

**Issue by Gaurav-CareMonitor** [leancodepl/patrol#934]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/113885801/218926359-40365f46-2278-4ecc-a242-4284e472f2b2.png">

https://github.com/leancodepl/patrol/issues/650#issuecomment-1334871652

**Comment by bartekpacia** [comment]
It's been removed in 1.0.

Migrate to `patrol test` command instead. [Full setup guide is here](https://patrol.leancode.co/native/setup).
