### ISSUE TITLE
Why is "patrol drive" removed in patrol test we cant able to get the logs which makes it difficult to debug ?

### ISSUE THREAD

**Issue by kameshWB** [leancodepl/patrol#935]
**I was not able see the app logs in console when running patrol test if build fails it was just showing a message**

Console output when executing patrol test:

```
No device specified, using the first one (4552035f)
• Building apk with entrypoint app_test.dart...
✓ Completed building apk with entrypoint app_test.dart (18.8s)
• Executing tests of apk with entrypoint app_test.dart on device 4552035f...
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':app:connectedDebugAndroidTest'.
        > There were failing tests. See the report at: file:///Users/kameshadadadi/Documents/GitHub/front-end/vestigas_app/build/app/reports/androidTests/connected/index.html
        
        * Try:
        > Run with --stacktrace option to get the stack trace.
        > Run with --info or --debug option to get more log output.
        > Run with --scan to get full insights.
        
        * Get more help at https://help.gradle.org
        
        BUILD FAILED in 1m 49s
✗ Failed to execute tests of apk with entrypoint app_test.dart on device 4552035f (Gradle test execution failed with code 1) (109.8s)
Exception: Gradle test execution failed with code 1
See the logs above to learn what happened. Also consider running with --verbose. If the logs still aren't useful, then it's a bug – please report it.
 FAIL  app_test.dart on 4552035f

```

**To Reproduce**

1. Go to write tests for app
2. Execute the command patrol test
3. See the results it wont show any logs 

  

**Can we have an extra arg like show-logs=true**

So if someone need the logs he can send set this arg to true.  

**Device information**

- Device: Realme RMX1805
- OS version: Android 9
- Does it also both on physical and virtual devices? No 

  

<details>
<summary>Additional information</summary>

Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (3 weeks ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1

patrol: ^1.0.0

patrol_cli v1.0.0
</details>

**Comment by bartekpacia** [comment]
Please use `flutter logs` as a temporary workaround to view logs made in Dart.

We're aware of the issue and it'll be fixed.
