### ISSUE TITLE
Waiting for ios-deploy to launch the app is taking unusually long time (30s)

### ISSUE THREAD

**Issue by Curosevic** [leancodepl/patrol#949]
I upgraded my cli to 1.0 and keep getting 

Completed building app with entrypoint demo_test.dart for device (232.8s)
• Running app with entrypoint demo_test.dart on device ... iPhone...
Executing on physical iOS device using ios-deploy...
$ ios-deploy --id 00008101-000A3D342629003A --bundle ../build/ios_integ/Build/Products/Debug-iphoneos/Runner.app --debug --no-wifi --args --enable-dart-profiling --enable-checked-mode --verify-entry-points
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)
Waiting for ios-deploy to launch the app is taking unusually long time (30s)". 

This isn't an urgent issue as older versions of the cli work, so it isn't blocking anything besides upgrading to the latest version. Running with verbose doesn't contain anything particularly interesting besides some warnings.

**Comment by bartekpacia** [comment]
Thanks for reporting. I'm encountering the same problem sometimes:

![Screenshot 2023-02-18 at 12 25 40 AM](https://user-images.githubusercontent.com/40357511/219815912-3240156c-5186-4607-94cd-8bc107b47a16.png)

Quite flaky.

**Comment by jeremiahlukus** [comment]
Running into this on the latest version

**Comment by bartekpacia** [comment]
Thanks for the info @jeremiahlukus.

Bumping priority on this /cc @mateuszwojtczak @jBorkowska

**Comment by Andreigr0** [comment]
Happens to me as well on a physical device, after exiting from command line (control+C) it starts to run Automation but fails as the app is not running anymore. 

On a simulator there is a loop trying to run test for 9 times with incorrect device orientation (landscape though the simulator is in portrait mode).
```
Test Suite 'RunnerUITests.xctest' passed at 2023-04-03 15:56:17.892.
                 Executed 9 tests, with 0 failures (0 unexpected) in 38.487 (38.493) seconds
        Test Suite 'All tests' passed at 2023-04-03 15:56:17.893.
                 Executed 9 tests, with 0 failures (0 unexpected) in 38.487 (38.494) seconds
```

 I've tried to force portrait orientation by using
```
 await SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.portraitDown,
      ]);
```
but it starts from landscape orientation anyway and quickly changes to portrait
Eventually test passes, but it seems to be broken

Also I would like to note this answer https://stackoverflow.com/a/73883185/9586934 in the setup section because otherwise running test creates 2 "clone iPhone 14 pro max" simulators 

Env: Xcode 14.3 (14E222b), patrol: 1.0.8, Flutter 3.3.10

**Comment by jeremiahlukus** [comment]
Im my ipad it shows that automation is running but nothing ever launches int the terminal 

i get 
```
✓ Completed building app with entrypoint walkthrough_test.dart for iOS device (43.2s)
• Running app with entrypoint walkthrough_test.dart for iOS device on device iPad...
Executing on physical iOS device using ios-deploy...
$ ios-deploy --id 00008030-001D38320EE0202E --bundle ../build/ios_integ/Build/Products/Debug-iphoneos/Runner.app --debug --no-wifi --args --enable-dart-profiling --enable-checked-mode --verify-entry-points
Waiting for ios-deploy to launch the app is taking unusually long time (30.0s)
Waiting for ios-deploy to launch the app is taking unusually long time (60.0s)
Waiting for ios-deploy to launch the app is taking unusually long time (90.0s)
Waiting for ios-deploy to launch the app is taking unusually long time (120.0s)
Waiting for ios-deploy to launch the app is taking unusually long time (150.0s)
```

my code is just test code 

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:patrol/patrol.dart';

void main() {
  patrolTest(
    'counter state is the same after going to home and switching apps',
    nativeAutomation: true,
    ($) async {
      // Replace later with your app's main widget
      await $.pumpWidgetAndSettle(
        MaterialApp(
          home: Scaffold(
            appBar: AppBar(title: const Text('app')),
            backgroundColor: Colors.blue,
          ),
        ),
      );

      expect($('app'), findsOneWidget);
      await $.native.pressHome();
    },
  );
}

```

![IMG_5729](https://user-images.githubusercontent.com/17206638/229575102-d86cc6ac-9029-4867-8492-8a99779f0307.jpg)

**Comment by ziadsarour** [comment]
Is there a workaround for this ?
I can't launch my tests because of this.
Thanks

**Comment by ziadsarour** [comment]
> Is there a workaround for this ? I can't launch my tests because of this. Thanks

Resolved by upgrading ios-deploy to latest version (1.12.2) by ```brew update && brew install ios-deploy```, you might need to overwrite symlinks using the command provided by brew.

I now have this issue https://github.com/leancodepl/patrol/issues/1244 but (maybe) not related to ios-deploy anymore.

**Comment by Jeonguk-ninehire** [comment]
@jeremiahlukus Can I ask you any progress of this issue? I have same problem with your case. Cannot launch on iOS real device.

**Comment by bartekpacia** [comment]
We no longer depend on `ios-deploy` in Patrol 2.0, which will be released soon.

See also [this important comment](https://github.com/leancodepl/patrol/issues/1004#issuecomment-1562852165).

**Comment by mzdm** [comment]
Confirming that 2.0 fixes this issue.

However await tester.enterText does not seem to work and after the test finishes there is this error -- looking
```
• Running app with entrypoint test_bundle.dart for iOS device on device sma21b634aa...
        2023-06-13 13:55:52.890 xcodebuild[76302:3461223] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
        2023-06-13 13:56:47.565 xcodebuild[76302:3461223] [MT] IDETestOperationsObserverDebug: 53.236 elapsed -- Testing started completed.
        2023-06-13 13:56:47.565 xcodebuild[76302:3461223] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
        2023-06-13 13:56:47.565 xcodebuild[76302:3461223] [MT] IDETestOperationsObserverDebug: 53.236 sec, +53.236 sec -- end
        2023-06-13 13:56:47.664 xcodebuild[76302:3461223] [MT] IDEResultKit: Warning: While writing a result bundle to /Users/mzidek/Library/Developer/Xcode/DerivedData/Runner-ehfudxiefzyoctcqlodbseibuatf/Logs/Test/Test-Runner-2023.06.13_13-55-54-+0200.xcresult, not all contents have been imported, as the Staging directory still contains the following files/directories: ["1_Test"]
        Failing tests:
                -[RunnerUITests patrolAppTest]
        
        ** TEST EXECUTE FAILED **

```

**Comment by bartekpacia** [comment]
@mzdm Great to hear that it works for you. Regarding the error – yeah, we're also aware of it (it was first detected internally so it's tracked internally as well. I'll consider making it public). It happens only on physical iOS devices. I suspect it's because of `--release`.

> After the test finishes there is this error -- looking

Do you mean these lines?

```
2023-06-13 13:55:52.890 xcodebuild[76302:3461223] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=2023-06-13 13:56:47.664 xcodebuild[76302:3461223] [MT] IDEResultKit: Warning: While writing a result bundle to /Users/mzidek/Library/Developer/Xcode/DerivedData/Runner-ehfudxiefzyoctcqlodbseibuatf/Logs/Test/Test-Runner-2023.06.13_13-55-54-+0200.xcresult, not all contents have been imported, as the Staging directory still contains the following files/directories: ["1_Test"]
```

If that's what you mean, then don't worry, they're not dangerous. It's just some weird Xcode warnings, they've been here since forever and I've no idea what they mean 🙃

**Comment by bartekpacia** [comment]
No longer relevant in Patrol 2.0.
