### ISSUE TITLE
`$.native.enterText()` is not working on iOS MDC TextFields 

### ISSUE THREAD

**Issue by Shrirama-Upadhya-A** [leancodepl/patrol#993]
**Describe the issue**

We use native iOS modules in our sample flutter project. Forms in our native iOS modules use iOS Material Design Component Text fields (MDC TextFields are very necessary for our designs, cannot use in-built TextFields)
When we try to make use of `$.native.enterText()` on these MDC TextFields, `Selector` is unable to find these textfields which ultimately leads to the failure of our integration tests.

**Current (wrong) behaviour**

The integration test is failing since Patrol is unable to find the MDC textfield `Name as per Govt. ID` and enter the text `bartkepacia` 
```
await $.native.enterText(
  Selector(text: 'Name as per Govt. ID'),
  text: 'bartekpacia',
);
```
Please take a look into the attached video for complete context

https://user-images.githubusercontent.com/35920893/220606447-432afb71-1163-43c7-9e6d-824ea22ef986.mp4

**Expected behavior**

Enter the required text (`bartekpacia`) into iOS MDC TextField `Name as per Govt. ID`

**Device information**

- Common understanding is that this issue is not device-specific
- Test device details : 
  - Device: iPhone SE2
  - OS version: iOS 16.3
  - Does it also both on physical and virtual devices?: Didn't check

<details>
<summary>Additional information</summary>

`flutter --version`

```
Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (13 days ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1
```

`patrol from pubspec.lock`

```
patrol:
    dependency: "direct dev"
    description:
      name: patrol
      sha256: <--masked-->
      url: "https://pub.dev"
    source: hosted
    version: "1.0.4"
```

`patrol --version`

```
patrol_cli v1.0.3
```
</details>

**Comment by Shrirama-Upadhya-A** [comment]
@bartekpacia Hope you're back from your vacation & hope you enjoyed it 🥳 
Were you able to look into this issue? Is there any workaround that I can add at my end for quick resolution?

**Comment by bartekpacia** [comment]
Hi, sorry I haven't yet had time to look into it.

Have you tried using `enterTextByIndex()`?

**Comment by Shrirama-Upadhya-A** [comment]
@bartekpacia `enterTextByIndex()` works beautifully, thank you 🙏 

Our use-case is that we are dynamically creating forms based on configurations which are fetched on run-time. 
Writing tests in such cases would become very easy if we could enter the required text using `Selector(text: <field-label>)`. 

Do let me know if you need any more details from my end ✌️

**Comment by bartekpacia** [comment]
@Shrirama-Upadhya-A Hi, can you create [a minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your app so I can fix this? A very simple `flutter create`d app a native side containing a few MDC text fields?

**Comment by Shrirama-Upadhya-A** [comment]
Hey @bartekpacia 
Apologies for missing your response.
Will create a sample app & share it across this weekend, would that work?

**Comment by bartekpacia** [comment]
Yes, that would be great.

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment and I'll be happy to continue the discussion :)
