### ISSUE TITLE
$.native.grantPermissionOnlyThisTime(); is not working on emulator pixel 6 pro API 30

### ISSUE THREAD

**Issue by m-jayy** [leancodepl/patrol#996]
**Describe the bug**

We use native $.native.grantPermissionOnlyThisTime() for Location permission on android Emulator Pixel 6 Pro API 30 the test is crashing with exception  

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/28633873/221160219-eafe16af-8458-495e-97d5-88362589b000.png">

Although Same test is running fine on android Emulator Pixel 6 Pro API 33

**To Reproduce**

Use  android Emulator Pixel 6 Pro with API 30 and try to grant native permission with $.native.grantPermissionOnlyThisTime().

**Expected behavior**

Should grant permission

<details>

**Device information**

- Device: [emulator pixel 6 pro]
- OS version: [API 30]
- Working as expected on OS version: [API 33]

<img width="659" alt="image" src="https://user-images.githubusercontent.com/28633873/221161526-703d2f66-64d6-4137-95bd-09b644c0203e.png">

<img width="179" alt="image" src="https://user-images.githubusercontent.com/28633873/221161679-6840decc-0c54-42ab-ad32-6d43484ef6f4.png">

<img width="166" alt="image" src="https://user-images.githubusercontent.com/28633873/221161764-fc96852d-cebf-4862-a55b-206def8c01d7.png">

</details>

**Comment by bartekpacia** [comment]
Hi @m-jayy, thanks for the bug report.

Can you wipe your emulator, rerun your tests, and confirm that the issue persists? The logs make me think that it's a one-off random problem with Android's UIAutomator.

**Comment by bartekpacia** [comment]
Closing because of lack of response. Feel free to comment with more details so I can reproduce it.
